### ISSUE TITLE
searching: call number browse

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#100]
If I do a call number browse search for "m" I am taken to the beginning of call numbers which have "m" as the first character.  The same thing happens if I search for "mi" or "mic" or "micr".  It seems as soon as I search for "micro" I am dumped into the very end of the index after the Zs where there is some flotsam and jetsam floating about.

**Comment by tampakis** [comment]
All call numbers are made all upper case in #159, which fixes this problem.
