### ISSUE TITLE
LOCATIONS constant error

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1003]
The error ```ActionView::Template::Error: uninitialized constant ApplicationHelper::LOCATIONS``` seems to be the most common one raised by OL. 

It is initialized in https://github.com/pulibrary/orangelight/blob/master/config/initializers/locations_initializer.rb. 

It stores all the locations information for use in building out what the user the sees in the holdings sidebar. I'm not really sure why this comes up so frequently. If you look at the Honeybadger logs it is clearly being raised by a bot trawling through the facet links. It is curious it comes up so much since I thought the initializers only ran when the app is started up but maybe I am incorrect in that assumption since it is clearly failing to load the JSON data for locations from bibdata frequently.

**Comment by eliotjordan** [comment]
@kevinreiss How often are locations updated? If the frequency of change is low, what about hard coding these values rather than pulling them from bibdata? From what I can tell, if bibdata returns anything other than a 200, the constant is not initialized. Which might explain this error.

**Comment by kevinreiss** [comment]
Updates are sporadic. There is odd label change but major revisions or additions of new locations happen only a few times a year at most.

**Comment by eliotjordan** [comment]
This issue references four errors in Honeybadger:

https://app.honeybadger.io/projects/54399/faults/35783657
https://app.honeybadger.io/projects/54399/faults/35783653
https://app.honeybadger.io/projects/54399/faults/35783655
https://app.honeybadger.io/projects/54399/faults/35784275
