### ISSUE TITLE
[Orangelight/production] Errno::EHOSTUNREACH: No route to host - connect(2) for "lib-ponyexpr.princeton.edu" port 25

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1004]
## Backtrace

    line 43 of [PROJECT_ROOT]/app/controllers/concerns/orangelight/catalog.rb: email_action

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/35728015)

**Comment by eliotjordan** [comment]
Is `lib-orange-prod6` on the pony express whitelist? Think this is a new server.

**Comment by kevinreiss** [comment]
No, it isn't. I will open a SN@P ticket asking it to be added.

**Comment by tampakis** [comment]
It is on it. John added it on Tuesday
