### ISSUE TITLE
[Orangelight/production] ActionView::Template::Error: undefined method `find_all' for nil:NilClass

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1013]
## Backtrace

    line 12 of [PROJECT_ROOT]/app/views/catalog/librarian_view.html.erb: _app_views_catalog_librarian_view_html_erb___3189914517497248432_70009362557200

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/35760678)

**Comment by kevinreiss** [comment]
This view depends on a backend http to bibdata for the MARC record. This record ID displays fine in this mode so the error must have been at a time bibdata couldn't service the request.
