### ISSUE TITLE
[Orangelight/production] NoMethodError: undefined method `to_marc' for nil:NilClass

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1015]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/35760792)

**Comment by eliotjordan** [comment]
Another example of a bot requesting a format that doesn't exist for that particular record.

https://github.com/pulibrary/orangelight/blob/master/app/helpers/application_helper.rb#L477-L478

**Comment by kevinreiss** [comment]
SCSB records are generated from MARCXML source data. If we wanted to service this sort of request we'd need to store the marcxml as a string in a solr field and serve that up when required.
