### ISSUE TITLE
[Orangelight/production] URI::InvalidURIError: bad URI(is not URI?): https://bibdata.princeton.edu/patron/22101 002491504

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1018]
## Backtrace

    line 6 of [PROJECT_ROOT]/lib/orangelight/bibdata.rb: get_patron
    line 15 of [PROJECT_ROOT]/app/controllers/users/omniauth_callbacks_controller.rb: barcode

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/35755278)

**Comment by eliotjordan** [comment]
Handle bad uri.

**Comment by escowles** [comment]
Closing because the linked HoneyBadger error is no longer available.
