### ISSUE TITLE
[Orangelight/production] ActionView::Template::Error: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1020]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/35790005)

**Comment by eliotjordan** [comment]
Error in requests gem.

**Comment by kevinreiss** [comment]
This is in part a data error. This record https://pulsearch.princeton.edu/catalog/5409973 has an online holding that is has no URL. Reported the data issue to e-support.

**Comment by kevinreiss** [comment]
Cataloging has corrected data error.
