### ISSUE TITLE
[Orangelight/production] JSON::ParserError: 784: unexpected token at '<h1>This website is under heavy load</h1><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>'

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1023]
## Backtrace

    line 25 of [PROJECT_ROOT]/lib/orangelight/bibdata.rb: get_patron
    line 119 of [PROJECT_ROOT]/app/controllers/account_controller.rb: current_patron?
    line 93 of [PROJECT_ROOT]/app/controllers/account_controller.rb: set_patron

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/35783658)

**Comment by escowles** [comment]
Closing because the linked HoneyBadger error is no longer available.
