### ISSUE TITLE
Non-LC Call Numbers in 050

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#103]
@joycebcat Some records have non LC call numbers in the 050 field. These values should be removed.
I've been doing some work on the call number topic facet and noticed something weird in this search: http://pulsearch-dev.princeton.edu/?f%5Blc_1letter_facet%5D%5B%5D=E+-+History+of+the+Americas+%28General%29

The counts within the hierarchy should add up to the value of its parent. In this case since there is only one child, the count should be the same. However, we see that there are less results in the the "full call number" facet than the "1 letter facet." My code takes the first letter of `050 a` and maps that the LC classification. In this case there are "Electronic Resources" that have matched the E because it takes only the first letter of the call number for mapping. I have since fixed this to only add the first letter of the call number in the cases when it also adds the full call number alphabetic classification.

**Comment by joycebcat** [comment]
Nikitas,

I’m going to have to talk to you about this.  I just can’t seem to find the time to concentrate on the issue.  I’m on campus tomorrow afternoon.  Could I stop by?

Joyce

**Comment by tampakis** [comment]
Fixed in https://github.com/pulibrary/orangeindex/commit/9a3a1d05959d934b97bbcab0bc68c16d186496bb
