### ISSUE TITLE
Streamline links to digital content on the same page

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1048]
Currently, we display links in the online content box that go through a couple of lookups and eventually redirect to the same page (when the viewer is at the bottom of the page).

We should be able to figure that out and just have a relative link to "#view" and make the link text something like "digital content below"

**Comment by tpendragon** [comment]
My understanding:

An example is here: https://pulsearch.princeton.edu/catalog/4609321

The second link under the "Online" header goes to resolve the Ark, which then goes back to the same page, but with the `#view` anchor. This ticket says we should be able to tell that will happen and instead just put a direct link to the anchor.

How might we figure that out? Is this an indexing problem? Do we resolve the ark as part of indexing?

**Comment by jrgriffiniii** [comment]
It should also be noted that, if that is indeed the case, then it would be affected by the following:

https://github.com/pulibrary/orangelight/blob/master/app/assets/javascripts/plum_viewer_loader.js.coffee#L2

Resolving this might bring it into conflict with a separate issue: https://github.com/pulibrary/orangelight/issues/1094

**Comment by escowles** [comment]
I think we should consider doing the lookup at index time, so we know when we're building the page whether to display the viewer and whether to link down to it.

The other option (that is probably less disruptive) would be for the javascript that displays the viewer to also change the ARK link to point to the viewer.
