### ISSUE TITLE
Icon Set

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#106]
Implement an icon set whose use can be mapped to the format type of a record.

**Comment by jpstroop** [comment]
Extend the set here: https://github.com/pulibrary/pul_library_drupal/tree/development/sites/all/themes/pul_base/pul_base_icons

**Comment by tampakis** [comment]
Blacklight formats:
Book
Journal
Audio
Map
Musical Score
Thesis
Video/Projected Medium
Data File
Senior Thesis
Visual Material

**Comment by axapu** [comment]
Use Streamline icons for more consistent look: http://www.streamlineicons.com/preview.html

**Comment by axapu** [comment]
Closed by #194
