### ISSUE TITLE
[Orangelight/production] ActionView::Template::Error: undefined method `collect' for #<ActionController::Parameters:0x...>

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1081]
## Backtrace

    line 22 of [PROJECT_ROOT]/app/views/saved_searches/index.html.erb: block in _app_views_saved_searches_index_html_erb__1968065400898295033_69899008710220
    line 20 of [PROJECT_ROOT]/app/views/saved_searches/index.html.erb: _app_views_saved_searches_index_html_erb__1968065400898295033_69899008710220

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/35902663)

**Comment by escowles** [comment]
Closing because the linked HoneyBadger error is no longer available.
