### ISSUE TITLE
Authentication via Omniauth CAS

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#109]
Think about CAS omniauth as the best option for PUL. @eliotjordan had some good suggestions on how to do this https://github.com/pulibrary/pul-store/issues/326. This will be available to any PU user with an official net id.

**Comment by jpstroop** [comment]
Users should be able to auth via:
 * [ ] CAS
 * [ ] Barcode (cf. #110)
 * [ ] OAuth (?)
