### ISSUE TITLE
Deprecate Recap Note Helper

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1091]
After 3ad469a89bfb1762ebede2aeb3c522b2aebe1a9f is deployed and a full re-index is preformed this helper can go away https://github.com/pulibrary/orangelight/blob/master/app/helpers/application_helper.rb#L528. It's used by the ```recap_notes_display``` field in catalog_controller.rb. See https://github.com/pulibrary/marc_liberation/issues/303 for more info.

**Comment by sandbergja** [comment]
This helper was removed in #3215
