### ISSUE TITLE
Refactor javascript to use umlaut's api instead of included js

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#1092]
Initially motivated by https://github.com/pulibrary/orangelight/issues/656, which documents a spec that fails when the fixture falls out of sync with voyager / umlaut IDs. TL;DR that issue goes on to describe various possible approaches to mocking client-side calls to external APIs.

Ultimately we decided to serve static fixture content during tests (see comment https://github.com/pulibrary/orangelight/issues/656#issuecomment-352900606) but this strategy was thwarted by our use of umlaut's [JQuery Content Utility](https://github.com/team-umlaut/umlaut/wiki/JQuery-Content-Utility). We could mock this way by refactoring the js to use umlaut's [HTML Snipped API](https://github.com/team-umlaut/umlaut/wiki/HTML-Snippet-API-Response) or, if necessary, the [full umlaut data api](https://github.com/team-umlaut/umlaut/wiki/Data-API-Response) (note, documentation recommends against using the full api if avoidable).

Note that refactoring the js here is probably best achieved by moving it out of the template, into es6, and unit testing with jasmine or similar. This might mean that we would use [jasmine's ajax mocking library](https://jasmine.github.io/2.0/ajax.html) instead of testing the response in a rails feature test.

**Comment by hackmastera** [comment]
see https://github.com/pulibrary/orangelight/issues/1094#issuecomment-354153878 for an update on mocking with static files.

**Comment by kevinreiss** [comment]
Another thing to note that if we deprecate the use of the JQuery utility umlaut provides any JS we replace it with locally will need to be structured to keep updating the page until the umlaut response is complete. See https://github.com/team-umlaut/umlaut/wiki/HTML-Snippet-API-Response#complete and https://github.com/team-umlaut/umlaut/wiki/HTML-Snippet-API-Response#in_progress.
