### ISSUE TITLE
"Title starts with" searches issue with punctuation

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1101]
When a title includes punctuation, e.g. "Quasi-experimentation : design & analysis issues for field settings", the space before the colon is required when doing a "title starts with" search.  So this works:  https://pulsearch-dev.princeton.edu/catalog?utf8=%E2%9C%93&search_field=left_anchor&q=Quasi-experimentation+%3A+design

But this does not: https://pulsearch-dev.princeton.edu/catalog?utf8=%E2%9C%93&search_field=left_anchor&q=Quasi-experimentation%3A+design

This is going to confuse users, because the space before the colon is nonstandard.  They should be able to search for "Quasi-experimentation: design" and find this item.

**Comment by jrgriffiniii** [comment]
#1109 should resolve this, but I would be curious as to whether or not this would best be approached as an indexing problem within [pulibrary/pul_solr](https://github.com/pulibrary/pul_solr)

**Comment by jrgriffiniii** [comment]
This may not be necessary (reindexing Solr with the new config. from https://github.com/pulibrary/pul_solr/pull/51 might have already resolved the same issue), but testing will be required in order to verify that this is indeed the case.
