### ISSUE TITLE
Markup generation for online and physical item holdings should be refactored into template partials

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/orangelight#1106]
As identified by @tpendragon and @hackmastera , the adjustments proposed within https://github.com/pulibrary/orangelight/pull/1100 could be greatly improved upon by replacing methods within HoldingRequestsBuilder, OnlineHoldingsMarkupBuilder, and PhysicalHoldingsMarkupBuilder with template partials

**Comment by christinach** [comment]
We plan to refactor 
- HoldingRequestsBuilder, 
- OnlineHoldingsMarkupBuilder, and 
- PhysicalHoldingsMarkupBuilder
and create a new ticket for this work.
