### ISSUE TITLE
Stack Map/Locator Integration

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#111]
Consider embedding these maps directly in the show page and as a modal on the index page. Both should support this.

**Comment by axapu** [comment]
Cannot pull remote content to modal. Getting error:

XMLHttpRequest cannot load http://library.princeton.edu/searchit/map?loc=scidoc&id=321. No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by kevinreiss** [comment]
The base path has change to http://library.princeton.edu/utils/map?loc=scidoc&id=321 though that route in discoveryutils is just a redirect. We will probably need to rewrite discoveryutils or add a simple route to orangelight that can serve up the actual content.

**Comment by kevinreiss** [comment]
Hmm, sorry I missed this. The URLs http://library.princeton.edu/utils/map?loc=scidoc&id=321 are actually just redirects to the two stack mapping services we use. I'll reconstruct it to actually serve up the content directly and make it easier to embed with a CORs request.

**Comment by tampakis** [comment]
For when we want to try embedding the map links directly in OL or another service. Offshoot of #338.

    Firestone Locator maps can be embedded in an iframe by adding the embed=true parameter to the standard call see http://library.princeton.edu/locator/index.php?loc=f&id=8381839&embed=true. This renders the map without the tabs that you see in the current interface.
    Stackmap Maps can be embedded by using the stackmap API. For reasons unknown to me the PDF files containing the API definitions are not on the web but I have them in an email as PDFs when this gets picked up. There are XML and JSON responses available.

**Comment by axamei** [comment]
Related to #1313

**Comment by tampakis** [comment]
https://xd.adobe.com/view/2dcc57fd-3f03-4e5d-4a31-1493c363013c-5bfd/screen/39980e3d-44b0-44ab-aa5d-0b10acc1d2ce/Catalog-Item-Record-Book-1

**Comment by tampakis** [comment]
Closing in favor of #1312
