### ISSUE TITLE
Missing Translation File Errors in Subject Display

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1114]
See the subjects section on the record page. This seems to be a global problem that just emerged.

Examples: https://pulsearch.princeton.edu/catalog/5572144
https://pulsearch.princeton.edu/catalog/377589
https://pulsearch.princeton.edu/catalog/10121874

You'll see the message: ```translation missing: en.``` appear after every heading.

**Comment by tpendragon** [comment]
I rolled back deploy so this wouldn't show up. We'll have to look at this on staging.

**Comment by tpendragon** [comment]
This was introduced here: https://github.com/pulibrary/orangelight/commit/f45e411db4b6208bf245e337eb1b2a75fac008ff#diff-127a850b7d7b20173ad3fba88f8a25e3R277

I18n.t and t look the same, but t is actually an alias for translate in a helper, which (per http://api.rubyonrails.org/v5.1/classes/ActionView/Helpers/TranslationHelper.html) does the following thing:

```
First, it will ensure that any thrown MissingTranslation messages will be rendered as inline spans that:

Have a translation-missing class applied

Contain the missing key as the value of the title attribute

Have a titleized version of the last key segment as text
```

So if there's a missing translation, it doesn't display it - it just wraps it in a span so you know about it. The dashes aren't translated.
