### ISSUE TITLE
Series indexing and display

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#112]
Just something to check on, following an exchange btw. Darwin and Janet:

Darwin:
> Can I ask (or even beg) that we index 490 fields and also display them in both Voyager and Primo? They are essential fields in the records for music editions. For example, try searching on Mozart (as author) and “Neue Ausgabe sämtlicher Werke” as title phrase) No hits, and no display. But we have probably close to a hundred records in this field (just recently loaded) that contains the alternative (and familiar) series title. Here’s a sample record (with some of the fields deleted for concision). Music researchers always refer to this as the Mozart Neue Ausgabe. To have it not search when this data is there is not at all helpful.

001      8853683

Later...
> My apologies – the field is indexing. However, it is suppressed from display in both Voyager and Primo. My comments about the importance of this field remain. If it’s absent from the records, no one knows why the record was retrieved. This is vital bibliographic information. It needs to be seen.

Janet:
> We had this conversation earlier, around Christmas I believe. Joyce can weigh in on the detailed reasoning behind this display decision. But if you display both 490 and the added entry you get double entry displays that in the majority of cases are identical.

> As you say they all search.

**Comment by jpstroop** [comment]
/cc @joycebcat, @tampakis

_As I understand the situation_, __until 2006__ or so you had either a 440 field that served and both the version to be indexed (series were controlled fields, similar to uniform titles) and displayed, or you had a 490 ___and__ an [8xx](http://www.loc.gov/marc/bibliographic/bd80x83x.html) (usually 830), where the 490 was the version to display and the the 8xx was the version to index.

Post-2006 (or so) 440 was deprecated and LC stopped controlling series entries, so transcribed series info goes in 490, but it's not intended to be controlled data, and controlled data goes in the 8xx fields.

RDA probably changed all of this again...

Darwin's example has:

```
490      1_ |a Neue Ausgabe sämtlicher Werke / Wolfgang Amadeus Mozart. Ser. 9, Klaviermusik, Werkgruppe 25: Klaviersonaten; |v Bd. 1-
800      1_ |a Mozart, Wolfgang Amadeus, |d 1756-1791. |t Works. |f 1955 ; |v Ser. 9, Werkgruppe 25, Bd. 1.
```

Which suggests a few things:

1. We should confirm the handling of 490s and legacy 440s
2. How feasible is a cleanup project to change all 440s to 490s and also copy the same data to 830s?
3. Should we by including 8xx fields in the starts-with search and 800, 810, and 811 in the name browse DB table?

**Comment by joycebcat** [comment]
Some of this was covered in e-mail, but for the record, yes, you are correct in the history of how series coding evolved.  Note that although 440 isn't in current use, it does still get used sometimes on member copy.  I have been considering a series cleanup for some time as it would allow for far simpler future maintenance of series headings.  I'm not sure how feasible such a change actually will be, and I don't have any actual plans in place to do so.  The 830 is a title field and the 800/810/811 are name/title headings and should presumably be treated like 700 name/title headings.

**Comment by tampakis** [comment]
From Darwin:
 > I know we fixed this for our version of Blacklight, but is it also possible to get the 490 fields to show publically in our Voyager records? I believe this was a decision on our part to turn them off, and is not a problem with Voyager functionality. For music materials, it’s bibliographic truncation (and unacceptable, in my view) not to have this information showing.

Current behavior in Blacklight is that both 440/490 index and display.
