### ISSUE TITLE
Strip whitespace from barcodes

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1123]
## Backtrace

    line 9 of [PROJECT_ROOT]/app/services/bibdata.rb: get_patron
    line 15 of [PROJECT_ROOT]/app/controllers/users/omniauth_callbacks_controller.rb: barcode

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/36109686)

**Comment by kevinreiss** [comment]
Looks like the barcode form allowing one submitted with a space to pass through.
