### ISSUE TITLE
Make restrictions clearer

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1124]
I have a vague note about creating a ticket for this

**Comment by kevinreiss** [comment]
Here is a good example that of a record that includes both types of use restrictions, https://pulsearch.princeton.edu/catalog/SCSB-8024487. The staff would like them to be more "prominent." We don't currently do any labeling on the search results page regarding these restrictions, https://pulsearch.princeton.edu/?page=1&q=SCSB-8024487&search_field=all_fields&utf8=%E2%9C%93.

**Comment by sdellis** [comment]
Related to: https://github.com/pulibrary/requests/issues/337

**Comment by sdellis** [comment]
There are a few conflated use cases here I think. I believe the goal is to prevent unwanted requests for restricted items. 

1. One user may not want a restricted item at all in which case the restriction should be more prominent. 
2. Another user may prefer a circulating item if there is one. 
3. Still yet another user may want the restricted item, even when they are aware of an alternate version.

Will this ticket cover all these cases, or should we break it up?

**Comment by jrgriffiniii** [comment]
This has been included within the scope of https://github.com/pulibrary/orangelight/issues/990#issuecomment-358319566
