### ISSUE TITLE
856 Link Display Issues

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1126]
Not sure if the issue is the same, but I got the following e-mails about link display issues:

> Records with curatorial documentation are displaying the same link twice (versus only once in Voyager): https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=%22curatorial+documentation%22

> See this record:
http://catalog.princeton.edu/cgi-bin/Pwebrecon.cgi?v2=1&ti=1,1&SEQ=20180109192442&Search_Arg=Petit%20Journal%20des%20Refus%C3%A9es&Search_Code=GKEY%5E&CNT=50&PID=dFxmInY7qGtxsL9fVAeot5aa1cOFtua&SID=1
> 
> And compare it to Blacklight
https://pulsearch.princeton.edu/catalog/2607273
> 
> The Blacklight record has messed up the 856s  --  You can tell from the Bib that there are two distinct URLs  -- But Blacklight has dropped one and twinned the other  --

**Comment by kevinreiss** [comment]
This record https://pulsearch.princeton.edu/catalog/5960204 also exhibits a similar problem. Two distinct URLs (w/labels) but a duplicate link in OL.
