### ISSUE TITLE
Call Number Schemes

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#113]
Because records can have LC and SuDocs Call numbers, I don't think it makes sense to put them in the same pivot facet. The hierarchy only makes sense if a record only has one call number and location in the pivot facet 'tree'
Note the following screenshot:
![classification_pivot_031215](https://cloud.githubusercontent.com/assets/4650153/6626318/27735ed6-c8cc-11e4-8b99-99861868fed9.png)
This record has an LC call number (050 field) and a SuDocs call number (086 field) associated with it. Because a record can have both properties, the "SuDocs: A-G" value appears under both the LC and SuDocs schemes. We can force them to be mutually exclusive (add only one call number classification per record, maybe prefer 050 to 086?), but I think it lessens the utility of faceting on these fields. For now I'll keep them in two separate facets.

**Comment by jpstroop** [comment]
I think splitting into separate facets will be less confusing; that's what
you're proposing, right?

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by tampakis** [comment]
Yes and that's what I have on the dev server currently. Otherwise limiting the facet to having one call number per record would allow it all to fit in one facet (so a record won't match the SuDoc scheme and H - Social Sciences in the LC scheme)

**Comment by kevinreiss** [comment]
Yes, I agree, splitting them out into separate schemes is better.

**Comment by tampakis** [comment]
https://github.com/sul-dlss/blacklight-hierarchy
Hmm...

**Comment by kevinreiss** [comment]
This could be useful, but maybe not so much for call numbers.

**Comment by tampakis** [comment]
Closed in 3c3609f
