### ISSUE TITLE
Link to request individual volumes in viewer?

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1133]
The Table of Contents project will create Figgy objects with scans of the tables of contents from journals sent to ReCAP.  These will be multi-volume works, with one volume for each physical volume.

Is there any way these volumes could link directly to a request for the volume from ReCAP?  It would make it much easier for a user to request only the volume they want, and not make a mistake or request the whole title instead.

**Comment by kevinreiss** [comment]
If we could link the individual volume to the voyager item id or barcode attached to the physical this could be pretty easily accomplished.

**Comment by tpendragon** [comment]
I think we can do this if we switch UV to the version that mutates the URL, but it'll mutate the url.

**Comment by escowles** [comment]
@kevinreiss Yes, these are journals currently at Lewis that are being moved to ReCAP.  The ToC scanning project is to capture the tables of contents for items where there isn't an online index anywhere.

**Comment by kevinreiss** [comment]
The current form doesn't accept the barcode as a parameter but it could be extended to do so.

**Comment by escowles** [comment]
Re-opening this — #1144 is about displaying holdings links, not creating links in the viewer.

**Comment by christinach** [comment]
The viewer come from figgy. If this is desired, this work should be done in figgy.
