### ISSUE TITLE
Upgrade all production servers to Ruby 2.4.2

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1136]
We have merged support for 2.4.2, so we'll need to make sure all of our production servers are upgraded before we can do a production deploy.

 - [x] lib-orange-prod2
 - [x] lib-orange-prod3
 - [x] lib-orange-prod4
 - [x] lib-orange-prod6

**Comment by hackmastera** [comment]
- [ ] update the ansible scripts to install 2.4.2
- [ ] create new branch compatible with 2.4.2 (use aeef6f63431705ecff0e0c2f709565b335531278)
- [ ] as each new box comes up deploy the new branch
- [ ] merge to master

**Comment by hackmastera** [comment]
resolved by #1142
