### ISSUE TITLE
Record Can't Load - Other Versions Data Issue

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1139]
https://pulsearch.princeton.edu/catalog/SCSB-5855877

Stack Trace
```F, [2018-01-17T09:21:22.715343 #29328] FATAL -- : ActionView::Template::Error (undefined method `[]' for nil:NilClass):
F, [2018-01-17T09:21:22.715612 #29328] FATAL -- :     1: <% linked_records(document[field], document[:id], linked_field).each do |records| %>
    2:   <dt class="blacklight-<%= field.parameterize %>"><%= render_document_show_field_label document, :field => field %></dt>
    3:   <dd class="blacklight-<%= field.parameterize %>">
    4:     <% if records.count == 1 %>
F, [2018-01-17T09:21:22.715684 #29328] FATAL -- :
F, [2018-01-17T09:21:22.715749 #29328] FATAL -- : app/helpers/blacklight_helper.rb:159:in `linked_records'
app/views/catalog/_other_versions_show.html.erb:1:in `_app_views_catalog__other_versions_show_html_erb___2585618892380001236_70185881510980'
app/views/catalog/_show_default.html.erb:10:in `block in _app_views_catalog__show_default_html_erb___3998208847711493484_70186197504580'
app/views/catalog/_show_default.html.erb:4:in `each'
app/views/catalog/_show_default.html.erb:4:in `_app_views_catalog__show_default_html_erb___3998208847711493484_70186197504580'
app/views/catalog/_show_main_content.html.erb:6:in `_app_views_catalog__show_main_content_html_erb__2518532613749834499_70185880922040'
app/views/catalog/show.html.erb:10:in `_app_views_catalog_show_html_erb__676749277960157183_70186182833660'
I, [2018-01-17T09:21:22.717901 #29328]  INFO -- : Processing by ErrorsController#error as HTML
I, [2018-01-17T09:21:22.718022 #29328]  INFO -- :   Parameters: {"id"=>"SCSB-5855877"}
I, [2018-01-17T09:21:22.727165 #29328]  INFO -- : Completed 500 Internal Server Error in 9ms (Views: 8.2ms | ActiveRecord: 0.0ms)```

**Comment by jrgriffiniii** [comment]
Resolved by #1145
