### ISSUE TITLE
CD/DVD sub-facets of Audio/Video formats to allow media-based discovery

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1148]

**Comment by christinach** [comment]
Will review the previous DSSG agenda

**Comment by christinach** [comment]
We're already doing [Video](https://catalog.princeton.edu/?f%5Bformat%5D%5B%5D=Video%2FProjected+medium), [Audio](https://catalog.princeton.edu/?f%5Bformat%5D%5B%5D=Audio)
