### ISSUE TITLE
Install Test Data?

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#115]
@tampakis what is the best way to get going with some test data from PUL with this project? Do I need to get https://github.com/pulibrary/orangeindex setup and pull some of our sample data off the test server?

Or should I just load some marc using: rake solr:marc:index?

Whatever the script is, I'll add it to the README when I get it out.

**Comment by tampakis** [comment]
`rake jetty:clean`
`rake jetty:start`
rspec

**Comment by kevinreiss** [comment]
Sorry, not to run the tests, but load marc into the development database.

**Comment by tampakis** [comment]
The records get loaded before the tests run.

**Comment by jpstroop** [comment]
See #128
