### ISSUE TITLE
Call number browse - only the date is displaying for RDA records

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1155]
e.g., see these call number browses with date-only display for some items:

* https://pulsearch.princeton.edu/browse/call_numbers?search_field=browse_cn&q=cd+46000
* https://pulsearch.princeton.edu/browse/call_numbers?search_field=browse_cn&q=ml410+b42+b49

Should incorporate 262 fields for full publisher info.

**Comment by tampakis** [comment]
Take the first value from the pub_created_display field, not the last one. This field pulls from both the 260 and 264 fields: https://github.com/pulibrary/marc_liberation/blob/master/marc_to_solr/lib/traject_config.rb#L176

**Comment by tampakis** [comment]
https://github.com/pulibrary/orangelight/blob/master/lib/orangelight/browse_lists.rb#L90

**Comment by mzelesky** [comment]
Ideally, there would be a hierarchy of 264 fields (if they exist), based on second indicator of the field:

1. 2nd indicator 0 (used for production info for unpublished materials)
2. 2nd indicator 1 (publication info)
3. 2nd indicator 2 (distribution info)
4. 2nd indicator 3 (manufacture info)
5. 2nd indicator 4 (copyright notice date)

Just in case the 264 with a 2nd indicator 4 comes before any of the other ones.

**Comment by mzelesky** [comment]
The hierarchy I describe above was approved by Joyce and Jennifer at LISSC.
