### ISSUE TITLE
Empty pub_created_display array displayed on search results 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1165]
See the empty array displayed on some records using this example search. https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=CStRLIN

Bib IDs that display this pattern can't be loaded in the record page view: https://pulsearch.princeton.edu/catalog/3567656. In the solr document you can see that pub_created_display is an empty array.

**Comment by tampakis** [comment]
This is going to require a full reindex to fix because they got indexed as empty array strings. In fact every document's pub_created_display field is surrounded by brackets.

**Comment by eliotjordan** [comment]
Related to #1197.
