### ISSUE TITLE
Index Catalog Date?

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#117]
I was looking at this sad [web service](http://library.princeton.edu/catalogs/newtitles.php) (not my words!) for newly catalogued titles:
It needs to get updated manually to be useful. Before today, it hadn't been updated in a month. Maybe we should index the catalog date and integrate this service into Blacklight?

**Comment by jpstroop** [comment]
Github has a feature that allows you to subscribe (via RSS or Atom) to searches. That alone would pretty much kill this, no?

**Comment by jpstroop** [comment]
I think we may need to map relevant index fields to a builder template somewhere...I looked into this very briefly for LAE about a month ago.

**Comment by kevinreiss** [comment]
If the searches could reasonably stand in for the various combinations at http://library.princeton.edu/catalogs/newtitles.php than yes, bringing up a production version of the site could kill this. We might consider a single view that highlights new titles a la http://library.brown.edu/titles.

**Comment by jpstroop** [comment]
Interesting. We'll need a way to distinguish between adds and updates in the index, then. I can probably get that into MARC Liberation, but we will need a field or two in Solr to support this.

**Comment by tampakis** [comment]
It seems like a separate index in Yale's system:
http://search.library.yale.edu/new_arrivals?q=&search_field=all_fields

**Comment by tampakis** [comment]
Err probably just a separate controller
