### ISSUE TITLE
Excessive Summary Holdings Statements From NYPL

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1177]
See https://pulsearch.princeton.edu/catalog/SCSB-5936783. NYPL records appear to have summary holdings generated by combining all item-level enumeration statements. Investigate want can do done on the SCSB to improve the data or figure out how to suppress/compress it using what we currently have in the SCSB partner data.

**Comment by tampakis** [comment]
This seems like a data quality issue. These holdings are item records in voyager
