### ISSUE TITLE
[Orangelight/production] ActionView::Template::Error: undefined method `reverse!' for #<Hash:0x00007f99e51e8d28>

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1178]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/36399053)

**Comment by kevinreiss** [comment]
Change to the data structure of the solr key electronic_access_1display when the key value is ```iiif_manifest_url``` breaks an assumption that the hash key will be a URL and the value will be an array.
