### ISSUE TITLE
Repeated Use Restrictions

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1179]
De-duplicate use restriction displays when the same restrictions is repeated.

https://pulsearch.princeton.edu/catalog/SCSB-8791804

**Comment by kevinreiss** [comment]
The issue here is this particular document has a separate "holding" for each item. The display currently de-duplicates the display value for each holding in the hash in the top-level holdings solr key.

**Comment by tampakis** [comment]
lol
