### ISSUE TITLE
Indexing Routine for Non-MARC

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#118]
What's the format for Theses records? What other types of records are we expecting to import? I could probably do this in Traject. Probably not needed immediately but it came up yesterday.

**Comment by kevinreiss** [comment]
They are in an XML file format that comes from an SQL server database table
dump.

**Comment by kevinreiss** [comment]
I'll get an example file.

**Comment by jpstroop** [comment]
Just emailed one

**Comment by tampakis** [comment]
Theses are done. Issue #421 covers visuals.
