### ISSUE TITLE
Extra commas in published/created display

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1197]
See https://catalog.princeton.edu/catalog/10572977 and https://catalog.princeton.edu/catalog/10578335

**Comment by mzelesky** [comment]
It looks like there's something going on with merging all 260/264s into one line. For example, https://catalog.princeton.edu/catalog/10578335

should have the following lines for the published/created:
Dijon: Éditions universitaires de Dijon, 2017.
©2017

I don't know why there are brackets around the field data in the display.
I remember the display for that field being a multiline display before.
