### ISSUE TITLE
Non-public scanned maps should not display an online link

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1201]
Arks from figgy should not be indexed into the `electronic_access_1display` field for scanned maps that aren't public.

Example: https://pulsearch.princeton.edu/catalog/5284554#view

**Comment by tpendragon** [comment]
You want the 856 to not be indexed for scanned maps if they aren't public in Figgy?

**Comment by eliotjordan** [comment]
The issue is that the ARK url still shows up in the "Online" section of non-public scanned maps, because that ARK is in the 865 field. That ARK points back to the catalog record (with the #view hash fragment appended) which has been pointed out is confusing. After much back-and-forth, the best solution we could come up with is to have the map catalogers remove the ARK from the 856:u field of non-public scanned maps. After all, copyrighted items aren't accessible electronically even though we might have a digital copy of the item in Figgy.

**Comment by escowles** [comment]
Related to #1211

**Comment by eliotjordan** [comment]
Closing this because links are fine now. When the scanned map ARKs all be point to Pulmap will be no issue.
