### ISSUE TITLE
Digital Content Below Label Missing

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1206]
https://pulsearch.princeton.edu/catalog/3093298

This is an open item that is embedded in a view on the page. The link in the Online section is rendering pointed to the ark rather than with the "Digital Content Below" label.

**Comment by tampakis** [comment]
Will be fixed once a full reindex is complete

**Comment by escowles** [comment]
The "Digital content below" label is now showing up now that the updated index is in place.
