### ISSUE TITLE
loading updated records from Voyager

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#121]
@tampakis Nikitas,  I have had catalogers fixing the records with bad non-roman script.  I checked some today in pulsearch-dev and found that they have not been updated there. The changes did go from Voyager to Primo.  An example updated 4/14 and OK in Primo but not in OL: 3058734

**Comment by tampakis** [comment]
I had been running this manually. I have the update task [bundled up](https://github.com/pulibrary/dockerhub/tree/master/images/orangeindex) now on lib-solr1 to run the updates daily at 4:30AM. It takes about 2 minutes.
