### ISSUE TITLE
Display a message when viewer is requested but not displayed

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1211]
We should display some information to the user when they have visited the #view URL, but we are not displaying a viewer for whatever reason.

**Comment by escowles** [comment]
This could be a generic "there may be digital content available by request" kind of notice.  In theory, it would be nice to check in Figgy if there is non-public content that would be available if they logged in.

**Comment by hackmastera** [comment]
e.g. the viewer is only available when logged in
