### ISSUE TITLE
[Orangelight/production] NoMethodError: undefined method `empty?' for nil:NilClass

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1216]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/37087897)

**Comment by kevinreiss** [comment]
I believe this error cropped up during the time bibdata was being re-provisioned this morning. The code here loads holding location and item data from bibdata to populate the params being the request form.
