### ISSUE TITLE
Retire bibdata-worker1

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1220]
Mark Zelesky may be using this

**Comment by mzelesky** [comment]
That's currently where the daily SCSB updates go. The process can be moved to worker2 if that's preferred.

**Comment by tampakis** [comment]
Yeah we shouldn't retire bibdata-worker1 until there is enough space on worker2 (https://github.com/pulibrary/orangelight/issues/1219)

**Comment by tampakis** [comment]
We did retire this
