### ISSUE TITLE
Focus order is illogical on homepage

### ISSUE THREAD

**Issue by axamei** [pulibrary/orangelight#1222]
Focus order is somewhat illogical. The focus is set to automatically be the search box, but could be problematic when users want to access the navigation on the top right, branding bar (help, feedback, and your account). 

However, because there is a search query in the input after doing a search, the focus order on search result pages begin with the library branding and follow a more logical order.

**Comment by christinach** [comment]
The intended behavior is to search; so perhaps it is appropriate to focus on the search input. We should confirm this through user testing / feedback.

**Comment by christinach** [comment]
this is not related any more.
