### ISSUE TITLE
Use first 7xx field for contributor field info in browse lists when there is no 1xx main entry

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/orangelight#1228]
For records with no 1xx field and at least one 7xx field, use the first 7xx field in the record as a basis for a contributor for display in the browse lists. Also, change the label of the 'creator' field in the browse list to 'contributor.' [per LISSC 3/26/18]

**Comment by tampakis** [comment]
Use author_display first, then check to see if there is an author_s field, if so take first value
Example: http://localhost:3000/browse/call_numbers?q=48.1
This record should display Gutenberg for the creator.
Update the browse fixtures for call number.
