### ISSUE TITLE
Bound-with titles not handled properly

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/orangelight#1230]
Marie discovered a problem in our handling of bound-with materials. Any query that uses the bib_item table to get bib IDs from an item ID needs to be updated. I have a branch for voyager_helpers ready to go to deal with this. It affects course reserves and the ReCAP dump jobs.

**Comment by kevinreiss** [comment]
When we get this ready to merge to master let's make sure to move the ReCAP dump job off the old bibdata-dev server to the new production machine.

**Comment by eliotjordan** [comment]
Closed.
