### ISSUE TITLE
By-title Stackmap locations are sending call number instead of title

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/orangelight#1245]
It looks like locations that are supposed to send the title to Stackmap for call numbers are instead sending the call number. Here are examples from each of the by title locations defined here: https://github.com/pulibrary/orangelight/blob/46cfcbdc4433668c51cf965bb7db2a16d2db65be/app/services/stackmap_service.rb#L90

https://catalog.princeton.edu/catalog/3397889 (from pplps)
https://catalog.princeton.edu/catalog/10789948 (from sciss)
https://catalog.princeton.edu/catalog/9134475 (from sprps)
https://catalog.princeton.edu/catalog/9460981 (from spiaps)

I know this used to work, but I don't know when it stopped working.

The data looks to be fine in Stackmap.

**Comment by kevinreiss** [comment]
This check must be failing https://github.com/pulibrary/orangelight/blob/46cfcbdc4433668c51cf965bb7db2a16d2db65be/app/services/stackmap_service.rb#L64.
