### ISSUE TITLE
Implement Browzine API on Search Results and Show Page

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1249]
Query the Browzine API for any issn in a search result or record display. Use the json response to display a link to the current issues of electronic journal content we have subscribed to. Present these links in a to-be-determined location with to-be-determined look/feel. The implementation should be an ajax call. The implementation will likely look similar to the Google Books API integration.

Note the request must strip hyphens:
`https://public-api.thirdiron.com/public/v1/libraries/499/search?issns=0022-0507&access_token=REDACTED`
`{"errors":[{"status":"422","title":"ISSNs must exclude hyphens"}]}`

[Browzine api general / auth info](https://thirdiron.atlassian.net/wiki/spaces/BrowZineAPIDocs/pages/65929220/BrowZine+Public+API+Overview)

[Browzine journal availability api](https://thirdiron.atlassian.net/wiki/spaces/BrowZineAPIDocs/pages/66191466/Journal+Availability+Endpoint)

code powering Google Books API integration: https://github.com/pulibrary/orangelight/blob/master/app/assets/javascripts/book_covers.js.coffee

**Comment by kevinreiss** [comment]
I will get the token needed for this from the vendor.

**Comment by kevinreiss** [comment]
I have the key for this now.

**Comment by kevinreiss** [comment]
The api provides what is essentially the electronic equivalent of the "current issues" we display for print journals.

**Comment by hackmastera** [comment]
"current issues" is a reference to "Location has" under "copies in library" see, e.g. https://catalog.princeton.edu/catalog/357613

**Comment by christinach** [comment]
Ask DSSG if this is a desirable feature.

**Comment by maxkadel** [comment]
@kevinreiss will ask Joe (e-resources manager) about whether this is still desired.

**Comment by kevinreiss** [comment]
Wrote Joe 5/30

**Comment by christinach** [comment]
@kevinreiss what was the update on this ticket? Can we close it?

**Comment by kevinreiss** [comment]
Discussed with ERM team today and this ticket can closed. The ERM team is going to review the current docs for the tool and reach out if their is a new ticket to create for an implementation based on the current API tool.
