### ISSUE TITLE
Require opt-in before enabling Google Analytics

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1251]
To comply with [GDPR](https://www.eugdpr.org/), we must display a notification about tracking cookies (like for Google Analytics) and allow them to opt out.

We are expecting more guidance from campus, but this will at a minimum include:
* Notification that we use cookies to track users
* Notification that some of these cookies (like session cookies) are essential
* Allow opting-out of analytics cookies

**Comment by eliotjordan** [comment]
No longer valid. See #1273
