### ISSUE TITLE
Link from ReCAP veto not working

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1252]
From John Logan:
> The link in each record in the ReCAP veto system to the catalog record for the item now only opens the main search page of the Library Catalog. You now have to copy and paste the bib id into the search window to get the record, and it is not unusual to have to scroll through several records to find the one you want. It would be much preferable to get the record right off.

**Comment by kevinreiss** [comment]
These links are formed as http://catalog.princeton.edu/cgi-bin/Pwebrecon.cgi?bbid=2233458, http://catalog.princeton.edu/cgi-bin/Pwebrecon.cgi?BBID=2233458. I think the redirect needs the params to be case insensitive. I'll see if we can change the link template in the application John is getting them from.
