### ISSUE TITLE
Improve RIS Mapping

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1255]
The RIS export for is using *_display field values when it should be using *_citation_display values instead. Update mapping in https://github.com/pulibrary/orangelight/blob/46cfcbdc4433668c51cf965bb7db2a16d2db65be/app/models/concerns/blacklight/document/ris.rb to reflect this. Open Libanswers ticket from a user about this question. Using *_display can result in wonky citations.

**Comment by tampakis** [comment]
Update the ris_field_names hash with the following mapping:
```
{
  title_citation_display: 'TI',
  call_number_display: 'CN',
  form_genre_display: 'M3',
  summary_note_display: 'AB'
  notes_display: 'N1',
  source_acquisition_display: 'N1', # Check to see if multiple notes can be included
  edition_display: 'ET',  # check to make sure zotero imports this field as ET
  number_of_pages_citation_display: 'SP'
}
```
remove description_display: 'N2',
