### ISSUE TITLE
Removing Formats in Advanced Search > Edit doesn't work

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1267]
Steps to reproduce:
1. perform an advanced search with a format
2. click "Edit search"
3. remove the format
4. click "Search"
5. the format limit is still present

**Comment by christinach** [comment]
Marked it as a bug. Every time I 'edit' and click search it populates the selected 'chosen' field.

**Comment by christinach** [comment]
While testing I came across:
![screen shot 2018-06-15 at 4 25 38 pm](https://user-images.githubusercontent.com/9905193/41488075-13b53368-70b9-11e8-8db3-8b710a238e52.png)
