### ISSUE TITLE
Digital content: display thumbnail with "Digital content" link

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1280]

**Comment by escowles** [comment]
Use instead of generic book icon

**Comment by jrgriffiniii** [comment]
After discussing this earlier today (09/10/18), it was decided that resolving this by addressing https://github.com/pulibrary/orangelight/issues/1359 would be the most straightforward approach.

**Comment by jrgriffiniii** [comment]
Resolved by #1361
