### ISSUE TITLE
Issue displaying viewer for item in IE

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1295]
Tom Ventimiglia reported an error for this item: https://catalog.princeton.edu/catalog/3554952

The viewer for the Figgy object is not displayed in UV.

@jrgriffiniii was able to confirm that for IE 11.0.70 UV breaks for that item

> From what I could determine, the AJAX requests for `books.google.com/books/content?id=[…]` images triggered errors in the IE console which I could not reproduce in Chrome or Firefox

**Comment by christinach** [comment]
Updated ajax viewer file to be compatible with IE11.
