### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#130]
Perhaps as an option for users that only have a barcode. Would be nice to be able to link your barcode to OAuth-based account. See also #109, #110.

**Comment by jpstroop** [comment]
@tampakis @kevinreiss @tpendragon thoughts about this approach? I'm sure there would still be users that prefer to key in their barcode, but this feels like it would be a more convenient option.

**Comment by kevinreiss** [comment]
I think OAUTH is a great long-term goal but for the roll-out in the next couple of weeks I think we are going to have go with injecting a new landing page in front of the account controller that gives unauthenticated users a choice between starting a login via Princeton CAS or supplying their lastname/barcode as a fall back option. 

A couple of issues to consider for the long-term:
1. OIT tells me that they will soon move both the employee staff/CAS endpoint and tigernet (the alumni CAS implementation) to CAS 5 and activate the OAUTH support available in that version. This would enable us to use OAUTH active pul community members, alums, as well as other users that might want to use to other OAUTH endpoints. 
2. I don't believe the "Friend" or "Guest" accounts people obtain to get Library privileges require users to give an email address. If we are going to make OAUTH the default option and remove any sort of barcode fallback we'll need to make sure users have a valid email address from an OAUTH compliant service.

**Comment by tpendragon** [comment]
@jpstroop Which O-Auth provider are you thinking of? "Login with Google" kind of thing?

Is there a way to validate barcodes/last names or do we just not care for these purposes?

**Comment by kevinreiss** [comment]
I think we'd want to validate the barcodes. The patron endpoint in bibdata can accept a barcode as param:

https://bibdata.princeton.edu/patron/{barcode}

**Comment by jpstroop** [comment]
It seems like it could lead to public services issues if users w/ Princeton creds starting logging in with an OAuth provider. Closing and will open a new issue if a real reason surfaces.
