### ISSUE TITLE
Covers

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#131]
Somewhat related to #106 (for search results).

Options: 
 * Umlaut (would require an OpenURL embedded on the page cf. #85)
 * Hit Amazon, Google, Hathi directly

**Comment by tampakis** [comment]
Bowker, Syndetic are other options.

**Comment by jpstroop** [comment]
From Marvin:
> We may be entitled to the Bowker ones, since we have so many other ProQuest subscriptions.
>
> I can check if you’d like.

**Comment by jpstroop** [comment]
Yes, that would be great, thanks
