### ISSUE TITLE
Create Unified Stackmap View

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1312]
Currently the "Where to find it" links on the show page and the map icon on the search results page direct you completely out of OL to our two shelf mapping tools. 

1. Firestone Library - https://library.princeton.edu/locator/index.php?loc=f&id=9242335
2. Branch Libraries - https://princeton.stackmap.com/view/?callno=QP38+.H666+2008&library=Lewis+Library&location=sci

The firestone tool provides some very outdated looking "help" options and the stackmap service doesn't provide anything. It would be good to provide a consistent experience with a common set of help options in a nicer looking and more readable display irregardless of the stackmap tool invoked. 

Both tools offer an "embeddable" version of their maps: 
1. Add the "embed=true" flag to the Firestone serice https://library.princeton.edu/locator/index.php?loc=f&id=9242335&embed=true
2. Utilize the Stackmap API to construct the map. See docs for the api in the OL team folder: https://drive.google.com/drive/folders/1lDOSa5mzlGp6ZA_nb14TwHAt1xprk-sB. See an implementation of this API in searchworks under the "check availability" option for on-site physical resources: https://searchworks.stanford.edu/?f%5Baccess_facet%5D%5B%5D=At+the+Library&f%5Bbuilding_facet%5D%5B%5D=Green&f%5Bformat_main_ssim%5D%5B%5D=Book. 

Our reference librarians on the WSG recommended including each "embeddable" map on a page header consisting of two menu options.

1.  Our "trace a missing book" service"
2. An option to go to a form that sends in a question to our lib answers reference queue. 

This newly unified view could be rendered as a modal the user gets after selecting a "where to find it" link, or an entirely separately view in OL at a new route that displays the new common menu items and the map together. 

Child of #1314

**Comment by tampakis** [comment]
Closed by #1559
