### ISSUE TITLE
Show page wireframe

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1313]
Address issues surfaced in usability testing, and move viewer to the top of the page.

**Comment by axamei** [comment]
Questions
- What level of detail do we want to present initially to our users?
- What is the default action we want users to perform on the item record page?
- more soon...

**Comment by kevinreiss** [comment]
*ReCAP label should clarify that it is our off-site storage facility. Maybe change to “ReCAP (Off-site Storage)”
*Availability labels are not clear / do not communicate availability to user. Perhaps we need to review these and present some alternatives that can be tested with users.

**Comment by christinach** [comment]
https://docs.google.com/document/d/1AniVQ-Zt5GY2xKmOzQ8pACU29mikT7pQTX9YCJ2rATA/edit
https://docs.google.com/document/d/1-sIz6mf8n7bXc_ayiZOdQUvjn2bi7I0HG37ab4aoAxI/edit

**Comment by axamei** [comment]
Include a mockup for complicated holdings

**Comment by axamei** [comment]
[Updated wireframes](https://xd.adobe.com/view/2dcc57fd-3f03-4e5d-4a31-1493c363013c-5bfd/)

**Comment by hackmastera** [comment]
these look really nice, @axamei 

Should https://github.com/pulibrary/orangelight/issues/1370 be part of the discussion here or should it be separate?

**Comment by tampakis** [comment]
Closing, wireframes have been created: https://xd.adobe.com/view/2dcc57fd-3f03-4e5d-4a31-1493c363013c-5bfd/
