### ISSUE TITLE
load denied by X-Frame-Options

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/orangelight#1328]
When staff use FireFox to access Orangelight via a link out from OCLC WorldCat, the following error appears:

Load denied by X-Frame-Options: https://catalog.princeton.edu/catalog?q=oclc_s%3A24167 does not permit cross-origin framing.

Kevin says this is a new header we need to set in the OL app.

**Comment by kevinreiss** [comment]
@mzelesky  could yousend a link to an OCLC that creates this error. I can't remember if this is worldcat.org or firstsearch?

**Comment by tampakis** [comment]
@mzelesky is this still an error?
