### ISSUE TITLE
Login form hides barcode login option when you visit it from a request button

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1332]
As an "unauthenticated" user if you visit a requestable item, ex: https://catalog.princeton.edu/requests/SCSB-8354369, and select the "Request" button you are taken to a screen and are presented with three options.

1. CAS/Princeton Net ID
2. Barcode
3. I don't have a net ID or barcode

Options 1 and 3 work as expected. Option 2 takes you to a screen that has the actual barcode login form hidden behind a link marked "No netID? Log in with your barcode" on our standard OL sign_in form at https://catalog.princeton.edu/users/sign_in. When a user invokes this from the context of the barcode option on the request form the barcode login form should be visible on page load. Ideally we'd probably not even show the CAS option at all since the user has already selected barcode. 

Potential complication, the sign in form is also invoked in the context of the "My Account" features where we do want users to prefer CAS over barcode authentication.

**Comment by tampakis** [comment]
We have processed a newer request from circ staff about the login to reflect updated needs
