### ISSUE TITLE
Research how to trigger invalid "back to search" link

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#1336]
## Backtrace

    line 39 of [PROJECT_ROOT]/config/initializers/blacklight_url_helper_behavior.rb: link_back_to_catalog
    line 9 of [PROJECT_ROOT]/app/views/catalog/_previous_next_doc.html.erb: _app_views_catalog__previous_next_doc_html_erb___141562302411537421_70097437451980
    line 1 of [PROJECT_ROOT]/app/views/catalog/show.html.erb: _app_views_catalog_show_html_erb__621661626053428788_36727780

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/36655673)

**Comment by escowles** [comment]
Users reported leaving results open for more than a day — maybe session timeouts are the core issue here?

**Comment by christinach** [comment]
check #1458 #1455

**Comment by escowles** [comment]
Anya Bartelmann just reported seeing this issue today: https://app.honeybadger.io/projects/54399/faults/36655673

The error looks like it's happening when trying to calculate the link back to the search results:
https://github.com/pulibrary/orangelight/blob/master/config/initializers/blacklight_url_helper_behavior.rb#L39

We should probably just rescue StandardError to prevent this.

**Comment by christinach** [comment]
I don't think we should rescue StandardError without checking first #1458 and #1455.

**Comment by christinach** [comment]
closing in favor of https://github.com/pulibrary/orangelight/issues/4011
