### ISSUE TITLE
Update indexing routine to handle data quality issues in the linked contained_in_s id field

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#1339]
## Backtrace

    line 23 of [PROJECT_ROOT]/app/services/faceted_query_service.rb: get_fq_solr_response
    line 83 of [PROJECT_ROOT]/app/services/linked_document_resolver.rb: response
    line 21 of [PROJECT_ROOT]/app/services/linked_document_resolver.rb: siblings

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/36780573)

**Comment by tpendragon** [comment]
I assume what's causing the problem is the requested `id` has a `#` in it.

**Comment by christinach** [comment]
https://bibdata.princeton.edu/bibliographic/2910021
```
<datafield ind1="0" ind2=" " tag="773">
    <subfield code="7">c2as</subfield>
    <subfield code="a">Bibliophile Society (Boston, Mass.)</subfield>
    <subfield code="t">Annual report of the Bibliophile Society for ...</subfield>
    <subfield code="g">27th (1929)</subfield>
<subfield code="w">(OCoLC)#4163933</subfield></datafield>
```

**Comment by christinach** [comment]
https://github.com/pulibrary/marc_liberation/blob/master/marc_to_solr/lib/traject_config.rb#L534
