### ISSUE TITLE
Include date in mouse hover for lost items

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1342]
This item is lost: https://catalog.princeton.edu/catalog/3491821
Display the date that the library declared the item lost when hovering over the item status. This will probably require an update to the SQL query in Voyager Helpers and an update to the availability API in Marc Liberation. Hopefully @mzelesky knows the query.

**Comment by mzelesky** [comment]
This will require retrieving the item status dates along with the item status labels.

**Comment by tampakis** [comment]
This was put on hold by the DSSG

**Comment by kevinreiss** [comment]
We no longer display the details of item status in the catalog. Given that this feature request is no longer relevant. Closing.
