### ISSUE TITLE
Rack::QueryParser::InvalidParameterError: Invalid encoding for parameter: ??��???

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1345]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/37610772)

```
GET https://catalog.princeton.edu/catalog?q=%3F%3F%A3%A4%3F%3F%3F&search_field=all_fields&format=json&per_page=5
```

```
 unless params.valid_encoding?
   # Raise Rack::Utils::InvalidParameterError for consistency with Rack.
   # ActionDispatch::Request#GET will re-raise as a BadRequest error.
   raise Rack::Utils::InvalidParameterError, "Invalid encoding for parameter: #{params.scrub}"
end
```

**Comment by eliotjordan** [comment]
@kevinreiss says this is coming from the Bento Box on the main library website. User input or perhaps a crawler. Is there a way to figure out what's driving this? It seems very consistent. Or can we scrub parameters like this before they hit Rails?

**Comment by kevinreiss** [comment]
I can't into it today but I'll try and see if the current bento code can be modified to not even run these queries.
