### ISSUE TITLE
Form/Genre subject subdivisions without punctuation

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#1352]
The form/genre headings displaying in the catalog have no punctuation between subdivisions making them difficult to interpret.  Below are two examples.

Twice / Stuart Mills ; [embroideries by Laurie Clark].
Link: https://catalog.princeton.edu/catalog/10863069
655 staff view: 655 7 a| Poems z| England y| 1977. 2| aat
655 public view: Poems England 1977.

In visible cities : [an artist book / by Jean-Pierre Hébert].
Link: https://catalog.princeton.edu/catalog/8881543
655 staff view: 655 7 a| Artists' books z| California z| Isla Vista y| 2012. 2| rbgenr
655 public view: Artists' books California Isla Vista 2012.

**Comment by jrgriffiniii** [comment]
This can only be resolved once either https://github.com/pulibrary/marc_liberation/pull/461 is merged or https://github.com/pulibrary/marc_liberation/issues/460 is resolved by further actions undertaken in response to the requirements of the Authorities Committee.
