### ISSUE TITLE
Course Reserves Currently Not Working

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1369]
Probably something to do with solr cloud migration

**Comment by tpendragon** [comment]
Course Reserves depends on a cross-collection join for performance reasons, and it might not work in solr cloud. :(

https://community.hortonworks.com/articles/49790/joining-collections-in-solr-part-i.html

**Comment by christinach** [comment]
@tampakis added in solrAdmin 3 replicas for the reserves core. It fixes the issue.
