### ISSUE TITLE
Does ./bundle need to be in repo?

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#137]
Google says there was a bug with installing Nokogiri on some platforms. Is this still the case? If so, perhaps this should be a feature the user implements rather than baked into the repo. Maybe reference this in the README.

[.gitignore](https://github.com/pulibrary/orangelight/blob/d7618d043f6787143891a0462cbdeca7c270d8d2/.gitignore#L7-L8)

**Comment by kevinreiss** [comment]
I don't think you want .bundle in a repo.

**Comment by tampakis** [comment]
Back in ad8d9d, I added .bundle to the repo. I just installed a fresh orangelight from the repo without the nokogiri config and it worked fine. This was also added before we set up pulsearch-dev with capistrano so I think this issue has been resolved.
