### ISSUE TITLE
Does anyone use result set paging links on show pages?

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1370]
There are lots of errors we think might be related to this feature — do users use this?

**Comment by tpendragon** [comment]
My two cents: I think "back to search" and "next" from a catalog record page is a representation of an anti-feature. The browser has "back" and clicking "next" to blindly go between catalog records when you could just return to the results and quickly get to what you want slows down the user experience and is probably confusing - when I hit next am I getting to a related item? When I get a next window from an external link because I had a search in the past, what's going on there, etc

**Comment by axamei** [comment]
@hackmastera we could mock this up as part of #1313. do we have any data / are we tracking this behavior in matomo?

**Comment by hackmastera** [comment]
@axamei We aren't tracking it, no.

From conversations on our team, there seem to be a few different reasons for general distaste on this issue:
a) maybe it's not used (if we want to pursue this we should set up tracking) -- a corollary to this is that there exist browser features (open in a new tab, the back button) that serve the same kinds of use cases this functionality looks to serve.
b) @tpendragon's comment above about clicking blindly being broken UX.
c) technical concern about the fact that this functionality is implemented using sessions, and therefore doesn't work correctly when a user opens more than one tab and navigates different searches between them.

It seems like b and c might be compelling enough reasons to remove the feature. If we also need usage data then we should make a sub-ticket for adding the tracking.

**Comment by escowles** [comment]
I think we might be able to get usage data from the existing logs — it seems like show page hits where the referer is also a show page would mostly be this, and otherwise I'd expect the referer to be search results pages (or blank).

**Comment by tampakis** [comment]
FWIW i've been actually using the feature a lot this week for searches with about 5 search results where it's unclear to me which of the results is something that I am looking for.

**Comment by escowles** [comment]
I did a quick-and-dirty dig through some Orangelight logs, and found that about 1.6% of our show pages with referrers look like next/previous clicks.  This is something like 600 over the past 10 days, so I don't think it's only @tampakis.  That said, I did notice that 5 library staff IP addresses account for 93% of those paging requests.

**Comment by axamei** [comment]
Can we identify these 5 library staff users? It would be helpful to have a conversation with them about their use of this feature. 

Are any of the other Blacklight institutions facing this same issue?

**Comment by tampakis** [comment]
We think that this needs to be continued to be supported. Will revisit if more bugs are reported.
