### ISSUE TITLE
[Orangelight/production] NoMethodError: undefined method `key?' for nil:NilClass

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1371]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/39527029)

**Comment by christinach** [comment]
[GEM_ROOT]/bundler/gems/requests-9f3ba5886877/app/models/requests/requestable.rb:258 :in `pageable?`
256       if charged?
257         nil
258       elsif !holding.first[1].key?('call_number_browse')
259         nil
260       elsif paging_locations.include? location['code']

**Comment by christinach** [comment]
created https://github.com/pulibrary/requests/issues/379

**Comment by christinach** [comment]
There is an issue in `requests` to address this error.
