### ISSUE TITLE
Prevent the request form from breaking if mfhd is nil

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1372]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/39535759)

**Comment by christinach** [comment]
[GEM_ROOT]/bundler/gems/requests-9f3ba5886877/app/helpers/requests/application_helper.rb:228 :in `hidden_fields_mfhd`
226     def hidden_fields_mfhd mfhd
227       hidden = ""
228       unless mfhd["call_number"].nil?
229         hidden += hidden_field_tag "mfhd[][call_number]", "", value: "#{mfhd['call_number']}"
230       end

**Comment by christinach** [comment]
This issue comes from the gem 'requests'. In this case one mfhd was nil and it was raising an error, breaking the form. After setting the correct SOLR_URL in the web bibdata server and reindexing the record, the specific mfhd was not nil. To be more specific the first request was including 
```
@holding={"10671769"=>nil}, 
```
while after reindexing the record it was updated to:
```ruby
@holding={"10671769"=>{"location"=>"Architecture Library", "library"=>"Architecture Library", "location_code"=>"ues"}}
```

**Comment by jrgriffiniii** [comment]
As the `requests` routes are just mounted and not overridden:
```ruby
[...]
    scope module: 'orangelight' do
    get 'browse', to: 'browsables#browse'
    get 'browse/call_numbers', model: Orangelight::CallNumber, to: 'browsables#index'
    get 'browse/names', model: Orangelight::Name, to: 'browsables#index'
    get 'browse/name_titles', model: Orangelight::NameTitle, to: 'browsables#index'
    get 'browse/subjects', model: Orangelight::Subject, to: 'browsables#index'
  end
  mount Requests::Engine, at: '/requests'
[...]
```
(https://github.com/pulibrary/orangelight/blob/master/config/routes.rb#L16)

...this is only resolved by https://github.com/pulibrary/requests/pull/385

**Comment by jrgriffiniii** [comment]
Updating this to use the branch for https://github.com/pulibrary/requests/pull/385 passes: https://circleci.com/gh/pulibrary/orangelight/393

**Comment by escowles** [comment]
Fixed by not indexing records without MFHDs
