### ISSUE TITLE
[Orangelight/production] Blacklight::Exceptions::ECONNREFUSED: Connection refused - Unable to connect to Solr instance using

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1375]
## Backtrace

    line 16 of [PROJECT_ROOT]/app/helpers/blacklight_helper.rb: search_results

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/39544131)

**Comment by christinach** [comment]
solr cloud connection issue. maybe look into the load balancer?
