### ISSUE TITLE
Explore integrating/developing Rack Middleware in order to handle Rack::QueryParser::InvalidParameterErrors

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1379]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/37610268)

**Comment by tpendragon** [comment]
@escowles We could just ignore this, but if we want to try and send a better response code to things like this I think we'd need some sort of rack middleware to catch invalid URLs and send an appropriate 4xx response without throwing to honeybadger. Would you like us to work on that or just mark this as ignored in honeybadger?

**Comment by escowles** [comment]
This looks like it's happening fairly frequently, so I think it's worth at least investigating possible fixes.

The reported URL is ~255 characters long, so maybe there's something that's truncating it at some point?  Maybe there are existing Rack (or nginx) plugins to at least handle this error better?

**Comment by jrgriffiniii** [comment]
https://github.com/rack/rack/issues/337 discusses this and confirms that Rack middleware is the best approach for handling this.
