### ISSUE TITLE
Display multiple Online Links in search results

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1386]
I'm not sure if we are thinking about refactoring the display in the search results, but a catalog feedback message suggests that there may be some potential improvements there as well.

This record has 2 online links: https://catalog.princeton.edu/catalog/10914777

The search results view only displays one, which could be problematic because users may click on the online without knowing we have access to volume 2 as well by viewing the record: https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=10914777

**Comment by christinach** [comment]
I think we should refactor the 'search results' and display a 'more >>' link if there are more than 1 or 2 online links. 
The 'more >>' link would direct to the show page where the user would view the full 'Online' list.

**Comment by kevinreiss** [comment]
close in favor #3824 which as has specific recommendation.
