### ISSUE TITLE
[Orangelight/production] NoMethodError: undefined method `[]' for false:FalseClass

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1389]
## Backtrace

    line 16 of [PROJECT_ROOT]/app/helpers/blacklight_helper.rb: search_results

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/39635992)

**Comment by tpendragon** [comment]
Needs replication. Real users are triggering this error.
