### ISSUE TITLE
On-site access green or orange?

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1393]
Theses display orange: [In Library access](https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&f%5Baccess_facet%5D%5B%5D=In+the+Library&f%5Bformat%5D%5B%5D=Senior+thesis&search_field=all_fields&q=id%3Adsp*)
Most other things are green: https://catalog.princeton.edu/catalog?f[location_code_s][]=hycrf

**Comment by christinach** [comment]
@tampakis the first link doesn't return something. What is the id:dsp in the search?

**Comment by tampakis** [comment]
The records with id starting with dsp are senior theses records loaded from DataSpace. They aren't marc records so they probably have a different method used for displaying the availability status

**Comment by christinach** [comment]
Thanks @tampakis. Can we make them all green?

**Comment by christinach** [comment]
I will look through the availability file and we can decide.

**Comment by tampakis** [comment]
It's this line I believe: https://github.com/pulibrary/orangelight/blob/b75e99801ae7c335b33e8f14438b1f54023df486/app/helpers/application_helper.rb#L209

**Comment by christinach** [comment]
I understand where the bootstrap classes colors are set. My main question in the meeting was if it makes sense to write down the current logic and how the colors are set before we apply a new change in the colors.
