### ISSUE TITLE
Better handle errors where invalid location codes get added to bib holding records

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1394]
## Backtrace

    line 71 of [PROJECT_ROOT]/app/services/holding_requests_adapter.rb: sort_by
    line 71 of [PROJECT_ROOT]/app/services/holding_requests_adapter.rb: sorted_physical_holdings
    line 420 of [PROJECT_ROOT]/app/services/physical_holdings_markup_builder.rb: physical_holdings

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/37296416)

 https://catalog.princeton.edu/catalog/4087706

**Comment by hackmastera** [comment]
here's the holdings for this record from solr
```
"holdings_1display":"{\"9323232\":{\"location\":\"Firestone Library\",\"library\":\"Firestone Library\",\"location_code\":\"f\",\"call_number\":\"DA911.2 .D86 2015\",\"call_number_browse\":\"DA911.2 .D86 2015\",\"location_has\":[\"Vol. 1-v. 2\"]}}",
```

**Comment by hackmastera** [comment]
I see the following at the bibdata holdings_locations endpoint:

```
{"label":"","code":"f","aeon_location":false,"recap_electronic_delivery_location":false,"open":true,"requestable":false,"always_requestable":false,"circulates":true,"url":"https://bibdata.princeton.edu/locations/holding_locations/f.json","library":{"label":"Firestone Library","code":"firestone","order":1},"holding_library":null,"hours_location":{"label":"Firestone Library - Building and Circulation/Reserves Hours","code":"firestone"}}
```

**Comment by hackmastera** [comment]
I've locally run the code that queries that hash and it comes out with an int -- `0`.

Perhaps there was a network hiccup at some point and the result was cached? Right now my only idea is to clear the rails cache. This could probably be done with a deploy; not sure if there is a better way.

**Comment by eliotjordan** [comment]
This issue has reappeared.

https://catalog.princeton.edu/catalog/7261976

**Comment by tampakis** [comment]
Catch the error in rails and use `Honeybadger.notify` to alert us that there is a data quality error for a record if an invalid location code gets indexed.

**Comment by christinach** [comment]
we dont index when an invalid location
