### ISSUE TITLE
Improve browse list performance

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#140]
Indexing the searched fields in the database didn't speed things up. Sometimes it really lags. One observation I have is that the browse search worked really well for authors and subjects before I loaded all of the call numbers in, so I think it is a question of finite memory resources. There are probably other postgres tuning strategies as well.
For starters: https://wiki.postgresql.org/wiki/Performance_Optimization

**Comment by kevinreiss** [comment]
Doing something similar for Mysql on othe prohects led to substantial improvements. Defintely worth putting some time in in this.

**Comment by kevinreiss** [comment]
Doing something similar for Mysql on othe projects led to substantial improvements. Defintely worth putting some time in in this.

**Comment by tampakis** [comment]
I set up the postgres database on a new server and browse is a lot faster!

**Comment by tampakis** [comment]
Also set in `/etc/postgresql/9.1/main/postgresql.conf`
```
#------------------------------------------------------------------------------
# RESOURCE USAGE (except WAL)
#------------------------------------------------------------------------------
shared_buffers = 4GB 
#------------------------------------------------------------------------------
# QUERY TUNING
#------------------------------------------------------------------------------
effective_cache_size = 8GB
```
In terminal: `sysctl -w kernel.shmmax=4518265088`

**Comment by jpstroop** [comment]
Great! Did someone provision a new VM or what?

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by tampakis** [comment]
I got John to allocate 16GB of RAM to pulsearch-prod which we hadn't been in use.

**Comment by jpstroop** [comment]
Cool.

-Js

Sent via mobile. Please excuse typos, brevity, etc.
