### ISSUE TITLE
61x field dsplay

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#141]
See, e.g.: 

(in orangelight:) http://pulsearch-dev.princeton.edu/catalog/8932138
(in Voyager:) http://catalog.princeton.edu/cgi-bin/Pwebrecon.cgi?BBID=8932138
(data:) http://bibdata.princeton.edu/bibliographic/8932138

The 610 field

```
610 10 $a United States. $t Fugitive slave law (1850)
```

is displaying properly in Voyager but as `United States.—Fugitive slave law (1850)` in Orangelight. Presumably the string should not be separated by em dashes (just left as is, correct, @joycebcat?), and we probably shouldn't bother with the broad to narrow link-to-canned search feature either.

**Comment by joycebcat** [comment]
6xx field display between subfields isn't always a dash. Before |v |x |y |z it should be a dash.  Before |t just a space.  Other subfields should not be preceded by any special punctuation, they should already have the appropriate punctuation.
