### ISSUE TITLE
Make favicon transparent

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#1412]
Small thing, but the macOS dark mode making it more noticable:

<img width="78" alt="screen shot 2018-10-03 at 11 50 51 am" src="https://user-images.githubusercontent.com/999701/46432329-e58ec080-c702-11e8-9f5b-6c00ccaba180.png">

**Comment by christinach** [comment]
I don't think we should change the background to transparent. What if a user uses an orange chrome theme?
<img width="73" alt="screen shot 2018-10-05 at 4 28 38 pm" src="https://user-images.githubusercontent.com/9905193/46558669-def77900-c8bb-11e8-86af-cf536871c7ce.png">

**Comment by tampakis** [comment]
Closing this because a branding decision should be made across all apps
