### ISSUE TITLE
Break up the 245 field on the show page

### ISSUE THREAD

**Issue by axamei** [pulibrary/orangelight#1425]
The current show page displays the entire 245 field, e.g., 
```a| The neighborhoods of Brooklyn / c| introduction by Kenneth T. Jackson ; John B. Manbeck, consulting editor. ```
See: https://catalog.princeton.edu/catalog/4246093. 

It would be much more readable if we could display 245a and 245c on two different lines as different html elements. See: https://xd.adobe.com/view/2dcc57fd-3f03-4e5d-4a31-1493c363013c-5bfd/screen/dcad339b-b3b9-4382-8060-b364a2b7f7eb/Catalog-Item-Record-Book

Related to #1313

Child of #1314

**Comment by mzelesky** [comment]
Be sure to account for the 245b, likely placing it on the same line as 245a.

**Comment by jrgriffiniii** [comment]
Should this be addressed during indexing using separate fields?  If so, I can offer the changes introduced in https://github.com/pulibrary/marc_liberation/compare/orangelight-issues-245-break-up?expand=1

**Comment by mzelesky** [comment]
Again, I think the 245b needs to be included with the 245a, since that is also title information (as opposed to author information in the 245c).

**Comment by tampakis** [comment]
@jrgriffiniii for now I recommend using the title_citation_display as the top line and using the title_display minus the title_citation_display field as the second line so we won't have to do a full reindex to test out the design in staging

**Comment by christinach** [comment]
Decided before the show page redesign.
