### ISSUE TITLE
Display thumbnails from Figgy

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1428]
@jrgriffiniii I think that based on the work here, we are already well-along with this feature: https://github.com/pulibrary/orangelight/pull/1361

Child of #1314

**Comment by jrgriffiniii** [comment]
This was actually introduced as a new feature in https://github.com/pulibrary/orangelight/pull/1361, but  https://github.com/pulibrary/princeton_ansible/pull/329 does not seem to have provided the staging and production URL's for https://github.com/pulibrary/orangelight/blob/master/config/global/graphql.yml#L2

**Comment by jrgriffiniii** [comment]
Blocked by https://github.com/pulibrary/princeton_ansible/pull/394

**Comment by tampakis** [comment]
We did this!
