### ISSUE TITLE
RefWorks import error for diacritics. Do we support RefWorks?

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1439]
I was looking at a potential import issue into RefWorks for records with diacritics. Do we support RefWorks any more? I [set up an account](https://refworks.proquest.com/) to test out the problem. From this record:
https://catalog.princeton.edu/catalog/1001582
Click "Send to" (next to bookmark) and then "RefWorks."
Log in to refworks.
Get error "Import failed"

Here's what the file RefWork imports looks like:
https://catalog.princeton.edu/catalog/1001582.refworks_marc_txt

**Comment by tampakis** [comment]
Will bring up with Audrey Welber and DSSG.

**Comment by christinach** [comment]
We can check if this works now with the new blacklight upgrade.

**Comment by christinach** [comment]
This is fixed.
