### ISSUE TITLE
Author/Title browse should ignore articles for sorting

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1446]
They currently sort including articles, e.g.:

Hardy, Thomas, 1840-1928. Talks with Thomas Hardy at Max gate, 1920-1922 (1)
Hardy, Thomas, 1840-1928. Talks with Thomas Hardy at Max Gate, 1920-1922 (2)
Hardy, Thomas, 1840-1928. Tess in the theatre (1)
Hardy, Thomas, 1840-1928. Tess of the d'Urbervilles (21)
Hardy, Thomas, 1840-1928. Tess of the D'Urbervilles (7)
Hardy, Thomas, 1840-1928. Tess of the d'Urbervilles. Russian (1)
Hardy, Thomas, 1840-1928. Tess z d'Urbervillů (1)
Hardy, Thomas, 1840-1928. The architectural notebook of Thomas Hardy (2)
Hardy, Thomas, 1840-1928. The bedside Thomas Hardy (1)
Hardy, Thomas, 1840-1928. The complete poetical works of Thomas Hardy (1)
Hardy, Thomas, 1840-1928. The Dorsetshire labourer (1)
Hardy, Thomas, 1840-1928. The duke's reappearance (1)
Hardy, Thomas, 1840-1928. The dynasts (12)

**Comment by christinach** [comment]
There is no programmatic language agnostic way to know if a title in the 7xx filed begins with an article. 
The cataloging convention is that you shouldn't put an article in the beginning of a title in a 7xx field.
