### ISSUE TITLE
Sending an email with a blank subject and message throws an error

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#1447]
## Backtrace

    line 6 of [PROJECT_ROOT]/app/models/record_mailer.rb: email_record
    line 43 of [PROJECT_ROOT]/app/controllers/concerns/orangelight/catalog.rb: email_action

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/36189905)

**Comment by tampakis** [comment]
No longer errors!
