### ISSUE TITLE
Aim for a Cornell-like record page

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#145]
E.g. :https://newcatalog.library.cornell.edu/catalog/3628296

**Comment by kevinreiss** [comment]
Do we want to provide the entire availability panel from the umlaut/getit app? I think all this can be provided from services available in that app already.

**Comment by jpstroop** [comment]
Maybe, but that would be separate from the real-time availability from Voyager (which @tampakis is starting to work on), right?

**Comment by kevinreiss** [comment]
We should discuss how to best implement this. I see this as two levels of service with contextual behavior based on the format of the material you are looking at.

**Comment by kevinreiss** [comment]
Basically you can have any or all service areas provided by umlaut if you implement and configure this simple jquery plugin:

https://github.com/team-umlaut/umlaut/wiki/JQuery-Content-Utility

For example you could ask for just the "holdings" service.

**Comment by kevinreiss** [comment]
The holdings service needs to be rewritten to use bibdata and I would like to make it pluggable for other data sources like finding aids, etc.
