### ISSUE TITLE
'Back to search' redirects to a Bad Request

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#1455]
check this example:
https://catalog-staging.princeton.edu/?page=3&q=&search_field=all_fields
https://catalog-staging.princeton.edu/catalog/10875023
click on 'Back to Search'  --> Bad Request

**ACCEPTANCE CRITERIA**
- [ ] If a user gets a bad request, it should not display an error, it should log the error, give the user a useful message (e.g., flash message: "Unexpected error." and send them back to the front page.)

**Comment by christinach** [comment]
Steps to reproduce:
- catalog
- empty search
- select page 3
- select a book
- back to search --> Bad Request

**Comment by escowles** [comment]
I think the difference between the original search and the "back to search" link is that the latter is missing the `q=` parameter.

**Comment by tampakis** [comment]
Solution may involve adding the utf8 param in the back to search link?

**Comment by christinach** [comment]
This is still an issue. Reproduce following https://github.com/pulibrary/orangelight/issues/1455#issuecomment-435360419

**Comment by christinach** [comment]
@hectorcorrea and I tested this again and it's still a problem.

**Comment by hectorcorrea** [comment]
Two users (Carol and Minje) have reported what seems to be similar versions of this issue, see https://pulibrary.slack.com/archives/CA0UY0Q07/p1631629023039800

**Comment by hectorcorrea** [comment]
See also https://github.com/pulibrary/orangelight/issues/2726

**Comment by christinach** [comment]
@hectorcorrea the issue that was reported is not the error page of this issue but https://github.com/pulibrary/orangelight/issues/2726 which is a journal facet.
