### ISSUE TITLE
[Orangelight/production] NoMethodError: undefined method `gsub' for ["0", "Audio"]:Array

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1459]
## Backtrace

    line 23 of [PROJECT_ROOT]/app/helpers/blacklight_helper.rb: search_results
    line 493 of [PROJECT_ROOT]/app/controllers/catalog_controller.rb: index
    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/41004925)

**Comment by jrgriffiniii** [comment]
Duplicates #1430
