### ISSUE TITLE
Managing bookmarks between Spot/Arc/[Geo]Blacklight installations

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/orangelight#1463]
Active users of catalog.princeton.edu have enquired as to what would be necessary in order to ensure that users who bookmark item records on other Blacklight-based platforms can share access to these bookmarks (e. g. creating a bookmark on lae.princeton.edu creates a bookmark on catalog.princeton.edu).  If this cannot not be supported, perhaps the user experience for those Blacklight platforms which do *not* serve as the primary catalog can be shaped in order to avoid this expectation or feature request in the future.

**Comment by escowles** [comment]
One idea we had was to create a separate application for the viewer/bookmark experience.  This application would host the UV viewer that other applications embed.  It could also:
* cache manifests so any issues in Figgy wouldn't interrupt access to the objects
* be a place to centrally manage bookmarks
* allow viewing objects in multiple viewers (e.g., UV and Mirardor)

**Comment by sdellis** [comment]
Another idea we had is to focus on creating API-first applications so that "separate applications" are transparent to the end user and their experience. We can then integrate all data through a single front-end/discovery UI.

**Comment by jrgriffiniii** [comment]
It seems as if the API-driven approach would offer some benefits (my original thought was to utilize a service broker like RabbitMQ and retain the current architecture).  Currently it seems as if other systems such as library.princeton.edu needs to maintain some access to Blacklight record data: https://library.princeton.edu/find/all/Bible%2C%20Latin%20%28Daniel%20fragment%29. for https://catalog.princeton.edu/?q=Bible%2C+Latin+%28Daniel+fragment%29.&search_field=all_fields

**Comment by tampakis** [comment]
Out of scope for Orangelight. Would be a separate application.
