### ISSUE TITLE
CSV export for bookmarks

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1467]
From SN@P:
```
I frequently copy titles, characters, call nrs etc from the catalog entry to lists.

I noticed that today, whatever I copy, add an extra line <img src="https://lib-analytics.princeton.edu/piwik.php?idsite=9&amp;rec=1" style="border:0" alt="" />

Can you make sure that that is no longer copied? It makes making lists etc. very cumbersome.


Martin Heijdra, Ph. D. 何義壯
Director, East Asian Library
```

**Comment by christinach** [comment]
from the same ticket:
```
Example: look at https://catalog.princeton.edu/catalog/4135604
Select Chinese title (both Chinese or Romanization will do)
Paste in Excel
You’ll see that <img src="https://lib-analytics.princeton.edu/piwik.php?idsite=9&amp;rec=1" style="border:0" alt="" /> has been copied with every selection
```

**Comment by christinach** [comment]
I tested Chrome, Firefox and IE (not all versions), but I wasn't able to reproduce what the user reported. This is the img tag we use from 'matomo' when JS is disabled. I will look a little bit more.

**Comment by hackmastera** [comment]
could the version of windows be a factor as well?

**Comment by christinach** [comment]
@tampakis can you try from the Edit menu in excel to select Paste special and choose through the options `Values Only: `?  This is more if you copy -> paste between excel spreadsheets but it might work.

**Comment by christinach** [comment]
I also seems that the `style="border:0"` in the img tag doesn't work in this case.

**Comment by christinach** [comment]
The img tag is not copied when I use IE 11 and the latest excel. I don't have an Excel 2007 to test.
 @tampakis did you disable JS to be able to have the img tag in the DOM or was it there without disabling JS?

**Comment by tampakis** [comment]
Javascript was enabled in IE. for more info I was also running Windows 7.

Thanks for the advice about the paste values @christinach, that's what I told Martin to try out while the img tag is still there.

**Comment by escowles** [comment]
I think fixing this issue directly is probably not the best way to address the underlying problem.  Exporting bookmarks, search results and/or item records as CSV is probably much easier to do, and will result in a better experience for getting data out of the catalog and into Excel.  I've emailed Martin to ask him if that sounds workable to him.

**Comment by kevinreiss** [comment]
👍 Several other librarians have mentioned this as a desirable feature over the years.
