### ISSUE TITLE
Rename the subject browse heading

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1474]
When clicking the heading, "Subject facet" displays. Replace with "Subject browse" https://catalog.princeton.edu/catalog/?f[subject_facet][]=Symphonies

**Comment by christinach** [comment]
![Screen Shot 2022-02-28 at 1.20.22 PM.png](https://images.zenhubusercontent.com/5cba0ad2e669a330f9c44d53/a88e1ca2-f345-471a-8295-686f099a5282)

**Comment by christinach** [comment]
We should reopen this ticket and resolve it if we have feedabck from user testing.
