### ISSUE TITLE
Index numeric forms of titles

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1476]
As a search enhancement, add into the indexing routine a filter/map to convert number words into numerals, to cover cases where this alternative form of the title might not be included in the 246.

For example:
1001 nights - https://catalog.princeton.edu/catalog/6883248
1001 ye (Chinese version) - https://catalog.princeton.edu/catalog/4592732
12 drawings - https://catalog.princeton.edu/catalog/80892

**Comment by christinach** [comment]
It might be possible to accomplish this with synonyms instead of indexing.

**Comment by christinach** [comment]
The marc format allows for alternate of titles to be put into the 246 field. If this is a priority for cataloging then it could be approached that way.
