### ISSUE TITLE
Addressing incorrect book covers

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1478]
Reviving #624. I've been getting a few incorrect Google book cover emails recently.

Most recent example: https://catalog.princeton.edu/catalog/3309489
Google books incorrectly matches http://www.worldcat.org/title/obstetrics-manuscript-17/oclc/177495194 with https://books.google.com/books?id=DwiovAEACAAJ&source=gbs_ViewAPI

I submitted feedback to Google Books, but maybe we should consider an approach where we exclude the reported bib records from the book cover lookup?

**Comment by christinach** [comment]
Superseded by #3570
