### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by axamei** [pulibrary/orangelight#148]
* [x] Home page content (What to include?) [Ideas - Current Alerts/Maintenance, Highlighted/Featured Content?, Info on where to get help]

Accessibility:
* [x] Landmark roles
* [x] Headings
* [x] Forms

Branding:
* [x] PUL header and footer (same as main library)
* [x] Change logo to go to main library site
* [x] Squish header to one line. Search form, guided/adv options, and util_links. 
* [x] Move my account to top bar. Remove Catalog.
* [x] Assets: Icons, Fonts, CSS, JS

Front page:
* [x] Wording in main content with links to other resources

Facets:
* [x] Spacing and sizing
* [x] Add missing icons

Results view:
* [x] Remove labels
* [x] Add format
* [x] No results should span 100%. Currently in content div next to sidebar.

Individual record view:
* [x] Availability feed
* [ ] Stack map as modal
* [x] Add classic catalog link next to librarian view
* [x] Shrink h1 font-size (match results view title)
* [x] change location of librarian view and link to main catalog (below book cover)
* [ ] condense cite, email, text options in record view?

Other views:
* [ ] start over button: saved searches, search history, bookmarks
* [ ] ui enhancement: saved searches, search history, bookmarks, advanced search (within search bar), guided search
* [ ] clean up responsive buttons in record view, bookmarks button is offset oddly

Tools sidebar: 
* [x] Remove sidebar
* [x] put librarian view on bottom of record
* [x] make everything else buttons on top right (collapse all but cite and place in "send to")
* [x] back to search and paging on top left
* [x] remove start over option

Search forms:
* [ ] Header
* [ ] Advanced (jquery slide)
* [ ] Guided (jquery slide)

**Comment by jpstroop** [comment]
:+1:

**Comment by kevinreiss** [comment]
I think modals are an anti-pattern at this point for map view. It would be preferable to have the maps hidden in a region the user can toggle on or off instead.

**Comment by axapu** [comment]
Full-screen overlays are less disruptive than typical modal dialogs, e.g., http://tympanus.net/Development/FullscreenOverlayStyles/index7.html. That's one alternative. Another alternative is to display an embedded widget. In both cases, users can toggle on/off.

**Comment by kevinreiss** [comment]
Agreed, I think the full screen overlay approach would be cool. The behavior I was thinking of was the standard kind of bootstrap modal behavior.

**Comment by tampakis** [comment]
Hey @axamei could you take a look at the checkboxes which aren't completed yet? If they are quick fixes could the remaining ones be handled before the beta release? Otherwise maybe make separate issues for what needs to be done later?

**Comment by axamei** [comment]
Will do. I'll do an audit and create new/separate issues for what needs to be done.
