### ISSUE TITLE
Make image thumbnail a link to the viewer

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1487]
Implement design from wireframe: https://xd.adobe.com/view/2dcc57fd-3f03-4e5d-4a31-1493c363013c-5bfd/screen/c0285955-70c3-442d-a1d6-db7b3829ebca/Catalog-Item-Record-Digital-content
Add zoom button
Child of #1314

**Comment by christinach** [comment]
Modal changes were added in `https://github.com/pulibrary/orangelight/tree/show_page_layout`
