### ISSUE TITLE
Make viewer link open the viewer in full window

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1488]
https://xd.adobe.com/view/2dcc57fd-3f03-4e5d-4a31-1493c363013c-5bfd/screen/d8724f7d-ba84-4a9b-9a7d-95ef7f349ac1/Catalog-Item-Record-Digital-content-1
Child of #1314

**Comment by christinach** [comment]
Modal changes were added in `https://github.com/pulibrary/orangelight/tree/show_page_layout`
