### ISSUE TITLE
Make where to find it link to stack map very apparent to users

### ISSUE THREAD

**Issue by axamei** [pulibrary/orangelight#1489]
Through the usability testing, we discovered that users rely heavily on the text "Where to Find It". It should be included in the availability holding info. Explore other design options for this display.

Child of #1314

https://xd.adobe.com/view/2dcc57fd-3f03-4e5d-4a31-1493c363013c-5bfd/

**Comment by axamei** [comment]
Something like this (but with a status column)?

<img width="706" alt="screen shot 2018-12-03 at 12 54 35 pm" src="https://user-images.githubusercontent.com/8161144/49391790-a4af2a00-f6fa-11e8-921b-7f1602db898c.png">

**Comment by kevinreiss** [comment]
Where would the status column go? In front of the request button?

**Comment by axamei** [comment]
Yes, something like this:

<img width="777" alt="screen shot 2018-12-05 at 11 29 13 am" src="https://user-images.githubusercontent.com/8161144/49528078-3ea0df00-f881-11e8-8ea0-1040d4374a65.png">
