### ISSUE TITLE
Bookmarks JSON view errors

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#1490]
## Error

[Orangelight/production] NameError: undefined local variable or method `render_search_results_as_json' for #<BookmarksController:0x00000000055ffd48>

## Backtrace

    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/42438614)

**Comment by jrgriffiniii** [comment]
This seems to have been in place in `Blacklight::Catalog
` for release 5.19.2: https://github.com/projectblacklight/blacklight/blob/v5.19.2/app/controllers/concerns/blacklight/catalog.rb#L218
