### ISSUE TITLE
Display the 505 field as a list on the show page

### ISSUE THREAD

**Issue by axamei** [pulibrary/orangelight#1502]
The current display of the "Contents" field is not very readable for users. We should attempt to refactor this to display as a list. 

Example records: 

- https://catalog.princeton.edu/catalog/5846515 
- https://catalog.princeton.edu/catalog/10585552 (with subfields)
- https://catalog.princeton.edu/catalog/4868841 (multiple 505 fields)
- https://catalog.princeton.edu/catalog/4868841 (long notes)

Screenshot of current "Contents" field display on show page:
<img width="654" alt="screen shot 2018-12-06 at 1 51 59 pm" src="https://user-images.githubusercontent.com/8161144/49605310-2357d180-f95e-11e8-854f-e756aaef6865.png">

**Comment by kevinreiss** [comment]
This seems sensible to me. This would make this more digestible to screen readers as well.

**Comment by maxkadel** [comment]
Works that are in non-Roman scripts have multiple Table of Contents - e.g. https://catalog.princeton.edu/catalog/9969362593506421. Is it ok if it displays as one continuous list? Or how do we want works like this to display?

**Comment by maxkadel** [comment]
When I manually change the contents_display field into a list, separated on `" -- "`, it looks like this:
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/68aee31e-f90e-4472-984e-73964b098679)
