### ISSUE TITLE
"Network error" message when clicking 'cite' button

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1505]
[Orangelight/production] ActionView::Template::Error: undefined method `value' for nil:NilClass

## Backtrace

    line 72 of [PROJECT_ROOT]/app/models/concerns/blacklight/solr/document/marc.rb: export_as_mla_citation_txt
    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/42823098)

**Comment by hackmastera** [comment]
Not getting this when tested on several other records.
