### ISSUE TITLE
Show redesign tweaks

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1509]
- [x] Viewer display for items with multiple scripts in title: https://catalog-staging.princeton.edu/catalog/4707756
 - [x] The "more" link for viewing the full list of current issues is easily missed: https://catalog-staging.princeton.edu/catalog/495892
 - [x] Better indicate that the thumbnail for Figgy items is a link to open the viewer.

**Comment by christinach** [comment]
@tampakis , I think the 3rd `Better indicate that the thumbnail for Figgy items is a link to open the viewer.' will be part of https://github.com/pulibrary/orangelight/pull/1498 after I do the adjustments for the viewer.
