### ISSUE TITLE
Error from impossible facet combination attempted by crawler bot

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1510]
[Orangelight/production] ActionView::Template::Error: undefined method `head' for #<#<Class:0x000000000487a290>:0x00007fdd75c70920>

## Backtrace

    line 81 of [PROJECT_ROOT]/app/helpers/facets_helper.rb: rescue in render_facet_partials
    line 77 of [PROJECT_ROOT]/app/helpers/facets_helper.rb: render_facet_partials
    line 19 of [PROJECT_ROOT]/app/views/catalog/_facets.html.erb: _app_views_catalog__facets_html_erb___671595992751124139_69990357921280

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/42999908)

**Comment by hackmastera** [comment]
the attempted url was `https://catalog.princeton.edu/?f[lc_1letter_facet][]=N - Fine Arts&f[lc_rest_facet][]=NX - Arts in General&f[location][]=ReCAP&f[pub_date_start_sort][]=2012&f[recently_added_facet][]=weeks_2`

Might be an issue with the pub date facet. the query string for pub date on a real search looks like
`range[pub_date_start_sort][begin]=2012&range[pub_date_start_sort][end]=2012`

**Comment by hackmastera** [comment]
Although this works so maybe it's some interaction of those facets somehow
`https://catalog.princeton.edu/?f[pub_date_start_sort][]=2012&search_field=dummy_range`

**Comment by hackmastera** [comment]
this one also works fine:
`https://catalog.princeton.edu/?f[lc_1letter_facet][]=N - Fine Arts&f[lc_1letter_facet][]=N - Fine Arts&f[lc_rest_facet][]=NX - Arts in General&f[location][]=ReCAP&f[pub_date_start_sort][]=2012&f[recently_added_facet][]=months_6`

**Comment by christinach** [comment]
This issue is resolved n honeybadger
