### ISSUE TITLE
Reduce whitespace between sections to reduce scrolling/fit more on page

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1520]
There is a lot of whitespace between the main info, available online, copies in the library, and details sections, reducing the amount of info that's on the screen.  In particular, it pushes the call number off the screen with lower resolutions.

**Comment by hackmastera** [comment]
The whitespace is good for readability.

**Comment by kevinreiss** [comment]
I agree. I think we've got a good ratio of whitespace to text in this
update.

**Comment by escowles** [comment]
@axamei reports users did scroll down in testing to find content below "the fold".  Given that evidence from testing and differing opinions about the amount of whitespace, I'm going to close this issue and we can revisit the spacing later if it's an issue.
