### ISSUE TITLE
Viewer not loading for figgy resource

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/orangelight#1531]
the resource is https://catalog.princeton.edu/catalog/11075933

Tom said he added an ARK to the record and the viewer showed up the next day. Now he doesn't see the viewer anymore.

I tried to debug the js that pulls from figgy via bibid, but encountered #1530.

Please update Tom V. on progress.

**Comment by jrgriffiniii** [comment]
I'm not certain if this is related, but I am finding some broken links between bib. IDs on Figgy and Orangelight.  https://catalog.princeton.edu/catalog/4782614 does not resolve a viewer, but https://catalog.princeton.edu/catalog/4782613 does.  https://catalog.princeton.edu/catalog/4782614 points towards an ARK which specifies 4782613 as the bib. ID:
```
...
electronic_access_1display: "{"https://catalog.princeton.edu/catalog/4782613#view":["Digital content"],"iiif_manifest_paths":{"http://arks.princeton.edu/ark:/88435/z316q164g":"https://figgy.princeton.edu/concern/scanned_resources/f9d5e7af-fac4-408e-8d5f-49fe3f5c026f/manifest"}}",
...
```
where http://arks.princeton.edu/ark:/88435/z316q164g redirects to https://catalog.princeton.edu/catalog/4782613#view

**Comment by jrgriffiniii** [comment]
I was mistaken and my questions do not concern https://catalog.princeton.edu/catalog/11075933.  Please see https://github.com/pulibrary/orangelight/issues/1532 for the proper issue.

**Comment by jrgriffiniii** [comment]
The viewer and thumbnail for https://catalog.princeton.edu/catalog/11075933 are now rendered as expected
