### ISSUE TITLE
Add a tooltip when hovering over a figgy thumbnail

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1549]
Indicating that it opens up the UV

**Comment by tampakis** [comment]
![Screen Shot 2019-01-23 at 10.47.49 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56994c7cebcf0b1300cf114b/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226456f06b7191a379ef0c2f56415b47bc30254d58eeb9cb74fce36f34985619e8d6695a22906b42abb88616e902e8208b4f8ce7ee884e94fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34fe94f50ac173f62e57e3e6e0a.png)

@axamei and I don't think that adding a tooltip solves the problem that our users don't know that content from our digital library is viewable in the catalog. Are there better labels for this?

**Comment by hackmastera** [comment]
![screen shot 2019-01-23 at 10 53 26 am](https://user-images.githubusercontent.com/845363/51618975-47b34180-1efd-11e9-9edf-324b5035180b.png)

(😁 this is a joke and anyway it's probably trademarked)

**Comment by christinach** [comment]
we have added the icon on the thumbnail
