### ISSUE TITLE
More call number normalization issues for CDs/Accession numbers

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1560]
From catalog-feedback:
>
> CD 51884 (there are several vols.) is not falling in numeric sequence: https://catalog.princeton.edu/browse/call_numbers?search_field=browse_cn&q=cd+51184
>
> Instead, all of the CDs with this call no. are coming after CD 51103 vol. 2: https://catalog.princeton.edu/browse/call_numbers?search_field=browse_cn&q=cd+51184+vol.+

Also spaces are to be required after the CD: CD 6004, CD-6004, CD- 6004 all lead to different spots on the list:
https://catalog.princeton.edu/browse/call_numbers?search_field=browse_cn&q=cd6004
https://catalog.princeton.edu/browse/call_numbers?search_field=browse_cn&q=CD-+6004
https://catalog.princeton.edu/browse/call_numbers?search_field=browse_cn&q=CD-6004

**Comment by christinach** [comment]
Different characters should point to different objects. this is a cleanup issue.
