### ISSUE TITLE
Printed item record page should look more like send by email

### ISSUE THREAD

**Issue by axamei** [pulibrary/orangelight#1564]
User expects print out to be closer to what the record one would send by email looks like:

```
Title: Atlas of cultural and environmental change in arid Africa / edited by Olaf Bubenzer, Andreas Bolten & Frank Darius.

Published/Created: Köln : Heinrich-Barth-Institut, 2007.

Format: Book

Holdings:

                Location: Firestone Library

                Call number: Oversize GB618.82 .A85 2007q

URL: https://catalog.princeton.edu/catalog/5598017
```
 

That is something one can take with one to locate the item in the stacks.

**Comment by hackmastera** [comment]
It seems like there might be other use cases for printing. Are we sure we want to strip so much data / content from the printed version?

**Comment by axamei** [comment]
I agree that there are many use cases for printing and am not suggesting we strip down the printed record. This was an effort to record feedback. Is there a better place for this?

**Comment by hackmastera** [comment]
👍 I think this is the right place! I guess I was thrown off by the title and interpreted it as an actionable ticket.
