### ISSUE TITLE
Single item print view is truncated after the first page in Firefox

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1565]
- [ ] In Firefox, location and call number do not print out (text is cut off after first page)
- [ ] Subjects should not print, but do now

**Comment by christinach** [comment]
Location and call number they do print they are at the bottom of the page.

**Comment by escowles** [comment]
Maybe this is related to text size or other factors, and the content being pushed off the bottom of the pages.  Here are two PDFs I printed, where the location/call numbers are not printed.

[4069321.pdf](https://github.com/pulibrary/orangelight/files/2845750/4069321.pdf)
[5598017.pdf](https://github.com/pulibrary/orangelight/files/2845751/5598017.pdf)

**Comment by escowles** [comment]
Or maybe it's more properly a browser issue — I tried printing them with Chrome and the text was not cut off after the first page:

[4609321-chrome.pdf](https://github.com/pulibrary/orangelight/files/2845767/4609321-chrome.pdf)
[5598017-chrome.pdf](https://github.com/pulibrary/orangelight/files/2845768/5598017-chrome.pdf)

**Comment by christinach** [comment]
Yes, it looks like a browser issue-support. I also tried it again with Firefox and they don't print.

**Comment by christinach** [comment]
related to #1563 #1564

**Comment by escowles** [comment]
Willow reports that the second page is being cut off in Chrome on Windows, too.
