### ISSUE TITLE
Numismatic frontend

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1567]
Provide query interface to numismatic content equivalent to: http://libweb5.princeton.edu/numismatics/db.aspx  (N.B., this page typically takes > 1 minute to load).

This is presumably either DPUL or OL.

Child of #2025

**Comment by eliotjordan** [comment]
- Facet icon for coins.
- Copies in library is currently blank. Ask Alan about how he wants requests to be handled.
- Add a iiif manifest field to coins.
- Use iiif manifest link to display the viewer on coin show page.
- Use iiif manifest for coin search results thumbnail.
- Grouping sections of the coin/issue metadata.
- Re-arrange the coin show page? Ask for feedback.

**Comment by eliotjordan** [comment]
Complete. https://catalog.princeton.edu/numismatics
