### ISSUE TITLE
Index numismatics

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1568]
Child of #1567

Index into Orangelight for now.  Depending on how searching works, we may reconsider if there are problems with retrieval or display.

**Comment by tampakis** [comment]
Currently in the process of creating a solr document fixture for Orangelight. These are some of our findings and challenges:
 - References aren't included with the coin object (at least not in the .json view)
 - Issue numbers need to be mapped into the string "Numismatic Issue: #"
 - Dates. Orangelight only supports start date for the date facet and display.
 - Proposing adding a new format "Coin," wondering also if medals should be included, ie https://catalog.princeton.edu/catalog/10634556
 - Locations. For now assuming everything is at num https://bibdata.princeton.edu/locations/holding_locations/num
 - Adding new fields in the catalog controller for numismatics specific fields
 - Reusing existing notes_display for public notes and references_display for reference info.
 - Will have to decide what gets included in the top section and the more details section.
 - Proposing indexing the iiif manfiest url.
 - Issue number to link to a search retrieving all coins within an issue.
 - Proposed id: coin-#

**Comment by escowles** [comment]
These are indexed now.
