### ISSUE TITLE
Numismatic objects should have a viewer and thumbnail

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1571]
Child of #1567

Numismatic objects may need to be added to GraphQL API

**Comment by eliotjordan** [comment]
Use GraphQl or just include manifest link in the orangelight document.

**Comment by escowles** [comment]
I'm torn on this.  On one hand, it seems simplest to look up the thumbnails the same way we look them up for everything else.  On the other hand, it does seem very indirect when we are pushing the records to OL and can easily include the iiif manifest.
