### ISSUE TITLE
Multivolume works should display index view by default instead of thumbnails.

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1575]
In Orangelight the thumbnail tab appears by default instead of the index tab: https://catalog.princeton.edu/catalog/4609321

Figgy displays the index view: https://figgy.princeton.edu/catalog/d446107a-bdfd-4a5d-803c-f315b7905bf4

**Comment by tpendragon** [comment]
@tampakis Yeah, you'll have to change the URL to append the config location (or try using `/viewer` as the location):

https://figgy.princeton.edu/uv/uv#?manifest=https://figgy.princeton.edu/concern/scanned_resources/d446107a-bdfd-4a5d-803c-f315b7905bf4/manifest&config=https://figgy.princeton.edu/uv/uv_config.json
