### ISSUE TITLE
Error with Stackmap

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1582]
## Backtrace

    line 41 of [PROJECT_ROOT]/app/services/stackmap_service.rb: location_label
    line 13 of [PROJECT_ROOT]/app/controllers/concerns/orangelight/stackmap.rb: stackmap
    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/45659948)

https://catalog.princeton.edu/catalog/902827/stackmap

**Comment by eliotjordan** [comment]
Kevin says this is a data issue and will forward it to cataloging.

**Comment by tampakis** [comment]
Lower priority, but the application shouldn't error if an expected location parameter is missing. If the stackmap route is requested without a location parameter either display a "Please provide a location" or have it use the first location_code_s value stored on the document. This won't be accurate for items with multiple locations or temporary locations:

ie 
https://catalog.princeton.edu/catalog/10079456/stackmap?loc=sci
https://catalog.princeton.edu/catalog/10079456/stackmap?loc=scires
https://catalog.princeton.edu/catalog/10079456/stackmap
