### ISSUE TITLE
Nil barcode value 

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1583]
## Backtrace

    line 60 of [PROJECT_ROOT]/app/controllers/users/omniauth_callbacks_controller.rb: barcode_token_in_request_params
    line 16 of [PROJECT_ROOT]/app/controllers/users/omniauth_callbacks_controller.rb: barcode

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/37070237)

**Comment by eliotjordan** [comment]
Comment I made months ago on Honeybadger:

> I can't replicate this locally, but somehow a nil barcode value is being sent. We could intercept that nil value, but that might have other consequences.

**Comment by christinach** [comment]
we dont use the barcode now. and we will not use it in the future.
