### ISSUE TITLE
Multi-Volume work with charged items does not display request button

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1584]
Several volumes of this set are charged but the request button is not being displayed for the holding location. 

Record: https://catalog.princeton.edu/catalog/4347242

The availability.js script should be toggling to the "data-requestable" attribute on the element with the selector ```.location-services.service-conditional``` to true so the button displays.

**Comment by christinach** [comment]
This has been changed and fixed with the new changes in the requests gem.
