### ISSUE TITLE
Better indicate that thumbnail is clickable for digital content without thumbnails

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1596]
This record has embedded Figgy digital content: https://catalog.princeton.edu/catalog/9029455

However, since it doesn't have a thumbnail, the display doesn't get updated to indicate that the book cover image is a link to the viewer. Clicking the book cover does still bring you to the UV

**Comment by christinach** [comment]
closing in favor of https://github.com/pulibrary/orangelight/issues/2147
