### ISSUE TITLE
CJK titles not displaying

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1598]
@tventimi reported a problem of updated records not updating, e.g., https://catalog-staging.princeton.edu/catalog/100808 wasn't showing a newly-added CJK title added in an 880 field.

```xml
<datafield ind1="0" ind2="0" tag="880">
  <subfield code="6">245-01</subfield>
  <subfield code="a">¹³C NMR データブック /</subfield>
  <subfield code="c">編集代表, 戶田芙三夫, Ōshimo Tokio.</subfield>
</datafield>
```

Solr appears to be updated, since I see the title from 880$a in `title_vern_display`:

```json
{
"id": "100808",
"title_display": "¹³C NMR dētabbuku / henshū daihyō, Toda Fumio, Ōshimo Tokio.",
"title_vern_display": "¹³C NMR データブック / 編集代表, 戶田芙三夫, Ōshimo Tokio.",
"pub_created_display": [
"[Tōkyō] : Sankyō Shuppansha Kabushiki Kaisha, Shōwa 56 [i.e. 1981].",
"[東京] : 三共出版社株式会社, 昭和 56 [i.e. 1981]."
],
"cataloged_tdt": "2000-06-13T04:00:00Z",
"format": [
"Book"
],
"oclc_s": [
"79110454"
],
"holdings_1display": "{\"112874\":{\"location\":\"ReCAP\",\"library\":\"ReCAP\",\"location_code\":\"rcppa\",\"copy_number\":\"1\",\"call_number\":\"QD96.N8 C65\",\"call_number_browse\":\"QD96.N8 C65\"}}",
"score": 64.7166
}
```

So I think the problem with identifying and displaying the title, not indexing it.

**Comment by tventimi** [comment]
I confirmed that these are displaying correctly in catalog-staging.  Thanks!

**Comment by escowles** [comment]
That's great @tventimi — maybe we just needed to wait for the nightly update and/or update the code to the latest version? Please let me know if you see this problem again.

**Comment by christinach** [comment]
I believe it was the code to the latest version . I checked the url example last night and it displayed correctly.
