### ISSUE TITLE
Enhance coin linked fields

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1607]
Show page should have more linked fields that are linked to search. Obverse Figure Relationship for example

Child of https://github.com/pulibrary/orangelight/issues/1567

**Comment by tampakis** [comment]
A lot of these are going to have to be switched to string types in order to support link to search

**Comment by tampakis** [comment]
I'm going to make them all facets so we can explore the data before deciding which ones make sense to have as links
