### ISSUE TITLE
Availability - Show the lost applied date as an availability status tooltip

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1611]
From catalog-feedback: 
>  https://catalog.princeton.edu/catalog/3733697. For the lost mouseover, is it also possible to provide the date that items such have this were declared lost? I know this info is available in Voyager, but it would be helpful for me doing collection development to have easy access to this information from the catalog. If lost for years, I'd more likely consider a replacement than if recently declared lost (it could get returned). Thanks, Darwin

**Comment by tampakis** [comment]
Probably requires a new voyager helpers query @mzelesky?

Once the information gets passed through to bibdata the status can be updated: https://bibdata.princeton.edu/availability?id=3733697

**Comment by mzelesky** [comment]
I am wondering if this is something that is better suited to a staff report generated outside of Blacklight. At the least, I would want the input of other staff involved with circulation before making this change.

**Comment by tampakis** [comment]
Reported again as something of interest October 8th.
