### ISSUE TITLE
Monogram display for coins

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1616]

**Comment by christinach** [comment]
![Screen Shot 2019-04-16 at 3.12.32 PM.png](https://zube.io/files/pulibrary/9b26e45b4b2c8b96783a9bacbd06db8a-screen-shot-2019-04-16-at-3-12-32-pm.png)

**Comment by christinach** [comment]
Adding monogram/s thumbnail below coin-thumbnail in the left column.
