### ISSUE TITLE
expand cataloging abbreviations in index

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#1617]
e.g. "facsim." should also be indexed as "facsimile". These are spelled out in RDA-world, but not prior to that. AACR2 probably has a list of common/allowed abbreviations.

**Comment by jpstroop** [comment]
Here you go: https://web.library.yale.edu/cataloging/AACR2-abbreviations

**Comment by christinach** [comment]
This should be addressed at the data level.

**Comment by jpstroop** [comment]
I wonder if @jbaxmeyer thinks this solution is feasible
