### ISSUE TITLE
Browse related items link displays for empty call_number

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#1621]
https://catalog.princeton.edu/catalog/10266460
An empty call_number in this record triggers the 
`Browse related items` link(https://catalog.princeton.edu/browse/call_numbers?q=) 
Also `Where to find it` link(https://catalog.princeton.edu/catalog/10266460/stackmap?loc=sci&cn=) doesn't show the stackmap for Lewis Library.

**Comment by kevinreiss** [comment]
Items without a call number cannot be resolved by the stackmap service. There are a couple of holding location codes [https://github.com/pulibrary/orangelight/blob/2c758d418f386e71498a83a3102fc60bf3b2523c/app/services/stackmap_service.rb#L88] that are resolved by passing the title to the "cn" parameter but other than those items w/o a call number will produce an error.  We should probably add something that fails more gracefully when an item lacks a call number and isn't in a shelve by title location.

**Comment by tampakis** [comment]
I recommend in marc_liberation to modify the code that indexes the `holdings_1display`, `call_number_display`, and `call_number_browse_s` fields to exclude blank strings. If the call number field is nil in a document then the browse related items and where to find it links won't display

**Comment by christinach** [comment]
Issue moved to [pulibrary/bibdata #1517](https://github.com/pulibrary/bibdata/issues/1517) via [**ZenHub**](https://www.zenhub.com/)
