### ISSUE TITLE
Adding slash accidentally to barcode raises exception

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1624]
Should we strip illegal and invalid characters?

## Backtrace

    line 11 of [PROJECT_ROOT]/app/services/bibdata.rb: get_patron
    line 17 of [PROJECT_ROOT]/app/controllers/users/omniauth_callbacks_controller.rb: barcode

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/36234816)

```
URI::InvalidURIError: bad URI(is not URI?): https://bibdata.princeton.edu/patron/22101002380343\

https://catalog.princeton.edu/users/auth/barcode/callback
```
https://github.com/pulibrary/orangelight/blob/master/app/services/bibdata.rb#L11

**Comment by christinach** [comment]
last time this happened was 5/17/2019
