### ISSUE TITLE
Update call number browse to only update incrementally

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1625]
Use the Solr timestamp to get the new/updated records for the call number browse as opposed  to dumping the whole database.
Removing deletes will be a bit more involved and probably requires using the bibdata events to fetch the removed ids.

**Comment by escowles** [comment]
Pull metadata from MARC instead of from Solr.

**Comment by tampakis** [comment]
> Pull metadata from MARC instead of from Solr.
My thoughts about this would be to output a csv with the fields that the call number browse postgres table fields and add them to the table. However, we need to take a look at the current approach of export and reloading the whole table in order to get them stored in sorted order

**Comment by christinach** [comment]
I unassigned my self for now so that @tampakis will give a priority to #1897

**Comment by christinach** [comment]
we dont want to change the current functionality
