### ISSUE TITLE
Edit facet browse to use Solr instead of Postgres

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1626]
Instead of retrieving millions of solr facet values at once, use either facet prefix or offset to retrieve subsets of the collection

**Comment by tampakis** [comment]
https://github.com/pulibrary/orangelight/blob/master/lib/orangelight/browse_lists.rb#L37-L50

**Comment by tampakis** [comment]
One potential approach would be to figure out an exhaustive list of Facet prefixes (perhaps while preparing the browse lists) and then iterate through them, but this list may expand as we get content in other languages

**Comment by tampakis** [comment]
Potentially have theses lists get updated by a solr collection that isn't facing the public

**Comment by tampakis** [comment]
Could we store all of the facet values in a solr collection instead of postgres? We would still need the ability to fetch the values all at once for initial load, but could update incrementally.

**Comment by jrgriffiniii** [comment]
I've started to restructure the functionality for this, and I'm working to POST the initially fetched values into a separate Solr Collection: https://github.com/pulibrary/orangelight/compare/issues-1626-jrgriffiniii-facet-browse-lists

**Comment by jrgriffiniii** [comment]
As call number values are a slightly more complex case, I shall prioritize working with names and other facets in order to proceed with this work.

**Comment by jrgriffiniii** [comment]
Apologies if this lies outside of the original scope of this issue (I might be increasing this into an epic, and I can split this out as needed), but it should noted that maintaining a separate Solr Collection for the browse list facet values is far more desireable given that there should be additional information stored in each Document in response to the work being undertaken by the Authorities Committee.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/orangelight/commit/57e77a8b7c6bb274d190dfcec28ee04b79ed12cd introduces a Solr Document structure for the separate Solr Collection for the Browse Lists using the following structure:
```ruby
{
  id: facet,
  facet_field.to_s => facet.to_s,
  normalized_s: facet.normalize_em,
  direction_s: facet.dir
}
```

Does this seem acceptable? This seems to work for name facets if I simply repurpose the existing Solr configuration for the `browse-lists-core` Collection.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/orangelight/commit/c190c8dfe405777d3115e45c816bd21a955ff059 advances an approach where I am using `RSolr` in order to provide a document-mapping in order to query for the browse list Documents, but there are bugs with the route parameters and model names.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/orangelight/commit/df42402b40869d923d6ba41cfae0bf25820b6701 restores pagination for the `BrowsablesController`

**Comment by jrgriffiniii** [comment]
The next step for this is to ensure that the browse lists are incrementally updated, with an initial approach being that a client will request a `fq` query for all updates following a datestamp, and then reindex these into the separate Solr collection.
