### ISSUE TITLE
[Orangelight/production] TypeError: no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1641]
## Backtrace

    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/49056734)

**Comment by jrgriffiniii** [comment]
The information for this on Honeybadger is no longer retained (please see https://app.honeybadger.io/projects/54399/faults/49056734).  Hence, I'm not certain that this can be addressed
