### ISSUE TITLE
CRC Press items not showing up in Catalog

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1642]
Anya Bartelmann reports:
> I came across a number of titles from CRC Press that we have access to, but none of them appear in the catalog. I remember something similar happened with Springer ebooks, although I do not remember how it was resolved. What group should I contact to help with this? A few sample ISBNs 9781498729604; 9780429444579; 9781138627161

**Comment by mzelesky** [comment]
Just an initial investigation:

Those ISBNs do not exist in Voyager. The first person I'd send this to would be Kevin Connell, or just esupport@princeton.edu. My guess is new records need to be exported from OCLC or some other source. It is thankfully not a bug with records not making it into Blacklight.
