### ISSUE TITLE
[Orangelight/production] ActionView::Template::Error: private method `select' called for nil:NilClass

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1644]
## Backtrace

    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/39796981)

**Comment by jrgriffiniii** [comment]
This seems to be triggered by https://github.com/pulibrary/requests/blob/master/app/helpers/requests/application_helper.rb#L318
