### ISSUE TITLE
In search results, show available items first

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1650]
See the first item in this search (https://catalog.princeton.edu/catalog/11072): https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=title&q=slave+community

The item has several available items, but only the missing items are shown in the search results.  There is a button to indicate there are other items in the full record, but the user might reasonably assume they were all missing given the two shown.

We should show available items first to indicate that at least some of the items are available.

**Comment by christinach** [comment]
This is only feasible if we ever choose to add the availability into the index.
