### ISSUE TITLE
No Environment specified on lib-pulindexer1

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1659]
## Backtrace

    line 77 of [PROJECT_ROOT]/lib/orangelight/browse_lists.rb: block (2 levels) in browse_cn
    line 73 of [PROJECT_ROOT]/lib/orangelight/browse_lists.rb: times
    line 73 of [PROJECT_ROOT]/lib/orangelight/browse_lists.rb: block in browse_cn

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/50525064)

**Comment by eliotjordan** [comment]
```
NoMethodError in rake browse:call_numbers --silent
```

```
browse_lists.rb  77 block (2 levels) in browse_cn(...)
[PROJECT_ROOT]/lib/orangelight/browse_lists.rb:77:in `block (2 levels) in browse_cn'
75           resp = conn.get cn_request.to_s
76           req = JSON.parse(resp.body)
77           req['response']['docs'].each do |record|
78             next unless record[facet_field.to_s]
79             record[facet_field.to_s].each_with_index do |cn, _i|
```

@tampakis Is this an issue or is it a mistyped rake command? If not a problem please close this ticket and the related Honeybadger ticket.

**Comment by tampakis** [comment]
Yep mistyped one-off command.
