### ISSUE TITLE
[Orangelight/production] NoMethodError: undefined method `values' for ["status", 500]:Array

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#1660]
## Backtrace

    line 109 of [PROJECT_ROOT]/app/repositories/course_reserve_repository.rb: block in courses=
    line 109 of [PROJECT_ROOT]/app/repositories/course_reserve_repository.rb: each
    line 109 of [PROJECT_ROOT]/app/repositories/course_reserve_repository.rb: map

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/36228596)

**Comment by christinach** [comment]
it doesn't happen anymore
