### ISSUE TITLE
Sitemap Not Working

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1665]
OL's robots.txt says the sitemap is https://pulsearch.princeton.edu/sitemap.xml.gz

However, that URL doesn't work, and neither does https://catalog.princeton.edu/sitemap.xml.gz

**Comment by escowles** [comment]
Looks like it's only generated on a single server and so doesn't work if you get one of the other servers.

**Comment by escowles** [comment]
Options for fixing this:
1. Generate sitemap on each machine (bad because it's very resource intensive)
1. Store on shared disk and link from each machine (seems overkill to setup a share just for this)
1. Copy to all other servers (need to switch from cron to capistrano to orchestrate this)
1. Direct all sitemap traffic to the server with the sitemap (not sure if this is possible)

**Comment by sandbergja** [comment]
When I checked catalog2 today, there were no sitemap files at all in the public directory.

It looked like the previous run had failed after creating sitemap377.xml.gz with:

```
RSolr::Error::ConnectionRefused: Connection refused - {:params=>{:wt=>:json, "q"=>"*:*", "fl"=>"id", "cursorMark"=>"AoEsU0NTQi03MDM5NzYy", "rows"=>1000, "sort"=>"id asc"},
 :method=>:get, :query=>"wt=json&q=*%3A*&fl=id&cursorMark=AoEsU0NTQi03MDM5NzYy&rows=1000&sort=id+asc", :path=>"select", :uri=>#<URI::HTTP http://lib-solr8-prod.princeton.e
du:8983/solr/catalog-alma-production/select?wt=json&q=*%3A*&fl=id&cursorMark=AoEsU0NTQi03MDM5NzYy&rows=1000&sort=id+asc>}
/opt/orangelight/shared/bundle/ruby/2.7.0/gems/rsolr-2.5.0/lib/rsolr/client.rb:218:in `rescue in execute'
/opt/orangelight/shared/bundle/ruby/2.7.0/gems/rsolr-2.5.0/lib/rsolr/client.rb:208:in `execute'
/opt/orangelight/shared/bundle/ruby/2.7.0/gems/rsolr-2.5.0/lib/rsolr/client.rb:203:in `send_and_receive'
(eval):2:in `get'
/opt/orangelight/releases/20220801163717/config/sitemap.rb:16:in `block (2 levels) in run'
/opt/orangelight/releases/20220801163717/config/sitemap.rb:15:in `loop'
/opt/orangelight/releases/20220801163717/config/sitemap.rb:15:in `block in run'
/opt/orangelight/shared/bundle/ruby/2.7.0/gems/sitemap_generator-6.2.1/lib/sitemap_generator/interpreter.rb:61:in `instance_eval'
/opt/orangelight/shared/bundle/ruby/2.7.0/gems/sitemap_generator-6.2.1/lib/sitemap_generator/interpreter.rb:61:in `eval'
/opt/orangelight/shared/bundle/ruby/2.7.0/gems/sitemap_generator-6.2.1/lib/sitemap_generator/link_set.rb:40:in `create'
/opt/orangelight/shared/bundle/ruby/2.7.0/gems/sitemap_generator-6.2.1/lib/sitemap_generator.rb:42:in `method_missing'
/opt/orangelight/releases/20220801163717/config/sitemap.rb:6:in `run'
/opt/orangelight/shared/bundle/ruby/2.7.0/gems/sitemap_generator-6.2.1/lib/sitemap_generator/interpreter.rb:78:in `instance_eval'
/opt/orangelight/shared/bundle/ruby/2.7.0/gems/sitemap_generator-6.2.1/lib/sitemap_generator/interpreter.rb:78:in `run'
/opt/orangelight/shared/bundle/ruby/2.7.0/gems/sitemap_generator-6.2.1/lib/sitemap_generator/tasks.rb:51:in `block (2 levels) in <top (required)>'
/opt/orangelight/shared/bundle/ruby/2.7.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'

Caused by:
Faraday::ConnectionFailed: end of file reached
```

There were successful runs in the logs, so I was surprised not to see any residual files from previous runs nor the first 377 files from this run.

I want to check to see if the sitemap files remain after a deployment.

Also a note that running this on prod takes something like 30 hours.  So it's definitely possible for some kind of minor solr connection blip to happen during that time, so we should also investigate making this a bit more resilient against solr blips.

**Comment by sandbergja** [comment]
Closing this ticket in favor of #3166
