### ISSUE TITLE
Availability - Location Has/Item Status Display Confusing for Multi-item periodicals

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1672]
Check out: https://catalog.princeton.edu/catalog/564882

The location has several items/volumes. The item status only shows the volumes that are unavailable. Users think that the item status column shows all of the items though. The "location has" section is supposed to do that.

Do we add additional text at the bottom of the availability list something like "All other items available?"

We could also experiment with displaying all of the items but I think it would take up too much space for some periodicals

**Comment by mzelesky** [comment]
I like the idea of explanatory text like you suggest. +1 for me. Displaying all of the items would be disastrous for serials with a lot of items.

**Comment by christinach** [comment]
we dont display items anymore
