### ISSUE TITLE
Use Blacklight's builtin robots handling

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1677]
Blacklight allows identifying requests as robots, e.g.:
```config.crawler_detector = ->(req) { req.env['HTTP_USER_AGENT'] =~ /Googlebot/ }```

This triggers certain behaviors like not creating sessions and saved searches.  We could also use that to trigger other changes like not allowing paging, not displaying live availability, and not show full MARC records

From @sandbergja is a possible tool that could be used to detect user agents: https://rubygems.org/gems/device_detector. 

API calls to target. 

1. Staff View (Server Side)
2. Availability on Search Results (JS)
3. Availability on Record Page (JS)
4. Figgy Graphql Lookup Record Page (JS)

**Comment by kevinreiss** [comment]
Let's look at this post Blacklight 8

**Comment by sandbergja** [comment]
This was already in place for availability, thanks to #1066.  I'll use voight_kampff, rather than device_detector, since it's already being used in Orangelight.
