### ISSUE TITLE
NoMethodError: #   undefined method `saved_searches_path' 

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#1700]

**Comment by christinach** [comment]
NoMethodError: undefined method `saved_searches_path' for #<ActionDispatch::Routing::RoutesProxy:0x00007f40f14d1dc0>
  ./app/views/_account.html.erb:12:in

**Comment by tampakis** [comment]
The Saved Searches feature was removed from Blacklight core. I'm going to check if anyone has used the feature. If it's a very small number I will remove it from the catalog
