### ISSUE TITLE
CAS Authenticated Users and Passwords

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#171]
We should set up the user profile page to not allow users signed in with SSO to set or change the password fields. We should just reserve that for guest users. @tampakis @axapu Any objections to this proposed change?

**Comment by tampakis** [comment]
I think we'll cover this when we deal with barcode and guest account authentication as in #110 and #130. Since devise doesn't actually have access to the CAS password, netid users can't actually change their passwords.

**Comment by jpstroop** [comment]
![cas](https://cloud.githubusercontent.com/assets/999701/9368859/d6f3b7e4-4693-11e5-88fe-00bc6b341d29.png)

**Comment by jpstroop** [comment]
:broken_heart: 

![cas2](https://cloud.githubusercontent.com/assets/999701/9368874/e63153f6-4693-11e5-83a3-b8ca0fb48902.png)

**Comment by jpstroop** [comment]
#211 isn't a total dupe...these screens also just need to look nicer

**Comment by tampakis** [comment]
Can be closed when the "View Profile" link goes away from the dropdown in the header.
