### ISSUE TITLE
Facets move to the left when they are all collapsed

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1732]
Expanded:
![Screen Shot 2019-07-18 at 11.13.14 AM.png](https://images.zenhubusercontent.com/5cba0b5a4671f7309882dbcc/5c015d83-aaf2-4541-916a-06fc057a00bd)
Collapsed, moves the main text over to the left:
![Screen Shot 2019-07-18 at 11.13.30 AM.png](https://images.zenhubusercontent.com/5cba0b5a4671f7309882dbcc/d515bfa1-1fec-472b-b7db-dd57c8f21e92)

**Comment by christinach** [comment]
child of #1682
