### ISSUE TITLE
[Orangelight/production] NoMethodError: undefined method `values' for ["status", 500]:Array

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1759]
## Backtrace

    line 113 of [PROJECT_ROOT]/app/repositories/course_reserve_repository.rb: block in courses=
    line 113 of [PROJECT_ROOT]/app/repositories/course_reserve_repository.rb: each
    line 113 of [PROJECT_ROOT]/app/repositories/course_reserve_repository.rb: map

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/52807022)

**Comment by hackmastera** [comment]
We need to improve error handling here; guard for the error before it gets to this point in the code.

**Comment by christinach** [comment]
we dont do course reserves
