### ISSUE TITLE
Browse lists not generating

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#1763]
## Backtrace

    line 77 of [PROJECT_ROOT]/lib/orangelight/browse_lists.rb: block (2 levels) in browse_cn
    line 73 of [PROJECT_ROOT]/lib/orangelight/browse_lists.rb: times
    line 73 of [PROJECT_ROOT]/lib/orangelight/browse_lists.rb: block in browse_cn

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/50525064)

**Comment by christinach** [comment]
When browse lists fail to generate **and** would like to run the rake task before it is scheduled:

1. ssh on lib-pulindexer1. Check the crontab and make sure the rake task for the call numbers runs on this box. If not then check lib-pulindexer2 and 3. 

1. While on the right box, run the call number rake task `browse:call_numbers`. When it finishes count the lines in the file (wc -l orangelight_name_titles.sorted) to ensure that there is not a big difference with the previous file. 

1. Run `browse:load_call_numbers`.

**Comment by christinach** [comment]
1. Check https://github.com/pulibrary/orangelight/blob/db70a0cb648ab73cd07c73128d943d5bfb8c0632/lib/orangelight/browse_lists.rb#L76 if you get a hash with no response key.
1. Log failure response object  in Rails log
1. Retry 3 times if you are still failing then notify honeybadger and send the response object.

**Comment by hackmastera** [comment]
The script gets slower as it goes on. The problem is likely the deep pagination issue: https://lucene.apache.org/solr/guide/8_0/pagination-of-results.html
