### ISSUE TITLE
Electronic Access URL Display

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#179]
Consider http://pulsearch-dev.princeton.edu/catalog/8299670. The URL from the 856 is really long, maybe we should be using the access label value from the 856 if it is present.

**Comment by jpstroop** [comment]
A couple of thoughts:

 * Yes, if `|y` is there, use it as the anchor text (but not `|x`)
 * If `|z` is there, it should probably be displayed as well but not as the anchor
 * If nothing else, what about parsing the URL and only using the host as the anchor, e.g.:

```ruby
2.2.1 :001 > require 'uri'
 => true 
2.2.1 :002 > url = URI.parse("http://ncco.galegroup.com/gdc/ncco/MonographsDetailsPage/MonographsDetailsWindow?disableHighlighting=false&prodId=NCCO&action=1&activityType=BasicSearch&javax.portlet.action=viewPortletAction&documentId=GALE%7CBGRKWK255805996&dviSelectedPage=1&userGroupName=prin77918")
 => #<URI::HTTP http://ncco.galegroup.com/gdc/ncco/MonographsDetailsPage/MonographsDetailsWindow?disableHighlighting=false&prodId=NCCO&action=1&activityType=BasicSearch&javax.portlet.action=viewPortletAction&documentId=GALE%7CBGRKWK255805996&dviSelectedPage=1&userGroupName=prin77918> 
2.2.1 :003 > "#{url.scheme}://#{url.host}"
 => "http://ncco.galegroup.com" 
```

**Comment by kevinreiss** [comment]
I like the hostname as the fallback.

**Comment by joycebcat** [comment]
The display of the URL rather than alternate text is a deliberate choice made by LISSC some years ago.  Nearly all of the |z text in the records comes from elsewhere and is sometimes in different languages or otherwise undesirable.

**Comment by kevinreiss** [comment]
Displaying the bare URL is quite poor when considering accessibility
standards. We should get away from it.

**Comment by jpstroop** [comment]
If it was years ago, I wonder if it's still the desired behavior, now that we have more content online.

**Comment by jpstroop** [comment]
Also, accessibility implications?

**Comment by jpstroop** [comment]
Hah. Mobile app is lagging...

**Comment by joycebcat** [comment]
It should be discussed at LISSC.  Since we are only looking at Blacklight, I suppose we could just change it and present it initially that way.  In addition to accessibility implications, there are also data implications--we would need to review and update the text for all loads into the system to get some degree of consistency and acceptability in wording of text.

**Comment by kevinreiss** [comment]
To my thinking the best option is to provide the same label text for all
resources. We could handle that within Blacklight and not have to touch the
marc data at all.

BTW the way how does Blacklight handle records that have non full-text 856
links like TOCs and abstracts? We should audit those as well.

**Comment by tampakis** [comment]
TOCs and abstracts are usually specified by the `|3` subfield and that text is displayed instead of the url. Here is a (German) example: http://pulsearch-dev.princeton.edu/catalog/3

**Comment by kevinreiss** [comment]
Are those reliable enough where we could just a set a default label for all
links that have that subfield?

**Comment by joycebcat** [comment]
We need to do some proper analysis on this topic.  There are some URLs (not many) which have special instructions built into the label text and others (again not many) where there are multiple links and our text indicates which volume the link covers.  I forgot that we do use standard text now for most serials--we get marcit records and we use "View Princeton's online holdings" for that.  What we need to figure out is how to identify links which can have a default label, which need special labels (or find a way to do away with these altogether) and how to identify the things which aren't full-text.

**Comment by kevinreiss** [comment]
Yes, I agree we should do a detailed analysis of what we currently have. It
would be a big win for the user facing portions of this if we can get these
labels consistently applied and used in future work.
