### ISSUE TITLE
Make sure that clicking the back button preserves the previously entered fields

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1791]
Reported on catalog-feedback:
>Try this search: https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&f1=publisher&q1=munchen&op2=AND&f2=author&q2=stanford&op3=AND&f3=series_title&q3=repertoire&f_inclusive%5Bformat%5D%5B%5D=Musical+score&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search
>
>Now back-arrow the browser.
>
>Note that the search words in boxes 1 and 2 disappear, but they stay in box 3. Also, the format selection sticks (in this case "scores"). I think the intention is to have the entire search present when you back-arrow.
>
>Darwin
(Feedback form reported Firefox was used)

**Comment by kevinreiss** [comment]
Confirm if this still an issue.

**Comment by kevinreiss** [comment]
This appears to work now. Closing.
