### ISSUE TITLE
Fix layout of search constraints

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#1796]

**Comment by christinach** [comment]
![Screen Shot 2019-08-26 at 8 25 49 AM](https://user-images.githubusercontent.com/9905193/63690618-255b0c80-c7db-11e9-92f6-9b89c21c174f.png)

**Comment by tampakis** [comment]
<img width="407" alt="Screen Shot 2019-08-26 at 8 25 43 AM" src="https://user-images.githubusercontent.com/4650153/63690655-41f74480-c7db-11e9-9491-ae7c87c6c593.png">
