### ISSUE TITLE
Fix pagination tools on Browse pages

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1809]
<img width="272" alt="Screen Shot 2019-08-28 at 7 20 37 AM" src="https://user-images.githubusercontent.com/4650153/63851553-6894b700-c964-11e9-99fa-662f16220811.png">
<img width="148" alt="Screen Shot 2019-08-28 at 7 20 58 AM" src="https://user-images.githubusercontent.com/4650153/63851558-6a5e7a80-c964-11e9-8cac-b3043932ce1b.png">

**Comment by christinach** [comment]
also update pagination tools to look like:
![Screen Shot 2019-09-03 at 2 31 32 PM](https://user-images.githubusercontent.com/9905193/64199110-993e8a00-ce57-11e9-9e44-c007a9a42dec.png)

**Comment by christinach** [comment]
not: 
![Screen Shot 2019-09-03 at 2 32 29 PM](https://user-images.githubusercontent.com/9905193/64199144-ad828700-ce57-11e9-89a6-3303c5c2ade9.png)
