### ISSUE TITLE
Fix request form layout

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1810]
<img width="1027" alt="Screen Shot 2019-08-28 at 7 24 58 AM" src="https://user-images.githubusercontent.com/4650153/63851860-ff617380-c964-11e9-83f0-a30b294dda3a.png">

**Comment by christinach** [comment]
child of https://github.com/pulibrary/orangelight/issues/1817

**Comment by christinach** [comment]
also:
![Screen Shot 2019-08-30 at 11 21 49 AM](https://user-images.githubusercontent.com/9905193/64032409-64a99600-cb18-11e9-9a4f-4253d940f1a9.png)

**Comment by christinach** [comment]
updated requests gem to:
![Screen Shot 2019-08-30 at 12 06 22 PM](https://user-images.githubusercontent.com/9905193/64035401-accbb700-cb1e-11e9-93a5-0edd1bd36d6a.png)
![Screen Shot 2019-08-30 at 12 06 14 PM](https://user-images.githubusercontent.com/9905193/64035402-accbb700-cb1e-11e9-98b8-813c7cb3d922.png)

**Comment by christinach** [comment]
fixed in https://github.com/pulibrary/requests/pull/411
