### ISSUE TITLE
RTL display issue - the table in browselists displays the rtl languages in the wrong place. The same issue exists in the record page.

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#1824]
In the browse pages for `rtl` languages like Arabic, the header `Title` is not correctly positioned in smaller responsive screens. `xs` and `sm`
Example:
![Screen Shot 2019-09-04 at 8 14 01 AM](https://user-images.githubusercontent.com/9905193/64253970-698d9180-ceec-11e9-82e5-d1be86a78d99.png)
 

This is an issue in production as well.

**Comment by christinach** [comment]
The same issue exists in the record page. https://catalog.princeton.edu/catalog/11404747
https://catalog.princeton.edu/catalog/5481513

**Comment by maxkadel** [comment]
I cannot reproduce this issue. 

I've tried with the show page using Chrome developer tools and on my own phone. I do not know how to access a browselist that mirrors the one above (is it a feature that has been removed, or do I just not know how to get to it?)

**Comment by christinach** [comment]
@maxkadel https://catalog.princeton.edu/browse/call_numbers?q=PJ7966.R3955+S34+2019 an example of a mobile screen is the one below:
you can also select another screen option form the dropdown. See the Title label how it moves. 

![Screen Shot 2022-09-29 at 9 03 13 AM](https://user-images.githubusercontent.com/9905193/193038697-6cdb3ca0-a9c9-49f5-9424-7bb41e21d34f.png)

**Comment by maxkadel** [comment]
It looks like only the title field has the `rtl` class, even though other fields have Arabic (non-transliterated) values (e.g. creator, publication info). 

Even though the title field has a `rtl` class, it seems to be wrapping on the left side, which seems like would be a major aspect of rtl display? Unfortunately, I'm not familiar with any rtl languages, so can't tell how legible the rtl display is. 

title wrapping example
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/b591103e-9af5-446d-a4f2-f9d96624ecbd)

publication info wrapping example
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/995fa197-740b-4f8b-b9cf-73f86e6cb3f5)

**Comment by maxkadel** [comment]
From team discussion:
* The label should be left-anchored
* The title itself should be right-anchored, and should wrap on the right side
