### ISSUE TITLE
[Orangelight/production] ActionView::Template::Error: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1830]
## Backtrace

    line 139 of [PROJECT_ROOT]/app/helpers/application_helper.rb: start_with?
    line 139 of [PROJECT_ROOT]/app/helpers/application_helper.rb: block in same_series_result
    line 139 of [PROJECT_ROOT]/app/helpers/application_helper.rb: select

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/49452104)

**Comment by jrgriffiniii** [comment]
Apologies, this was created in error.
