### ISSUE TITLE
User Preferences

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#186]
Some users may prefer to have 50 results returned be the default behavior across all search sessions. Others may want to have records be sorted alphabetically or by newest by default. When the user is signed into their account can we create an account preferences page to allow users to specify their own default search options?

**Comment by jpstroop** [comment]
Hijacking this issue. There are a number of things that could go into a Blacklight preferences plugin.

 * Preferred results per page
 * Default results sort
 * Default search field (#748)
 * Show / Hide Facets (#780)
 * Brief-er search results (#782)
