### ISSUE TITLE
IE - update rss icon

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#1861]
![Screen Shot 2019-09-13 at 4 40 45 PM](https://user-images.githubusercontent.com/9905193/64955494-5cf72a80-d856-11e9-9e9c-066acdad2b05.png)
 vs

![Screen Shot 2019-09-16 at 7 50 58 AM](https://user-images.githubusercontent.com/9905193/64955641-c5460c00-d856-11e9-959f-2274337efafc.png)

**Comment by kevinreiss** [comment]
Can we check the current Edge and see if this still an issue. If not, close.

**Comment by sandbergja** [comment]
Here it is on Edge 104.0.1293.70:

![search results page on Edge, showing an RSS icon](https://user-images.githubusercontent.com/7086943/188003026-aefcdbcf-7ab8-4f67-a6da-a65f61d940d5.png)

Since the RSS icon is displaying as expected, I'm closing this ticket.
