### ISSUE TITLE
Lazy load facets on the search results.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#1868]
Options:

1. Start loading them via AJAX as soon as the page loads.
2. Don't load them until the facet clicks.

**Comment by christinach** [comment]
Only request the facets on page load when 'collapse' is set to 'false' in the catalog controller; The collapse is set to false only for 'Access' and 'Format'. For the rest of the facets get the request only when you click on them.

**Comment by christinach** [comment]
@tampakis mentioned to check the publication year functionality.

**Comment by christinach** [comment]
After asking @tampakis to understand better the issue, the facet_counts is what stresses solr. I was looking in the wrong spot ->( removing the default query from BL that returns all the documents. ) This does not stress solr.

**Comment by christinach** [comment]
- [ ] Remove the default blacklight query(functionality) that returns all the facets in the home page
- [ ] Load a facet when `click` -> `expand` a facet. Don't load collapsed facets.
