### ISSUE TITLE
Facets that aren't displayed on the page are being loaded

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#1869]
This may require work in Blacklight to fix.
e.g: https://catalog.princeton.edu/catalog.json?utf8=%E2%9C%93&search_field=all_fields&q=Music class_year_s does not display.

This happens because the facets are in the catalog controller but set to `show: false` so that it creates a click to search link from the show page, but doesn't result in a facet.

**Comment by tampakis** [comment]
https://github.com/projectblacklight/blacklight/blob/0ac60aa80d9b99a0cc96ab3e234064b356b00709/spec/models/blacklight/configuration_spec.rb#L293-L308
