### ISSUE TITLE
[Orangelight/production] NoMethodError: undefined method `get_facet_field_response' for #<CatalogController:0x00007f871ceb9c90>

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1871]
[Orangelight/production] NoMethodError: undefined method `get_facet_field_response' for #<CatalogController:0x00007f871ceb9c90>

## Backtrace

    line 637 of [PROJECT_ROOT]/app/controllers/catalog_controller.rb: facet
    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/54980800)

**Comment by hackmastera** [comment]
Yep, `get_facet_field_response` doesn't exist anymore in OL 7.

The `facet` method in catalog controller was overridden to provide an additional point of error handling in https://github.com/pulibrary/orangelight/pull/1405 in response to a honeybadger error which longer holds any data. However, that honeybadger error did recur after the change in that PR was deployed (but still long enough ago that there's no data for it) and experimenting with the method and its test reveals that only the first error condition was being tested.

I think we should try removing the method override and trying again if https://app.honeybadger.io/projects/54399/faults/36286262 recurs. I'll submit a PR reverting #1405
