### ISSUE TITLE
Citations link broken for record 9946263

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1874]
[Orangelight/production] ActionView::Template::Error: undefined method `[]' for nil:NilClass

## Backtrace

    line 79 of [PROJECT_ROOT]/app/models/concerns/blacklight/solr/document/marc.rb: export_as_chicago_citation_txt
    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/47616219)

**Comment by hackmastera** [comment]
Couldn't resolve this in runner time allotment. Need a fixture for this item, a test for `export_as_chicago_citation_txt`. Then it will be possible to debug and see what's going on.
