### ISSUE TITLE
Features on home page

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#1882]
(Cf. #215 and #444)

What about featuring new faculty publications and newly digitized content on the home page? Other featured items might be nice, but would require more manual labor to maintain and keep fresh than we have.

<img width="1322" alt="Screen Shot 2019-10-10 at 11 28 45 AM" src="https://user-images.githubusercontent.com/999701/66583350-2bba0380-eb51-11e9-9233-68d5ee777b87.png">

**Comment by tampakis** [comment]
Sounds like a great idea! [Duke's catalog](https://find.library.duke.edu/) has something like this. The catalog homepage is on the agenda for the next DSSG meeting.
