### ISSUE TITLE
Google isn't indexing all our stuff

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1886]
Google has only about [150K](https://www.google.com/search?q=site%3Acatalog.princeton.edu&rlz=1C5CHFA_enUS857US857&oq=site%3Acatalog.princeton.edu&aqs=chrome..69i57j69i59l3j69i58.7521j0j7&sourceid=chrome&ie=UTF-8) of our 14 million pages indexed
Load balancer issue - since the files are only on [one server](https://github.com/pulibrary/orangelight/blob/master/config/deploy/production.rb#L29) the files don't always download: https://catalog.princeton.edu/sitemap31.xml.gz

**Comment by tampakis** [comment]
Looking at at an implementation to generate the sitemaps on the fly, also got our websites on the Google web search console
https://github.com/pulibrary/orangelight/tree/sitemap-generator
https://github.com/sul-dlss/SearchWorks/pull/2351

**Comment by tampakis** [comment]
Waiting to hear back from OIT about princeton gsuite access to search console tools

**Comment by kevinreiss** [comment]
Possibly can close pending confirmation of success of https://github.com/pulibrary/orangelight/pull/3169
