### ISSUE TITLE
Requests buttons showing when items are 3 hour reserves

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/orangelight#1888]
We originally discussed this and thought it was a request issue, but after further review the request page once you click through to it has the appropriate buttons.  It seems like there may be some logic issue in orangelight, or some combination of the two.

Here is the original ticket created over in requests:
https://github.com/pulibrary/requests/issues/421

There are two examples of this:

Records with request buttons it should not have: https://catalog.princeton.edu/catalog/1782308 & https://catalog.princeton.edu/catalog/4803624

Issue described in: https://princeton.service-now.com/snap?sys_id=7f3be905dba404d4a341de82ca96190f&view=sp&id=ticket&table=incident

**Comment by tpendragon** [comment]
![Screen Shot 2019-11-18 at 10 58 51 AM](https://user-images.githubusercontent.com/2806645/69081242-6c2f5b80-09f2-11ea-927c-f8afb8c4e16e.png)

This one in https://catalog.princeton.edu/catalog/1782308 should not have a request button.

**Comment by christinach** [comment]
same https://catalog.princeton.edu/catalog/4981710

**Comment by christinach** [comment]
Find an example record from alma

**Comment by hectorcorrea** [comment]
See also https://github.com/pulibrary/orangelight/issues/2711

**Comment by christinach** [comment]
This will be resolved by https://github.com/pulibrary/bibdata/issues/1646

**Comment by christinach** [comment]
resolved by https://github.com/pulibrary/bibdata/pull/1653

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/9905193/133656212-18ebe2fd-37ac-4fc2-9349-7d599b8f2786.gif)
