### ISSUE TITLE
Use dynamic configuration

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1893]
This item displays a viewer with a download button that should be suppressed:
https://catalog.princeton.edu/catalog/6142969

We should use the dynamic configuration, e.g.:

`https://figgy.princeton.edu/viewer#?manifest=https://figgy.princeton.edu/concern/scanned_resources/dada213d-68f4-4dcb-ab22-fefe9e1fe19c/manifest&config=https://figgy.princeton.edu/viewer/config/dada213d-68f4-4dcb-ab22-fefe9e1fe19c.json`

`config=https://figgy.princeton.edu/uv/uv_config.json`
becomes:
`config=https://figgy.princeton.edu/viewer/config/dada213d-68f4-4dcb-ab22-fefe9e1fe19c.json`

**Comment by tpendragon** [comment]
We don't have to do this anymore, Figgy takes care of it.
