### ISSUE TITLE
Availability - Document the availability.js functionality

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#1895]
https://github.com/pulibrary/orangelight/blob/master/app/assets/javascripts/availability.js.coffee.erb

**Comment by tampakis** [comment]
A lot of the logic for assigning availability is also here: https://github.com/pulibrary/marc_liberation/blob/master/app/controllers/availability_controller.rb

**Comment by tampakis** [comment]
As https://github.com/pulibrary/marc_liberation/issues/573 indicates, Ideally with a refactor/new system the logic for this can live all in one place.

**Comment by christinach** [comment]
Previous documents for the availability and the status https://docs.google.com/spreadsheets/d/1yjHqjtl_Bs_MiKKu0FzjdIIe2NzgskVeBlJsWPTkgN0/edit#gid=0
https://docs.google.com/drawings/d/1AZWqQ3r2AFRSO45SaHyR9Rlo-3koqK6ME2r5PVsIEOQ/edit
https://docs.google.com/spreadsheets/d/1MVM4_Q2ZzFnrpzWtEGywnAoB5hndySOgFzr4Hfun200/edit#gid=979200987
