### ISSUE TITLE
Update call number browse to use Solr instead of the database

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1897]
See Solr call number browse from ~Penn~, ~Cornell~, and/or Stanford.

**Comment by escowles** [comment]
Ideally, we could just get the call number info from the main index — if not, having a separate index for this info.

**Comment by escowles** [comment]
If this doesn't work, alternative is #1625

**Comment by kevinreiss** [comment]
Add to weekly OL weekly agenda for when we meet next.

**Comment by escowles** [comment]
FWIW, I believe I created this ticket because I perceived the database-based functionality as unreliable. If the current call number browse functionality is reliable, feel free to just close this.

**Comment by kevinreiss** [comment]
Ok, we believe it's reliable now and will close, also the browse area will be getting a lot of attention with the authorities project so we can return this question if it's helpful in the context of that work.
