### ISSUE TITLE
Right to left with numbers

### ISSUE THREAD

**Issue by axapu** [pulibrary/orangelight#190]
ID: 2953299 / http://pulsearch-dev.princeton.edu/catalog/2953299

![rtl](https://cloud.githubusercontent.com/assets/8161144/9092481/737142a6-3b74-11e5-89ca-7926ac17d094.png)
Close-up:
![screen shot 2015-08-05 at 1 12 53 pm](https://cloud.githubusercontent.com/assets/8161144/9092493/7f737e0c-3b74-11e5-890c-66381f33a1d4.png)
Proposed "fix" though numbers are still jumbled up:
![screen shot 2015-08-05 at 1 12 40 pm](https://cloud.githubusercontent.com/assets/8161144/9092495/83dc7660-3b74-11e5-8c6e-37cfc04de42b.png)

**Comment by joycebcat** [comment]
Yes!  This looks lovely on my mac.  I'll check on my PC tomorrow.

**Comment by tampakis** [comment]
The font yes, but not the [Browse] bit.
