### ISSUE TITLE
Request to index finding aids at the component-level for members of the General Manuscripts Miscellaneous Collection (C0140)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/orangelight#1902]
Following the initial discussions of the Single Item Manuscripts Description Working Group, there is an outstanding need in order to provide support at the discovery layer for one specific finding aid collection, https://findingaids.princeton.edu/collections/C0140.

This collection is to serve as a designated collection for material acquired which is not bound, and  for which membership within a subject-specific collection elsewhere is not possible to assert or simply inaccurate. Due to the varied and generic nature of the components within this collection, the request is to ensure that each component can be indexed as a separate Blacklight Document, with the hopes of including (at minimum):

* Title
* Creator
* Description

There was also some discussion of supporting some basic rendering of provenance, but no physical description of the material itself need be captured within the Orangelight Document.

**Comment by christinach** [comment]
@regineheberlein is working on thathttps://github.com/pulibrary/aspace_helpers/issues/181
