### ISSUE TITLE
Dissertations not discoverable

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1913]
Anya Bartleman reports: When I search for dissertation and limit to Mudd Library, I only see 796 items, but we have many more dissertations than that.

**Comment by escowles** [comment]
There is not a "Dissertation" format to match "Senior thesis", so doing a keyword search for dissertation and limiting to Mudd Library seems like the best strategy to find them: https://catalog.princeton.edu/?f%5Baccess_facet%5D%5B%5D=In+the+Library&f%5Blocation%5D%5B%5D=Mudd+Manuscript+Library&q=dissertation

**Comment by kevinreiss** [comment]
Discussed at DACS ATT meeting. We think it can be closed. @escowles do you agree?

**Comment by kevinreiss** [comment]
From our RDSS cross-team meeting

```
From our cross-team notes of RDSS: “Revisiting dissertation-to-Alma upcoming workflow using XSLT and ProQuest”
Also “Dissertation catalog loading from DataSpace/Proquest troubleshooting completed”
```
