### ISSUE TITLE
[Orangelight/production] URI::InvalidURIError: URI must be ascii only "https://bibdata.princeton.edu/patron/22101002361913\u202C"

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#1931]
## Backtrace

    line 10 of [PROJECT_ROOT]/app/services/bibdata.rb: get_patron
    line 17 of [PROJECT_ROOT]/app/controllers/users/omniauth_callbacks_controller.rb: barcode
    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/60184136)

**Comment by tpendragon** [comment]
It looks like someone put the RTL character at the end of their barcode? I'm not really sure if we should handle this. @tampakis

**Comment by tampakis** [comment]
Yeah just saw that, maybe we should sanitize the input? From the form, ascii characters only? I would say only alphanumeric but we recently found a net id with a `.` character

**Comment by kevinreiss** [comment]
Should we sanitize the input on the now Alma user login board, or is the failed response for bibdata acceptable?

**Comment by maxkadel** [comment]
The alma login does not use the bibdata API, but uses the Alma gem to authenticate the user. The username is also being url encoded (we ran into an issue earlier this year with spaces in the alma usernames, which can occur - see https://github.com/pulibrary/orangelight/issues/3046)

**Comment by maxkadel** [comment]
What's being put in the database is not what the user inputs, but what is returned from Alma, so I think we don't need to do anything further with this.
