### ISSUE TITLE
Allow reserves core to be on a different solr instance

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/orangelight#1933]
Currently the reserves core is assumed to be on the same solr instance as the catalog index. Current migration strategy to solr 8 moves the catalog index before the reserves core, so we want to specify the reserves core location by complete url.

https://github.com/pulibrary/orangelight/blob/b4f83e65e4b07159d60e5a5a20ab0a6c9ab27046/app/indexers/reserve_indexer.rb

**Comment by tpendragon** [comment]
I don't think this is possible. If I'm remembering Reserves, it performs a cross-core join. It can't do a cross-server join.

**Comment by hackmastera** [comment]
dang it!
