### ISSUE TITLE
Inaccessible Lewis Locations Need Shelf Note/Icon

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1939]
Lewis Library would like to display a message and icon indicates the following locations are closed by construction: 'sci', 'scith', 'sciref', 'sciefa', 'sciss'. At one time we had an icon for this when a floor of Firestone was closed back in 2017, I'm not sure if that icon is still in the project.

**Comment by christinach** [comment]
@kevinreiss do we need this?

**Comment by kevinreiss** [comment]
No longer needed
