### ISSUE TITLE
Update Mudd items display for library closure starting March 13

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1943]
From Mudd staff:
In the OPAC, we wish to display messages for collections with location codes mudd, rcpph, prnc to inform people of the availability of collections during certain phases of the collections move and library closure. 

For example, as of March 13, collections with mudd, rcpph and prnc holdings should display the message “Mudd Library collections are unavailable until approximately June 3, 2020 due to a renovation. See our webpage for the most current information.” This message would have a hyperlink to our webpage as shown here.

Once we resume services in early June from Firestone Special Collections, we would ask for another message to display for the mudd, rcpph and prnc holdings, namely, “Mudd Library Collections will be delivered to the Firestone Special Collections Reading Room.” The messages would need to change again in November when we halt services for the move back in to the building.

**Comment by christinach** [comment]
@kevinreiss can you provide an update on this issue?

**Comment by kevinreiss** [comment]
We can close this. Mudd closure is over.
