### ISSUE TITLE
Update Ruby to 2.6

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#1944]
- [x]  Add Ruby 2.6 to CircleCI
- [x]  Fix any failing tests or dependency issues caused by upgrade to 2.6.
- [x]  Deploy code that hopefully works with both 2.4 and 2.6.
- [x]  Provision boxes to use Ruby 2.6.
- [x]  Remove Ruby 2.4 from CircleCI

**Comment by tpendragon** [comment]
Orangelight has some work going on, so putting this back to "To Do". Some in progress work: 

https://github.com/pulibrary/orangelight/tree/update_bundler updates bundler
https://github.com/pulibrary/princeton_ansible/compare/update_orangelight_ruby updates staging to be Ruby 2.6

**Comment by christinach** [comment]
we should also update https://github.com/pulibrary/requests/issues/442
