### ISSUE TITLE
Encrypt Borrow Direct Redirect

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1948]
The route: https://catalog.princeton.edu/borrow-direct redirects successfully authenticated users over the borrow direct service. The relais software in this system will soon require the data passed over it to be encrypted with a key they will provide customers per this documentation: https://help.oclc.org/Resource_Sharing/Relais_D2D/Authentication/Security_in_Relais. I have a test key the vendor has provided. 

We'll need to implement something like like the ruby example from this page https://help.oclc.org/Resource_Sharing/Relais_D2D/Authentication/Encryption here:

https://github.com/pulibrary/orangelight/blob/b4f83e65e4b07159d60e5a5a20ab0a6c9ab27046/app/controllers/account_controller.rb#L131

**Comment by kevinreiss** [comment]
To test.

1. Reach out to James Robinson at BD to tell them we are testing. Ultimately when successful he will activate our production configuration to use encryption. 
2. Encrypt the "PI" parameter with the public key provided by the Borrow Direct coordinator.
3. Change the RELAIS_BASE URL to the the BD test system configured for encryption with the accompanying private key.  https://sandbox.relais-host.com/user/login.html?group=patron 
4. Test Borrow Direct route(s) in Orangelight.

**Comment by christinach** [comment]
Communicate with @kevinreiss to coordinate with vendor.

**Comment by kevinreiss** [comment]
Borrow Direct will be deprecated this summer. Won't fix at this point.
