### ISSUE TITLE
Create an orangelight-staging queue for the rabbitmq

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#1949]

**Comment by christinach** [comment]
It will make it easier to create an `orangelight_staging` rabbitmq in the EventHandler.

**Comment by christinach** [comment]
When we implement that we should also consider https://github.com/pulibrary/orangelight/pull/1978

**Comment by christinach** [comment]
we have a rails_env staging. I will revisit this one for the orangelight_staging rabbitmq

**Comment by hackmastera** [comment]
Currently there is only a queue for "orangelight" (i.e. production). See screenshot below -- you can see production / staging queues for other applications, but only the 1 queue for orangelight.

The environment needs to be be used when creating the queue in https://github.com/pulibrary/orangelight/blob/21881ca33ccdaa4ce852e6fa76b0807bebfde685/app/workers/event_handler.rb#L5

see https://github.com/pulibrary/pomegranate/blob/4aba5d15df698492c7c65ff417c7e0366ed298fa/app/workers/figgy_event_handler.rb#L5 for an example of how it should look.

General info on configuration is on the pomegranate wiki: https://github.com/pulibrary/pomegranate/wiki/RabbitMQ---Sneakers




![Screen Shot 2020-05-28 at 9 34 25 AM](https://user-images.githubusercontent.com/845363/83151194-41713e80-a0ca-11ea-889c-6d1c10a83524.png)

**Comment by hackmastera** [comment]
Current workaround for building a new index using orangelight-staging is to turn off sneakers workers in production, set ol-staging to use the figgy production rabbitmq, and then trigger the figgy rake task.

**Comment by christinach** [comment]
catalog-qa uses the figgy-staging rabbitmq
catalog-alma-qa uses the figgy-staging rabbitmq
catalog-staging uses the figgy-staging rabbitmq
catalog (production) uses the figgy (production) rabbitmq.
With the workaround in the previous comment plus how the boxes are set in ansible there is no danger messages from figgy production to be pushed to a catalog box other than the production one.

However we should create a new queue for catalog-alma-qa. 
queue name: catalog_alma_qa, catalog_alma_qa-error, catalog_alma_qa-retry.
The consumers in the queue would be lib-orange-alma-qa1 and lib-orange-alma-qa2.

**Comment by hackartisan** [comment]
resolved by https://github.com/pulibrary/orangelight/pull/2544
