### ISSUE TITLE
Add item-page alerts

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1957]
- ReCAP Physical Delivery is closed, EDD still available
 - Special Collections and Marquand are digital only
 - All other items are paged/article express

Use the restrictions sidebar design: https://catalog.princeton.edu/catalog/10627841

**Comment by kevinreiss** [comment]
For Recap: Delivery of ReCAP Items to campus is suspended while campus is closed."
For Marquand: "Marquand Items are available as via our "Scan and Deliver" service. "
For Special Collections : "TBD".

**Comment by christinach** [comment]
@kevinreiss do we still want to add these item page alerts? If so what will the new content be?

**Comment by kevinreiss** [comment]
No, we can close this. This reflect past situations that aren't the case any longer.
