### ISSUE TITLE
Re-weight all the solr fields

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#1958]
Absolute scores have gone down as of solr 8.0, and our weighting was not longer accurate to make our tests pass. See:
      * https://lucene.apache.org/solr/guide/8_0/major-changes-in-solr-8.html#schema-changes-in-8-0
      * https://lucene.apache.org/solr/guide/8_0/other-schema-elements.html#similarity

In the meantime we will use the `LegacyBM25SimilarityFactory` but in order to move onto the new default similarity factory we'll need to close this ticket.

**Comment by kevinreiss** [comment]
We need to check the current production state to see if this is still a valid issue.

**Comment by kevinreiss** [comment]
Closing per OL meeting discussion on 4/13.
