### ISSUE TITLE
Home Page Updates

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1961]
- [ ] Add a prominent link to online content (https://catalog.princeton.edu/?f%5Baccess_facet%5D%5B%5D=Online) to the home page main area
- [x] Update the "Digital Collections" link to go to https://dpul.princeton.edu/
- [x] Should we move or remove "Welcome to the Catalog", and the about/tour links?

**Comment by christinach** [comment]
![Screen Shot 2020-03-19 at 8 35 18 AM](https://user-images.githubusercontent.com/9905193/77072635-66f41480-69c4-11ea-8b35-e9b4ae90ed55.png)

**Comment by sdellis** [comment]
The usability study we did before we released OrangeLight has a lot of good advice for how to improve this page, mostly under "General" and "Layout and Navigation" sections. Github issues were created in Spring 2016, but I can't seem to find them now. 

https://docs.google.com/document/d/1dPYkICkHbS6QSTJLXWt-e_uqCwvOgpeAby1bcgCSHag/edit?usp=sharing

**Comment by christinach** [comment]
Thank you @sdellis

**Comment by christinach** [comment]
closed by #1970
