### ISSUE TITLE
Temporarily Disable Request Button on Show Page

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#1972]
Disable all request buttons on the show page until the Library re-opens on 4/6, including reading room request button.

**Comment by carolyncole** [comment]
To remove request button in organgelight for every item:

ssh to deploy@bibdata1 and run
```
cd /opt/marc_liberation/current
RAILS_ENV=production bundle exec rails c
Locations::HoldingLocation.where(requestable:false).each{|hl| hl.requestable = false; hl.save}
```
ssh deploy@catalog-boxes and run
```
cd /opt/orange_light/current
RAILS_ENV=production bundle exec rails c
Rails.cache.clear
We have already tested the above changes on bibdata-staging1 and orangelight-staging1
```

**Comment by carolyncole** [comment]
Here are all the ones that are currently true:

["anxa", "anxadoc", "anxafst", "l", "p", "res", "sct", "sdt", "set", "sht", "spt", "srt", "stlo", "t", "anxb", "anxbl", "anxbnc", "ned", "hygf", "new", "sci", "sciefa", "scilaf", "sciref", "sciresp", "sciss", "scith", "sarp", "sat", "mlis", "other", "ppl", "pplt", "hsvc", "hsve", "hsvg", "hsvm", "hsvn", "hsvp", "hsvr", "pres", "rcpgp", "rcpjq", "rcppa", "rcppb", "rcppe", "rcppf", "rcppg", "rcpph", "rcppj", "rcppk", "rcppl", "rcppm", "rcppn", "rcppq", "rcpps", "rcppt", "rcppw", "rcppz", "rcpqb", "rcpqk", "rcpql", "rcpqv", "rcpqx", "rcpxc", "rcpxg", "rcpxm", "rcpxn", "rcpxp", "rcpxr", "rcpxx", "sprf", "pplnb", "scsbcul", "scsbnypl", "rcpxw", "hsvw", "fac", "gss"]

**Comment by kevinreiss** [comment]
requests are not being accepted until at least 4/6 including Borrow Direct and Interlibrary Loan services.
