### ISSUE TITLE
Display links to Hathi Trust items if they are available

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1985]
On the show page for an item with an OCLC number, search for the OCLC number in Hathi:

* https://catalog.hathitrust.org/api/volumes/full/oclc/424023.json

If any items are present, display a link to the item in Hathi Trust. A new feature will allow users to login and view items based on our holdings data (which we already send them for other projects).

**Comment by carolyncole** [comment]
Show the link in the show page in a new section for Hathi Trust similar to other editions.
Here is an example:  https://catalog.princeton.edu/catalog/3510207
try in order: 
https://catalog.hathitrust.org/api/volumes/brief/oclc/42579288.json
https://catalog.hathitrust.org/api/volumes/brief/isbn/1576070751.json
https://catalog.hathitrust.org/api/volumes/brief/lccn/99047618.json

**Comment by carolyncole** [comment]
Create an additional section like Online that gives a little information about Hathi Trust's temporary access due to COVID-19 and libraries being closed.
![Screen Shot 2020-03-31 at 11 22 16 AM](https://user-images.githubusercontent.com/1599081/78043913-f0e79a00-7341-11ea-8b5b-0fadd557a403.png)

**Comment by escowles** [comment]
Here are the docs for querying the Hathi API: https://www.hathitrust.org/bib_api

* Doing a query with multiple IDs: https://catalog.hathitrust.org/api/volumes/brief/json/isbn:0804753148;oclc:61211255

Which returns JSON that looks like this with an `itemURL` linking to online content we can now access (when logged in via CAS):
```
{
  "isbn:0804753148;oclc:61211255": {
    "records": {
      "005097385": {
        "recordURL": "https://catalog.hathitrust.org/Record/005097385",
        "titles": [
          "SARS in China : prelude to pandemic?"
        ],
        "isbns": [
          "9780804753142",
          "9780804753142",
          "9780804753135",
          "9780804753135",
          "9780804753142",
          "9780804753135"
        ],
        "issns": [
          
        ],
        "oclcs": [
          "61211255"
        ],
        "lccns": [
          "2005021276"
        ],
        "publishDates": [
          "2006"
        ]
      }
    },
    "items": [
      {
        "orig": "University of California",
        "fromRecord": "005097385",
        "htid": "uc1.31822035655224",
        "itemURL": "https://hdl.handle.net/2027/uc1.31822035655224",
        "rightsCode": "ic",
        "lastUpdate": "20170301",
        "enumcron": false,
        "usRightsString": "Limited (search-only)"
      }
    ]
  }
}```

**Comment by escowles** [comment]
Users who are not logged in to Hathi will see a message that the item is "not available online"
![Screen Shot 2020-04-01 at 8 42 55 AM](https://user-images.githubusercontent.com/856924/78138406-d9b5b480-73f4-11ea-814f-ffcccc8c950e.png)

Maybe we should send them to the login URL instead of to the item URL?

**Comment by carolyncole** [comment]
Since this is throw away...

The plan is to override the show in catalog controller: https://github.com/pulibrary/orangelight/blob/master/app/controllers/catalog_controller.rb#L634

The controller will call a helper service to create the url

if the url is set in the controller we will show a new partial in the availability: https://github.com/pulibrary/orangelight/blob/04d9ae4f1aea6da5547a0bacf59d3b97ab7c5b28/app/views/catalog/_show_availability.html.erb

To complete this we need to:

- [ ] HathiUrlService
- [ ] Override catalog controller show to run the service
- [ ] change _show_availability to display a partial if the url is set
- [ ] create the partial to show the url

**Comment by carolyncole** [comment]
https://babel.hathitrust.org/cgi/wayf?target=https%3A%2F%2Fbabel.hathitrust.org%2Fcgi%2Fpt%3Fid%3Dmdp.39015047450062

**Comment by escowles** [comment]
One issue that came up — we may want to exclude SCSB records, because we think their holdings wouldn't be counted, and therefore our users wouldn't be given access.

**Comment by carolyncole** [comment]
Yes we noticed those are not available.
