### ISSUE TITLE
We do not have access to Hathi Trust Items that match via isbn or lccn 

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/orangelight#1989]
ISBN Matches:
* https://catalog-staging.princeton.edu/catalog/4595525
* https://catalog-staging.princeton.edu/catalog/2790823
* https://catalog-staging.princeton.edu/catalog/10628403

LCCN Matches:
* https://catalog-staging.princeton.edu/catalog/3752451
* https://catalog-staging.princeton.edu/catalog/3141397
* https://catalog-staging.princeton.edu/catalog/5864864

If we were to add oclc numbers to these records they would match when Hathi ran a new report. This would give us access to more Hathi items. Note these are examples, not a complete list. Method for determining the full list is not yet clear.

**Comment by christinach** [comment]
@kevinreiss can we close this?

**Comment by kevinreiss** [comment]
Yes
