### ISSUE TITLE
Check Hathi spreadsheet to see which items are present in API

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/orangelight#1990]
For every match in the Hathi spreadsheet got out to the PAI and verify that there is really data there.

**Comment by carolyncole** [comment]
`HathiUrl.new(oclc_id: '173852588', isbn: nil, lccn: nil).url` for each item and output the url to a new file.

**Comment by christinach** [comment]
@escowles I'm running a local script for a while to get the numbers. I'm not sure if it will finish by the time you want to have the results. The file is very big. Many of the listed oclc don't return a hathi url though.

**Comment by christinach** [comment]
I'm looking if I can get something faster with jaavscript.

**Comment by christinach** [comment]
I ran the script against this file: overlap_20200316_princeton, to test a sample of 
32,572 records.
From these records:
4,806 resulted to a valid API url (14,75%) and 
27,766 resulted to a nil not a valid api url (85,24%)

**Comment by christinach** [comment]
there are 2 files from these results on google drive:  hathi_valid & hathi_nil
