### ISSUE TITLE
Check our Hathi links to be certain we really have access

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/orangelight#1991]
Write a test that can go through a list of orangelight items and log into Hathi and check to make sure we have emergency access.  Double check that even when we are logged in we do not get the unavailable due to copyright.

**Comment by carolyncole** [comment]
`HathiUrl.new(oclc_id: '173852588', isbn: nil, lccn: nil).url` for each item and output the url to a new file.

**Comment by carolyncole** [comment]
This is not under copyright just opens: https://catalog-staging.princeton.edu/catalog/426420
undercopyright checkout button appears: https://catalog-staging.princeton.edu/catalog/3510207

**Comment by carolyncole** [comment]
This is not under copyright just opens: https://catalog-staging.princeton.edu/catalog/426420
undercopyright checkout button appears: https://catalog-staging.princeton.edu/catalog/3510207

**Comment by carolyncole** [comment]
I went a slightly different route after thinking on this for a bit:
https://github.com/pulibrary/orangelight/pull/1995

Basically I thought that oclc was only going to allow us access to anything they though we had.  That list was in the spreadsheet...

I'm running the code locally against a tunneled version of solr.  It may take some time, but I am hopeful to have a list by the 3pm meeting.

**Comment by carolyncole** [comment]
I'm realizing this method may not get us results in time for the 3pm.  The .spreadsheet has 400K records, so loading them into the database is taking a long time.  I'm going to do it another way to in the hopes of having some intermediate results.  It will be generally slower, but some results will be better than no results.

**Comment by hackmastera** [comment]
Related to #1995; closing both of these since we are using a different strategy now.
