### ISSUE TITLE
Do we want to show temporary links to Hathi items we already had access to?

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1992]
Related to #1985 

If we already had access to a HathiTrust item (because it was our scan, or public domain), it already shows a link in the "Available Online" section. Do we want to show a second link to the temporary access?

Sample record: https://catalog-staging.princeton.edu/catalog/2786666

**Comment by christinach** [comment]
related to #1994

**Comment by escowles** [comment]
We decided to turn off Umlaut so the normal links would not be displayed, so there is only the temporary access link for consistency.
