### ISSUE TITLE
[Orangelight/production] ActionView::Template::Error: undefined method `-' for "汪精衛, 1883-1944":String

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1996]
## Backtrace

    line 11 of [PROJECT_ROOT]/app/views/catalog/_constraints.html.erb: _app_views_catalog__constraints_html_erb___4128021406604034719_70178128495320
    line 1 of [PROJECT_ROOT]/app/views/catalog/index.html.erb: _app_views_catalog_index_html_erb___1883187448846022735_70178128457620
    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/61802705)

**Comment by jrgriffiniii** [comment]
The query which triggers this error is the following:

`https://catalog.princeton.edu/?f%5bauthor_s%5d=%E6%B1%AA%E7%B2%BE%E8%A1%9B%2C+1883-1944`
which, decoded and parsed by the Rails Controllers, yields the following parameters:

```
{
  "f" => {"author_s" => "汪精衛, 1883-1944"},
}
```

Please find the stack trace here:
```
ActionView::Template::Error: undefined method `-' for "汪精衛, 1883-1944":String

 _constraints.html.erb  11 _app_views_catalog__constraints_html_erb(...)
[PROJECT_ROOT]/app/views/catalog/_constraints.html.erb:11:in `_app_views_catalog__constraints_html_erb'
 9       </div>
10       <span class="constraints-label sr-only"><%= t('blacklight.search.filters.title') %></span>
11       <%= render_constraints(params) %>
12     </div>
```
