### ISSUE TITLE
Unicode character in linked document id causing error

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#2009]
Re-opened this Honeybadger:
https://app.honeybadger.io/projects/54399/faults/52176374

Related to, but not fixed by:
https://github.com/pulibrary/orangelight/pull/1806

Need to strip unicode characters from linked document IDs.

The error affects this record:
https://catalog.princeton.edu/catalog/9770811/raw

If you look carefully, the second `other_editions_s`  id has an accidental unicode character instead of an ASCII "O":

```
"other_editions_s": [
"(OCoLC)78364531",
"(ОCoLC)78364531"
]
```

**Comment by christinach** [comment]
@mzelesky and I looked into the new field other_editions_s that was added (775w) and we should normalize it in a similar way we normalize 776 https://github.com/pulibrary/marc_liberation/blob/3c95829ef3d4e5f21c026d40f36bd1c0f6951a4e/marc_to_solr/lib/princeton_marc.rb#L141
