### ISSUE TITLE
The Request button should redirect to the Finding Aids website?

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2015]

**Comment by escowles** [comment]
Example record: https://catalog.princeton.edu/catalog/2139652

If you go to "Reading Room Request" for these items, you get a list of boxes with no description. We should instead display a link to the finding aid where they get a description of what's in what boxes. This should be done for any record with a call number starting with "AC" or "MC".

**Comment by regineheberlein** [comment]
There are two collections in the publicpolicy repo starting with "WC". We should determine whether they need to be included in this.

**Comment by christinach** [comment]
Will check the DSSG agenda.
