### ISSUE TITLE
Use New Solr Facet Syntax

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#202]
Facets have been slowing down Blacklight. When Solr 5.3 gets released, the newer facet request syntax will get a significant [performance boost](http://yonik.com/facet-performance/). I'm not sure if the [JSON response syntax](http://yonik.com/solr-json-request-api/) is compatible with RSolr yet.

**Comment by jpstroop** [comment]
This is technically a blacklight issue. Leaving open as a reminder.
