### ISSUE TITLE
Replicate 'Your Account' functionality with Alma

### ISSUE THREAD

**Issue by kelynch** [pulibrary/orangelight#2025]
Use the switch created in #2362

The following sections of the [account page](https://catalog.princeton.edu/account) need to be reimplemented for alma:

- patron blocks (remove; we can't get these from alma)
- charged items
- available held items
- hold requests
- fines / fees

Relevant areas of the code:
- [account controller](https://github.com/pulibrary/orangelight/blob/109970f3ed6c3d1a4d3da4104b18bed1e1d0b7bc/app/controllers/account_controller.rb)
  - [tests](https://github.com/pulibrary/orangelight/blob/109970f3ed6c3d1a4d3da4104b18bed1e1d0b7bc/spec/controllers/account_controller_spec.rb) note this controller is not well-tested in the actions that will require migration
  - [voyager patron client](https://github.com/pulibrary/orangelight/blob/109970f3ed6c3d1a4d3da4104b18bed1e1d0b7bc/lib/orangelight/voyager_patron_client.rb#L6)
  - [voyager account](https://github.com/pulibrary/orangelight/blob/109970f3ed6c3d1a4d3da4104b18bed1e1d0b7bc/lib/orangelight/voyager_account.rb)
  - [account helper](https://github.com/pulibrary/orangelight/blob/109970f3ed6c3d1a4d3da4104b18bed1e1d0b7bc/app/helpers/account_helper.rb#L3)

Areas of the page not affected:
- "Outstanding digitization requests" - this is illiad functionality

Implementation notes:
- use alma-rb. there may be places where we need to submit PRs upstream
- [Alma API documentation](https://developers.exlibrisgroup.com/alma/apis/docs/users/R0VUIC9hbG1hd3MvdjEvdXNlcnMve3VzZXJfaWR9/)
- Ensure the case where the patron log-in by barcode is working and has test coverage
- There is some javascript involved in these pages to submit forms without refreshing the page
  - because of pagination required to get all loans, requests, or fees, we may need to move more logic into javascript.
- Note there is a use case for renewing a LOT of items at once (like all 500 books that a person has checked out)
  - We won't be able to accommodate this with the alma api; it only allows one renewal at a time. We should implement a "renew this item" button on each row to avoid hitting that endpoint rapid-fire.
- The fees may have a decimal value; make sure that's coming through from bibdata.
- Test a renew request when the patron account has limits.
- Provide useful feedback when we've hit the api concurrency limit (ask user to wait a moment and try again)

Other Notes:
- What are recalls? Is there functionality here that needs to be migrated?
  - This functionality was removed as part of covid-related policy changes. Assume we do not need to re-implement for now.

**Comment by kelynch** [comment]
Example from [alma_rb](https://github.com/tulibraries/alma_rb) gem for accessing user objects:

```ruby
require 'alma'

Alma.configure do |config|
  config.apikey = 'X'
  # ...
end

$primary_identifier = "john.doe"

u = Alma::User.find($primary_identifier)

# Methods 
$ ls u
Alma::User#methods: 
  []        loans                  preferred_name        save!         
  []=       loggable               preferred_suffix      to_json       
  email     method_missing         renew_all_loans       total_fines   
  fines     preferred_email        renew_loan            total_loans   
  has_key?  preferred_first_name   renew_multiple_loans  total_requests
  id        preferred_last_name    requests              validate      
  keys      preferred_middle_name  response            
```

**Comment by hackartisan** [comment]
The account controller in orangelight fetches patron "first_name", "last_name", "barcode" from bibdata using the netit.

Then it hits voyager to get the account object with the following properties:
- avail_items has keys:
  - itemID
  - itemTitle
  - expireDate
  - pickuplocation
- request_items has keys:
  - itemID
  - itemTitle
  - expireDate
  - pickuplocation
  - queuePosition
- fines_fees has keys:
  - date
  - title
  - postingType
  - amount
  - balance
- charged_items has keys:
  - itemId
  - renewable
  - title
  - dueDate
- borrowing_blocks has keys:
  - patronGroupName
  - blockCount
  - blockReason
- demerits renders all keys / values; sample data has keys:
  - demeritId
  - demeritDate
  - itemTitle
  - demeritType
  - amount
  - amountTotal
  - balance
  - balanceTotal

**Comment by hackartisan** [comment]
Block info needs to be added to the bibdata response so it can be pulled from the patron without an additional API call. Block data from alma looks like

```
      "user_block": [
        {
          "segment_type": "Internal",
          "block_type": {
            "value": "LOAN"
          },
          "block_description": {
            "value": "CONSORTIA"
          },
          "block_status": "string",
          "block_note": "string",
          "created_by": "string",
          "created_date": "2024-05-30T09:30:10Z",
          "expiry_date": "2019-12-18T14:36:48.659Z"
        }
      ],
```

How does this map onto our current values?

- patronGroupName
- blockCount
- blockReason

**Comment by hackartisan** [comment]
I don't see demerits in alma at all. Will we still have demerits?

**Comment by hackartisan** [comment]
`avail_items` and `request_items` I think would both come from the [user requests GET endpoint](https://developers.exlibrisgroup.com/alma/apis/docs/users/R0VUIC9hbG1hd3MvdjEvdXNlcnMve3VzZXJfaWR9L3JlcXVlc3Rz/).

Data coming back looks like:
https://developers.exlibrisgroup.com/alma/apis/docs/xsd/rest_user_requests.xsd/?tags=GET

itemID: we get a holding_id will that work?
itemTitle: chapter_or_article_title
expireDate: not given? we get last_interest_date, booking_start_date, and booking_end_date. Not sure if any of those are relevant here
pickuplocation: pickup_location_library and pickup_location_circulation_desk
queuePosition: not given. Is there another way to get this?

**Comment by hackartisan** [comment]
fines_fees will come from the [user fines endpoint](https://developers.exlibrisgroup.com/alma/apis/docs/users/R0VUIC9hbG1hd3MvdjEvdXNlcnMve3VzZXJfaWR9L2ZlZXM=/). Returns active fees by default. Is that what we want?

[fees object](https://developers.exlibrisgroup.com/alma/apis/docs/xsd/rest_fees.xsd/?tags=GET)

[fee object](https://developers.exlibrisgroup.com/alma/apis/docs/xsd/rest_fee.xsd/)

- `date`: creation_time
- `title`: title
- `postingType`: type description (but from the example it looks like the api only sends the type value? maybe we can ask them to add the description)
- `amount`: original_amount
- `balance`: balance

**Comment by kevinreiss** [comment]
Yes, active fees would be what we want to display. We didn't have the option to display past fees in Voyager so that would be new functionality that could potentially added to allow users to see their paid/cancelled fines.

**Comment by hackartisan** [comment]
- request cancel endpoint takes request_id and returns `204 No Content` on success.
- renew loan takes loan_id and returns the loan object

**Comment by hackartisan** [comment]
We'd like to have a discussion about whether it would make sense to link out to alma's "library card" page instead of reimplementing this in blacklight. Arguments in favor of doing this are:

1. The local implementation requires 5 API calls to build the display page. Note that this is 1/5th of the concurrency limit for API calls.
2. There is functionality we cannot implement via the API, such as "renew all" (the api only provides single renewal, and again the concurrency limit) and up-front account limit notifications (e.g. "You can't renew this because you have too many fines" in the API is just "renewable: false")
3. Using the alma page would release developer time as we move toward go-live.

There are a few considerations we'd need to iron out:
1. What do we do with guest accounts? Provide them with usernames / passwords directly in Alma? Provide a minimal UI for them in blacklight (guests don't have as many privileges so this could be loans display only with one renewal at a time)? Just not provide an online account service?
2. Others?

Work for this issue is in progress on branch [2025-alma-account](https://github.com/pulibrary/orangelight/compare/2025-alma-account?expand=1). Setting aside / blocking for now until we get some feedback.

**Comment by hackartisan** [comment]
We've decided to continue this implementation, replacing the "renew" check boxes with a button next to each loan so that only one renewal can be performed at a time. The API doesn't support multiple renewals and keeping the check boxes would require us to throttle the api calls to avoid the concurrency limit.

**Comment by hackartisan** [comment]
closing in favor of #2401
