### ISSUE TITLE
Holding Location for RCPPZ shows up twice in advanced search options

### ISSUE THREAD

**Issue by kelea99** [pulibrary/orangelight#2032]
See screenshot: 
<img width="1440" alt="Screen Shot 2020-05-11 at 3 04 31 PM" src="https://user-images.githubusercontent.com/45043014/81607812-4aac9c80-93a3-11ea-8285-4ba7b2f5ca46.png">

**Comment by christinach** [comment]
This is not a bug. It displays twice as expected. This ticket has the old recap location code from voyager but the concept is the same . see: https://github.com/pulibrary/orangelight/issues/2744

**Comment by christinach** [comment]
see https://github.com/pulibrary/bibdata/issues/2031
