### ISSUE TITLE
Add a more/less button for items with multiple locations

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2050]
example: https://catalog.princeton.edu/catalog/SCSB-5936783

**Comment by kelynch** [comment]
Non-SCSB example: https://catalog.princeton.edu/catalog/11059902

**Comment by kevinreiss** [comment]
Closing this issue. Will raise the weird display for teh SCSB example with circ management group.

**Comment by kevinreiss** [comment]
The second scenario is under this https://github.com/pulibrary/orangelight/issues/3276.
