### ISSUE TITLE
Holds are only valid for 7 days in emails, but voyager allows 60 days

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/orangelight#2059]
This may confuse the patrons!

![Screen Shot 2020-06-01 at 10.06.47 AM.png](https://images.zenhubusercontent.com/5c925e2d9d1bd30b8d310436/790303f9-22cc-4b61-813c-a9dc4d3a7711)

**Comment by mzelesky** [comment]
Looks like I have some Voyager work remaining! Can you tell me what item ID was used?

**Comment by carolyncole** [comment]
https://catalog.princeton.edu/requests/11807092?mfhd=11467956&source=pulsearch
![Screen Shot 2020-06-01 at 10.12.16 AM.png](https://images.zenhubusercontent.com/5c925e2d9d1bd30b8d310436/f75955ff-0899-414e-b835-223e4109a18e)

**Comment by mzelesky** [comment]
Ok, it looks like it's taking the expiration from https://github.com/pulibrary/requests/blob/aa193410e6416f5e42ec8ebab035e2fa8a0b6235/app/models/concerns/requests/voyager.rb#L79

**Comment by mzelesky** [comment]
<last-interest-date> should be 7 days from the date of the request for holds.

**Comment by mzelesky** [comment]
This expiration date is what is sent to patrons when the item is available.

**Comment by mzelesky** [comment]
To clarify: it is nothing wrong with Voyager's configuration. Changing the last-interest-date to 7 days from now instead of 60 days will fix it.
