### ISSUE TITLE
Use "Classic Catalog" instead of "Main Catalog" on record view page

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#206]
![screenshot from 2015-08-19 16 13 03](https://cloud.githubusercontent.com/assets/999701/9367773/85002b9e-468d-11e5-85ca-4764a7c52f40.png)

**Comment by jpstroop** [comment]
defer, or close as wontfix per @marvinmarvinb ?

**Comment by jpstroop** [comment]
We should probably close as wontfix for now (sorry @axapu !)

**Comment by tampakis** [comment]
:+1:
