### ISSUE TITLE
What does the checkbox do?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#207]
I know what it does, but I don't think a user would. Maybe a tooltip when hovering on the checkbox should indicate what it does? I don't :heart: that solution, but it's not clear to me where a label should go, and redundant text in each result would be annoying.

![screenshot from 2015-08-19 16 23 12](https://cloud.githubusercontent.com/assets/999701/9368140/984006dc-468f-11e5-93c9-38a31907b83b.png)

Also, the relationship to the graphic/cover placeholder seems a little awkward. Maybe it should line up with the left edge of the image (maybe it does an there's white space padding in the image making it confusing?.

**Comment by tampakis** [comment]
#214 has "Add to folder" placed to the right, similar to the default "Bookmark" text in the demo [Blacklight app](http://demo.projectblacklight.org/?utf8=%E2%9C%93&search_field=all_fields&q=).
