### ISSUE TITLE
Get "orangelight" out of title bar

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#208]
![title](https://cloud.githubusercontent.com/assets/999701/9368357/cb7727fa-4690-11e5-8711-84ce92f08439.png)

Replace w/ what, I'm not sure, but I doubt LISSC etc. will go for OrangeLight.

**Comment by tampakis** [comment]
Catalog?

**Comment by tampakis** [comment]
Related issue - Advanced search appears on instead of guided search in the title bar.
![guided_search](https://cloud.githubusercontent.com/assets/4650153/9368462/75540d92-4691-11e5-9741-9a2d7ed1d3e0.png)
