### ISSUE TITLE
Line up facet value "x", and count, add label for "x"

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#210]
![facet](https://cloud.githubusercontent.com/assets/999701/9368552/dfb773e0-4691-11e5-87f7-9d253639db47.png)

The "x" is high, and I also wonder if the count is higher. I can't tell.

Also, not to harp on tooltips, but I wonder if there are accessibility issues around the fact that what this does isn't labeled?

The HTML markup is this:

```html
<a class="remove" 
    href="/?q=john+cage+variations&amp;search_field=all_fields">
    <span class="glyphicon glyphicon-remove"></span>
    <span class="sr-only">[remove]</span>
</a>
```

I wonder if add `@data-original-title` and/or `@title` with the value 'Remove Format facet value "Book"' (or something like that) to the anchor tag that would be a good idea?

**Comment by tampakis** [comment]
![facet_x](https://cloud.githubusercontent.com/assets/4650153/9466331/1b737fae-4b02-11e5-8e38-528ed37c9719.png)
I'm also +1 for a tooltip.

**Comment by axamei** [comment]
@tampakis what browser are you using?

**Comment by tampakis** [comment]
I took that screenshot from Firefox, but it looks the same in Chrome too.
![facet_x_chrome](https://cloud.githubusercontent.com/assets/4650153/9467378/49a02812-4b09-11e5-8256-4274f89ead86.png)

**Comment by jpstroop** [comment]
Yeah, still looking high to me too (in Chrome). And I think the tooltip should happen.
