### ISSUE TITLE
Remove checkbox from the 'Requested Items Section'

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2102]
The table 'Requested Items section' has a checkbox that is not used. We should remove it. 
![Screen Shot 2020-06-12 at 1 27 10 PM](https://user-images.githubusercontent.com/9905193/84530020-7081d580-acb0-11ea-9c24-caf4d347d406.png)

**Comment by christinach** [comment]
there is not select all button for the request items.

**Comment by kevinreiss** [comment]
Oh, sorry. Yes it should be removed.

**Comment by kevinreiss** [comment]
Closing.
