### ISSUE TITLE
Use matomo to add event tracking for the different searches.

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2110]
I would like to add an event tracking for the different searches we provide:
![Screen Shot 2020-06-16 at 10 52 46 AM](https://user-images.githubusercontent.com/9905193/84790634-91ec0580-afbf-11ea-849a-db1fe1fd1fe8.png)

**Comment by kevinreiss** [comment]
Matomo is no longer in the mix for analytics. Closing.
