### ISSUE TITLE
[Orangelight] JSON::ParserError: lexical error: invalid char in json text.
                                       <html> <head> <meta http-equiv=
                     (right here) ------^

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#2113]
## Backtrace

    line 39 of [PROJECT_ROOT]/lib/orangelight/browse_lists.rb: browse_facet
    line 23 of [PROJECT_ROOT]/lib/tasks/browse.rake: block (2 levels) in <top (required)>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/64058586)

**Comment by jrgriffiniii** [comment]
Perhaps better error handling could be introduced for these errors.

**Comment by christinach** [comment]
this was resolved and didnt happen again
