### ISSUE TITLE
Allow users to digitally "check out" items through the CDL workflow

### ISSUE THREAD

**Issue by kelynch** [pulibrary/orangelight#2117]
Allow users to digitally “check out” a copy of an item available through through the CDL workflow.  The number of copies available must be equal to the number of physical copies owned by PUL.  Once an item is checked out, it should be marked "unavailable" in the catalog.  Other users are barred from checking out that copy.

Limit the number of simultaneous checkouts of CDL items to N authenticated users, when N is equal to the number of physical copies owned by PUL.

Once the CDL workflow is in place, items that are paged and digitized for this or the digitization service workflow are then held in an inaccessible location to reflect the limit.  [Pickup requests](https://library.princeton.edu/phased-planning-updates) and CDL checkout requests go in the same queue and users will be served on a first-come, first-served order.

**Comment by tpendragon** [comment]
Close in preference of https://github.com/pulibrary/figgy/issues/4030
