### ISSUE TITLE
When the loan period ends, CDL items should stop being accessible

### ISSUE THREAD

**Issue by kelynch** [pulibrary/orangelight#2119]
Items checked out through CDL should be returned in one of the following ways:

* The item is automatically returned after a determined amount of time has passed (regardless of interaction with the viewer).
* When an item is nearing automated return, the user should be notified of this, with the option to renew if there is not a queue, or to add themselves to the queue to check it out again. (see #2127)
* The user the item is checked out to returns the item explicitly, making it available for lending again. (see #2137)

**Comment by escowles** [comment]
There may be different loan periods for different categories of materials, e.g., items on course reserve may have a 3 hour loan period, but other items may have a 24 hour loan period.

**Comment by tpendragon** [comment]
Close in preference of https://github.com/pulibrary/figgy/issues/4032
