### ISSUE TITLE
Copyright notice on show page for CDL items 

### ISSUE THREAD

**Issue by kelynch** [pulibrary/orangelight#2120]
Display a copyright notice (language forthcoming) at all times on the show page for checked-out items loaned through CDL.

Proposed language in https://docs.google.com/document/d/1XgEZOlR5bdCS8_IbdoPp42RNzQKUS-HvyNaTFR9NpEQ/edit

**Comment by escowles** [comment]
The copyright notice in the linked document is displayed before a user is allowed to check out an item.
