### ISSUE TITLE
Click-through copyright notice for CDL items

### ISSUE THREAD

**Issue by kelynch** [pulibrary/orangelight#2121]
Provide a click-through notice on the show page for items loaned through the CDL workflow.  No digitized content should load before the click-through is clicked.

Proposed language in https://docs.google.com/document/d/1XgEZOlR5bdCS8_IbdoPp42RNzQKUS-HvyNaTFR9NpEQ/edit

**Comment by tpendragon** [comment]
Close in preference of https://github.com/pulibrary/figgy/issues/4030
