### ISSUE TITLE
Keep de-identified usage logs for CDL service

### ISSUE THREAD

**Issue by kelynch** [pulibrary/orangelight#2122]
Keep logs for usage of the CDL workflow (recording which items are "checked out" and "returned," and any attempts to check out that fail if the item is checked out), with no personally-identifiable information.  This should specifically avoid being a log of who checked out what, consistent with what we avoid in logging of physical items.

**Comment by tpendragon** [comment]
The notes for this recommended hashing the netid. Unfortunately we have a limited number of users, so hashing isn't a good way to make the log anonymous (it would be trivial for us to just hash all the registered ids and see who checked it out.) Can we just not log the user who did it at all?

**Comment by tpendragon** [comment]
Closed in preference of https://github.com/pulibrary/figgy/issues/4031
