### ISSUE TITLE
Block browser download of items presented through CDL workflow

### ISSUE THREAD

**Issue by kelynch** [pulibrary/orangelight#2123]
As much as possible, prevent browser behaviors that would facilitate download of images from the page.  This should include disabling right-clicking for download.

See @escowles note below for additional context.

**Comment by escowles** [comment]
Note: for disabling right-click or other browser functionality for users to download content, the goal is not to be 100% effective (which we don't think is possible). The goal is to deter casual downloads, and require circumvention, which shows good-faith effort on our part.

**Comment by tpendragon** [comment]
Closed in preference of https://github.com/pulibrary/figgy/issues/4028.

Regarding right-click, UV is a tiled viewer and already doesn't provide right-click as an option.
