### ISSUE TITLE
Present items checked out through CDL workflow in Orangelight show page

### ISSUE THREAD

**Issue by kelynch** [pulibrary/orangelight#2124]
When an item is checked out through the CDL workflow, the item should be viewable during the period of checkout in Orangelight, on the record's show page. 

Note additional requirements for the viewer in #2123

**Comment by escowles** [comment]
This was demonstrated 7/10 — keeping this ticket open to track production deployment of this feature.

**Comment by escowles** [comment]
This was deployed in production in late July/early August.
