### ISSUE TITLE
Limit availability of the CDL service to authorized users

### ISSUE THREAD

**Issue by kelynch** [pulibrary/orangelight#2125]
This service will only be available to authorized members of the Princeton community.  Limit access to the digital checkout workflow only to authenticated users who fall into this group.

Access group is defined as anyone with a Princeton NetID.

**Comment by kelynch** [comment]
I'm working with @escowles to make a more granular definition of the authorized group.

**Comment by tpendragon** [comment]
Closed in preference for https://github.com/pulibrary/figgy/issues/4027
