### ISSUE TITLE
How are reserves items identified and what is their loan period?

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#2128]
- [ ] How do we determine if an item is a reserve item?
- [ ] Physical reserves items are typically a 3-hour loan, do we want to use the same loan period?

**Comment by tpendragon** [comment]
@escowles Did it seem like they wanted to manually define items which could be reserved, or do we need some programatic way?

**Comment by escowles** [comment]
In Bibdata, the location code is in the `852$b` field: https://bibdata.princeton.edu/bibliographic/5317354

``` xml
<datafield ind1="0" ind2=" " tag="852">
    <subfield code="0">5491155</subfield>
    <subfield code="b">spir</subfield>
    <subfield code="t">1</subfield>
    <subfield code="h">HD9576.C372</subfield>
    <subfield code="i">L48 2007</subfield>
</datafield>
```

Info about the locations can be looked up at: https://bibdata.princeton.edu/locations/holding_locations/ `code` .json, e.g., https://bibdata.princeton.edu/locations/holding_locations/spir.json

**Comment by christinach** [comment]
If you check the mfhd availability for this item it will give you the information `on_reserve: "N"` https://bibdata.princeton.edu/availability?mfhd=5491155

**Comment by escowles** [comment]
Peter also said that the mechanics of putting items on reserve are somewhat complicated, so we may just create a reserves user and check items out to that user. So we could list the items checked out to that user (like we do on the "Your Account" page) to see if an item is on reserve.

**Comment by escowles** [comment]
Decision 7/9: CDL items will be in the `cdlres` (reserves) or `cdl` (non-reserve) locations.
