### ISSUE TITLE
Implement a 'Subject (exact)' search

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2140]
![Screen Shot 2020-06-30 at 4 15 53 PM](https://user-images.githubusercontent.com/9905193/86172866-0741f500-baed-11ea-93d9-01e70bf6bc79.png)

https://catalog.princeton.edu/catalog/11845403

Subject browse for Data mining--Congresses returns https://catalog.princeton.edu/browse/subjects?q=Data+mining%E2%80%94Congresses 503 items. 

Subject browse for Data mining returns https://catalog.princeton.edu/browse/subjects?search_field=browse_subject&q=Data+mining which includes the 503 items from the search above.

We want the browse to remain this way.
We want to implement a 'Subject (exact)' search  to return only those records with the exact string of 'Data mining' in the subject heading.

For example this record https://catalog.princeton.edu/catalog/11916654/staff_view should not appear in the search results because there is a subdivision after 'Data mining' `650 0 a| Data mining v| Congresses.`

**Comment by carolyncole** [comment]
Quotes will not help this, because they want only the subject not sub subjects
(not the answer) https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=subject&q=%22Parent+and+teenager%22

**Comment by carolyncole** [comment]
https://catalog.princeton.edu/catalog/?f[subject_facet][]=Data+Mining

**Comment by kevinreiss** [comment]
This appears to be something you can do in Alma.

**Comment by mzelesky** [comment]
For staff, see the following screen shots for how to search for exact LC subjects:

<img width="548" alt="Screen Shot 2023-02-23 at 1 14 17 PM" src="https://user-images.githubusercontent.com/15231732/220994988-65736d11-92c6-4eaf-9d27-b7ce333c0a6d.png">
<img width="523" alt="Screen Shot 2023-02-23 at 1 13 57 PM" src="https://user-images.githubusercontent.com/15231732/220995003-9eef5440-5807-41d2-801e-3515d6c7575a.png">
<img width="942" alt="Screen Shot 2023-02-23 at 1 13 34 PM" src="https://user-images.githubusercontent.com/15231732/220995005-3cfa80e8-58ef-4a02-9544-99f7ddd6ea65.png">

**Comment by kevinreiss** [comment]
Closed per 7/1/2024 backlog review meeting.
