### ISSUE TITLE
Locator request to catalog causing error

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#2145]
[Orangelight/production] ActionView::Template::Error: undefined method `[]' for nil:NilClass

URL: https://catalog.princeton.edu/requests/7348786?mfhd=7348786&source=firestone_locator7348786
Referrer: https://locator-prod.princeton.edu/index.php?loc=f&id=7348786&embed=true
## Backtrace

    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/39796981)

**Comment by kevinreiss** [comment]
This route is only useful if a "loc" parameter containing a current voyager shelf location code is passed to it. We should handle any requests to this route without this parameter in a more graceful way that avoids the 500 error.

**Comment by kevinreiss** [comment]
This bib ID in the example URLs doesn't even exist.
