### ISSUE TITLE
Try "dropping search context to Advanced Search"

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2148]
While investigating https://app.honeybadger.io/projects/54399/faults/54936527/99971268-c0b6-11ea-83e4-0700d0f6e42e#notice-summary I found https://github.com/projectblacklight/blacklight_advanced_search/issues/102 which suggests "dropping search context to Advanced Search". Unfortunately we don't currently have a way to replicate the bug. But it might be worth determining exactly what it means to drop this search context, and if there wouldn't be undesirable side effects it might be worth doing it and seeing whether we stop getting that error.

**Comment by kevinreiss** [comment]
We are replacing advanced search with the upgrade to Blacklight 8. Closing.
