### ISSUE TITLE
Search tips on home page?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#215]
Less verbose, but something similar to what http://catalog.princeton.edu has now would probably be a good idea, in the hearts and minds department.

![tips](https://cloud.githubusercontent.com/assets/999701/9386859/83414b28-472b-11e5-8eda-ebd8ae7cba9c.png)

**Comment by kevinreiss** [comment]
I guess it could be an opportunity put these tips in the context of solr search.

**Comment by jpstroop** [comment]
That page also probably covers everything LISSC is going to ask about wrt to search syntax. Might as well have it ready.

**Comment by tampakis** [comment]
Adapt from: http://pulsearch-dev.princeton.edu/guided
