### ISSUE TITLE
Configure Shibboleth Authentication 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#2150]
* Set-up basic SAML configuration 
* Set-up profile for staff users
* Set up profile for patrons

**Comment by kevinreiss** [comment]
Basic SAML Handshake working set-up notes:

Look under ‘integration profiles’ in the sandbox
Alma SAML documentation
https://idp.princeton.edu/idp/shibboleth
This URL works as of 2020-06-24: https://sandbox02-na.alma.exlibrisgroup.com/institution/01PRI_INST/SAML/idpCode/SAML becomes https://sandbox02-na.alma.exlibrisgroup.com/mng/login?institute=01PRI_INST&auth=SAML (using default SAML profile)
SAML: https://<Alma sandbox domain>/institution/{INST_CODE}/SAML/idpCode/{sandbox SAML integration profile code}

**Comment by hackartisan** [comment]
This was slotted as "not needed" in the project plan - closing
