### ISSUE TITLE
Allow faculty to reserve CDL items for use during class

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#2162]
Use case: As an instructor, I want to show a CDL item in a class lecture. I would like to reserve an item for a specific time period so I can show it during the lecture.

**Comment by christinach** [comment]
@escowles if this is a still nice to have ticket , can we please close it in OL and create a new one in figgy?

**Comment by tpendragon** [comment]
It's been two years and students are in class again, I'd like to just close this.

**Comment by escowles** [comment]
👍🏻 I think it's fine to close this since the time where it would have been important has passed.
