### ISSUE TITLE
Add links to other versions based on Voyager config

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#217]
See here: https://github.com/pulibrary/orangeindex/blob/development/voyagersamplecfg/newdisplay12.cfg#L139-L151

and here:

https://github.com/pulibrary/orangeindex/blob/development/voyagersamplecfg/newdisplay12.cfg#L288-L289

The ones that contain 'BBID' should be pretty straight forward. E.g., given `3500 BBID787W` use the bib id in `787|w` to build a link.

The others, like `020Z020A` are trickier, because there's no guarantee that we have a that title, and hitting a service to check at index time would _really_ slow things down. We should probably try to find a way to rely on Umlaut for those. I assume that in `020Z020A`, z before a is an order of preference?

We'll also need to find a way to get the ISBN from, e.g. "9780691134970 (hardcover : alk. paper)" if we haven't already. I'm sure it won't be as easy as tokenizing on the first whitespace in the string, but that might be a place to start.

**Comment by kevinreiss** [comment]
I think the ISBN gem can help with the tokenizing, https://rubygems.org/gems/isbn.

**Comment by jpstroop** [comment]
```ruby
2.2.1 :001 > require 'isbn'
 => true 
2.2.1 :002 > ISBN.from_
ISBN.from_image   ISBN.from_string  
2.2.1 :002 > ISBN.from_string("9780691134970 (hardcover : alk. paper)")
 => "9780691134970" 
```

Yup.

**Comment by jpstroop** [comment]
Ahh, but it doesn't normalize:

```ruby
2.2.1 :023 > ISBN.from_string("1-84356-028-3 (hardcover : alk. paper)")
 => "1-84356-028-3" 
```

**Comment by jpstroop** [comment]
Based on what he's doing: https://github.com/tkersey/isbn/blob/master/lib/isbn.rb#L86

We can probably tack on a gsub and be just fine:

```ruby
2.2.1 :024 > ISBN.from_string("1-84356-028-3 (hardcover : alk. paper)").gsub(/\s|\-/,'')
 => "1843560283" 
```

**Comment by joycebcat** [comment]
@jpstroop Actually, you should be able to chop ISBN data off at the first whitespace.  Unless the data is bad, that should always work.  Keep in mind that there can be numbers in the additional data and "x" in the ISBN.

The purpose of bib linking is to lead users from one version of a resource to another--primarily print and e-versions but not always.  It does not have to be accomplished the same way it is done in V if you feel creative.  If you do mimic the bib linking feature, the profile names are illustrative of their structure, albeit backwards.  In V BBID787W means that if a record has a 787W, V will use the data in that subfield to look for a match with a BIBID.

**Comment by tampakis** [comment]
See #218, #223, #224, #22.

**Comment by tampakis** [comment]
@billdueber's [library_stdnums](https://github.com/billdueber/library_stdnums) looks awesome! It even converts to 13 digits.
```ruby
jruby-1.7.19 :012 > StdNum::ISBN.normalize("1-84356-028-3 (hardcover : alk. paper)")
 => "9781843560289"
jruby-1.7.19 :014 > StdNum::ISBN.convert_to_10("1-84356-028-3 (hardcover : alk. paper)")
 => "1843560283"
```
It also returns nil rather than raising an error when it comes across invalid ISBNs.
```ruby
jruby-1.7.19 :008 > ISBN.from_string('2251003982 (v. 2)')
ISBN::InvalidSourceString: ISBN::InvalidSourceString
jruby-1.7.19 :010 > StdNum::ISBN.normalize('2251003982 (v. 2)')
 => nil 
```

**Comment by billdueber** [comment]
I do a pretty good job trying to find an isbn/issn in there if there's something valid-ish. If you have edge cases that I'm not dealing with, lemme know and I'll try to address them.
