### ISSUE TITLE
Wireframe CDL item statuses in the catalog

### ISSUE THREAD

**Issue by kelynch** [pulibrary/orangelight#2171]
Wireframe options for representing items' statuses as "available" and "checked out" through CDL.

**Comment by tpendragon** [comment]
Current example: https://catalog.princeton.edu/catalog/679947

**Comment by hackmastera** [comment]
Scenarios:

1. There's one copy and its on CDL
2. There are 2 copies in the same location and 1of them is on CDL
3. There are 3 copies in the same location and 2 of them are on CDL
4. There are 2 copies in different locations and 1 of them is on CDL

**Comment by hackmastera** [comment]
Question for @escowles Should CDL items be requestable? Currently they can be requested for "pick-up or digitization" e.g. https://catalog.princeton.edu/catalog/679947

**Comment by escowles** [comment]
@hackmastera No, the CDL items should not be requestable. I believe the plan is to have selectors review the CDL items and decide which to reshelve and make requestable again.

**Comment by hackmastera** [comment]
Here's one initial sketch. Thoughts / suggestions? I think doing it this way could be good because we don't have to mix the CDL link into the "in the library" info -- this way no matter how many copies are on CDL there's only one link to the checkout. @escowles 

![OL-digital-lending-UI.png](https://images.zenhubusercontent.com/5cba1f45fec3b63424e0f761/21741b81-c0b3-46ea-a0e9-10b7e493a05f)

**Comment by escowles** [comment]
@hackmastera That looks good — and I agree that having the CDL access highlighted in the Online section makes more sense than under the Copies in the Library section. I'm not sure about using the word "Sequestered" though — maybe "Reserved for Digital Lending" or "Available via Digital Lending"?

**Comment by escowles** [comment]
One other piece of feedback from the DATF meeting this morning: it would be good to have the language for CDL and public/non-CDL items be the same, to help users consistently identify how they can access digital content. Right now, public items have a "Digital content" link. So please make the link text "View digital content" for both CDL and non-CDL items, with "Princeton users:" added for CDL items like you have here.

**Comment by hackmastera** [comment]
@escowles :thumbsup: thanks for this feedback

**Comment by hackmastera** [comment]
Here are updated wireframes under scenarios 1 and 3. I think scenarios 2 and 4 could easily be extrapolated from these but if not I'm happy to create more or simply clarify.

![Web 1920 – 1.png](https://images.zenhubusercontent.com/5cba1f45fec3b63424e0f761/43c437c1-33ad-40fc-a4e4-b5b0207ac8d0)

![Web 1920 – 2.png](https://images.zenhubusercontent.com/5cba1f45fec3b63424e0f761/d5be867e-6f91-4f0f-8bc4-758d1cb944ce)

**Comment by escowles** [comment]
@hackmastera 👍  Yes, those look great!

**Comment by hackmastera** [comment]
Thanks! Also reviewed by @tpendragon and @christinach.

**Comment by hackmastera** [comment]
Just realized the capitalization should probably be "View digital content" not "View Digital content" -- will update those images.
