### ISSUE TITLE
Display "snippets" from Google Books if possible

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#2178]
Displaying Google snippets of non-public items will help users evaluate items, and reduce unnecessary pickup or scanning requests.

This is only for materials that we don't have a better alternative for (eg. Hathi, already-completed CDL).
## Additional implementation details:

* UPDATE 9/10/2020 - Implement this feature using the link out to Google Book Search (example: https://developers-dot-devsite-v2-prod.appspot.com/books/examples/previewwizard-linktogbs), not the embed. 
* Display disclaimer text stating that this is a preview, and that PUL does not recommend/endorse purchasing options on the following page ([text for this](https://docs.google.com/document/d/1xbjEzo4p0vcblY9-KE6Fsv73kNHj151iJysYMCSJnvc/edit)). Initially, display text in line with the link itself. If the text is too long, use a click-through modal that is presented only once per session.
* If possible, link out to the New Google Books view of the page (de-emphasizes purchase). Example: [old view](https://books.google.com/books?id=VpNa9UckT24C&printsec=frontcover&source=gbs_ViewAPI&hl=en#v=onepage&q&f=false) | [new view (preferred)](https://www.google.com/books/edition/_/VpNa9UckT24C?hl=en&gbpv=1&pg=PP1)
* Add the snippet link to the "Show" page in the catalog, where the UV display for items with digital representations
* Make it clear through labeling the link that this is a snippet, not the full book (based on user feedback from a previous implementation)
* Only attempt to match ISBN numbers
* Only display this for items that are print monographs (no serials, no e-resources)
* ~~Link the thumbnail image in the "Show" page to the snippet viewer at the bottom of the page, if possible~~

**Comment by escowles** [comment]
The main motivation here is to give users as much information as possible about the item, to help them evaluate whether they want to request pickup or digitization.

**Comment by kelynch** [comment]
Here's the Google Books snippet code wizard - https://developers.google.com/books/docs/preview-wizard

**Comment by kelynch** [comment]
Here's the HathiTrust embed documentation - https://www.hathitrust.org/embed

**Comment by tpendragon** [comment]
https://developers.google.com/books/docs/viewer/developers_guide is the JS version.

**Comment by tpendragon** [comment]
![Screen Shot 2020-09-01 at 10 59 05 AM](https://user-images.githubusercontent.com/2806645/91906235-b2416d00-ec5c-11ea-94b3-092ba0fd4f0e.png)

**Comment by kelynch** [comment]
Based on stakeholder feedback, I've revised and added technical implementation details (see issue abolve).  We're getting click-through language currently.

**Comment by tpendragon** [comment]
We want a pop-up click-through notification for every page? That seems pretty bad

**Comment by escowles** [comment]
We have plenty of real-estate in the viewer section that we could just display the disclaimer with the link to Google Books — that seems like it would be less annoying than a click-through, right?

**Comment by kelynch** [comment]
Yes, putting the text there makes a lot of sense.  It's shaping up to be a short snippet (text here: https://docs.google.com/document/d/1xbjEzo4p0vcblY9-KE6Fsv73kNHj151iJysYMCSJnvc/edit).
