### ISSUE TITLE
Create `/catalog/<bibd>/hathi.json` to return the Hathi URL

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#2184]
## Technical Implementation

Use https://github.com/pulibrary/orangelight/blob/master/app/services/hathi_url.rb to get the Hathi URL. It should return a JSON response like
```
{
  hathi_url: "blabla"
}
```

If the URL is nil, it should return a 404.

This will be used by javascript to add a Hathi link to the show page.

**Comment by hackmastera** [comment]
This would have been closed by #2198 but we decided to fetch from the hathi api directly in javascript since it turns out there is not an auth concern.
