### ISSUE TITLE
Use Javascript to Insert HathiTrust link in "Available Online"

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#2185]
## Technical Implementation

There is a hathi url service in the ruby code, but we'll move it to javascript to reduce network calls.

Add it to the availability javascript, where the [CDL implementation](https://github.com/pulibrary/orangelight/blob/master/app/javascript/orangelight/availability.es6#L323) also is, for now.

First check bibdata. If the item is in the Hathi location, get & insert the hathi link.

Links collected during feasibility/implementation meeting:

- [Old Hathi URL code](https://github.com/pulibrary/orangelight/commit/140b9800ceb3d7686a648441c880bb33db4bb49a); notes about that implementation are on issue #1985 
- [Hathi API documentation](https://www.hathitrust.org/bib_api)
- [Hathi rake tasks](https://github.com/pulibrary/marc_liberation/blob/master/lib/tasks/hathi.rake)
- [Traject](https://github.com/pulibrary/marc_liberation/blob/6e7462747a3b5da6d08ff9f1df04c6ad55d6e680/marc_to_solr/lib/princeton_marc.rb#L778)
- [Original code to just show the URL when you load the page](https://github.com/pulibrary/orangelight/pull/2084/files)

**Comment by carolyncole** [comment]
Can we add a google analytic event here since it will give us an accurate count of the usage?

**Comment by hackmastera** [comment]
Description says: "Do the check after the CDL check. If it's on CDL, don't check for Hathi." But we later realized that it won't be possible to be on CDL (checked out) and activated for hathi (given an non-circulating location) at the same time, so we don't need to worry about this. Updating description.

**Comment by hackmastera** [comment]
Re: Above comment, here is a potential scenario: Bib has 2 items. 1 is on CDL and 1 is available from Hathi. We would want both links to display. @escowles do we expect to have this use case or always do one or the other?

**Comment by escowles** [comment]
@hackmastera I expect this to be a rare circumstance, because in general I would expect us to send users to Hathi if it was available, and only scan an item for CDL if it wasn't. But I agree it's possible that a Bib could have one item available for CDL, and a second item available from Hathi. This is most likely now when we've scanned items for CDL while Hathi ETAS access was disabled, but now it's available again.
