### ISSUE TITLE
Button for requests should only say digitize for columbia

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/orangelight#2206]
We are turning off access to physical requests for Columbia Recap items location code “scsbcul”

This means the button in orangelight should not show Request Pickup
https://catalog.princeton.edu/catalog/SCSB-9161184

This should already say just Request Digitization https://catalog.princeton.edu/catalog/9138419

Here is one that just says request: https://catalog.princeton.edu/catalog/11234594

**Comment by tpendragon** [comment]
We should be able to do this by just updating the scsbcul location in bibdata to not allow circulation. Is that okay, @mzelesky and @carolyncole ?

**Comment by tpendragon** [comment]
I've done this and the button works, but the only request option is "Help Me Get It"

**Comment by tpendragon** [comment]
https://catalog.princeton.edu/catalog/SCSB-3085213 works.
