### ISSUE TITLE
Items in Columbia's ETAS program should not show "Pick-up" in the request button, but others should.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#2207]
This is a follow-up to https://github.com/pulibrary/orangelight/issues/2206

Use the API call from https://github.com/pulibrary/marc_liberation/issues/758

**Comment by hackmastera** [comment]
In testing, this won't really look right until https://github.com/pulibrary/marc_liberation/issues/764 is done, but that shouldn't be done in prod until this is merged / deployed.
