### ISSUE TITLE
Temporary Homepage note 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#2213]
Add another alert to the homepage regardin columbia ReCAP titles.

Header: Temporary Restrictions on ReCAP Holdings

```Access to some items from the ReCAP shared collection may be restricted as we work to reconcile our shared holdings with those of the HathiTrust Emergency Temporary Access Service (ETAS). This is necessary to ensure that we are in compliance with copyright law. Access to as many titles as possible will be restored as soon as possible.```

**Comment by carolyncole** [comment]
Use the same icon and color as the other announcement: covid19-temporary-access
