### ISSUE TITLE
PUL Items  with ETAS Temporary Location should have status label "Online Access"

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#2221]
Example records: 
- https://catalog.princeton.edu/catalog/2160730 (recap etas location, etasrcp)
- https://catalog.princeton.edu/catalog/11401609 (library etas location, etas)

<img width="658" alt="Screen Shot 2020-08-31 at 8 31 01 PM" src="https://user-images.githubusercontent.com/278825/91784618-f3883d00-ebc8-11ea-98a8-d1500932b4ba.png">

Instead of "On-Site Access" these ETAS item at ReCAP should show a message stating "Online Access". The change should be made in marc liberation, e.g., https://bibdata.princeton.edu/availability?id=2160730

status labels are enumerated in https://docs.google.com/spreadsheets/d/1ekw8Ogad8U31phrU9Up95WzhnAac6vsyFPkci7729kk/edit#gid=0

**Comment by carolyncole** [comment]
Should we be marking all (both Princeton and Recap) ETAS items as digital access only?

**Comment by carolyncole** [comment]
Here is where the current value is inserted into the page: https://github.com/pulibrary/orangelight/blob/master/app/javascript/orangelight/availability.es6#L443 . If we change marc_liberation (bibdata) then no change should be needed here.

**Comment by carolyncole** [comment]
Here is a spreadsheet that includes all the Statuses for Non Circulating items:
 https://docs.google.com/spreadsheets/d/1ekw8Ogad8U31phrU9Up95WzhnAac6vsyFPkci7729kk/edit#gid=0

**Comment by hackmastera** [comment]
status label has been added to marc liberation's get_availability response.

The logic needs to be removed from orangelight's JS and instead pulled directly from marc liberation.

Then this value should be added into marc_liberation.

**Comment by hackmastera** [comment]
@kevinreiss I updated this issue to reflect the first 2 rows of the spreadsheet here https://docs.google.com/spreadsheets/d/1ekw8Ogad8U31phrU9Up95WzhnAac6vsyFPkci7729kk/edit#gid=0

Are the values correct for the other rows or do we need more issues?

**Comment by christinach** [comment]
this was done
