### ISSUE TITLE
Reenable BL Folders

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#225]
Too buggy right now.

**Comment by tampakis** [comment]
No one is dying for this feature to work currently. Would be a nice enhancement. Gem is still buggy.

**Comment by jpstroop** [comment]
Nancy says this is desired - good for faculty who want to make reserve lists.

**Comment by kevinreiss** [comment]
I think this will require some TLC to make it work under BL6. @tampakis @axamei do you recall what were the buggy parts we encountered?
