### ISSUE TITLE
'Bad request' when using pagination (page 2 and higher) and trying to remove the keyword

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2254]
Example: https://catalog.princeton.edu/?page=2&q=A+Slice+through+America&search_field=all_fields
(While on page 2) remove the search keyword. It will return a Bad request. https://catalog.princeton.edu/?page=2&search_field=all_fields

similar issue https://github.com/pulibrary/orangelight/issues/1455

**Comment by sandbergja** [comment]
We can no longer reproduce this issue.
