### ISSUE TITLE
When I create a digitization request I'm not seeing it in "My Account"

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#2261]
Is this a bug? @carolyncole @kevinreiss

**Comment by tpendragon** [comment]
Question was received by Anu Vedentham.

**Comment by kevinreiss** [comment]
Example? If it is for an item stored at ReCAP they will not show up under digitization request.

**Comment by tpendragon** [comment]
Oh I guess it was a RECAP one. Give me a minute..
