### ISSUE TITLE
CDL item showing "Some items not available" based on item availability

### ISSUE THREAD

**Issue by kelynch** [pulibrary/orangelight#2280]
An item charged to CDL (https://catalog.princeton.edu/catalog/10392153) is showing up correctly at the bottom of the show page, however the status label message is displaying "Some items not available" rather than the "Reserved for CDL" message based on the logic in the availability JS in Orangelight.  It looks like there are two items associated with the bib, one of which is charged to CDL, one of which is overdue/recalled.  This should display "Reserved for CDL" when one of the items is charged to CDL.

**Comment by hackmastera** [comment]
Please note the status label logic has all been migrated to marc_liberation. It hasn't been pulled out of OL yet but changes to the logic should be made in marc_liberation, not OL.

**Comment by kelynch** [comment]
No; I'll close this issue.  Thanks for following up.
