### ISSUE TITLE
Mobile Usability issues

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2290]
#### Acceptance Criteria
- [x] Investigate whether the below issues are still present via the google search console for mobile
- [x] Create tickets for individual issues that are still present

from google search console:
Top Issues
The following issues were found on your site:
Text too small to read
Content wider than screen
Clickable elements too close together
https://www.google.com/appserve/mkt/p/AD-FnExLHc_644ZRBowOaRvVIAWPs_ihhxfuIAQCZHJl0NvI6HvxIn9_i-Bfp-2Rh0OaN92zrP_RoEr7AalPL4FOGzKfsKs9O2kISADkRnFug63L5IBXAcnwbCrA9B9GJFGnGlsuBvBIV5AxLw87WVxwaiIZ6CgihqMMLVPrfUv0hJKEzAsyfmefq8X9ANj3X1HdICIZv8_xd9cnsp7dUMIkeVgAI6vJ6VVL9aWpgOmIlkQ5Nngt7vNCEJ0QYXYg31sQs7YF3WUz--IP_kDBsKFY92ieSG1Ovw_3caw23e8-O8sm_3WiUK6CquM8UP0uA8Gdlk2pz2VOj0DC7MGq

**Comment by christinach** [comment]
https://search.google.com/search-console/mobile-usability?resource_id=sc-domain:catalog.princeton.edu&utm_source=wnc_10030322&utm_medium=gamma&utm_campaign=wnc_10030322&utm_content=msg_100058679&hl=en

The same error was reported on this record: https://catalog.princeton.edu/catalog/SCSB-5895075

**Comment by kevinreiss** [comment]
Check in on current search console errors and create specific tickets for each on that seems relevant, then close this ticket.

**Comment by maxkadel** [comment]
These types of issues no longer seem to be reflected on Google Search Console - it's possible using Lighthouse for accessibility could find similar issues.

I did create two new tickets based on the google search console info
- #4054
- #4055
