### ISSUE TITLE
CUL ETAS materials at recap should have status label "Digitization Only"

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2295]
Currently says "Available". Example: https://catalog.princeton.edu/catalog/SCSB-2879160

Status labels spreadsheet https://docs.google.com/spreadsheets/d/1ekw8Ogad8U31phrU9Up95WzhnAac6vsyFPkci7729kk/edit#gid=0

**Comment by hackmastera** [comment]
Seems like this needs to be updated upstream at the scsb server

**Comment by sandbergja** [comment]
closing, since we are no longer using ETAS
