### ISSUE TITLE
Update Menu Label for illiad requests on the BL User Menu

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#2311]
<img width="980" alt="Screen Shot 2020-10-23 at 8 11 06 AM" src="https://user-images.githubusercontent.com/278825/97007719-71046580-1507-11eb-848b-9f1ce1fc85d7.png">

We have both digitization and resource sharing requests for charged items show up in this section right now. We have it labeled "Digitization Requests".  We should consider alternative labels. The illiad web app calls the service "Article Express and Interlibrary Loan" so for lack of anything else I'd go with that but that still seems a bit unsatisfactory.

**Comment by carolyncole** [comment]
We could separate them out.  We are filtering based on ProcessType, but if we filtered with RequestType then we could get just Article for digitization and Loan for other.
