### ISSUE TITLE
Add unique numismatic rights information with Stahl contact

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/orangelight#2329]
### Current display
check with @kelea99 if what we have https://catalog.princeton.edu/numismatics is sufficient.

### Desired display
Exact language requested by Stahl:

> Images may be downloaded from this site and used for scholarly purposes without permission. All objects in the Numismatic Collection can be viewed by appointment with the Curator of Numismatics; for information on viewing and on the publication of images contact astahl@princeton.edu .
### Acceptance criteria

- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

**Comment by christinach** [comment]
@kelea99 Information was added in https://catalog.princeton.edu/numismatics. Do we need to change/update this or is the request to add it somewhere else?
