### ISSUE TITLE
Font weight looks bold for everything on Windows

### ISSUE THREAD

**Issue by axamei** [pulibrary/orangelight#2338]
Around 3-4 days ago, 12/11/20, staff member noticed all text on the catalog site was bolded. I've confirmed that I see the same issue on a Windows machine.

![image](https://user-images.githubusercontent.com/8161144/102259064-a52f4d80-3edc-11eb-9716-05806243343d.png)

used to look like...

![image](https://user-images.githubusercontent.com/8161144/102259092-ac565b80-3edc-11eb-9ecb-8728f202ec55.png)

**Comment by axamei** [comment]
Looks like we are missing a closing tag in https://github.com/pulibrary/orangelight/blob/main/app/views/shared/_announcement.html.erb#L4

**Comment by hackartisan** [comment]
resolved in #2339
