### ISSUE TITLE
Form submit control for searchbox is problematic on mobile

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#2346]
![Screenshot_20210113-174845](https://user-images.githubusercontent.com/999701/104519681-d4aea400-55c7-11eb-9528-89fdb98c31db.png)

**Comment by axamei** [comment]
Also seeing issues on the record page:
![image](https://user-images.githubusercontent.com/8161144/111908043-13c8fd80-8a2e-11eb-8e0f-18889a4c553e.jpeg)

**Comment by kevinreiss** [comment]
Needs to become part of an EPIC on mobile display issues.

**Comment by christinach** [comment]
duplicate of https://github.com/pulibrary/orangelight/issues/2174
