### ISSUE TITLE
Update "where to find it" stack map feature to use alma

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2348]
There are 2 pieces of software that drive this feature, depending on which library the resource is located in (firestone or any branch).

Both systems are dependent on the locations table and the location that comes out of voyager.

* https://github.com/pulibrary/firestone_locator
  * this does check status but maybe that can be deprecated
  * example record: https://catalog.princeton.edu/catalog/1352437 
* the other is a vendor tool called stackmap
  * example record: https://catalog.princeton.edu/catalog/6501488
  * In orangelight there was a hack added to the route to make it work.
  * We'll have to adjust configuration
  * there's no staging instance of this that we could use to make sure the integration works

## Implementation

Looking at the code, it appears the changes will primarily be the hard-coded locations, probably both in orangelight and in the 2 apps that provide the data.
* https://github.com/pulibrary/orangelight/blob/6f35623fb747934e4ef2bd428ed725787390c0f8/app/services/stackmap_service.rb
* https://github.com/pulibrary/orangelight/blob/6f35623fb747934e4ef2bd428ed725787390c0f8/app/services/stackmap_location_factory.rb

Ensure we have any new machines provisioned to support go-live

NOTE: this code should handle a possible 429 (too many requests) status from both bibdata `/items` and `/solr` endpoints.

### firestone_locator

The [firestone_locator uses the location key](https://github.com/pulibrary/firestone_locator/blob/00ad7b643305ea055bee34cd717446aa950bb399/includes/bibdata_info.php#L60-L78) to drive some of its logic. It looks for location code `f` which has been changed -- this will need to be updated for migration.

These locations have been [updated](https://github.com/pulibrary/marc_liberation/pull/1066) to use the new library$holding locations as keys, so that they'll be unique. see, e.g. https://bibdata-alma-staging.princeton.edu/bibliographic/9934883173506421/items

## Notes 
If we don't do this before alma go-live, we need to disable the feature.

**Comment by kevinreiss** [comment]
@hackartisan @carolyncole I think we can deprecate the status check in the firestone locator. We aren't doing anything status based in our current "Where to Find It" implementation. All we do is just provide the map to the item's shelf location.

**Comment by hackartisan** [comment]
@kevinreiss Thank you for that! Removing the status from that endpoint will definitely simply things. I created https://github.com/pulibrary/firestone_locator/issues/41. I'm not sure who knows this code well enough to work the ticket.

**Comment by hackartisan** [comment]
@kevinreiss What about "sortable_call_number"? I don't think we have implemented that for the alma endpoint. Will we need to?

**Comment by kevinreiss** [comment]
I think we will need to pull the data from the "call_number_browse_s" key in the solr document. The locater does need a call number passed to it.

**Comment by hackartisan** [comment]
We're sending it a callnumber, but the endpoint currently provides both call number and sortable call number. Does it need both?

**Comment by hackartisan** [comment]
Nevermind it looks like we're doing both already. https://github.com/pulibrary/marc_liberation/blob/alma/app/controllers/bibliographic_controller.rb#L236

**Comment by hackartisan** [comment]
These updates can't be deployed until Catalog-on-Alma launches, August 2nd. See go-live plan.
