### ISSUE TITLE
Hide dirty data on the production server

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#235]
Examples:
 - [blank call numbers](http://pulsearch-dev.princeton.edu/browse/call_numbers)
 - [names without characters](http://pulsearch-dev.princeton.edu/browse/names)
 - [subjects](http://pulsearch-dev.princeton.edu/browse/subjects) seem pretty good. Prevent blank headings from creeping in
 - Exclude [unknown format](http://pulsearch-dev.princeton.edu/?f%5Bformat%5D%5B%5D=Unknown)
 - Exclude dates [later than 2017](http://pulsearch-dev.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=&range%5Bpub_date_start_sort%5D%5Bbegin%5D=2018&range%5Bpub_date_start_sort%5D%5Bend%5D=9999&commit=Limit)
 - Make sure only libraries are included in the [library facet](http://pulsearch-dev.princeton.edu/catalog/facet/location?search_field=all_fields&utf8=%E2%9C%93)

**Comment by joycebcat** [comment]
@tampakis Nikitas, be careful about excluding dates later than 2017.  Anytime you put a block on based on a moving wall there is the danger that you start losing legitimate things.  The exclusion would be best based around the idea of blocking things with dates more than 3 years ahead of the current year.

**Comment by tampakis** [comment]
@joycebcat yes of course. Current year +3
