### ISSUE TITLE
lib-orange-prod6 giving sneakers / bunny errors and crashing

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2360]
The server is crashing with memory errors.

From Philippe: Here is the first two seconds (!!) from syslog, repeated over and over till the reboot.
[syslog-prod6.txt](https://github.com/pulibrary/orangelight/files/6012974/syslog-prod6.txt)

**Comment by christinach** [comment]
We haven't seen this issue for a long time.
