### ISSUE TITLE
Date1 9999 after date1 is changed

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#238]
@tampakis Nikitas, there are 6 records left when you look for a publication date of 9999.  None of them actually have 9999 in them any more.  Most of them have date1="1uuu" indicating sometime in the 20th century and at two of them had "uuuu" but I changed that today to "1uuu".  They shouldn't be showing up as date 9999 any longer.

**Comment by tampakis** [comment]
Should they be 1000 instead?

**Comment by joycebcat** [comment]
They should match however we are handling dates like "198u" or "19uu".  I'm not sure how those are handled.

**Comment by tampakis** [comment]
@joycebcat They're all gone! Last week, one of the daily updates didn't get applied to Solr. If you are ever confused about a record in Blacklight, you can check when it was last updated in the index by visiting its json view. For instance: http://pulsearch-dev.princeton.edu/catalog/1962671.json
At the bottom of the page is a field called timestamp which shows when the record was last updated in Solr. So in this record, which I have just updated, the timestamp shows today's date `2015-09-04T22:00:48.647Z`.
