### ISSUE TITLE
Online holdings do not display

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2387]
electronic_portfolio_s is indexed as expected but not displayed in the UI. 
See in catalog-alma-staging https://catalog-alma-qa.princeton.edu/catalog/99122412208706421

This is in production https://catalog.princeton.edu/catalog/9774575

Doing a quick search I would look into OnlineHoldingsMarkupBuilder and HoldingRequestsAdapter

**Comment by hackartisan** [comment]
This record needed to get through a reindex. Show page looks right now.

**Comment by christinach** [comment]
The record was not displaying because we had not deployed the latest orangelight updates to the catalog-qa.
