### ISSUE TITLE
Electronic records need "online" badge and link in search results

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2388]
These records have portfolios but no holdings. See screenshots / details in comments below.

**Comment by hackartisan** [comment]
likely a dup of #2387

**Comment by eliotjordan** [comment]
Example: https://catalog-alma-qa.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=99122438989606421

![Screen Shot 2021-04-01 at 11 01 22 AM](https://user-images.githubusercontent.com/784196/113321868-a2b10200-92d9-11eb-82b2-a45951aacb1c.png)

**Comment by kevinreiss** [comment]
I think #2387 does need to be implemented on the record page for this display corrected. Right now you only get the google books preview link on the record page. 

On the search results page we do this for the record now:

<img width="741" alt="Screen Shot 2021-04-01 at 12 01 47 PM" src="https://user-images.githubusercontent.com/278825/113328568-16570d00-92e2-11eb-9a4f-1619ba7a6985.png">

The display text for the link comes from the 856 field in production and the links in Alma stored in 'electronic_portfolio_s' are structured differently so I'd probably use the title attribute value from 'electronic_portfolio_s' as the link text on both the results and the record page.

**Comment by hackartisan** [comment]
@kevin the ebook central link is showing. catalog-alma-qa was undergoing a reindex when this ticket was written. We were checking the show page from a local instance which had the latest indexing changes.
