### ISSUE TITLE
Copies in the library section should not display in the record page for online resources

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2389]
https://catalog-alma-qa.princeton.edu/catalog/99121576653506421/
vs 
https://catalog.princeton.edu/catalog/12157665

**Comment by tpendragon** [comment]
@christinach has indicated that we should continue indexing ELF holdings if they show up, so the implementation here is to add an exception to this view so that if it's an ELF holding don't display it in the physical holdings.

**Comment by tpendragon** [comment]
Summarizing content in #alma-development:

We should close https://github.com/pulibrary/bibdata/issues/1203# first, there's a chance this will result in ELF locations not being indexed into the holdings field and thus closing this ticket without adding view logic.

**Comment by christinach** [comment]
> @christinach has indicated that we should continue indexing ELF holdings if they show up, so the implementation here is to add an exception to this view so that if it's an ELF holding don't display it in the physical holdings.

@tpendragon  we don't want to index elf holdings. I said that we want to index the records but not the elfs. The electronic records (elf invalid locations) will be addressed with https://github.com/pulibrary/bibdata/issues/1202.

**Comment by tpendragon** [comment]
These won't index now that elfs are not in the locations table.
