### ISSUE TITLE
Refreshing the alma qa site shows different facet counts

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2409]
There appear to be 3 different sets of values. Solr looks fine.

**Comment by tpendragon** [comment]
Problem seems to be something with solr replication. If I tunnel to Solr and just run a query from the alias I get three numFound values:

Sometimes it’s 9096261, sometimes it’s 7378437, sometimes it’s 10814756

**Comment by tpendragon** [comment]
Appending `shards.info=true` shows smaller numbers for lib-solr6, and that shard's having issues with other collections. We're gonna reboot it.

**Comment by tpendragon** [comment]
lib-solr-staging6 threw a disk available error on the 6th, it might just be full.

**Comment by tpendragon** [comment]
We deleted a large core that was no longer in use and it freed up 30% of the disk space. Closing.
