### ISSUE TITLE
Umlaut Tuning?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#241]
@kevinreiss: Visit http://pulsearch-dev.princeton.edu/catalog/7058493

Click on how Proquest makes this video available....

**Comment by jpstroop** [comment]
Could start by disabling Umlaut for a/v?

**Comment by kevinreiss** [comment]
I think we should review the OpenURL template at https://github.com/pulibrary/orangelight/blob/development/config/initializers/blacklight_initializer.rb#L16 and make it behave with some more granularity. We should set the rft.genre parameter and make sure any standard numbers like the ISBN in this record get included. Having those set would have prevented the weird match the knowledge base found against the current OpenURL produced. (I know the idea here is to ultimately shift the creation of this OpenURL to index time). 

The default SFX behavior (which appears to treat everything as a Journal and run a title search for matching ISSNs against the OCLC xISN service) is dumb but making the OpenURL robust seems like the way to go. I'll take a pass at that. 

Here is the same bib record in JHU's system https://catalyst.library.jhu.edu/catalog/bib_2651076. They OpenURL template they are producing is a lot richer than the one (which is basically the blacklight default) we are currently using. 

Compare:

url_ver=Z39.88-2004&url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&ctx_ver=Z39.88-2004&ctx_tim=2015-09-10T18%3A32%3A40-04%3A00&ctx_id=&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rft.genre=unknown&rft.au=Federico+Fellini+%3B+prodotto+da+Ibrahim+Moussa+per&rft.date=2005&rft.isbn=1417200715&rft.btitle=Intervista&rft.place=Port+Washington%2C+NY&rft.pub=Koch+Lorber+Films+Distributed+by+KOCH+Vision&rft.edition=Widescreen&rft.tpages=&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&rft_id=info%3Aoclcnum%2F59109978&rft_id=https%3A%2F%2Fcatalyst.library.jhu.edu%2Fcatalog%2Fbib_2651076&rfr_id=info%3Asid%3Alibrary.jhu.edu%2Fblacklight

to ours:

ctx_ver=Z39.88-2004&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Adc&rfr_id=info%3Asid%2Fblacklight.rubyforge.org%3Agenerator&rft.title=Intervista&rft.creator=&rft.date=c2005.&rft.place=Port+Washington%2C+NY+%3A&rft.pub=Koch+Lorber+Films+%3A&rft.format=video_projected_medium&rft_id=pul_7058493

**Comment by kevinreiss** [comment]
Making this template more robust also has the added benefit of improving support for Zotero which will scrape the page for metadata about the embedded coins <span> tag containing the OpenURL.

**Comment by kevinreiss** [comment]
A few pointers to review in the context of this issue (mostly for my own memory, @tampakis, @joycebcat @jpstroop):

Leader 06 Position - https://www.loc.gov/marc/bibliographic/bdleader.html - type of record
https://github.com/pulibrary/orangelight/issues/47 - Genre Terms for Facets

Traject Code for determining Format
* https://github.com/pulibrary/orangeindex/blob/development/lib/format/bib_format.rb
* https://github.com/pulibrary/orangeindex/blob/development/lib/translation_maps/format.rb

**Comment by kevinreiss** [comment]
Example Records

Repeat of the 856 Field
Hathitrust - http://pulsearch.princeton.edu/catalog/2003397

Link via API - Accurate
Internet Archive - http://pulsearch.princeton.edu/catalog/2228838

Link via API - Failed
SFX API - http://pulsearch.princeton.edu/catalog/1675796

**Comment by kevinreiss** [comment]
Make sure that oclc numbers and lccn numbers are present in the OpenURL.

Compare https://catalyst.library.jhu.edu/catalog/bib_560124 with http://pulsearch.princeton.edu/catalog/1694819. If we included either on our page we'd get the Hathi Full-text and Search Inside links.
