### ISSUE TITLE
Handle possible 429 from bibdata patron endpoint

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2415]
It would happen here: https://github.com/pulibrary/orangelight/blob/ace3e1ba6188b85a091eac310adb82b18ac1cfe2/app/services/bibdata.rb#L10

And error handling would have to present a message like "We're sorry we are currently unable to complete this request due to request load. Please try again later" here https://github.com/pulibrary/orangelight/blob/ace3e1ba6188b85a091eac310adb82b18ac1cfe2/app/controllers/users/omniauth_callbacks_controller.rb#L19

**Comment by jrgriffiniii** [comment]
This should be resolved with #2503
