### ISSUE TITLE
Location label changes on availability load

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2418]
See first result of https://catalog-alma-qa.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=musicals

Can we just make sure it has the right location to begin with?
What is causing the location to change? Do we need this to happen?

Before javascript runs:
![Screen Shot 2021-04-16 at 4.10.54 PM.png](https://images.zenhubusercontent.com/5cba1f45fec3b63424e0f761/d81a299a-c008-4507-a6ce-47783e067c4f)

After javascript runs:
![Screen Shot 2021-04-16 at 4.10.35 PM.png](https://images.zenhubusercontent.com/5cba1f45fec3b63424e0f761/6c56222e-cad1-4402-b308-7ee2c4972c56)

**Comment by christinach** [comment]
The location is right, the label differs. The first one comes from the bibdata holding_locations lookup which is part of the https://github.com/pulibrary/orangelight/blob/ace3e1ba6188b85a091eac310adb82b18ac1cfe2/app/services/physical_holdings_markup_builder.rb 
and the HoldingRequestAdapter 

https://github.com/pulibrary/orangelight/blob/ace3e1ba6188b85a091eac310adb82b18ac1cfe2/app/services/holding_requests_adapter.rb#L112. 

The second one comes from the api call getting only $c. 
`AVA    
0| 9918888023506421 8| 22260730640006421 a| 01PRI_INST b| recap c| Remote Storage: Mendel Music Library use only d| LS- 9073 e| available f| 1 g| 0 j| qk k| 8 p| 1 q| ReCAP`

If we want to follow the same pattern with production and display the same location label we would need to:

1.Remove location['library']['label'] from https://github.com/pulibrary/orangelight/blob/ace3e1ba6188b85a091eac310adb82b18ac1cfe2/app/services/holding_requests_adapter.rb#L114

2.Update https://github.com/pulibrary/bibdata/blob/1fbf110c3fc595d301b1ed0a592bbd8aff1f407c/app/services/location_data_service.rb#L35 to equal only to the external name and not append the library_record.label. 

I will work on a branch for this solution and index a couple of records.

**Comment by christinach** [comment]
I have 2 solutions:
1.The first one is to display only the location and it will look like:
![Screen Shot 2021-04-21 at 4 45 22 PM](https://user-images.githubusercontent.com/9905193/115619952-90b3f500-a2c2-11eb-8918-d98e13fbc898.png)

This will be identical with what is coming from the availability.js call and overrides the physical holding.

2.The second one is to display the library and the location. This will create a repetition of the library name since it is included in the external_name that we pull from alma.
![Screen Shot 2021-04-21 at 4 55 14 PM](https://user-images.githubusercontent.com/9905193/115620119-c35ded80-a2c2-11eb-9ae8-b84b6d355ee3.png)

If we go with the second solution we will need to update the availability.js to include the library label in the response, which is ok. 
@mzelesky @kevinreiss what do you think?

**Comment by christinach** [comment]
This is the 3rd example from the screenshots https://catalog-alma-qa.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=9912286923506421 from alma-qa using the availability.js

![Screen Shot 2021-04-21 at 5 07 00 PM](https://user-images.githubusercontent.com/9905193/115621183-29974000-a2c4-11eb-88a5-d16e9e63e5bc.png)

and this is the same example with the physical holding not using javascript on alma-qa
![Screen Shot 2021-04-21 at 5 11 17 PM](https://user-images.githubusercontent.com/9905193/115621549-acb89600-a2c4-11eb-907b-3f90a8c09793.png)

**Comment by christinach** [comment]
In my local I have reindexed the record with the correct updated location. This is why you dont see Recap but you see Mendel.

**Comment by kevinreiss** [comment]
I would vote for only the location name. Will this pattern hold up for the default locations at each library. For the Firestone "stacks" we'd still want to see "Firestone - Stacks" rather than just "Stacks"

**Comment by christinach** [comment]
Yes it will be 'Firestone Library Stacks' as it appears in the first screenshot here https://github.com/pulibrary/orangelight/issues/2418#issuecomment-824358152

**Comment by kevinreiss** [comment]
Sorry I missed that. I think the first approach works best. Less text > more text.

**Comment by christinach** [comment]
Thank you @kevinreiss

**Comment by christinach** [comment]
We decided to update the external_name in alma so that it does not include the library name. https://github.com/pulibrary/bibdata/issues/1282

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/orangelight/pull/2456
