### ISSUE TITLE
Display boundwith host holdings on boundwith constituent records

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2431]
As part of the show page logic, a boundwith constituent record (i.e a record with a `contained_in_s` value) should pull physical holdings from its host record (given by the mms id in that field).

Availability needs to populate correctly on the show page for these records. In search results, availability should be "View Record for Full Availability", a value that we're already using in other places.

Example records: the host record 99121886293506421 with the constituent records 9929455783506421, 9929455793506421 and 9929455773506421.
https://catalog-alma-qa.princeton.edu/catalog/99121886293506421

**Comment by hackartisan** [comment]
As an alternative to actually inserting the host holdings on the page, we could bump the link to the host record to a more prominent position.

Note there might be some constituent records that do have holdings.
