### ISSUE TITLE
Does/should instrumentation facet use 382 field?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#245]
See, e.g. 8853567

**Comment by tampakis** [comment]
https://github.com/traject/traject/blob/master/lib/traject/macros/marc21_semantics.rb#L244


-------- Original message --------

**Comment by jpstroop** [comment]
So no, then? This is a very new field. We should find out what practice is.

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by tampakis** [comment]
382 isn't included yet.

**Comment by joycebcat** [comment]
We are using 382 now in our records.  Older records have similar information coded into 048.

**Comment by jpstroop** [comment]
Right now we're only using 048. This won't be updated this week, but we should figure out how to use 382, and then some logic for when to use which. Is 048 deprecated?

**Comment by joycebcat** [comment]
No, it is not.

**Comment by tampakis** [comment]
This issue is relevant for a music-specific search page.

**Comment by tampakis** [comment]
Proposed to remove from main search too.

**Comment by christinach** [comment]
382 is not indexed and it seems that it was proposed to be removed see comment on 11/25/2019.
