### ISSUE TITLE
Timeout error when requesting

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#2452]
Timeout error when requesting

```
[Orangelight/production] Faraday::TimeoutError: Net::ReadTimeout with #<TCPSocket:(closed)>
```

Should we bump up the timeout value?

## Backtrace

    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/39851088)

**Comment by kevinreiss** [comment]
duplicate of #3228.
