### ISSUE TITLE
DataTables not loading

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2463]
Error in the dev tools console:

Uncaught TypeError: $(...).DataTable is not a function
    at HTMLDocument.<anonymous> (application-23b9b27d1365a8323174e4ba2a7f76024204b0e6e0a99b5c0e291a48b406613e.js:171)
    at u (application-23b9b27d1365a8323174e4ba2a7f76024204b0e6e0a99b5c0e291a48b406613e.js:52)
    at Object.fireWith [as resolveWith] (application-23b9b27d1365a8323174e4ba2a7f76024204b0e6e0a99b5c0e291a48b406613e.js:52)
    at Function.ready (application-23b9b27d1365a8323174e4ba2a7f76024204b0e6e0a99b5c0e291a48b406613e.js:52)
    at HTMLDocument.s (application-23b9b27d1365a8323174e4ba2a7f76024204b0e6e0a99b5c0e291a48b406613e.js:41)

**Comment by hectorcorrea** [comment]
Eliot found that this "had to do with bidata-staging not having any holding locations + caching of the empty result. Deleting everything in the Rails cache and setting `bibdata_base` to production bibdata did the trick.
https://bibdata-staging.princeton.edu/locations/holding_locations"

**Comment by christinach** [comment]
No, this error has nothing to do with the locations. @eliotjordan issue was that bibdata-staging was missing location flags and the button would not display for a specific record.

**Comment by christinach** [comment]
This error exists everywhere and in production as well.

**Comment by kevinreiss** [comment]
Yes, something has happened with this feature in both production and alma-qa, I poked around and couldn't identify the root of the issue. There is js code in the requests gem that looks for datatables https://github.com/pulibrary/requests/blob/main/app/assets/javascripts/requests/requests.js#L184, that I think isn't finding the library. This form should be paginated and allow for search by enumeration when dataTables is working.

**Comment by hackartisan** [comment]
@kevinreiss should this be an issue in [requests](https://github.com/pulibrary/requests)?

The description says it's not breaking anything but according to your comment it is breaking functionality.

**Comment by christinach** [comment]
According to @kevinreiss it is breaking the requests form when there are big records. But I think we should troubleshoot in OL before we move it to the requests gem. Orangelight is also having the datatables gem but it seems that it doesn't loading properly.

**Comment by hackartisan** [comment]
Okay I updated title and description to make it look more like a real bug

**Comment by christinach** [comment]
Do we want to merge this on main or in the alma branch? @kevinreiss

**Comment by christinach** [comment]
we decided to make the fix on the alma branch.

**Comment by carolyncole** [comment]
@axamei found this commit, which likely removed the functionality: https://github.com/pulibrary/orangelight/pull/2383/files
