### ISSUE TITLE
Add write key for requests app use

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2479]
Use the ansible scripts to add an alma write key.

**Comment by carolyncole** [comment]
It is utilized here: https://github.com/pulibrary/orangelight/blob/alma/config/alma.yml#L2. I'm guessing this just needs to be added in princeton_ansible.

**Comment by hackartisan** [comment]
@carolyncole This is already in ENV on the orangelight alma qa box. https://github.com/pulibrary/princeton_ansible/blob/7c7a14cea37621a373fdd104109120f682504f76/group_vars/orangelight/alma_qa.yml#L90

Is it not working?

**Comment by hackartisan** [comment]
closed by https://github.com/pulibrary/princeton_ansible/pull/2285
