### ISSUE TITLE
Link to digital content does not scroll down the page to viewer

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2485]
User report; needs replication.

**Comment by jrgriffiniii** [comment]
http://localhost:3000/catalog/3395923#view does scroll down to the viewer, I will look to reproduce this elsewhere.

**Comment by jrgriffiniii** [comment]
I am incorrect, this seems to just be specific to when the user clicks a link with this fragment. Otherwise, pasting the link into the browser does *not* scroll down the viewer.

**Comment by jrgriffiniii** [comment]
Resolved by #2493
