### ISSUE TITLE
Add an announcement to the Orangelight homepage for Alma downtime

### ISSUE THREAD

**Issue by kelynch** [pulibrary/orangelight#2494]
Wording forthcoming; this should be in the announcements section of the page, and will likely replace the Hathi block:

https://catalog.princeton.edu/

**Comment by escowles** [comment]
The news story has been updated, so we can link to that (replacing the Hathi block):

>[System Upgrades This Summer](https://library.princeton.edu/news/general/2021-08-02/pul-launch-new-library-system-summer-2021-hathitrust-etas-update)
A system upgrade this summer will replace a 20-year-old platform and provide more efficient and easier access to library resources. This is a behind-the-scenes process and will not result in any changes in the catalog itself. Requesting materials through the catalog will not be available from July 22 through July 27, and requesting items from ReCAP will not be available from July 16 to August 8. Please see [our announcement](https://library.princeton.edu/news/general/2021-08-02/pul-launch-new-library-system-summer-2021-hathitrust-etas-update) for more information.

**Comment by hackartisan** [comment]
There will be some changes to catalog, especially the account /  login stuff. Should we soften "will not result in any changes in the catalog itself"?

**Comment by escowles** [comment]
@hackartisan That's a good point — I'll ask Barbara about that since that wording is taken directly from the news story.

**Comment by escowles** [comment]
We've updated the news story to soften that language. Here's the  new text:

>[System Upgrades This Summer](https://library.princeton.edu/news/general/2021-08-02/pul-launch-new-library-system-summer-2021-hathitrust-etas-update)
>A system upgrade this summer will replace a 20-year-old platform and provide more efficient and easier access to library resources. This is a behind-the-scenes process and will not result in any significant changes in the catalog itself. Minor appearance changes will be seen on the My Account page. Requesting materials through the catalog will not be available from July 22 through July 27, and requesting items from ReCAP will not be available from July 16 to August 8. Please see [our announcement](https://library.princeton.edu/news/general/2021-08-02/pul-launch-new-library-system-summer-2021-hathitrust-etas-update) for more information.

**Comment by hackartisan** [comment]
This needs to happen in the main brach.
