### ISSUE TITLE
No Stackmap Links for Plasma Physics

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#2495]
Plasma Physics will remain closed for the forseeable future. We should suppress the links to stackmap for that location since patrons actually cannot go there.

**Comment by christinach** [comment]
@kevinreiss do we need to remove the Plasma Physics from bibdata delivery and holding locations? 
Does something need to change in Alma as well?

**Comment by christinach** [comment]
Also suppress stackmaps links for Marquand. Per @kevinreiss marquand's items are all offsite.

**Comment by hectorcorrea** [comment]
This issue involves removing the "pin" icon next to the record in Search results and the pin/label in the Show page.
 
Plasma Physics library sample record: https://catalog.princeton.edu/catalog/99117069583506421

![search_results](https://user-images.githubusercontent.com/568286/133095822-44210f76-32ae-49a9-abf8-ae07665d54bf.png)

![show_page](https://user-images.githubusercontent.com/568286/133095831-2c5539ab-0aa6-4cee-a6f8-2c384d405948.png)
