### ISSUE TITLE
Location label code 

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/orangelight#2534]
The location code in PR #2521 looks to be duplicated and could use some refactor.

In `app_helper.rb` we have a `holding_location_label` function that implements the following logic:
```
  def holding_location_label
    if loc == nil
      [H] holding.lib + holding.loc
    else
      [L] location.lib.label +loc.label
    end
  end
```

This code seems to be tested indirectly via `search_history_spec.rb` and via `locations_spec.rb`. Notice that `locations_spec.rb` describes `AppHelper`.

The second implementation is in `holding_request_adapter.rb` where we have a function with the same name that it seems to implement the same logic, but broken down in a slightly different way:

```
    def holding_location_label
      # calls alma_location_label_display_bibdata_location (same as [L] above)
      # or 
      # calls alma_location_label_display_holding (same as [H] above)
    end
```

This code is tested in `holding_block_spec.rb`, which also describes `AppHelper`. There are some test in `availability_spec.rb` that test this function but only for the Voyager branch.

**Comment by christinach** [comment]
@hectorcorrea the code follows what is currently in production. There is a duplicate but I didn't take the time to refactor since this would be a different issue.
