### ISSUE TITLE
Use a dynamic queue name for sneakers configuration in alma

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2543]
https://github.com/pulibrary/orangelight/blob/52507572ee0da4d70ab3f7776e84a3c0e868a2ff/app/workers/event_handler.rb#L6

Should be `from_queue :"catalog_#{RAILS.env}"`

reference: https://github.com/pulibrary/orangelight/commit/6a1b6783192058d586a4843c39b1d5f5f032e350

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/orangelight/pull/2544
