### ISSUE TITLE
Test CDL Link

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#2552]
The marquand holding is out under CDL: https://catalog-alma-qa.princeton.edu/catalog/994081873506421. Clicking it doesn't seem to initiate anything, I don't see any console errors or xhr actions kicked off (in Chrome at least).

**Comment by tpendragon** [comment]
This particular one doesn't work because it's pointed at Figgy-prod, which is pointed at bibdata-prod, whose equivalent ID isn't checked out for CDL (https://catalog.princeton.edu/catalog/408187)

**Comment by hackartisan** [comment]
We should put this item in figgy-staging and point figgy-staging at bibdata-alma-qa.

Need to do this test before we turn off our API access.
