### ISSUE TITLE
Move OpenURL generation algorithm to Orangeindex

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#256]
A valid, complete OpenURL including an rft_id parameter storing the Orangelight index key should be created at index time for each record and stored in a retrievable solr document field marked "openurl".  

Most of this logic (which is incomplete) lives in https://github.com/pulibrary/orangelight/blob/development/config/initializers/blacklight_initializer.rb#L16. 

Having this as a reliable field in the index because it will enable the following.
1. More robust support for Zotero on the "show" record view
2. Support for Zotero on the "search results" view [since the OpenURL can be embedded in a COINS span tag without any expensive MARC parsing]
3. Having a reliable, robust support for OpenURL will enable better integration with the Aeon OpenURL based requests.

**Comment by kevinreiss** [comment]
@tampakis is this something you still think is in scope this week? If we don't get to this there are a few making sure lccns and oclcnums are included by the current helper that generates the OpenURL can go a long way to improving #241.

**Comment by kevinreiss** [comment]
The current "citation" routines from come in part (for zotero, endnote, refworks) from the blacklight-marc gem. 

See https://github.com/projectblacklight/blacklight-marc/blob/7c60e441cfa7c529b9797b8d293b60dfd9d754c0/lib/blacklight/solr/document/marc_export.rb

If we want to update these routines to come from our normalized solr values we'll need to audit these values and make sure any overrides do at least as well as these marc-based routines.

**Comment by tampakis** [comment]
Yes there has been some work done on this here in this branch: https://github.com/pulibrary/orangelight/commits/citation-solr

**Comment by kevinreiss** [comment]
Another potential use for OpenURL is with Borrow Direct's API via umlaut. This menu in our development instance of Umlaut for a charged Voyager item demonstrates what can be brought back for that service from umlaut for records that are cataloged with an ISBN or an ISSN (the only two match keys that will really work under Borrow Direct's broadcast search via z39.50 model). 

http://getit-dev.princeton.edu/go/4 

We could embed the borrow direct response in the above link directly within orangelight's availability section on the show page or on the "request" form if we pass the OpenURL data to umlaut's javascript utility. The request dialog in the example isn't fully configured because if you try to actually invoke the request option it is going to fail because we need to make umlaut aware of the data in our marc_liberation patron response. 

In the event a charged record doesn't have an isbn or issn you will get back an option that allows you to run a title or other fallback search against the actual borrow direct web app. This is an example of a title that doesn't have one of those standard numbers:

http://getit-dev.princeton.edu/go/5

The link provided for borrow direct in this example also doesn't currently work. That piece also needs to a bit more work within umlaut to work properly (it needs to pass through the same patron aware call as the the previous example for a direct request).
