### ISSUE TITLE
Availability not displayed for records in reserves 

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/orangelight#2571]
@kevinreiss found that records on reserves don't display availability.

![av_empty](https://user-images.githubusercontent.com/568286/125674366-953edc69-cde3-4ab9-9a94-1653176f4581.png)

**Comment by hectorcorrea** [comment]
For these records we make a second call to bib data to get the availability and the result of this second call is not being handled correctly. 

This was an issue introduced when I updated the code to [handle availability for bound-with records](https://github.com/pulibrary/orangelight/pull/2553). In particular, the call to `update_single` now expects two parameters and the AJAX success method is only passing one.

**Comment by christinach** [comment]
closed by #2572
