### ISSUE TITLE
Rename status 'some items not available' to 'some items are not available'

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2598]
![Screen Shot 2021-07-30 at 11 35 39 AM](https://user-images.githubusercontent.com/9905193/127676876-ca6fa2f5-fb6e-43f7-834a-bfd9b5f44cbb.png)

**Comment by hackartisan** [comment]
It's already pretty long. I think an extra word makes it harder to parse.

**Comment by christinach** [comment]
I agree that it is long as it is but it also doesn't look correct.

**Comment by christinach** [comment]
What about 'Limited item availability' ?

**Comment by hackartisan** [comment]
Do we not have this type of status in the old catalog that we can pull wording from?

I'm not sure about 'limited' that sort of makes me think I might only have in-library use or something.

"Some items not available" Isn't a complete sentence but I don't think it reads as incorrect, just slightly abbreviated. Maybe this is something to do usability testing on?
