### ISSUE TITLE
citation formating?

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#26]
What comes out of the box for blacklight and what needs to be configured? Librarian MARC view seems fine, refworks doesn't seem to export properly. Zotero customization necessary?

**Comment by tampakis** [comment]
See https://github.com/projectblacklight/blacklight-marc/blob/master/lib/blacklight/solr/document/marc_export.rb#L142-L155

**Comment by tampakis** [comment]
Need to support MARC 264 for publisher info.

**Comment by tampakis** [comment]
I think our citations are in pretty good shape. But reivew

**Comment by escowles** [comment]
Closing this old ticket — we have newer, more specific issues about citation functionality.
