### ISSUE TITLE
create and provision catalog3 as a webserver

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2603]
we have 2 boxes and we've just experienced that 1 alone can't handle the traffic. A 3rd will give us some wiggle room if one goes down.

**Comment by hackartisan** [comment]
we have 2 boxes and we've just experienced that 1 alone can't handle the traffic. A 3rd will give us some wiggle room if one goes down.

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/orangelight/pull/2606
