### ISSUE TITLE
Problems with EAL rare books 

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/orangelight#2607]
[Received from Martin via Service Portal]: I have been looking at how EAL rare books are displayed, and I see many strange “Some items are not available” designations, when that is not true (it very rarely is). It even says so for one case items.

https://catalog.princeton.edu/catalog/9990294553506421
https://catalog.princeton.edu/catalog/99111299423506421
https://catalog.princeton.edu/catalog/9940554593506421

I also note that there is a slight delay before that designation comes up.

@kevinreiss indicated that these items are all “holdings-only” materials that have no item records.

The Alma API returns "check_holdings" for record 99111299423506421 in the AVA field, subfield "e" (see below). We translate that to "Some items not available" https://github.com/pulibrary/bibdata/blob/main/app/adapters/alma_adapter/status.rb#L17

We could tweak the logic to display something else. What would be the expected availability for a record like this, should we do some special logic for this location?

```
    <datafield ind1=\" \" ind2=\" \" tag=\"AVA\">
        <subfield code=\"0\">99111299423506421</subfield>
        <subfield code=\"8\">22741556190006421</subfield>
        <subfield code=\"a\">01PRI_INST</subfield>
        <subfield code=\"b\">rare</subfield>
        <subfield code=\"c\">East Asian Library Rare Books</subfield>
        <subfield code=\"d\">QM21 .K85 1774</subfield>
        <subfield code=\"e\">check_holdings</subfield>
        <subfield code=\"j\">jrare</subfield>
        <subfield code=\"k\">0</subfield>
        <subfield code=\"p\">1</subfield>
        <subfield code=\"q\">Special Collections</subfield>
        <subfield code=\"t\">Prefatory volume, Vol.1-v.4</subfield>
    </datafield>
```

@kevinreiss said that in the old catalog we used to mark all special collection holdings in serviced by Aeon with no item level records attached to as “Available”. That is probably what Martin is expecting here. It seems like we could just draw on the bibdata aeon=true flag if we want to avoid doing anything further with the APIs. Another possibly to toggle this sort of behavior is the subfield b marked “rare” in this example. Is that consistent data point we’d find across all rare book locations Mark? 

Notice that, according to the [alma_rb gem](https://github.com/tulibraries/alma_rb/blob/main/lib/alma/availability_response.rb#L51-L65) there is also a subfield "f" that is supposed to indicate the "total items". Is the fact that there is no subfield "f" in this AVA section enough to assume that there are no items?

**Comment by tpendragon** [comment]
Decision: All aeon items are "On-site Access"

**Comment by hectorcorrea** [comment]
See also https://github.com/pulibrary/bibdata/issues/1314

**Comment by hectorcorrea** [comment]
@kevinreiss this has been fixed in production: https://catalog.princeton.edu/catalog/99111299423506421
