### ISSUE TITLE
[Orangelight/production] ActionView::Template::Error: key not found "title_display"

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#2614]
## Backtrace

    line 34 of [PROJECT_ROOT]/app/services/decorator_service.rb: title
    line 2 of [PROJECT_ROOT]/app/views/catalog/_show_linked_record.html.erb: _app_views_catalog__show_linked_record_html_erb__4431314700156777078_47359678478860
    line 3 of [PROJECT_ROOT]/app/views/catalog/_show_linked_records.html.erb: block in _app_views_catalog__show_linked_records_html_erb___1873907832438617096_47359678374340

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/80747144)

**Comment by christinach** [comment]
See: https://github.com/pulibrary/orangelight/blob/1a5d4d325d08676a3aedbbaa2a705f16d5c8dc83/app/services/decorator_service.rb#L14

I looked into the api call to make sure there is a 245 https://bibdata.princeton.edu/bibliographic/99123444323506421 

I will export the document from alma to test.

**Comment by christinach** [comment]
I tested and indexed locally the record with mms_id 99123444323506421 using the rake liberate:index_file with no errors and it displays as expected in OL. 
I will reindex it in staging as well.

**Comment by christinach** [comment]
I reindexed the record in staging but nothing changed https://catalog-qa.princeton.edu/catalog/99123444323506421/.

**Comment by christinach** [comment]
This is a screenshot of the record from my local environment: 

![Screen Shot 2021-08-04 at 12 56 10 PM](https://user-images.githubusercontent.com/9905193/128222679-8f52b485-e0fb-4f9a-b63d-6bf1c3eebf4b.png)

**Comment by hectorcorrea** [comment]
The culprit seems to be that the other version points to https://catalog.princeton.edu/catalog/99123923123506421 and this record does not have a `title_display`
