### ISSUE TITLE
Search results page shows html in the online section

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2631]
View record for availability -> red label
The online section displays the html.

![Screen Shot 2021-08-05 at 7 51 43 PM](https://user-images.githubusercontent.com/9905193/128435575-2cfe2476-735f-44fd-b865-700f7fdf7ab5.png)

**Comment by christinach** [comment]
Looking the record staff view: `856 4  
u| https://ezproxy.lau.edu.lb:2443/login?url=https://doi.org/10.1007/978-3-662-61068-8 y| <b>View Full Text</b>`.
Looks like incorrect entry. Is this part of a cleanup in alma?

**Comment by christinach** [comment]
I asked in the alma-cataloging-and-inventory-mngmt channel if it's possible to update the 856. Kevin C. will update it.

**Comment by kconnellmail** [comment]
Record updated.  URL has incorrectly formatted (with EZProxy prefix in the 856 & Portfolio Linking).  The 856 was added to a print record, too.  We do not have ebook access to the title.  856 & Portfolio deleted.  Marc record cleaned up. Print holdings remain.
