### ISSUE TITLE
Table of contents appear in the online label in the search results

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2632]
Is it also counted in the online facet?
Do we want to show this in the online label in the search results?

https://catalog.princeton.edu/catalog/99122674443506421
https://catalog.princeton.edu/catalog/99121162503506421
https://catalog.princeton.edu/catalog/99122539623506421
https://catalog.princeton.edu/catalog/99122676453506421
@mzelesky

**Comment by christinach** [comment]
I'm looking into this. 
Table of contents should not appear in the search results page.

**Comment by christinach** [comment]
Some of these records will clean up during a data cleanup of 856s https://github.com/pulibrary/bibdata/issues/1600

**Comment by kevinreiss** [comment]
Clean-up is still in progress.

**Comment by kevinreiss** [comment]
Some of the examples are still exhibiting the behavior. Fundamentally this is a clean-up ticket. @mzelesky can I close this one in favor of any alma-config tickets related to 856 clean-up?

**Comment by mzelesky** [comment]
99121162503506421 is an ark, which is the only one I see.

**Comment by mzelesky** [comment]
All URLs that are a Princeton domain were not touched. Also, cataloging managers explained that they will continue to add tables of contents when they feel it is appropriate.

Does this mean a new use case?

**Comment by mzelesky** [comment]
Ok, we will communicate the importance of correct indicators for tables of contents URLs.
