### ISSUE TITLE
'Available Online' section links will not navigate the user to the viewer.

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2647]
Reported in the catalog channel:
Record https://catalog.princeton.edu/catalog/99125378309606421/ contains two 856 fields -
856 4 0 3| Picture book u| https://figgy.princeton.edu/catalog/40ffdb32-6de6-470c-b677-9e422c8a4039 z| Access restricted to PUL patrons
856 4 0 3| Reading guide u| https://figgy.princeton.edu/catalog/c4322cf9-9023-4809-a73c-1b6202614021 z| Access restricted to PUL patrons
The Figgy URLs work fine if you put them into the web browser address bar and log in via CAS. 

- Issue: Clicking on the hyperlinks under `Available Online` in the record page -
Access restricted to PUL patrons: Picture book
Access restricted to PUL patrons: Reading guide
renders an error page -
`Remote Access @ PUL Error
We are unable to provide you access to the URL you requested at https://figgy.princeton.edu/catalog/c4322cf9-9023-4809-a73c-1b6202614021. Please let us know about this issue and we will resolve the issue as quickly as possible.
Both digital files have Visibility set as Princeton`

**Comment by tpendragon** [comment]
I assume the link resolver checks the link somehow, @kevinreiss would maybe know better?

On a different note, we should probably recommend that they put the ARKs for the record in the 856.

**Comment by christinach** [comment]
Following @tpendragon comment, they updated the 856s with arks and it resolves.
