### ISSUE TITLE
Remove voyager fixtures

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2649]
Remove voyager fixtures. Update tests accordingly with alma fixtures. There might be tests that they are no longer meaningful based on the alma changes. For example status changes.

**Comment by sandbergja** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DACS-Maintenance-5da0db919c4ddf0001b2eb92/issues/pulibrary/orangelight/2649?planning-poker) with Zenhub @christinach @maxkadel @regineheberlein @rladdusaw
