### ISSUE TITLE
Select All Feature for Bookmarks

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#265]
Is it feasible to add a select all option to add items on current page of search results to the bookmarks of the current user?

**Comment by tampakis** [comment]
Stanford's implementation seems like a good one to model. Select all/Unselect all
http://searchworks.stanford.edu/?utf8=%E2%9C%93&search_field=search&q=

**Comment by terrellt** [comment]
So is the wording "Select All" or "Bookmark All"

**Comment by terrellt** [comment]
"Select All" implies there's a second option to actually bookmark what you've selected.

**Comment by jpstroop** [comment]
I think that... two steps.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by kevinreiss** [comment]
Second step doesn't exist in BL currently.

**Comment by terrellt** [comment]
Well, I've got bookmark all done now. For a two step process we need to talk about the UI.
