### ISSUE TITLE
Marquand request - 'See Front desk'

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2659]
Reported in the catalog channel.
Marquand is a non-circ library and make their collection available to anyone who asks (when items are on-site). Items that are charged out used to say "SEE FRONT DESK," to prompt users to ask at their service desks to where an item is charged (i.e. shelf/carrel). Now, it seems to say "UNAVAILABLE." Might this be changed for SA/SAPH/RCPPJ items?.

**Comment by christinach** [comment]
@hectorcorrea will check if we can get this info from the api call.

**Comment by christinach** [comment]
@kevinreiss I forgot to tag you.

**Comment by hectorcorrea** [comment]
The data that comes in the typical Alma API for a bib record (`curl -X GET "https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/99101378413506421?view=full&expand=p_avail%2Ce_avail`) has the following information for Availability:

```
<datafield ind1=\" \" ind2=\" \" tag=\"AVA\">
  <subfield code=\"0\">99101378413506421</subfield>
  <subfield code=\"8\">22555592710006421</subfield>
  <subfield code=\"a\">01PRI_INST</subfield>
  <subfield code=\"b\">marquand</subfield>
  <subfield code=\"c\">Remote Storage: Marquand Use Only</subfield>
  <subfield code=\"e\">unavailable</subfield>
  <subfield code=\"f\">1</subfield>
  <subfield code=\"g\">1</subfield>
  <subfield code=\"j\">stacks</subfield>
  <subfield code=\"k\">#</subfield>
  <subfield code=\"p\">1</subfield>
  <subfield code=\"q\">Marquand Library</subfield>
</datafield>
```

Notice that this data comes as the AVA field inside the `anies` field in the API call.

The status that we get is "unavailable" (see `subfield e`) but it seems that we also get Location information and therefore we could implement some logic in BibData (or Orangelight) to treat this records slightly different and provide a more user friendly message to our patrons.

**Comment by kevinreiss** [comment]
I'm not really sure how much "SEE FRONT DESK" means any longer. Marquand is operating out of temporary space in Firestone and really doesn't have a front desk.
