### ISSUE TITLE
Remove references to getit

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2664]
https://github.com/pulibrary/orangelight/blob/8998c32af47876285885fda357edf23920bcfcc6/app/services/online_holdings_markup_builder.rb#L74

**Comment by hectorcorrea** [comment]
Does this ticket involve just removing the `if` block with the `getit` logic *or* does it involve restructuring the logic into electronic access links (as [indicated on the comment on that code](https://github.com/pulibrary/orangelight/blob/8998c32af47876285885fda357edf23920bcfcc6/app/services/online_holdings_markup_builder.rb#L73-L82)) ?

**Comment by sandbergja** [comment]
closed by #3174
