### ISSUE TITLE
[Orangelight/production] NoMethodError: undefined method `merge' for nil:NilClass

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#2665]
## Backtrace

    line 82 of [PROJECT_ROOT]/app/services/bibdata.rb: build_api_patron
    line 18 of [PROJECT_ROOT]/app/services/bibdata.rb: get_patron
    line 93 of [PROJECT_ROOT]/app/controllers/account_controller.rb: current_patron

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/80809081)

**Comment by christinach** [comment]
def build_api_patron(api_response:, user:)
--
81 | base_patron_json = JSON.parse(api_response.body)
82 | patron_json = base_patron_json.merge(
83 | valid: user.valid?
84 | )

**Comment by christinach** [comment]
we havent seen this issue again
