### ISSUE TITLE
Make a title starts with field

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#267]
Most of the feedback from Lissc+ has indicated that the starts with field only makes sense with the title. The browse lists seem to handle the author, subject, call number well enough.
Include the fields that Voyager uses for the "Title (omit initial articles..." field. 

@joycebcat - should I include all of the fields in TKEY? http://library.princeton.edu/departments/tsd/katmandu/voyager/scommand.html

**Comment by joycebcat** [comment]
@tampakis I'm not sure any longer what index is behind the title starts with search in Voyager.  I think we should use the same thing V does, and I'm not sure it includes all the things on the webpage you referred to.  Can you find out what is used in V or do you need me to look into it?

**Comment by kevinreiss** [comment]
Joyce do you know offhand where the configuration for these resides in
Voyager's file system. We cannot track it down in the Voyager directory
tree?

**Comment by jpstroop** [comment]
Seems to meet like it would be 245 boosted the most, followed by the other
2xxs, then 4xx, 880(?), 740, 7xx 12 $t, 130, 8xx ...

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by tampakis** [comment]
Sounds about right. I'm not so concerned about boosting for starts with (since we want a-z by default), but this is relevant for the title keyword search, which currently only hits 245.

**Comment by jpstroop** [comment]
Martin mentioned 500 $t as well.

Are we still sure about alpha sorting by default? That seemed to confuse
Rick.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by tampakis** [comment]
If only title is included, it might be less confusing, but since we're doing more than just 245 it still might be and that's where relevance does come in.

**Comment by joycebcat** [comment]
@kevinreiss @tampakis It looks like the search index behind "Title (omit initial articles: a, the, la, etc.)" in the voyager opac is TALL. 

TALL is a composite index that includes these indices:
700F
710F
711F
Formatted Content Note
Host Item Entry
Host Item Entry: Title
Main Series Entry
Parent Record Entry
Parent Record Entity: Title
Preceding Title (780t)
Series AE: Personal
Series AE: Uniform Title
Series Title: Title AE
Subseries Entry
Succeeding Title (785t)
Title Statement
Title, Former
Title, Key
Title, Varying Form
Translation (767)
Uncont. Title AE
Uniform Title AE
Uniform Title ME

If you need the data behind those, let me know and I can try to get it before I leave today.

**Comment by kevinreiss** [comment]
I should have updated the thread @joycebcat. @tampakis and I hunted this down in the Voyager docs after I posted this. I'll defer to him if he needs more info beyond what you've put here. Thanks.
