### ISSUE TITLE
Exporting Bookmarks as a CSV returns the wrong ID number

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#2695]
When I export my bookmarks as CSV, the ID ends in 420 instead of 421.  e.g., 9912140633506421 comes out as 9912140633506420. 

Reported by Dave Jenkins

**Comment by christinach** [comment]
I can't reproduce this. I exported the csv while logged in and not logged in:
`ID,Title,Title (Original Script),Author,Author (Original Script),Format,Language,Published/Created,Date,Description,Series,Location,Call Number,Notes
9912140633506421,Cats,"","","",Book,English,New York: G. P. Putnam's Sons,1974,108 p. illus. (part col.) 33 cm.,Animal world series,Stacks,Oversize QL737.C23C36.1974q,""`

@escowles is there more info on this issue?

**Comment by escowles** [comment]
@christinach I think the issue is really with Excel. That was the default app for handling CSV files for me, and it treats the long numeric IDs as numbers. It renders as `9.91214E+15` and when I look at the cell, I see the off-by-one value. So maybe there is some weird floating-point rounding going on? I'm not sure what we can do, but I think it will be pretty common to open the CSV files in Excel. I checked and Google Spreadsheets handles them just fine.

**Comment by christinach** [comment]
The other option is to import the csv file using the excel wizard:

Data -> From Text -> (select the csv file) -> click Get Data -> Select Delimited (click Next) -> Select Comma (click Next) -> (Under column data format) Select Text (click Finish).

**Comment by escowles** [comment]
@christinach I like putting the id in single quotes — that doesn't require special action for the user (which I think would be hard to communicate and unlikely to be followed), and it seems like it would keep the value usable in Excel and other applications.
