### ISSUE TITLE
Code improvement for availability.es6

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/orangelight#2696]
The code in [apply_availability_label()](https://github.com/pulibrary/orangelight/blob/main/app/javascript/orangelight/availability.es6#L362-L399) in availability.es6 has some logic that is probably not needed.

We used to receive the isCdl flag for both Search results and the Show page, but because it is very slow to get this value from Alma we now only receive it on the Show page. Therefore the part of the code that handles search results (see code below) is not needed.

```
apply_availability_label(availability_element, availability_info, addCdlBadge) {
    ...
    if (status_label.toLowerCase() === 'unavailable') {
      // The physical copy is not available but we highlight that the online copy is.
      if (isCdl) {
        if (addCdlBadge) {
          // This part of the code is used for the Search results
          // BUT WE PROBABLY NEVER REACH THIS CONDITION BECAUSE isCDL IS 
          // ALWAYS FALSE FOR SEARCH RESULTS
        } else {
          // this part of the code is used for the Show page
        }
      } else {
        ...
      }
    } else if (status_label.toLowerCase() === 'available') {
      ...
    } else {
      ...
    }
  }
```

**Comment by maxkadel** [comment]
@christinach - can this be closed?

**Comment by sandbergja** [comment]
per @rladdusaw this ticket is still valid.

**Comment by christinach** [comment]
> @christinach - can this be closed?

@maxkadel no this is a valid and large ticket.

**Comment by christinach** [comment]
closing in favor of https://github.com/pulibrary/orangelight/issues/3913
