### ISSUE TITLE
My Account does not link back to the Catalog, only to the Library account in Alma

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#2708]
**ACCEPTANCE CRITERIA:**
- [x] Add this in the 10/05/21 agenda to discuss with @kevinreiss.
- [ ] Assuming approval, Change the top left logo to link back to the catalog. 

Reported by Fernando Acosta-Rodriguez:

> When I go into the catalog and login to my account, I'm automatically directed to the Library Account page that shows loans, requests, fines, etc. That page does not have a direct link to return to the catalog. The only option is to click on the PUL logo on the upper left corner of the page and find the catalog link again. Once back in the catalog, one isn't logged in and, for example, can't see bookmarks placed before attempting to login. 

Can we add a link back to the Catalog? Should we make the PUL logo link to the Catalog instead of the Library website?

**Comment by christinach** [comment]
Linking https://github.com/pulibrary/orangelight/issues/2709
and https://github.com/pulibrary/orangelight/issues/2446

**Comment by christinach** [comment]
per @kevinreiss :

'We unfortunately cannot add new links to the header
It shares templates with the Alma “services” menu that serves up full-text links that is referred to from many third party sites outside of the catalog - Example link: 

https://princeton.alma.exlibrisgroup.com/discovery/openurl?institution=01PRI_INST&vid=01PRI_INST:Services&%3Fctx_ver=Z39.88-2004&ctx_enc=info:ofi%2Fenc:UTF-8&rfr_id=info:sid%2Fsummon.serialssolutions.com&rft_val_fmt=info:ofi%2Ffmt:kev:mtx:journal&rft.genre=article&rft.atitle=Striving%20for%20crisis%20resolution%20or%20crisis%20resilience%3F%20The%20crisis%20layers%20and%20thresholds%20model%20and%20Information%20and%20Communication%20Technology%E2%80%90mediated%20social%20sensing%20for%20evidence%E2%80%90based%20crisis%20management%20and%20communication&rft.jtitle=Human%20behavior%20and%20emerging%20technologies&rft.au=Gaspar,%20Rui&rft.au=Domingos,%20Samuel&rft.au=Brito,%20Duarte&rft.au=Leiras,%20Gisela&rft.date=2021-01-01&rft.pub=John%20Wiley%20%26%20Sons,%20Inc&rft.issn=2578-1863&rft.eissn=2578-1863&rft.volume=3&rft.issue=1&rft.spage=40&rft.epage=52&rft_id=info:doi%2F10.1002%2Fhbe2.241&rft.externalDocID=HBE2241&paramdict=en-US. '
