### ISSUE TITLE
Map Collections Should Show "On-Site Access"

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#2711]
The Lewis map collection "lewis$map" are non-circulating and have no item level data. Instead of Unavailable, these should take the "On-Site Access" label we provide for Special Collections and Marquand Library locations.

**Comment by hectorcorrea** [comment]
See https://github.com/pulibrary/bibdata/pull/1572 for work done in bibdata to display "On-site" access for Aeon location. See also https://github.com/pulibrary/orangelight/pull/2667 for work done to display custom status values for Marquand items.

**Comment by christinach** [comment]
Location codes that we should look for:
![Screen Shot 2021-09-02 at 3 31 33 PM](https://user-images.githubusercontent.com/9905193/131918935-f9cb2ddc-8ac8-45bf-888d-6df34f587251.png)
