### ISSUE TITLE
Ebooks on Ipads should not have request button and update the language

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/orangelight#2714]
I had a slack discussion with Joan M. today about these items.  She asked the catalog should not show the request button and that the language be updated
```
Joan M  3:16 PM
Yes the request should be removed and I'd prefer the language to say: 
To access this ebook, please visit the circulation desk at the ?? Library to checkout an iPad.
```
An example record is:
https://catalog.princeton.edu/requests/9976174773506421?mfhd=22170509880006421&source=pulsearch

**Comment by hectorcorrea** [comment]
How do we know that a book is only available via Library iPads? Is that specified in the MARC record that we get from Alma, available via the Alma API, or another mechanism?

**Comment by mzelesky** [comment]
I see this AVE field on this record:
`AVE 8| 53887401550006421 e| Available n| Available only on a library iPad. Click here for information about iPad lending at Princeton University Library u| publishing_base_url undefined?u.ignore_date_coverage=true&rft.mms_id=9976174773506421`

**Comment by mzelesky** [comment]
I think that would mean it's also in the files from the publishing job.

**Comment by hectorcorrea** [comment]
So if `AVE` subfield `n` contains "only on a library iPad" then that's good enough?

**Comment by mzelesky** [comment]
Really, it looks to me like iPads should be in a different location than books.

**Comment by mzelesky** [comment]
There is a location 'ltop' under several libraries that is used for laptops. I would suggest that iPads are put in the same location as other computer equipment, then it can be a location-based rule.

**Comment by mzelesky** [comment]
Really, there shouldn't be a portfolio (or AVE field) at all. The reason a portfolio was created was because the indicators of the 856 field indicated that the libguide link was a full-text link.

**Comment by christinach** [comment]
@mzelesky does this mean that you will update the ipad records in alma to have location 'ltop' ?
This location is also included in the fulflllment_unit as 'media' in the ALma locations https://github.com/pulibrary/bibdata/issues/1646#issuecomment-915584313.

**Comment by christinach** [comment]
@mzelesky is this a data issue and the portfolio will be removed from the record?

**Comment by mzelesky** [comment]
It means I think a larger conversation is needed about iPads and how they are represented in Alma. Solving the immediate request issue sounds like it may fix the immediate issue, but lead to more work down the road.

**Comment by christinach** [comment]
Thank you @mzelesky !

**Comment by christinach** [comment]
@mzelesky can you create a ticket in the alma-config and link it here? Thank you!

**Comment by mzelesky** [comment]
See https://github.com/PrincetonUniversityLibrary/alma-config/issues/67.
