### ISSUE TITLE
Bad Edition

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#272]
The online copies returned from the Gale Collection are incorrect.

http://pulsearch-dev.princeton.edu/catalog/4241899

**Comment by kevinreiss** [comment]
@tampakis The Gale links come from a routine in SFX for a package that searches only for a title and treats any object in system as an exact match if the title string supplied is contained in a target. These collections are for 18th Century documents so the routine supplied doesn't really take into other parameters beyond the title. See http://getit.princeton.edu/go/275 for what happens with just the string "Satires" supplied. I'm going to ask the SFX group why we activated this package is even an active option since it is very unlikely an OpenURL is going to give a positive match. 

The Internet archive result is a bit better in that the api searches upon title, author, and format.

**Comment by tampakis** [comment]
The false positives are avoided by only using the Umlaut online holdings service when the 856 is a getit link.
