### ISSUE TITLE
Search History adds Format:Journal

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2720]
**Issue**: it defaults to Format:journal even though no Format:Journal filter was selected. 
**Reproduce**: Load https://catalog.princeton.edu/ -> click 'Search History'

**ACCEPTANCE CRITERIA**
- [ ] I click "back to search" and it has not added any extra search criteria (e.g., "Format:Journal")

**Comment by bess** [comment]
Closing as a duplicate.
