### ISSUE TITLE
Rabbitmq orangelight queue will not process messages

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2721]
https://app.datadoghq.com/monitors/45852662?q=rabbitmq_queue%3Aorangelight&from_ts=1631528169000&to_ts=1631531769000&eval_ts=1631532601274

The datadog alert refers to orangelight-queue and there are 76 (unacked) unprocessed messages. Based in the rabbitmq docs: `Unacked means that the consumer has promised to process them but has not acknowledged that they are processed. When the consumer crashed the queue knows which messages are to be delivered again when the consumer comes online. When you have multiple consumers the messages are distributed among them.`

In the orangelight code base the name of the queue is defined as `catalog_#{Rails.env}`, in this case it is the catalog_production queue in rabbitmq. 
see: https://github.com/pulibrary/orangelight/blob/a7a071d5fb7e9e40ec650c46f8b6e4d1ada73a9b/app/workers/event_handler.rb#L5

Restarted orangelight-sneakers in catalog1,2,3. 
Restarting orangelight-sneakers in catalog1,2,3 (I think) should only affect the catalog_production queue and not the orangelight queue. 

Related pr to check the logs: https://github.com/pulibrary/orangelight/pull/2717

**Comment by christinach** [comment]
The orangelight queue makes sense not to find a consumer since the codebase is defining catalog_production queue. 
Both catalog_production queue and orangelight queue are receiving events from the orangelight_events. 
My understanding is that in rabbitmq we should remove  the orangelight queue (or deactivate or unlink the orangelight_events from this orangelight queue); but we don't want to loose the unprocessed messages in this queue. Is there a way to force send them to the catalog_production queue.  @eliotjordan any thoughts?

**Comment by hackartisan** [comment]
I don't think we need to worry about those events. They would only be for catching changes to numismatics items, and we should have all the changes that were made since the time we did the full index from the newer queue.

I would just delete the old one.

**Comment by christinach** [comment]
@jrgriffiniii and I unbound the orangelight-events from the orangelight queue. Then we deployed https://github.com/pulibrary/orangelight/commit/09ba924c9b177c3ec196fd523ebe74cfbbf92e49 and restarted sneakers in the 6 orangelight boxes so that messages will be processed. 
We deployed back main to production after the fix.

**Comment by christinach** [comment]
closed by deploying a temporary fix https://github.com/pulibrary/orangelight/commit/09ba924c9b177c3ec196fd523ebe74cfbbf92e49
