### ISSUE TITLE
Constituent CDL records have a digital content link, but it doesn't have a viewer.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#2727]
See https://catalog.princeton.edu/catalog/99125039643506421 (host record), vs https://catalog.princeton.edu/catalog/998127893506421 (constituent record)

The host record is under CDL and is a MVW in Figgy. The host record has the barcode and you have to check out the entire bound-with at once under CDL.

## Possible Solutions

1. There should be no digital content link for CDL items in constituent records.
2. Constituent records for CDL items should display the viewer for the host record.
    * Implication: If one of these volumes are made public in the future it would result in two viewers on that constituent record page - one to check out the entire MVW via CDL, and one which is just a viewer of that one portion. This is a real use case for these items (microfilm reels) - they intend to make them public one by one as their copyright dates end.

**Comment by mzelesky** [comment]
Proposal 2 sounds worthy of consideration, at least. Would there be some way of guaranteeing that the viewer for the constituent record appears above the viewer for the CDL?

**Comment by christinach** [comment]
CDL feature is not supported and has been removed.
