### ISSUE TITLE
Scroll and follow/fixed search button for advanced/guided search

### ISSUE THREAD

**Issue by axamei** [pulibrary/orangelight#273]
So that the search button always visible on advanced/guided search view(s).

Sticky search button on the bottom of the screen for mobile? 

Remove search tips?

**Comment by kevinreiss** [comment]
:+1: To the button sticking at the bottom of the screen on both mobile and desktop.

**Comment by tampakis** [comment]
Not needed after the redesign of the advanced search layout.
