### ISSUE TITLE
Linking to other records via 773/774

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#274]
I'm looking the Voyager config had 2 additional fields that would link to other records (similar to the other verisions field):
```
Contained in:
   3500 BBID773W

Related record(s):
   3500 BBID774W
```

These fields are currently not included in Orangelight (as links to other records). Should we add it?

**Comment by joycebcat** [comment]
@tampakis  Yes, these should be included.  They are particularly important for rare books.
