### ISSUE TITLE
Advance search - Architecture Locations

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/orangelight#2744]
The holding location `arch$pw` (Architecture ReCAP) shows twice in the Holding Location dropdown in the Advanced Search

![adv_arch_pw](https://user-images.githubusercontent.com/568286/134249114-6b1973cd-446f-49b2-ad9a-4fdc77771ac4.png)

I believe this is because in the past the "library" for Architecture ReCAP items was "ReCAP" instead of "Architecture Library" but now the ReCAP items have "Architecture Library" as their library and that causes the [code that creates the list used in this dropdown](https://github.com/pulibrary/orangelight/blob/main/app/helpers/advanced_helper.rb#L71-L84) to not handle this well and we endup with the code listed twice. 

My uneducated guess is that in the pass the code `arch$pw` was added to the `recap_code` property but not to the `codes` property but now it is added to both in the code mentioned above.

**Comment by christinach** [comment]
Location code that is included in this file https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/translation_maps/holding_library.rb is expected to appear twice in the holding location dropdown in the advanced search. However we need a different ticket in bibdata to update the holding library to Recap for location codes that have remote storage recap_rmt or totally remove the holding library file.

**Comment by christinach** [comment]
see https://github.com/pulibrary/bibdata/issues/2031
