### ISSUE TITLE
Full Text Link Displayed When Only Table of Contents is Available

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#2752]
https://catalog.princeton.edu/catalog/9953431693506421

**Comment by christinach** [comment]
@kevinreiss I think this is a cleanup in Alma. The specific electronic portfolio in alma has a url to the table of contents.

**Comment by christinach** [comment]
I transferred the ticket to eSupport and let Joe M. know about it. The record will be updated in Alma.
