### ISSUE TITLE
Audit Orangelight for accessibility issues

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2760]
- [ ] Accessibility Audit

**Comment by christinach** [comment]
See progress of this work:
-https://github.com/pulibrary/orangelight/commit/d9dc030cdf94fdfea4fd91d6666d31618d781c8e
      - https://docs.google.com/spreadsheets/d/1lV8AyTh1VZUrx-41s2impPCIn722MjRHJ_bvgLScuLs/edit#gid=590015898
      - https://docs.google.com/document/d/1EFV8OB5gZ8l3YXSs_badUVX8DT-SNLS_vcEF0mpZkeY/edit#

**Comment by sandbergja** [comment]
Everything in this epic has been completed!
