### ISSUE TITLE
Request button for analytical records should point to parent record

### ISSUE THREAD

**Issue by tventimi** [pulibrary/orangelight#2772]
There is an issue (pre-Alma) regarding how to place ReCAP requests for analytical records.  The "Request" button for the analytical record does not point to anything usable, as the relevant item records are attached to the parent.  See, e.g. the analytical record https://catalog.princeton.edu/catalog/99116725063506421 . The request form that the user really needs is linked to the parent record, https://catalog.princeton.edu/catalog/99103282343506421 .

Our stopgap measure was to put a note in the 866 field providing a direct link to the parent's request form.  These hard-coded links contained Voyager Bib IDs which are now broken.  We are looking into a way to fix the 866 links, but we also wanted to report the general issue and see if there is a way for the request buttons in the analytical records to point to the request form for the parent.

**Comment by christinach** [comment]
Talk to @tventimi when we are going to work on this issue. Having the individual item id may allow us to create a more automated process.

**Comment by sandbergja** [comment]
This is done.
