### ISSUE TITLE
Add an FAQ page

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2773]
ACCEPTANCE CRITERIA

- [ ] Wireframe if needed
- [ ] Get acceptance from DSSG
- [ ] Add FAQ page with questions and answers to assist the users.
- [ ] Add links to 5 min recorded videos.
- [ ] Deploy in qa to demo to stakeholders

**Comment by kevinreiss** [comment]
For a future OL weekly check-in meeting is this still desirable.

**Comment by kevinreiss** [comment]
Discussed at OL check-in on 12/7. Will close this, but in the future we should review the existing help documentation at https://catalog.princeton.edu/help with public services stakeholders.
