### ISSUE TITLE
Generate a report from automated a11y testing

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/orangelight#2781]
Ongoing work. See: https://docs.google.com/spreadsheets/d/1lV8AyTh1VZUrx-41s2impPCIn722MjRHJ_bvgLScuLs/edit#gid=825091091

https://docs.google.com/document/d/1EFV8OB5gZ8l3YXSs_badUVX8DT-SNLS_vcEF0mpZkeY/edit#

https://github.com/pulibrary/orangelight/tree/auto-accessibility-audit

**Comment by christinach** [comment]
Updated https://docs.google.com/document/d/1EFV8OB5gZ8l3YXSs_badUVX8DT-SNLS_vcEF0mpZkeY/edit#
