### ISSUE TITLE
Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2795]
**Home page**

impact: unknown

issue tag: cat.color, wcag2aa, wcag143

#search_field 
Element source: `<select name="search_field" id="search_field" title="Targeted search options" class="custom-select search-field">`

ACCEPTANCE CRITERIA

- [ ] Element's background color could not be determined due to a background image

**Comment by sandbergja** [comment]
I believe this is a false positive in aXe.  Lighthouse and WAVE didn't flag this issue.  There is a background image, but it is off to the side of the field -- it doesn't collide with the text in any screen size that I've tried, so doesn't affect the color contrast.  The text on the white background has a contrast ratio of 8.17:1, which is sufficient.

I'll close this for now, but we can re-open if necessary.
