### ISSUE TITLE
Ensuring proper list structure aids screen reader output.

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2801]
**Search results page**

Lists do not contain only elements and script supporting elements (<script> and <template>).
Screen readers have a specific way of announcing lists. 
Ensuring proper list structure aids screen reader output. https://web.dev/list/?utm_source=lighthouse&utm_medium=devtools

Fix the following:
List element has direct children that are not allowed inside <li> elements

Related node:
abbr[title="\39 9125289673606421"]

**Comment by sandbergja** [comment]
Closing as duplicate of #1063
