### ISSUE TITLE
Ensures that every form element has a visible label and is not solely labeled using hidden labels, or the title or aria-describedby attributes

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2805]
**Search results page**

Impact: serious

Issue Tags:
cat.forms
best-practice
Element location: #search_field
Element source: 
`<select name="search_field" id="search_field" title="Targeted search options" class="custom-select search-field">`

Fix the following: Only title used to generate label for form element.

ACCEPTANCE CRITERIA

- [ ] Add a label in the form element

**Comment by sandbergja** [comment]
Closed by https://github.com/pulibrary/orangelight/pull/2981
