### ISSUE TITLE
criteria for dataset facet

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#281]
@tampakis @jpstroop The limit for Bobray for datasets:

I found my messages about this from 2007, the best approach would be these two criteria
> Type of record from LDR (byte 06) = m
> and
> 008 Type of file (byte 26) = a

**Comment by tampakis** [comment]
@joycebcat currently all records with 'm' in LDR byte 06 are classified as _Data File_. Are we proposing to take some of the records that have 'a' in 008 byte 26 and call them _Data Set_? Are there any other more specific data file types we are looking to facet on based on the 008 byte 26? I've pasted the spec below. 
```
26 - Type of computer file (006/09)

    a - Numeric data
    b - Computer program
    c - Representational
    d - Document
    e - Bibliographic data
    f - Font
    g - Game
    h - Sound
    i - Interactive multimedia
    j - Online system or service
    m - Combination
    u - Unknown
    z - Other
    | - No attempt to code
```

**Comment by joycebcat** [comment]
Bobray has been asking for such a limit for years.  With Blacklight's completely different design, perhaps we should check in with him about the current "data file" facet and see whether that is specific enough or whether he feels that a further refinement for the subset of data sets is really important.  I was surprised to see that there are only 11,000 or so records with 008/06=m to start with.  I'll e-mail him.
