### ISSUE TITLE
Think through indexing improvement process, iterative tests

### ISSUE THREAD

**Issue by kelynch** [pulibrary/orangelight#2813]
As a team, brainstorm small, iterative testing and improvement processes to begin making the catalog full reindexing process less manual and labor-intensive.

* While thinking about simplifying it, think about how this can be a process that anyone in DRDS, Ops, or elsewhere can run without domain expertise.
* Also consider ultimately making it *extremely* easy to roll back in the event of a corrupted index in future, to take the pressure off.

See [shared agenda notes](https://docs.google.com/document/d/1JsSnjcSLqazI61tL2D6EuuyI17UcUvydGbhLPF6fc_w/edit#heading=h.c0hapr8gtqgm) for relevant discussion.

**Comment by kevinreiss** [comment]
We have updated the documentation on this extensively. https://github.com/pulibrary/bibdata/blob/main/docs/indexing.md
