### ISSUE TITLE
Location and Call Number Should be included in "email-a-record" feature. 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#2818]
Current Example Output

--------------------------------------------------------------------------------
Title: The prehistory of eastern Europe. Part 1. Mesolithic, neolithic and copper age cultures in Russia and the Baltic area, by Marija Gimbutas. Edited by Hugh Hencken.
Author: Gimbutas, Marija, 1921-1994
Published/Created: Cambridge, Mass.: Peabody Museum, 1956.
Format: Book
URL: https://catalog.princeton.edu/catalog/9960712583506421
--------------------------------------------------------------------------------

**Comment by sandbergja** [comment]
This example seems to be a special case, since it has no holdings_1display.

Emailing [this record, which has a holdings_1display](https://catalog.princeton.edu/catalog/9916414413506421), does include the location and call number.

**Comment by kevinreiss** [comment]
This is not a global issue. This is a boundwith record with at 773 value. There is no holdings1_display in the JSON indexed for the records so the email does not have a call number value to pull into the email erb template. Likely an issue with all boundwith records.
