### ISSUE TITLE
Open Dataset page should link to POD dataset, not main Events list

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#2825]
Related to https://github.com/pulibrary/bibdata/issues/1694

We will update link that now goes to the bibdata events page to point at the files on lib-jobs.

**Comment by carolyncole** [comment]
Submit collection job has a method to handle the namespace.

**Comment by maxkadel** [comment]
Per @sandbergja have to log in to POD in order to get any information (not super open).  @escowles Is there another link we could give?

* Catalog page with link to change - https://catalog.princeton.edu/dataset  
* Current POD page - https://pod.stanford.edu/organizations/princeton

**Comment by escowles** [comment]
I agree that linking to POD doesn't seem like it will address this need, since the target audience is much broader than the people who would have POD accounts.

Is there a place in Lib-Jobs where we can link to the data files for anonymous users to download them?

**Comment by escowles** [comment]
I took a look at Lib-Jobs and it looks like there's a way to download at least the latest version of a file, but I couldn't get it to work for the POD dataset. The specs, so I assume this is an access control issue, so we might need to open up access to this particular dataset.

The other option would be to update the process to copy the files to a separate directory and expose that using an nginx directory listing or something like that, where there wouldn't be access controls.

Either of those seem like reasonable ways to let anonymous users actually download the most recent POD dataset.
