### ISSUE TITLE
Do not display 306 field

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#283]
Mark:
>> I was looking at a record for a CD (Crazy Jane, bib ID #9117316), and I noticed that playing times are displaying oddly. The times display as strings of numbers in the Description area (000247, 000918, 000214, etc.) without any indication of what the numbers mean. Would it be possible to make them display as times (i.e., 2:47, 9:18, 2:14, etc.) or in some way as to make it clearer that these are durations? This is something both in Primo and Blacklight.

Joyce:
> Good catch, Mark.  I think this data from the 306 field should not be displaying at all.  If you look at Mark’s example, you can see that it is a coded from of the same data which is presented in a people-friendly way in the contents note

Example: http://pulsearch.princeton.edu/catalog/9117316

**Comment by tampakis** [comment]
The 306 tag was removed from the solr description field in pulibrary/orangeindex#32
