### ISSUE TITLE
856 Display on on Search Results View

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#284]
@tampakis, @terrellt, @jpstroop  a micro-issue for #107, #108. Since the location code and the 856 field are both stored in the solr document it would be pretty straightforward to display a direct link to the online holdings on the search results page. That seems pretty desirable to me. We have five location codes for online holdings, elf, elf1, elf2, elf3, elf4 that are always going to hold resources that have a link to the full-text representation stored in the 856 fields.

**Comment by tampakis** [comment]
Yes I agree - we should include a link from the 856 if full text is available online. That's what Cornell does too: https://newcatalog.library.cornell.edu/catalog?utf8=%E2%9C%93&q=stroop&search_field=all_fields

They use a green checkbox for available and "Online" is a link to the record. @kevinreiss can we say for certain that these location codes are all for full text versions? Are any of the codes for on-campus use only?

**Comment by kevinreiss** [comment]
We should confirm with @joycebcat that elf, elf1, elf2, elf3, elf4 are all for full-text.

**Comment by joycebcat** [comment]
@tampakis @kevinreiss @jpstroop @terrellt Demystifying the elves

elf1 - main location, used for everything but the things below, large number of records, includes MarcIT records
elf2 - local access only; accessible through library web computers
elf 3 - permanent access has been purchased
elf4 - overdrive material

**Comment by joycebcat** [comment]
@kevinreiss Yes, the elf locations are for full-text.  856s in the bib record are not dependable because they are sometimes for tables of contents, publisher descriptions, etc. but they don't have an elf mfhd unless there is full-text

**Comment by jpstroop** [comment]
No :elf: or :gnome: Emoji? seriously? Guess :santa: is the closest.

**Comment by kevinreiss** [comment]
@tampakis, et. al. I think the consensus was that we should render whatever we do with these with some blue coloring to keep them in the patter with the green/red/grey labels going to other groupings.
