### ISSUE TITLE
Convert Barcode Login to Utilize Alma User Authentication (Guest Accounts)

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#2846]
Guest users that logged in using their last name/barcode under Voyager will be reactivated with Alma internal username and password. This API https://developers.exlibrisgroup.com/alma/apis/docs/users/UE9TVCAvYWxtYXdzL3YxL3VzZXJzL3t1c2VyX2lkfQ==/ will allow us to use that combination in the context of a form. 

Update issue based on the notes from https://docs.google.com/document/d/1GxpYrcRc6w3kMFU1XU6CEpnumFzvxFrj2GkCq_XvoWw/edit# 2/3/2022

We should make these users have the same as the barcoded user: They do not have access borrow direct/ resource sharing (ILL),  digitization, and not on campus pickup service.

This will be in addition to the current barcode login.

**Comment by carolyncole** [comment]
https://github.com/pulibrary/requests/blob/756c5a7fb7947a432646ab438f4752902c5e556d/lib/generators/requests/templates/app/controllers/users/omniauth_callbacks_controller.rb#L12-L27

**Comment by carolyncole** [comment]
Will need Alma Test account and API key that will work with that API.

**Comment by carolyncole** [comment]
@kevinreiss do we know if alma account holders get access to partner materials?

**Comment by kevinreiss** [comment]
Yes, they can request these.

**Comment by carolyncole** [comment]
Additional Items to Consider
- [ ] What should we show for On Order and In Process Recap items?  The usual form?
- [ ] What message should we show a user when they try to request an item in the library that is available
- [ ] What message should we show a user when they try to request an item in the library that is not available? Is it different from the Available message?
- [ ] Are we going to try and allow these users a way to login to AEON with their Alma Account?  I believe the answer to this has to be no...

**Comment by kevinreiss** [comment]
I think for all these items except for the second one we should show the same message:

Request options for this item are currently only available to Faculty, Staff, and Students. Joan and Marie were okay with that wording. Aeon accounts are incompatible with the Alma login, that will have to remain a separate process.
