### ISSUE TITLE
Marc-It Holdings Location Code

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#285]
Also an off-shoot of #107, #108. 

@joycebcat do you know if one of our online locations (elf, elf1, elf2, elf3, elf4) is reserved  for the "marc-it" records we have loaded from the SFX knowledge-base? If yes, that might enable us to do something more sophisticated and reliably interact with the knowledge-base through a call to the API when that code is encountered. If can always say the 856 field for elf1 is a value from our "marc-it" holdings we can then explicitly embed the results from the menu whenever we encounter one. 

This would let us embed the full-text area from http://getit.princeton.edu/go/298 directly in:
http://pulsearch-dev.princeton.edu/catalog/8606659 instead of having the user go off to another page.

**Comment by joycebcat** [comment]
@kevinreiss Sorry but the MarcIT records are in elf1 along with the bulk of our electronic material.

**Comment by kevinreiss** [comment]
@joycebcat why do we have five different codes than?

**Comment by kevinreiss** [comment]
Sorry, I missed the comment at #284.

**Comment by kevinreiss** [comment]
Okay, we can close this one. If we to do any "special" treatment we will have to scan the 856 to see if the URL begins with our link resolver prefix of "getit.princeton.edu".
