### ISSUE TITLE
Search by ISSN/ISBN

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#286]
Should pasting in an ISSN or ISBN in the form in a keyword search in any form work?

Right now:

http://pulsearch-dev.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=1095-9203 - doesn't work

But:

http://pulsearch-dev.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=10959203 - does

Same goes for ISBN:

http://pulsearch-dev.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=9784103534228

vs. 

http://pulsearch-dev.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=978-4103534228

Would it be possible to have the ISSN/ISBN check algorithms run against the query string and then alter it accordingly before the query gets to the index? Most systems do seem to handle this, even Primo.

**Comment by terrellt** [comment]
I'm a little shocked solr doesn't strip the dashes from the tokenized version.

**Comment by terrellt** [comment]
My opinion would be to do this from the solr side (better to leave the host data in tact, and not start messing with queries - this kind of data manipulation is what solr's good at). What that would mean is defining a new field type for isbn_display and giving it a CharFilterFactory with a mapping to strip out dashes. https://cwiki.apache.org/confluence/display/solr/CharFilterFactories

**Comment by tampakis** [comment]
We come across this problem because the dash is used for tokenizing in Solr. I'm not sure whether I prefer fixing it by normalizing in Blacklight or in Solr. If all we are talking about is removing a dash, then the char filter should help us out. As this is the basic keyword search and text will be in there too, I guess the pattern I should match is `\d-` so I don't remove the dash in between words. Maybe we want to do away with dashes even for text? I am skeptical that the dash tokenizer really gains us much in terms of relevancy/recall (like merry-go-round becoming merry go round).

The one benefit about normalizing in Blacklight is for more involved normalizations like for ISBN:
```
StdNum::ISBN.normalize('0-9752298-0-X') => "9780975229804"
```

**Comment by terrellt** [comment]
http://robotlibrarian.billdueber.com/2012/03/solr-field-type-for-numericish-ids/ may be useful here

**Comment by terrellt** [comment]
> We come across this problem because the dash is used for tokenizing in Solr.

The standard factory only tokenizes on dashes if the rest of the string isn't numeric. Otherwise searching with the dashes wouldn't work.

**Comment by kevinreiss** [comment]
Searches that start with ISBNs/ISSNs that aren't nicely normalized are working now but I think we may want to refine things further. Consider this example for the journal Science:

https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=0036-8075

We get 2712 results and the relevant records are 2, 6, and 7. If we try a search in Primo for the same ISSN:

http://princeton-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlSearch.do?institution=PRN&onCampus=false&indx=1&dym=true&highlight=true&displayField=title&query=any%2Ccontains%2C0036-8075&bulkSize=10&loc=local,scope:(OTHERS),scope:(FIRE),scope:(RECAP),scope:(EAD)&vid=PRINCETON&tab=location

We get two results, both of which are direct matches for that ISSN. A small point but I think if the user supplies something that matches the pattern of an ISSN or ISBN we should default to use only the index relevant to those values if possible.

**Comment by kevinreiss** [comment]
@tampakis didn't want to sidetrack the meeting today but is this an issue you think we can address.
