### ISSUE TITLE
click View Bookmarks triggers: Blacklight::Exceptions::InvalidRequest

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2860]
reported in the catalog channel: 
I bookmarked a bunch of records in Blacklight, but when I click to view my bookmarks, I get a message that says "sorry, I don't understand your search"

https://app.honeybadger.io/projects/54399/faults/81114343

**Comment by christinach** [comment]
The error happens when the user is logged in or logged out.

**Comment by carolyncole** [comment]
This is the line that we do this: https://github.com/pulibrary/orangelight/blob/main/app/controllers/bookmarks_controller.rb#L20

**Comment by sandbergja** [comment]
closed by #2870

**Comment by carolyncole** [comment]
The maximum ids that allow the page to work is 1024.  We should limit the number of bookmarks to 1024, otherwise we will continue to get this strange error.

**Comment by kevinreiss** [comment]
Failpoint for bookmarks is 1024 items.

**Comment by kevinreiss** [comment]
I think this one can be closed.
