### ISSUE TITLE
Do we still need the introjs-rails gem?

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#2868]
We are pinned to a branch that is almost six years old. The introjs tour was removed in 9ae4ba290c8e04a2c850d267683134d34ac568b4, but the gem remains, along with some styles.

FWIW, the gem is tied to an old version of the introjs library that gives us the following deprecation warning in our test output:

autoprefixer: /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/bundler/gems/intro.js-rails-6638f10ec30d/app/assets/stylesheets/introjs.css:11:3: Gradient has outdated direction syntax. Replace `cover` to `farthest-corner`.

**Comment by kevinreiss** [comment]
I think we can definitely remove this one.
