### ISSUE TITLE
Advanced Search fails when right hand side choices are added to an existing search (has facets)

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2874]
ActionView::Template::Error: undefined method `to_sym' for ["Mendel Music Library", "ReCAP"]:Array
Did you mean?  to_s
               to_set

honeybadger error:
https://app.honeybadger.io/projects/54399/faults/84204121

https://github.com/pulibrary/orangelight/blob/652a275746d36b11f07b10d044259268d97fc2eb/app/helpers/application_helper.rb#L392

def render_location_code(value)
  location = Bibdata.holding_locations[value.to_sym]
  ocation.nil? ? value : "#{value}: #{location_full_display(location)}"
end

**Comment by kevinreiss** [comment]
Appears to fail with any advanced search combining any facet plus a holding location.

**Comment by christinach** [comment]
If you pick advanced search first and then add the facet it will work.

**Comment by christinach** [comment]
The opposite will error. Add facet and then do an advanced search.
