### ISSUE TITLE
Migrate barcode users to alma users

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/orangelight#2902]
In the catalog the current barcode users should be migrated to alma logins with barcode as an identifier

**Comment by kevinreiss** [comment]
Is this a bulk task we need to do prior to releasing the new alma internal account request support?

**Comment by kevinreiss** [comment]
We should do some analysis of the user database to see if any barcode users are actually signing in to use bookmarks.

**Comment by kevinreiss** [comment]
Steps to finish this
1. See if any barcode are actually logging into the system. Look at BL users table. 
2.

**Comment by christinach** [comment]
talk to @pmgreen @mzelesky and request an analytics report with the alma user accounts that they've been created since we started the new program.

**Comment by pmgreen** [comment]
@christinach since what date?

**Comment by pmgreen** [comment]
Sent via email to @christinach and @kevinreiss

**Comment by christinach** [comment]
Thanks @pmgreen !

**Comment by kevinreiss** [comment]
We only need to check the "affiliate" user group.

**Comment by sandbergja** [comment]
`User.where(provider: 'barcode').select {|user| user.last_sign_in_at > '2022-01-01' }.select {|user| user.bookmarks.count > 0}` shows 5 users who have signed in this year and have bookmarks.

**Comment by sandbergja** [comment]
Per Joan, we can close this ticket.
