### ISSUE TITLE
Record page should display all the "Related records". 

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2904]
Example record: https://catalog.princeton.edu/catalog/9952273613506421

@jpstroop shared feedback from the DSSG meeting and the suggestion is to display all the related records and not only ten as we do now. 
See https://pulibrary.slack.com/archives/CA891BNR0/p1648068079767149

**Comment by escowles** [comment]
There are potentially a large number of related records, so we should have an accordion to prevent a very long list from making it hard to see the rest of the record.

**Comment by mzelesky** [comment]
This issue was raised on July 12th by staff in the Alma Cataloging channel.

**Comment by christinach** [comment]
a new example https://catalog.princeton.edu/catalog/99125017273506421

**Comment by sandbergja** [comment]
@christinach says there is a pre-existing "show more"/"show less" ui pattern that was used for the item display before the alma migration.
