### ISSUE TITLE
suppress Reading Room Request button for certain location codes

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/orangelight#2910]
This is to prevent requesting of archival collections from the catalog. The list of location codes is still being vetted by SC. I will provide it here once it's been finalized.

**Comment by regineheberlein** [comment]
See https://github.com/PrincetonUniversityLibrary/alma-config/issues/193

**Comment by christinach** [comment]
Right now in Blacklight:
1. We hide the request button for locations with `fulfillment unit: Reserves`. (instant hide)
2. We hide the ‘Request’ button for  locations that have in bibdata `requestable: true` and are `temporary locations` (this is not instant . It happens with JS)
3. We will add a new feature in blacklight to hide the ‘Request’ button for the listed locations in the proposal.

**Comment by kevinreiss** [comment]
Three steps need to happen that are blocking this one. The following needs to happen for these locations:

1) Create them in Alma 
2) Create them in ASpace
3) assign them to the correct resources.

**Comment by regineheberlein** [comment]
Also see https://docs.google.com/document/d/1FYpmZwRNuhnyoG2LfRGVm0nHyOhpgASYhFiV3lwOPXw/edit

**Comment by regineheberlein** [comment]
@christinach 
I wonder whether it would make sense to leverage the prefix: all the newly created non-requestable SC location codes start with "sca". (Instead of hard-coding the locations.)

This is of interest also because SC is currently requesting the creation of additional non-requestable location codes. They will also start with "sca". If the prefix can be used for this, then we won't need to do more work for additional locations in this category later on.

**Comment by christinach** [comment]
@regineheberlein in this issue https://github.com/pulibrary/bibdata/issues/1963 we also added rare$xmr, which doesn't have a prefix sca. Is the location rare$xmr still part of this SC location group?

**Comment by regineheberlein** [comment]
Yes, you're right. "xmr" is part of the request. I wasn't thinking of the ReCAP ones because their user-facing code still starts with "sca" (i.e., the archivists use "scarcpxmr") but maps to "xmr" behind the scenes. I guess we're back to hardcoding then. :-(

**Comment by christinach** [comment]
@regineheberlein thanks! Your suggestion can always be used + any other location which is part of this group and doesn't start with sca.

**Comment by christinach** [comment]
example mmsid in the alma sandbox 9937155363506421

**Comment by regineheberlein** [comment]
more examples:
MMS ID: 9922522883506421 scaex
MMS ID: 998057023506421 scamudd
MMS ID: 998517783506421 scamss
MMS ID: 9930565623506421 scahsvm
MMS ID: 99125500898806421 scactsn
MMS ID: 9961356593506421 scagax
MMS ID: 9925879933506421 scathx
MMS ID: 9946283343506421 scawa
MMS ID: 99125501031906421 xmr

**Comment by christinach** [comment]
From some local testing the button is hidden because the new locations are marked as not requestable in bibdata. However I will hide the button based on the indexed holding as well so that we dont rely only in the bibdata response.
