### ISSUE TITLE
Refactor record view 

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#292]
* Move the thumbnail to the left side of the screen
 * Move the metadata slightly right to make room for the above
 * Move the availability window up to the top

I.E.:
 
![md_layout_refactor](https://cloud.githubusercontent.com/assets/999701/10524916/fdb03d56-734f-11e5-8c74-74a28f24eac2.png)

**Comment by jpstroop** [comment]
Black lines are what I'd imaging you'd do w/ Bootstrap (but what do I know...)
![md_layout_refactor_bootstrap](https://cloud.githubusercontent.com/assets/999701/10525430/c54e59ea-7352-11e5-8e5c-d2184961357c.png)

**Comment by terrellt** [comment]
![screen shot 2015-10-15 at 1 00 25 pm](https://cloud.githubusercontent.com/assets/2806645/10526001/e2de7c44-733c-11e5-86b7-6241ffa1085c.png)
Like that?

**Comment by jpstroop** [comment]
I _think_ so. Wondering if there should be some padding on the left of the graphic--but I'm terrible about these things

**Comment by jpstroop** [comment]
Now wondering if, as long as you're making Bootstrap soup, it should be:

![md_layout_refactor_bootstrap1](https://cloud.githubusercontent.com/assets/999701/10526129/edc1e96a-7356-11e5-9d8c-a24635f09d2e.png)

**Comment by jpstroop** [comment]
but yeah, let's get covers merged before this goes any further

**Comment by tampakis** [comment]
it's merged

**Comment by tampakis** [comment]
I'd agree that there should be some padding on the left of the thumbnail as well as to have the title in the same column with the rest of the record information.

**Comment by terrellt** [comment]
> Now wondering if, as long as you're making Bootstrap soup, it should be:

Personally I like it better with the title taking up 100%.

**Comment by jpstroop** [comment]
I think what's bothering me is that the actual text "Copies in Library" doesn't line up w/ anything, even if its border does.

**Comment by jpstroop** [comment]
plus I'm having fun drawing pictures :wink:

**Comment by jpstroop** [comment]
@tampakis can you think of a record with an insanely long title?

**Comment by terrellt** [comment]
@jpstroop Ah, yes, I think that's a side effect of the umlaut styling. How's this?
![screen shot 2015-10-15 at 1 18 08 pm](https://cloud.githubusercontent.com/assets/2806645/10526353/3c972ce8-733f-11e5-8c7a-7035cfc03598.png)

**Comment by jpstroop** [comment]
Ugh

**Comment by tampakis** [comment]
![screenshot from 2015-10-15 16 18 41](https://cloud.githubusercontent.com/assets/4650153/10526397/98be1f0e-7358-11e5-8491-da9806d4c48c.png)

**Comment by jpstroop** [comment]
How does 2881792 look?

**Comment by tampakis** [comment]
![screenshot from 2015-10-15 16 22 38](https://cloud.githubusercontent.com/assets/4650153/10526458/f91c5fe6-7358-11e5-84aa-0af607df5036.png)

**Comment by jpstroop** [comment]
I think we should try what I said up in https://github.com/pulibrary/orangelight/issues/292#issuecomment-148506745

I'd like to see those long titles wrap earlier, and it might solve the weird "Copies in Library" alignment problem as well.

Also, I think the graphic should be centered in its column.

**Comment by terrellt** [comment]
I tried to center the graphic and the gods of CSS came down upon me. I'll give it another shot.

292 may take a bit, it's a big change from how blacklight usually formats these views.

**Comment by terrellt** [comment]
@jpstroop I lied. This is what it looks like with title wrapped earlier.
![screen shot 2015-10-15 at 1 30 47 pm](https://cloud.githubusercontent.com/assets/2806645/10526641/fa722c9e-7340-11e5-8a0e-c2d8bd03fd73.png)

**Comment by terrellt** [comment]
And this is if you kill umlaut's padding top:

![screen shot 2015-10-15 at 1 32 07 pm](https://cloud.githubusercontent.com/assets/2806645/10526687/2ce8fd2e-7341-11e5-8caa-8a95d45a2dc2.png)

**Comment by jpstroop** [comment]
I kind of like that. (the first version)

>  the gods of CSS came down upon me

I'm a CSS atheist. Can you fake it with an em or three of padding on the left?

**Comment by joycebcat** [comment]
@jpstroop A long title (assuming you mean a long title/subtitle combination)?
The order and manner of the sitting of the Lords spirituall and temporall
OR
Reasons most humbly offered to the honourable House of Commons in Parliament

**Comment by terrellt** [comment]
@jpstroop You like the padding there?

**Comment by jpstroop** [comment]
where?

**Comment by tampakis** [comment]
For the thumbnail

**Comment by terrellt** [comment]
@jpstroop On the top of "Copies in Library"

**Comment by jpstroop** [comment]
I don't like the test pushed all the way to the top

**Comment by tampakis** [comment]
I think the padding should be there but maybe a few pixels less.

**Comment by jpstroop** [comment]
but the space between the top border and the line underneath should be the same

**Comment by tampakis** [comment]
@jpstroop i agree

**Comment by terrellt** [comment]
@jpstroop 
![screen shot 2015-10-15 at 1 42 04 pm](https://cloud.githubusercontent.com/assets/2806645/10526928/8bbfc14c-7342-11e5-80d7-da037212a413.png)

I don't think I can reliably "center" the image, because that white space isn't assigned to the thumbnail's div - it's the white space which is a result of right-justifying the labels.

**Comment by terrellt** [comment]
This is as close as I can get I think:

![screen shot 2015-10-15 at 1 44 34 pm](https://cloud.githubusercontent.com/assets/2806645/10526981/e76cc97c-7342-11e5-9e00-c56ff8659aac.png)

**Comment by jpstroop** [comment]
> I don't think I can reliably "center" the image, because that white space isn't assigned to the thumbnail's div - it's the white space which is a result of right-justifying the labels.

Right, but it's in its own column, no?

**Comment by terrellt** [comment]
> Right, but it's in its own column, no?

Yup, and when I align the image to the right I get the last picture I sent. So the right edge of that camera is the right of the thumbnail's column.

**Comment by jpstroop** [comment]
Ugh, ok. We're not going to solve this, but for now I'm thinking go back to what we had in https://github.com/pulibrary/orangelight/issues/292#issuecomment-148509856 and add some padding to the graphic.

**Comment by jpstroop** [comment]
Wait, the column can't be wider?

**Comment by jpstroop** [comment]
yuck, @tampakis just tried that. Nevermind

**Comment by terrellt** [comment]
@jpstroop The one in that comment has no room for alignment - you could pad it, but the character would bleed into the white space of the other div and possibly overlap with text.

**Comment by jpstroop** [comment]
OK. This is going to be a bigger project. I have a feeling that the Umlaut div should be inside the div that contains the metadata and floated right. @tampakis just showed me an abstract that was wrapping to the width of the center column even though it was well below the Umlaut div, and it looked really awkward.

**Comment by jpstroop** [comment]
@tampakis can you put a shot of that up?

**Comment by tampakis** [comment]
![screenshot from 2015-10-15 16 59 08](https://cloud.githubusercontent.com/assets/4650153/10527394/2f889c5c-735e-11e5-91ea-14d63c1a1067.png)

**Comment by terrellt** [comment]
Oh, you wanted the metadata to wrap around the right column if there's no content in it?

**Comment by tampakis** [comment]
I think if we were to have the summary note go all the way the right end of the page below the availability panel then we should also have the title go all the way to the right.

**Comment by jpstroop** [comment]
I didn't realize it, but I think so :wink:

**Comment by tampakis** [comment]
Never mind, I change my mind on that. We're on the right track with the availability appearing to the right of the title.

**Comment by terrellt** [comment]
This is title all the way right: 
![screen shot 2015-10-15 at 2 06 25 pm](https://cloud.githubusercontent.com/assets/2806645/10527562/fd2b687e-7345-11e5-998d-dae83b43cd0c.png)

**Comment by jpstroop** [comment]
If there's any way we can left-pad the graphic all all, I'm :+1:

**Comment by jpstroop** [comment]
![md_layout_refactor_bootstrap2](https://cloud.githubusercontent.com/assets/999701/10527652/9b56f55e-735f-11e5-929f-19f653d61a85.png)

**Comment by tampakis** [comment]
Looking at this I'm :+1: too, but I think we should make the availability 4 wide instead of 3.

**Comment by terrellt** [comment]
Okay. I'll fiddle with the graphic, make availability bigger, and then I need to add breakpoints to make the float behave nice for mobile.

**Comment by jpstroop** [comment]
:+1:

**Comment by terrellt** [comment]
This is now in PR #293 
![screen shot 2015-10-15 at 2 26 32 pm](https://cloud.githubusercontent.com/assets/2806645/10528060/c77ab1c8-7348-11e5-8c71-9fb348870bc8.png)

**Comment by terrellt** [comment]
Er, this:
![screen shot 2015-10-15 at 2 29 07 pm](https://cloud.githubusercontent.com/assets/2806645/10528111/1fa14f92-7349-11e5-9a13-9255e30f59fb.png)

**Comment by jpstroop** [comment]
Yay!

**Comment by tampakis** [comment]
Reopened because of right-to-left script issues:
![rtl_text_wrapping](https://cloud.githubusercontent.com/assets/4650153/10619629/a2df6a16-7744-11e5-8d5d-51656e37168b.png)

**Comment by tampakis** [comment]
Two fixed width columns
