### ISSUE TITLE
[Orangelight/production] NoMethodError: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#2926]
## Backtrace

    line 97 of [PROJECT_ROOT]/app/controllers/requests/request_controller.rb: sanitize_submission
    line 44 of [PROJECT_ROOT]/app/controllers/requests/request_controller.rb: submit
    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/84837051)

https://catalog.princeton.edu/requests/submit.js

https://catalog.princeton.edu/requests/99599773506421?mfhd=22486663390006421

**Comment by christinach** [comment]
The item was removed a while ago. The record had to be deleted. 
@mzelesky removed it. It will be removed from the catalog in the next incremental dump from alma.
