### ISSUE TITLE
Request form errors

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/orangelight#2929]
https://catalog.princeton.edu/requests/99125453129606421?mfhd=22917265440006421
![Screen Shot 2022-03-23 at 12 25 18 PM](https://user-images.githubusercontent.com/1599081/159748270-3b5fca0f-1019-42aa-af24-b6f63f1e9fee.png)

If the temporary location is sent as a mfhd the form does not error, but also does not work correctly: https://catalog.princeton.edu/requests/99125453129606421?mfhd=arch$newbook

**Comment by christinach** [comment]
This issue somehow is half fixed. Check this example in catalog-staging. We have set it in the alma sandbox to be in a temporary location and I reindexed it in catalog-staging to reflect the temp location which is arch$la. 
https://catalog-staging.princeton.edu/catalog/99105816503506421/raw
```
"holdings_1display": "{\"22514405180006421\":{\"location_code\":\"arch$stacks\",\"location\":\"Stacks\",\"library\":\"Architecture Library\",\"call_number\":\"NA682.B7 S673 2017b\",\"call_number_browse\":\"NA682.B7 S673 2017b\",\"items\":[{\"holding_id\":\"22514405180006421\",\"enumeration\":\"vol.2\",\"id\":\"23514405170006421\",\"status_at_load\":\"1\",\"barcode\":\"32101103846810\",\"copy_number\":\"0\"}],\"location_has\":[\"[1]-[2]\"],\"supplements\":[],\"indexes\":[]},    
\"arch$la\":{\"location_code\":\"arch$la\",\"current_location\":\"Librarian's Office\",\"current_library\":\"Architecture Library\",\"call_number\":\"NA682.B7 S673 2017b\",\"call_number_browse\":\"NA682.B7 S673 2017b\",
\"items\":   
[{\"holding_id\":\"22514405160006421\",\"enumeration\":\"vol.1\",\"id\":\"23514405150006421\",\"status_at_load\":\"1\",\"barcode\":\"32101103663520\",\"copy_number\":\"0\"}]}}"
```

visit https://catalog-staging.princeton.edu/requests/99105816503506421?mfhd=22514405160006421

The form displays with the item.
the response from https://bibdata-staging.princeton.edu/bibliographic/availability.json?deep=true&bib_ids=99105816503506421

```{
"99105816503506421": {
"arch$la": {
"on_reserve": "N",
"location": "arch$la",
"label": "Architecture Library - Librarian's Office",
"status_label": "Available",
"copy_number": null,
"cdl": false,
"temp_location": true,
"id": "arch$la"
},
"22514405180006421": {
"on_reserve": "N",
"location": "arch$stacks",
"label": "Architecture Library - Stacks",
"status_label": "Available",
"copy_number": null,
"cdl": false,
"temp_location": false,
"id": "22514405180006421"
}
}
}
```

https://bibdata-staging.princeton.edu/bibliographic/99105816503506421/holdings/22514405160006421/availability.json

```
[
{
"barcode": "32101103663520",
"id": "23514405150006421",
"holding_id": "22514405160006421",
"copy_number": "0",
"status": "Available",
"status_label": "Item in place",
"status_source": "base_status",
"process_type": null,
"on_reserve": "N",
"item_type": "Gen",
"pickup_location_id": "arch",
"pickup_location_code": "arch",
"location": "arch$la",
"label": "Architecture Library - Librarian's Office",
"description": "vol.1",
"enum_display": "vol.1",
"chron_display": "",
"in_temp_library": true,
"temp_library_code": "arch",
"temp_library_label": "Architecture Library - Librarian's Office",
"temp_location_code": "arch$la",
"temp_location_label": "Architecture Library - Librarian's Office"
}
]
```

I am able to place an 'Electronic Delivery' but not a `Physical Delivery`. I will look into the Physical Delivery issue.

**Comment by christinach** [comment]
![Screen Shot 2022-04-08 at 3 33 28 PM](https://user-images.githubusercontent.com/9905193/162511935-85799735-3d8a-4aff-ace2-343629070d85.png)

**Comment by christinach** [comment]
![Screen Shot 2022-04-08 at 5 27 56 PM](https://user-images.githubusercontent.com/9905193/162534987-a19613f7-339b-4a75-8275-eb554e1ae1bb.png)
This is the form that displays for a temp holding. It doesn't error but does not list the items. Earlier I was testing the form in staging but staging was still looking pulsearch_base of production. I opened https://github.com/pulibrary/orangelight/pull/2941/files to fix this and test the form accordingly.

**Comment by christinach** [comment]
![Screen Shot 2022-04-08 at 6 06 50 PM](https://user-images.githubusercontent.com/9905193/162538346-072a957d-92ce-4a68-93a4-14c4f866ee04.png)
I'm able to return the item
