### ISSUE TITLE
[Orangelight/production] ActionView::Template::Error: undefined method `to_sym' for ["0", "Mendel Music Library"]:Array

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#2942]
/app/helpers/application_helper.rb:389:in `block in render_location_code
def render_location_code(value)

388 | values = Array(value).map do \|loc\|
389 | location = Bibdata.holding_locations[loc.to_sym]
390 | location.nil? ? loc : "#{loc}: #{location_full_display(location)}"
391 | end

https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&f%5Baccess_facet%5D%5B0%5D=Online&f1=all_fields&f2=author&f3=title&op2=AND&op3=AND&q1=Tchaikovsky&q2&q3&range%5Bpub_date_start_sort%5D%5Bbegin%5D&range%5Bpub_date_start_sort%5D%5Bend%5D&search_field=advanced&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&f_inclusive%5Bformat%5D%5B0%5D=Audio&f_inclusive%5Badvanced_location_s%5D%5B0%5D=Mendel+Music+Library&f_inclusive%5Badvanced_location_s%5D%5B1%5D=elf1&commit=Search

https://app.honeybadger.io/projects/54399/faults/84908397

**Comment by maxkadel** [comment]
Another example url

https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&f2=author&f3=title&op2=AND&op3=AND&q1=Cello+Suite+No.+3+in+C+Major%2C+BWV+1009&q2=bach&q3&range%5Bpub_date_start_sort%5D%5Bbegin%5D&range%5Bpub_date_start_sort%5D%5Bend%5D&search_field=advanced&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&f_inclusive%5Bformat%5D%5B0%5D=Audio&f_inclusive%5Badvanced_location_s%5D%5B0%5D=Mendel+Music+Library&f_inclusive%5Badvanced_location_s%5D%5B1%5D=Online&commit=Search
