### ISSUE TITLE
Can we remove voyager_api_base and voyager_ub_id

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2947]
https://github.com/pulibrary/orangelight/blob/37a4a88ae8870822947b436e60bceecae7e549ef/config/requests.yml#L6

https://github.com/pulibrary/orangelight/blob/37a4a88ae8870822947b436e60bceecae7e549ef/config/requests.yml#L22

https://github.com/pulibrary/orangelight/blob/37a4a88ae8870822947b436e60bceecae7e549ef/config/requests.yml#L26

**Comment by sandbergja** [comment]
Check to make sure there are no old tests that use these values/logic.

**Comment by kevinreiss** [comment]
Yes, these serve no purpose any longer.
