### ISSUE TITLE
Printing records

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#296]
From Marvin:

> I see there is no obvious way for a user to Print a record. Could use a Print button
>
> Lots of other options, but not print

**Comment by jpstroop** [comment]
Maybe a print css?

**Comment by tampakis** [comment]
Related to #77.

**Comment by axapu** [comment]
Yes. Add print css that prints out main content/record.

**Comment by tampakis** [comment]
![print-css](https://cloud.githubusercontent.com/assets/4650153/10896625/2b209b4a-8189-11e5-9aa8-8363847e577f.png)

I'm not sure what to do with the availability panel. At first I was thinking it should have its own row, but now I'm thinking we should hide it completely. When a record has a call number/holding location it will be included with the rest of the bibliographic info. That's probably the bit that the user cares about anyway and the availability panel would be redundant.

Maybe (re)moving will fix the alingment issue with some of the other dl labels.
