### ISSUE TITLE
Review WAF for bots errors

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2961]
Errors from bots appear very often in honeybadger. example [85044560](https://app.honeybadger.io/projects/54399/faults/85044560)

 Mozilla/5.0 (compatible; PaperLiBot/2.1; https://support.paper.li/hc/en-us/articles/360006695637-PaperLiBot)

It would be nice if we knew how to investigate this in Signal Sciences. https://dashboard.signalsciences.net/corps/pu_library/overview

@kayiwa maybe we could schedule a training session?

**Comment by sandbergja** [comment]
renamed this ticket, since we are using the NGINX WAF now

**Comment by kevinreiss** [comment]
Discuss on the next Friday Check-in with ops team.

**Comment by kevinreiss** [comment]
Discuss current WAF capabilities with @kayiwa and @acozine.

**Comment by kevinreiss** [comment]
Looking at new WAF that devs can interact with being up this summer (June).
