### ISSUE TITLE
Text messages not sending call number

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#297]
From Marvin:

> Also, the SMS option does not fully work.
>
> I used that to send the record to my mobile…I did get an SMS message, but only with Title and Author. No call number.

**Comment by jpstroop** [comment]
This is probably related to #289

**Comment by tampakis** [comment]
The problem with the text messages is that it has the same format as the e-mail, but it gets cut off after the first 140 characters.

**Comment by tampakis** [comment]
send call number before title.

**Comment by kevinreiss** [comment]
Blacklight 6.x has re-factored the location of the SMS (and email) templates.
