### ISSUE TITLE
Purge ETAS code from requests codebase

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#2973]
Search for methods that reference "etas".

**Comment by maxkadel** [comment]
Etas / hathi code was removed from bibdata under https://github.com/pulibrary/bibdata/issues/1209

**Comment by sandbergja** [comment]
Check requests for tests that check both etas and something else.  Be cautious with the tests and make sure we don't lose any test coverage.

**Comment by christinach** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DACS-Maintenance-5da0db919c4ddf0001b2eb92/issues/pulibrary/orangelight/2973?planning-poker) with Zenhub @sandbergja @rladdusaw @kevinreiss @regineheberlein @maxkadel
