### ISSUE TITLE
Remove references to voyager

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/orangelight#2980]
https://github.com/pulibrary/orangelight/search?q=voyager
Related #2947

**Comment by sandbergja** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DACS-Maintenance-5da0db919c4ddf0001b2eb92/issues/pulibrary/orangelight/2980?planning-poker) with Zenhub @regineheberlein @christinach @maxkadel @rladdusaw
