### ISSUE TITLE
Search results - CDL result does not display an 'Online' label next to the availability status.

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2995]
Based on the JS code, CDL records in the search results, should display an 'Online' label next to the availability status. Do we still want to do that?

Example record https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=99125464716806421

We will discuss this on Thursday 05-12-2022 (Orangelight meeting)
question came in https://faq.library.princeton.edu/admin/ticket?qid=9414780

**Comment by christinach** [comment]
@kevinreiss @mzelesky  I checked this record again and noticed that the availability response returns that **it is not** on cdl, `cdl: false`. This is why the extra blue online badge is not there. https://bibdata.princeton.edu/bibliographic/availability.json?deep=true&bib_ids=99125464716806421
{
"99125464716806421": {
"22919898220006421": {
"on_reserve": "N",
"location": "firestone$pf",
"label": "Firestone Library - Remote Storage (ReCAP): Firestone Library Use Only",
"status_label": "Unavailable",
"copy_number": null,
"cdl": false,
"temp_location": false,
"id": "22919898220006421"
}
}
}

I think we need to look in alma and make sure that this item is in the type of order controlled digital lending and if not to update it.

**Comment by mzelesky** [comment]
In Alma, the only item on that bib is indeed in the CDL work order.

**Comment by mzelesky** [comment]
So something is happening with the availability call.

**Comment by christinach** [comment]
Thank you for checking @mzelesky . I will check

**Comment by mzelesky** [comment]
When I just clicked the link above, it gave cdl:true.

**Comment by christinach** [comment]
yeah you are right. I dont know what's going on. I copied the response from the webpage like I did with this one.
{
"99125464716806421": {
"22919898220006421": {
"on_reserve": "N",
"location": "firestone$pf",
"label": "Firestone Library - Remote Storage (ReCAP): Firestone Library Use Only",
"status_label": "Unavailable",
"copy_number": null,
"cdl": true,
"temp_location": false,
"id": "22919898220006421"
}
}
}

**Comment by kevinreiss** [comment]
@mzelesky @christinach Would there be any way to include a flag in the data we index that denotes something is on CDL rather than trying to deal with this information in real-time?

**Comment by christinach** [comment]
for the search results see https://github.com/pulibrary/orangelight/blob/90434bd3b056390d50e8d3d0a3a4e1583ed6941f/app/javascript/orangelight/availability.es6#L168 

https://github.com/pulibrary/orangelight/blob/90434bd3b056390d50e8d3d0a3a4e1583ed6941f/app/javascript/orangelight/availability.es6#L134

https://github.com/pulibrary/orangelight/blob/90434bd3b056390d50e8d3d0a3a4e1583ed6941f/app/javascript/orangelight/availability.es6#L369

**Comment by christinach** [comment]
When closing this ticket. Follow up with Joann: https://faq.library.princeton.edu/admin/ticket?qid=9414780

**Comment by ellen-aa** [comment]
The results page is misleading for a user. Instead of displaying "Unavailable", could this display "Available for digital checkout"?

**Comment by christinach** [comment]
@ellen-aa this is a great suggestion. I will add this as an item for discussion in the [Orangelight agenda](https://docs.google.com/document/d/1GxpYrcRc6w3kMFU1XU6CEpnumFzvxFrj2GkCq_XvoWw/edit#heading=h.45hpkgtqrqze)

**Comment by kevinreiss** [comment]
Unclear if we will continue to support CDL features. Review this again when we have clarity.

**Comment by christinach** [comment]
CDL has been removed. All items that were in CDL show now as unavailable.
