### ISSUE TITLE
Add Rails and webpacker to lando 

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/orangelight#2996]
Can we move the rails and webpacker steps into lando so we do not need to add them separately?

Maybe include https://github.com/francoisvdv/lando-mutagen based on @maxkadel previous experience.  It can make running the application faster in a docker container.

**Comment by kevinreiss** [comment]
Is this something we would like to do?

**Comment by christinach** [comment]
we dont use webpacker anymore. We've replaced it with vite. If needed create a new ticket for vite and lando.
