### ISSUE TITLE
OL Feedback Form Spam

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3004]
There has been uptick in spam generated from the OL feedback form resulting in tickets in libanwers from obvious bot submissions. The current form has no spam protections. Need to investigate options that might be able to afford it some protection from this sort of abuse.

**Comment by kevinreiss** [comment]
Do we still have sensu available to us? If anyone has any past experience in this space it would be helpful to hear your experience.

**Comment by sandbergja** [comment]
Noting that there is a honeypot on this form.  Steps to exercise the honeypot:

1. Open mailcatcher using the instructions in the README
2. Go to https://catalog-staging.princeton.edu/feedback
3. Fill out the form and submit
4. Note that an outgoing email to libanswers appears in the mailcatcher.
5. Go back to https://catalog-staging.princeton.edu/feedback
6. Apply this CSS rule in your browser to make the honeypot field appear:
```
.blacklight-feedback-hidden {
  display: block;
}
```
7. Fill out the whole form, including the honeypot field, and submit
8. Note that the form gives you a success message, but no email appears in the mailcatcher.

So we need to focus on the spam is not fooled by the honeypot.

**Comment by sandbergja** [comment]
While spam occasionally comes through this form, the majority of spam in our queue comes from emails sent directly to the libanswers.com email address.  I wonder if we can close this ticket.

**Comment by sandbergja** [comment]
Closing, but we should try to find where spammers are getting that email address.
