### ISSUE TITLE
Should we send HTML email to work around Safelinks URL mangling?

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#3011]
Incoming email to Princeton recipients is now processed by Microsoft's Safelinks feature that rewrites URLs behind a redirect script that will prevent accessing known-malicious sites. The behavior differs between HTML and plaintext email:
* In plaintext email, the link is changed directly, so the link is obviously changed and difficult to read
* In HTML email, the href attribute is changed, but the displayed URL is not changed (so the user may not even notice the change). See: https://langbein.org/microsoft-outlook-office365-url-rewriting-in-e-mails/

Should we send HTML email to avoid this problem?

**Comment by christinach** [comment]
@escowles can you provide an example of this email?

**Comment by escowles** [comment]
I tried to reproduce this today and did not see the Safelinks in emails sent by Orangelight to my Princeton email address. I think campus has disabled the behavior, at least for email coming from Princeton senders/hosts. So I'm closing this issue, since it looks like the problem has been resolved.
