### ISSUE TITLE
Different Book Covers API

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#304]
I'm hitting rate limits in local development already (mostly because of trying to add book covers to search results). Further, it turns out there are branding guidelines to using google books which we may not want to deal with: https://developers.google.com/books/branding

**Comment by jpstroop** [comment]
I heard back from Bowker. Docs are here:

http://corpweb.proquest.com/docs/syndeticsstarterdocument.pdf

**Comment by jpstroop** [comment]
SUL is definitely using Google: http://searchworks.stanford.edu/?utf8=%E2%9C%93&search_field=search&q=cage+silence

Are they breaking terms or ?

**Comment by cbeer** [comment]
Paging @jkeck?

**Comment by tpendragon** [comment]
Mostly concerned about what the requirements are around https://developers.google.com/books/branding and using just thumbnails.

**Comment by jkeck** [comment]
We are linking out in most cases, there is a bug right now (that we plan on addressing in an upcoming round of development) that is preventing the block that we have the google linking/attribution from rendering under certain conditions. (our GBS code is sub-optimal to say the least).

**Comment by tpendragon** [comment]
@jkeck What's the attribution look like?

**Comment by jkeck** [comment]
Example: http://searchworks.stanford.edu/view/10916374

**Comment by tpendragon** [comment]
Using the dynamic API in Google now, which should have fewer rate limit problems. Attribution may still be an issue, it's unclear if it matters since we're not using preview functionality.

**Comment by jpstroop** [comment]
See also #703 (nearly a dupe)
