### ISSUE TITLE
Safari issue - JS:focus transfer loop

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3040]
There is some sort of bug wherein a user in Safari holding down Tab to hurry through the fields ends up highlighting two different things at once, with a JS :focus transfer loop continously cycling between them and trapping the cursor. It is possible to back out of the loop by holding down shift+tab.

Suggestion:
Add some sort of loop detection or delay to whatever script is moving focus.

WCAG Guidelines:
https://www.w3.org/WAI/WCAG21/quickref/#no-keyboard-trap

**Comment by rladdusaw** [comment]
This is not a bug it's a "feature" of Safari. To tab through all elements of a page you have to enable "Press tab to highlight each item on a webpage" on the advanced tab in the settings.
