### ISSUE TITLE
For items that are in resource sharing change the status in the Request form to be Not Available

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3044]
For items that are in resource sharing change the status in the Request form to be `Not Available`.
Remove the `- Resource sharing Request`.

<img width="1272" alt="Screen Shot 2022-06-15 at 1 01 59 PM" src="https://user-images.githubusercontent.com/9905193/173884441-fef8e8c1-c550-4145-8740-7782df3acc69.png">

**Comment by kevinreiss** [comment]
Pull a current example from Alma to confirm what the current behavior is.
