### ISSUE TITLE
Alma Affiliate Account Users are submitting requests with invalid barcodes

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3045]
We have had at least four instances where an affiliate account that has more than one barcode in the patron record has submitted an old, invalid barcode for a ReCAP request rather than the active barcode on the record. When checked the "patron" route in bibdata does return the active barcode. Further investigation is needed. Possible steps in order of what might be likelihood of the problem source. 

1. Look at the raw alma api response for the patrons in question and see those do seem to consistently report the active barcode or if there are instances where an invalid barcode is returned as the active barcode intermittently.
2. Review the code in bibdata that parses the api response to see if something there that might cause the issue when the api response is parsed: https://github.com/pulibrary/bibdata/blob/main/app/controllers/patron_controller.rb#L54. 
3. Look at if there is anything with how SCSB validates a patron record that might cause this. Would have to reach out to HTC (the recap vendor) to ask them to dig into an example record. 

@kevinreiss can provide an example patron record.

**Comment by kevinreiss** [comment]
I looked a bit at the alma response. It includes all barcodes on a patron's record, both active and inactive. 

The structure looks like this in JSON

```{
      "value": "22101xxxxxxx37",
      "id_type": {
        "value": "BARCODE",
        "desc": "Barcode"
      },
      "note": "02 Sep 2015",
      "status": "INACTIVE",
      "segment_type": "Internal"
    },
    {
      "value": "22101xxxxxxx47",
      "id_type": {
        "value": "BARCODE",
        "desc": "Barcode"
      },
      "note": "01 Mar 2016",
      "status": "ACTIVE",
      "segment_type": "Internal"
    },```

The "incorrect" inactive barcode we are seeing show up in the patron request in SCSB appears to be the first barcode that appears in the identifiers array in the Alma API user response, https://developers.exlibrisgroup.com/alma/apis/docs/users/R0VUIC9hbG1hd3MvdjEvdXNlcnMve3VzZXJfaWR9/. I cannot see that the bibdata patron route ever sends back the incorrect inactive barcode though so I'm still unclear how the request form is passing over the incorrect barcode.

**Comment by maxkadel** [comment]
Tested the bibdata behavior on PR https://github.com/pulibrary/bibdata/pull/1909 . 

Also, in investigating an example user, I found that they had two User objects in the Orangelight database - one was connected to their patron_id, and the other was connected to their currently active barcode. I was not able to find any attached to previous barcodes.

```bash
irb(main):004:0> User.find_by(uid: patron_id)
=> #<User id: random_number_2, email: "", created_at: "2022-06-14 23:57:32", updated_at: "2022-06-15 23:28:08", provider: "alma", uid: patron_id, username: patron_id, guest: false>
irb(main):005:0> User.find_by(uid: inactive_barcode)
=> nil
irb(main):006:0> User.find_by(uid: active_barcode)
=> #<User id: random_number_1, email: active_barcode, created_at: "2017-08-12 21:09:51", updated_at: "2022-06-15 15:32:13", provider: "barcode", uid: active_barcode, username: first_name_of_user, guest: false>
```
