### ISSUE TITLE
URI::InvalidURIError in errors # error 

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3046]
Honeybadger link: https://app.honeybadger.io/projects/54399/faults/85258949

In https://github.com/pulibrary/orangelight/blob/2656fb0ad6c2c1a6baf282d2290d749c93c85758/app/controllers/users/omniauth_callbacks_controller.rb#L36:

```
    def alma
      if Alma::User.authenticate(user_id: alma_params[:username], password: alma_params[:password])
        @user ||= User.from_alma(access_token_in_request_params)
        @user.save
```

My guess is that the spaces are being passed without being url-encoded.

**Comment by christinach** [comment]
URI::InvalidURIError: bad URI(is not URI?): "https://api-na.hosted.exlibrisgroup.com/almaws/v1/users/Antonia Lenilma Meneses de andrade"
URI::InvalidURIError: bad URI(is not URI?): "https://api-na.hosted.exlibrisgroup.com/almaws/v1/users/Prasanta " 
URI::InvalidURIError: bad URI(is not URI?): "https://api-na.hosted.exlibrisgroup.com/almaws/v1/users/ BC002370427"
URI::InvalidURIError: bad URI(is not URI?): "https://api-na.hosted.exlibrisgroup.com/almaws/v1/users/ BC002370427" 
URI::InvalidURIError: bad URI(is not URI?): "https://api-na.hosted.exlibrisgroup.com/almaws/v1/users/CARMEN VENTURA" 

URI::InvalidURIError: bad URI(is not URI?): "https://api-na.hosted.exlibrisgroup.com/almaws/v1/users/Antonia Lenilma Meneses de andrade"
(https://app.honeybadger.io/projects/54399/faults/85258949/01G9QR5EJCYQ59GR5D8BHP49GF?page=0)
URI::InvalidURIError: bad URI(is not URI?): "https://api-na.hosted.exlibrisgroup.com/almaws/v1/users/Prasanta "
(https://app.honeybadger.io/projects/54399/faults/85258949/01G9Q6HHEP0733P8BYZ98Q2KK3?page=0)
URI::InvalidURIError: bad URI(is not URI?): "https://api-na.hosted.exlibrisgroup.com/almaws/v1/users/ 
(https://app.honeybadger.io/projects/54399/faults/85258949/01G9Q6EGZZME3R30MHF85N95D1?page=0)
URI::InvalidURIError: bad URI(is not URI?): "https://api-na.hosted.exlibrisgroup.com/almaws/v1/users/ 
(https://app.honeybadger.io/projects/54399/faults/85258949/01G9GD3PF94D5EZC61ESQPN1FQ?page=0)
URI::InvalidURIError: bad URI(is not URI?): "https://api-na.hosted.exlibrisgroup.com/almaws/v1/users/CARMEN VENTURA"

**Comment by christinach** [comment]
https://app.honeybadger.io/projects/54399/faults/87346313

same error on catalog-qa
