### ISSUE TITLE
NoMethodError in selected_items_validator

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3052]
Honeybadger link: https://app.honeybadger.io/projects/54399/faults/84900330

https://catalog.princeton.edu/requests/9912046983506421?mfhd=22600685930006421

This line is erroring: https://github.com/pulibrary/orangelight/blob/2656fb0ad6c2c1a6baf282d2290d749c93c85758/app/models/requests/selected_items_validator.rb#L37

Backtrace:
```
NoMethodError: undefined method `errors' for #<Array:0x00007f87f4973fa0>

[PROJECT_ROOT]/app/models/requests/selected_items_validator.rb:37 :in `validate_selected`
          validate_pick_up_location(record, selected, selected["type"])
        else
          record.errors[:items] << { selected['mfhd'] => { 'text' => 'Please choose a Request Method for your selected item.', 'type' => 'pick_up' } }
        end
      end
```

**Comment by maxkadel** [comment]
Similar (possibly the same?) error happening in https://app.honeybadger.io/projects/54399/faults/85031385
