### ISSUE TITLE
NoMethodError in errors # error

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/orangelight#3068]
https://app.honeybadger.io/projects/54399/faults/86723612

[PROJECT_ROOT]/app/models/requests/patron.rb:217:in `build_cas_patron'
215 |  
216 | patron_resource = JSON.parse(api_response.body)
217 | patron_resource.with_indifferent_access
218 | end
219 | end

**Comment by christinach** [comment]
duplicate of #3054
