### ISSUE TITLE
NoMethodError in rake assets:precompile

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/orangelight#3069]
Error on Orangelight staging: https://app.honeybadger.io/projects/54399/faults/86731451

[PROJECT_ROOT]/config/initializers/alma.rb:6:in `block in <top (required)>'
5 | Alma.configure do \|config\|
6 | config.apikey = Rails.configuration.alma[:read_write_apikey]
7 |  
8 | # Alma gem defaults to querying Ex Libris's North American API servers. You can override that here.

**Comment by rladdusaw** [comment]
Stack trace: https://gist.github.com/pulbot/90181d724730b8d7e5a13668ca8da63a

**Comment by maxkadel** [comment]
This was due to testing a branch. Closing.
