### ISSUE TITLE
Make it clearer that you can also pick up materials from the shelf

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3075]
### Current display

On the record show page, we prominently show the request buttons, but don't make it clear that many items can be used without first requesting it.

### Desired display

From a conversation with Joan, we should also make it clear that you don't _have_ to place a request.  You can also just go to the shelf, pick it up, and take it to circulation to check it out.

### Acceptance criteria

- [x] Create wireframes in Figma and get approval from POs and the team
   - [x] It is clear from the catalog record show page that you can request an item OR use it directly
   - [x] It is clear when you can't use an item without first requesting it (e.g. aeon items in special collections)

**Comment by christinach** [comment]
Create wireframes and show them to Joan. @carolyncole suggests move 'where to find it' link closer to the 'Request ' button for more parity.

**Comment by sandbergja** [comment]
Maybe we can take some inspiration from this kind of display, which includes a pickup and delivery option:
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/7086943/180839375-1c026b88-e906-44d2-90af-371c70efdbee.png">

Also, I remember that part of the issue is that patrons may be coming from closed stacks libraries, and don't realize that Princeton allows people to pick up materials from the shelf.

**Comment by christinach** [comment]
We will follow up on tis ticket with AUX

**Comment by ellen-aa** [comment]
Carol and I would like to discuss this with the team, particularly how best to get the user testing that would allow us to move forward.

**Comment by rladdusaw** [comment]
I've created some wireframes for a couple of options https://www.figma.com/design/BTU6c0uNhVFf4wLgB5p8BC/Orangelight-PO-workcycle?node-id=0-1&node-type=canvas&t=rxB9IEVeVMN6HD9r-0

**Comment by kevinreiss** [comment]
@ellen-aa @caroldh when you all have a chance could you give a quick look at the wireframes in the last comment. Thanks.

**Comment by ellen-aa** [comment]
@kevinreiss @rladdusaw , Beth German is taking a look from a UX perspective. More soon!

**Comment by caroldh** [comment]
@rladdusaw - I need some clarification. What do you mean by the "first" option? Am I understanding correctly that there are two options for each scenario - "available on shelf" and "by request only"? Is the "first option" the first one listed for each scenario?

**Comment by caroldh** [comment]
@rladdusaw - @ellen-aa  and @caroldh viewed the wireframe options and commented in Figma

**Comment by sandbergja** [comment]
We will talk about this in today's Orangelight meeting.  Before then, please [review the figma wireframes and the comments on them.](https://www.figma.com/design/BTU6c0uNhVFf4wLgB5p8BC/Orangelight-PO-workcycle?node-id=0-1&node-type=canvas&t=rmCDFWBGqQ6ofKwW-0)

**Comment by kevinreiss** [comment]
Stackmaps button should have same look, color scheme, etc. as the request button.  It should be on the same line as the request button.  It should have the text “Find on shelf” (Option 1 in the first group)

**Comment by christinach** [comment]
closing in favor of https://github.com/pulibrary/orangelight/issues/4453
