### ISSUE TITLE
Display homosaurus subject headings

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3078]
User story 1: as a catalog user, I would like to search for records using terms in the homosaurus vocabulary.
User story 2: as a catalog user, I would like to see homosaurus vocabulary terms display in record show pages.

@kevinreiss is going to get some more clarity and prioritization of this ticket.

- [x] https://github.com/pulibrary/orangelight/issues/3092

- [ ] Companion ticket in bibdata: https://github.com/pulibrary/bibdata/issues/1925
- [ ] Companion ticket in pul_solr: https://github.com/pulibrary/pul_solr/issues/340

**Comment by christinach** [comment]
Sara Howard and Sarah Hamerman provided positive feedback on the wireframe https://xd.adobe.com/view/a27a67e6-1cc3-4c27-a2b6-c67cff0e2e9f-f729/. When we implement the changes we should provide a staging or a qa url for them to review. If everything looks ok we need to run a full reindex to index all the additional terms from alma.
