### ISSUE TITLE
Can't unbookmark after bookmarking all

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#308]
I checked "Bookmark All" and then unchecked it, and started getting alert boxes that just said "Error", and some items--a seemingly random subset--were not unchecked. I am unable to uncheck them individually as well. Here's the console output:

![screenshot from 2015-10-19 08 50 24](https://cloud.githubusercontent.com/assets/999701/10578278/2933bdbc-763f-11e5-8c9a-9ab6675a8e39.png)

**Comment by tpendragon** [comment]
Probably need to implement a timer to wait for the sub-boxes to actually be checked

**Comment by axamei** [comment]
This appears to have fixed itself.
