### ISSUE TITLE
Cannot open advanced search on catalog-staging

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#3080]
```
[PROJECT_ROOT]/app/services/bibdata.rb:49:in `holding_locations'

      # don't cache if we didn't get a success
      response = Faraday.get("#{Requests.config['bibdata_base']}/locations/holding_locations.json")
      return {} unless response.status == 200
```

The error seems to be occurring when we are trying to connect to the bibdata-staging server

https://app.honeybadger.io/projects/54399/faults/86938594

Per @kayiwa, some utilities mark the certificates as good, others mark them as bad.

**Comment by kayiwa** [comment]
Fixed by this https://github.com/pulibrary/princeton_ansible/pull/3158
