### ISSUE TITLE
Constituent part(s) and Related record(s) fields largely duplicate one another

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3082]
**Expected behavior**
Each constituent record is listed once on a host record's show page

**Actual behavior**
The first ten constituent records are listed twice on a host record's show page: first as a link in the "Related record(s)" field, then as plain text in the "Constituent part(s)" field.

**Steps to replicate**

Go to https://catalog.princeton.edu/catalog/99124945733506421 and look at the two fields.

**Impact of this bug**

More cluttered look on the show page.  For records with a viewer, this pushes the viewer even farther down below the fold.

**Additional info**

Both are taken from the 774 field:

- related record field uses the MMS ID from the 774$w in a solr call to fetch the title from the constituent record
- Constituent parts field uses the metadata directly from the 774 in the host record

**Comment by maxkadel** [comment]
From `app/controllers/catalog_controller.rb`

```ruby
config.add_show_field 'related_record_s', label: 'Related record(s)', link_field: 'id'
...
config.add_show_field 'constituent_part_display', label: 'Constituent part(s)' 
```

I'm still not sure what we want to be displayed on the show page. It seems like the specific type of relationship is important to represent (that these particular related records are "constituent part" related records).

**Comment by maxkadel** [comment]
From notes:

```
Duplicative display on host records https://github.com/pulibrary/orangelight/issues/3082
Example from the ticket: https://catalog.princeton.edu/catalog/99124945733506421 
Partner records might not link properly?
Possible choices
Make constituent parts linkable 
Only display Constituent Parts, default to links, but in the rare case where the mms_id cannot be found in Solr, display only the id
Similar issue with “Contained in” and “In”
Suggested: Only keep “Contained in”, remove “In”. Display link when possible, when not possible, only show title.  Makes sense to start with just 773 and 774.
Action Item: write proposal to re-factor Related Records/Constituent Parts into the same display section with hyperlinks. Kevin R. will draft ticket. 
```

**Comment by maxkadel** [comment]
On staging, it looks like this doesn't work on 5 SCSB records:

- SCSB-9588344
- SCSB-5715787
- SCSB-6740416
- SCSB-9401911
- SCSB-8915880
