### ISSUE TITLE
Update Empty Results Screen to Use New Borrow Direct Interface

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3091]
When one executes a search with no results we present a screen encouraging folks to try a search in borrow direct. 
<img width="1627" alt="Screen Shot 2022-07-29 at 3 07 38 PM" src="https://user-images.githubusercontent.com/278825/181835893-cfe9a82a-b040-4caa-b569-1acdf4cbcece.png">

The link to borrow should be updated to the new re-share discovery interface. We current pass the query over in context. It appears we should be able to do that with a link template that looks like:

https://borrowdirect.reshare.indexdata.com/Search/Results?lookfor={query_value}&type=AllFields

**Comment by maxkadel** [comment]
example - https://borrowdirect.reshare.indexdata.com/Search/Results?lookfor=cats&type=AllFields

**Comment by maxkadel** [comment]
This should be done behind a feature flipper

**Comment by christinach** [comment]
If the user is using the subject search, we would pass the search to this interface. subject or author or title example https://borrowdirect.reshare.indexdata.com/Search/Results?lookfor=Dogs+Egypt+History.&type=Subject&limit=20
