### ISSUE TITLE
Deprecate borrow-direct Route

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3094]
When the current Borrow Direct Relais platform we can deprecate all code behind the "borrow-direct" route that authenticates users and passes them over to the current Borrow Direct Search interface. Once this happens we move #3087 into main branch.

**Comment by christinach** [comment]
The new Borrow direct interface: https://borrowdirect.reshare.indexdata.com/

**Comment by christinach** [comment]
THe url is referred in the footer library website, catalog. We can redirect the old link to the new interface https://borrowdirect.reshare.indexdata.com/

**Comment by kevinreiss** [comment]
Complete ticket #3091 prior to completing this one.
