### ISSUE TITLE
Document the different ways orangelight communicates with figgy to retrieve the viewer. 

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3104]
I started drafting https://docs.google.com/document/d/1MiltehCL79gspKp_wd4k7Bqo3VXguV6aIN5Z5VoGK24/edit 

related issues:
https://github.com/pulibrary/bibdata/issues/505 Remove figgy ark cache?
https://github.com/pulibrary/bibdata/issues/1720 Figgy arks resolving to voyager ids instead of Alma ids.
https://github.com/pulibrary/bibdata/issues/1724 Indexing 856 content on records without anh holdings or portfolios.
https://github.com/pulibrary/bibdata/issues/770 Figgy ARK overrides shouldn't replace the 856 label with 'Digital content' if it's not a link.
https://github.com/pulibrary/bibdata/issues/1848 Update fragment to be viewer-container
https://github.com/pulibrary/orangelight/issues/2147 Default book/manuscript thumbnail misses the icon to navigate to the viewer.

**Comment by kevinreiss** [comment]
Still need to add documentation about Figgy-OL communications specific to CDL.

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/orangelight/pull/3144
