### ISSUE TITLE
Install flipflop gem to turn on and off features

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#3126]
**User story**
As a developer, I want to be able to easily turn on and off features without needing to deploy code.

**Concrete example**
Sometimes we need to turn on / off features (e.g. when requests won't work, or switching BorrowDirect to the new provider

**Implementation note**
Possible gem to use: https://github.com/voormedia/flipflop

**Comment by sandbergja** [comment]
For this ticket, just install the gem, configure it, and possibly add a test feature to make sure you can turn features on/off as expected.

**Comment by maxkadel** [comment]
Closed with https://github.com/pulibrary/orangelight/pull/3134
