### ISSUE TITLE
Exception: Requests::Submission: Item does not have a delivery mode

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3127]
**Expected behavior**
We expect items to have a delivery mode

**Actual behavior**
Exception that item has not delivery mode

**Steps to replicate**
https://catalog.princeton.edu/requests/9923208643506421?mfhd=22670348320006421

[**Honeybadger link and code snippet, if applicable**](https://app.honeybadger.io/projects/54399/faults/87416546)

**Comment by christinach** [comment]
this was because of the scsb issue we had with the new api key. we restarted nginx and everything looks ok.

**Comment by christinach** [comment]
https://app.honeybadger.io/projects/54399/faults/87416546

**Comment by kevinreiss** [comment]
@christinach Can we close this ticket then? Or do we need to update our error handling?

**Comment by christinach** [comment]
@kevinreiss the error handling was added to track items that have no delivery mode. I opened it in case we want to track down the items and why they don't have a delivery mode. Do we need to create a report for circulation? Or was there another reason for raising this exception.

**Comment by rladdusaw** [comment]
The polling service had stopped running and the new location had not been updated in the index. Restarting the polling service resolved the issue.
