### ISSUE TITLE
Remove the Borrow Direct Gem

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3140]
Once we deactivate and then purge the features related to the old Relais integration for Borrow Direct we can remove the "borrow_direct" gem from the Project Gemfile.

**Comment by kevinreiss** [comment]
Blocked by #3091, #3093, #3094

**Comment by kevinreiss** [comment]
Leave in backlog until Relais has a sunset date later this fall.

**Comment by kevinreiss** [comment]
Move to blocked until new reshare implementation date.

**Comment by christinach** [comment]
We can unblock this now that we start using the new Reshare service.

**Comment by kevinreiss** [comment]
closing as we have actually removed this Gem already.
