### ISSUE TITLE
Route Requests that have a SCSB API Error to ReCAP Problems

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3142]
Currently when the availability call for SCSB does not provide any data we assume the items are "in-process". In-process means the items are filed in a ReCAP holding location but are not yet accessioned into the facility. We need to add a case that accounts for a scenario when the SCSB availability API produces an error. These items should not be treated as "in-process", but should instead be sent into our triage procedure for SCSB errors. For items in this case we accept the user's request for the item but route it to the recapproblems email address. This points in the code are useful reference points to track current behavior and see where we can make adjustments.

https://github.com/pulibrary/orangelight/blob/e9554b8bac6f51d08e4e4741aefb8e6704301b3b/app/models/requests/request.rb#L243

https://github.com/pulibrary/orangelight/blob/e9554b8bac6f51d08e4e4741aefb8e6704301b3b/app/models/requests/request.rb#L221

https://github.com/pulibrary/orangelight/blob/ddb644404b5471b5c7d263efc9f62be017ef0b1e/app/models/concerns/requests/scsb.rb#L54

**Comment by kevinreiss** [comment]
The SCSB api returns this when the api key that used is invalid for the request

< HTTP/2 401
< date: Wed, 17 Aug 2022 18:57:47 GMT
< content-length: 22
< set-cookie: AWSALB=8/TCKulRFRbiIarXnWGHb/WulOMkXWIkdd1oTqSxFM/807nj3YndBojFlaSlhSMV3npSYEPSHxfWy2sNFpwUiqkXkmvLr3isfjVNiVDeEf/YfbYCBHRHMtmkx9e/; Expires=Wed, 24 Aug 2022 18:57:47 GMT; Path=/
< set-cookie: AWSALBCORS=8/TCKulRFRbiIarXnWGHb/WulOMkXWIkdd1oTqSxFM/807nj3YndBojFlaSlhSMV3npSYEPSHxfWy2sNFpwUiqkXkmvLr3isfjVNiVDeEf/YfbYCBHRHMtmkx9e/; Expires=Wed, 24 Aug 2022 18:57:47 GMT; Path=/; SameSite=None; Secure
<
Authentication Failed
* Connection #0 to host scsb.recaplib.org left intact
* Closing connection 0

 curl --verbose -X POST "https://scsb-url/sharedCollection/itemAvailabilityStatus" -H "accept: application/json" -H "api_key: mykey -H "Content-Type: application/json" -d "{ \"barcodes\": [ \"abarcode" ]}"

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OrangelightBibdataRequests-571691cab409d8d821b873be/issues/pulibrary/orangelight/3142?planning-poker) with ZenHub @maxkadel @sandbergja @rladdusaw @regineheberlein

**Comment by maxkadel** [comment]
So, the behavior I'm seeing in development is that, with a bad api key, when I look at the "show" page, the item is marked as "Available", I click the "Request" button and it takes me to the "Help me get it" request page. 

With the same object in production, with a good API key, I get the ReCap request page. 

With the bad API key, do we want it to go to the ReCap request page, but then send the information to recap problems?
