### ISSUE TITLE
Requests::RequestHelper#zero_results_link tests flaky

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3148]
Example run with failures: https://app.circleci.com/pipelines/github/pulibrary/orangelight/2768/workflows/a68d8116-7222-4109-970d-1e40bb01ef56/jobs/6599

I wonder if the flipflop feature isn't being set reliably in our CI environment?

**Comment by maxkadel** [comment]
Nooo! I'll check this out.
