### ISSUE TITLE
JSON::Parser error

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/orangelight#3155]
**Expected behavior**

Should correctly handle a "request rejected" response.

**Actual behavior**
build_cas_patron is trying to parse an html "request rejected" response as JSON.

**Steps to replicate**
In an incognito window, follow 

https://catalog-staging.princeton.edu/requests/99125412083106421?mfhd=22906396720006421

and log in

**Impact of this bug**
Patrons get an error message when trying to log in

https://app.honeybadger.io/projects/54399/faults/87582063/01GB5EYTWAH8F9MW46JK1FGB3B?q=occurred.after%3A%227+days+ago%22#notice-trace

```
    return if api_response.nil?
    patron_resource = JSON.parse(api_response.body)
    patron_resource.with_indifferent_access
end
```

```
```

**Comment by kevinreiss** [comment]
If I understand this it appears Alma sends back HTML if the CAS patron who logs in does not have a matching record in the system

**Comment by kevinreiss** [comment]
I have an example patron who can be used to debug this issue.

**Comment by kevinreiss** [comment]
I notice this error lists catalog-staging not prod, is that correct?

**Comment by kevinreiss** [comment]
This page loads fine for me in prod when I'm logged in.

**Comment by regineheberlein** [comment]
Yes, the honeybadger error was limited to staging1 and staging2
