### ISSUE TITLE
Items in Holdings Management cannot be requested from ReCAP. 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3162]
In Alma this record is in the process type transit but is not yet accessioned into ReCAP. The Request it's trying is a standard recap request. I believe it should be treated as an item eligible for the "Resource Sharing" option when in it's in this state. 

Example form: https://catalog.princeton.edu/requests/9910859343506421?mfhd=22683272740006421

Error Response:

Type	recap
Bibid	9910859343506421
Item	["32101042046753"]
User Name	kr2
Barcode	22101008926206
Error	Item Barcode(s) not available in database.

1. Confirm with circ staff that these should be in process. 
2. Look into where the "Holdings Management" label is coming from. Is this an Alma Work Order?

**Comment by christinach** [comment]
It should display as 'Not Available'. Check the work order in (https://github.com/pulibrary/bibdata/blob/64c6a74c5bf234ce4d05060b2a4178d999a1825e/app/adapters/alma_adapter/alma_item.rb#L284)

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OrangelightBibdataRequests-571691cab409d8d821b873be/issues/pulibrary/orangelight/3162?planning-poker) with Zenhub @regineheberlein @rladdusaw @sandbergja

**Comment by maxkadel** [comment]
Alma search for examples:
* Go to advanced search
* Physical Items
* In Process Type equals Holdings Management

**Comment by maxkadel** [comment]
Closed by https://github.com/pulibrary/bibdata/pull/1981
