### ISSUE TITLE
Submit sitemap to google after our next full re-index

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3171]
Discussed at today's Orangelight/Bibdata meeting.  Since it's been a while since we've had a reliable sitemap, we should submit the new sitemap to Google Search Console when it is complete (i.e. after a full re-index)

**Comment by kevinreiss** [comment]
Trying to submit the sitemap.xml again.

**Comment by kevinreiss** [comment]
Failed to load, maybe a timeout

**Comment by kevinreiss** [comment]
Checking Google Search Console today it seems the sitemap is being crawled but roughly 8 out of 10 individual sitemap files fails to load when the crawl happens.

**Comment by kevinreiss** [comment]
superseded by ticket https://github.com/pulibrary/orangelight/issues/4019
