### ISSUE TITLE
Refactor user authentication to isolate and remove barcode users

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/orangelight#3182]
Devise is creating routes for barcode users that appear in other login methods: https://github.com/pulibrary/orangelight/blob/main/app/controllers/users/omniauth_callbacks_controller.rb#L44

Also multiple tests that are not specific to barcode users use the test barcode user and should be refactored to use a different test user: https://github.com/pulibrary/orangelight/blob/main/spec/controllers/omniauth_callbacks_controller_spec.rb#L113-L136

The barcode login form was removed in PR: https://github.com/pulibrary/orangelight/pull/3167

**Comment by kevinreiss** [comment]
A few other places where we can look at purging references to the barcode.

Campus_authorized is a deprecated feature from the pandemic, we can remove this method: https://github.com/pulibrary/orangelight/blob/3336eb7506facd8b34d8bae6ba3085eb2d65a1c7/app/models/requests/patron.rb#L56. 

Barcode users shouldn't be logging in any longer so we can remove it from this statement: https://github.com/pulibrary/orangelight/blob/c982bbd35d2924d6826f5f98e2b8b413fbae2490/app/models/requests/router.rb#L134
