### ISSUE TITLE
Display title-only Uniform title on Show page

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#3184]
### User story
* See uniform titles for works that do not have any author information
* Link to search for other works with the same uniform title

### Concrete example
https://catalog.princeton.edu/catalog/9946018083506421/

### Implementation notes, if any
* Currently Uniform title display is being built from `name_uniform_title_1display`. [bibdata ticket] will create a parallel field `uniform_title_1display` which should be used to build this display in the same location. 
* For the link, it should be the left-anchored search for the different segments of `uniform_title_1display`, e.g. 
  * [Bible. Latin.](https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=left_anchor&q=Bible.+Latin.)
  * [Bible. Latin. Vulgate.](https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=left_anchor&q=Bible.+Latin.+Vulgate.)

**Comment by christinach** [comment]
In order to display this field it needs first to be approved see https://github.com/pulibrary/bibdata/issues/1721

**Comment by maxkadel** [comment]
My understanding is that the plan is to implement this and get sign-off from Esmé and cataloging with it on staging.

**Comment by mzelesky** [comment]
Is it a possibility to treat it like subjects are treated, meaning you can search for a title on each part of the uniform title?

Meaning, for example:

240  _1 $a Sonatas, $m horns (2), $n no. 4-6

You could search
Sonatas
Sonatas, horns (2)
Sonatas, horns (2), no. 4-6

Darwin Scott is a major stakeholder with uniform titles, as they are used extensively in music scores for allowing an efficient browse.

**Comment by maxkadel** [comment]
Wait, that led me to a record that does have a Uniform title displayed - https://catalog.princeton.edu/catalog/SCSB-3263617. It looks like it's coming from `name_uniform_title_1display`, which other records that *do* have a `uniform_title_s` do not have. Clearly more investigation is required.

**Comment by mzelesky** [comment]
Uniform titles exist in 2 fields.

130 is used when there is no author.
240 is used when there is a 1xx field for an author.

That SCSB record has a 240 field, while the Bible record has a 130. My hunch is the MARC fields are indexed into 2 different fields.

**Comment by maxkadel** [comment]
Yes, looking at Bibdata, it looks like that's what's happening. Now the question is - should we change the indexing of `name_uniform_title_1display` in Bibdata, or change the display of Uniform title in Orangelight? I'm leaning towards the Bibdata side now...

**Comment by maxkadel** [comment]
Better example of `name_uniform_title_1display` - https://catalog.princeton.edu/catalog/99125416143706421

**Comment by mzelesky** [comment]
I would think you'd want the values from 130 fields and 240 fields to be in the same indexed field, since there _shouldn't_ be a record that has both a 130 and a 240. Catalogers would likely want to revise the records where both exist.
