### ISSUE TITLE
Update On Shelf Pickup Class to reflect Alma Patron Group Eligibility

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3188]
The "patron_group" attribute contains the type of Alma user account group an account is part of. 

[Alma Patron Groups organized by the type of Requests Services they can utilize](https://docs.google.com/spreadsheets/d/1c4lmMiOzSqMbPYEM5Ni2pofI8lvKpv0FlaRx-xui39E/edit?gid=0#gid=0)

### Acceptance criteria 

- [x] Patron groups "P" , "REG", "GRAD", "SENR", "UGRAD" can request an on shelf pick-up. 
- [x] Patron groups "Affiliate", "Affiliate-P", "CASUAL", and "GST" cannot request an on shelf pick-up. 

## Notes
This is the [service class](https://github.com/pulibrary/orangelight/blob/main/app/models/requests/service_eligibility/on_shelf_pickup.rb) to update.

**Comment by mzelesky** [comment]
The GST Guest Patron patron group (code GST) should also be included in groups that have these limited request options.

**Comment by mzelesky** [comment]
These 3 patron groups should also be able to request Marquand off-site materials.

**Comment by sandbergja** [comment]
These restrictions/abilities should not depend on how the user logs in (alma login vs CAS).  There is a mix of login types within these patron groups.

Patrons may change their patron group throughout the year (for example, if a staff member retires).

**Comment by christinach** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OrangelightBibdataRequests-571691cab409d8d821b873be/issues/pulibrary/orangelight/3188?planning-poker) with Zenhub @leefaisonr @maxkadel @sandbergja @rladdusaw @regineheberlein

**Comment by kevinreiss** [comment]
Discussed with Joan/Mark/Marie as a priority for the near future at circ meeting on 9/27.

**Comment by kevinreiss** [comment]
First step is create documentation on current patron categories aligned with the services they receive.

**Comment by kevinreiss** [comment]
Patron group to fulfillment option matrix: https://docs.google.com/spreadsheets/d/1c4lmMiOzSqMbPYEM5Ni2pofI8lvKpv0FlaRx-xui39E/edit#gid=0

**Comment by kevinreiss** [comment]
@caroldh and @ellen-aa. Implementing this will allow us to solve a number of regularly occurring scenarios where users who can't actually use a request option are allowed to submit the form (IAS and other guest users with net IDs being the common user groups who encounter), so I think we should include this one in our feature sprint if we can.

**Comment by ellen-aa** [comment]
@kevinreiss Makes good sense to me. Greenlight to adjust the ticket label to PO (high priority) and add to the feature sprint if @caroldh agrees too.

**Comment by caroldh** [comment]
@ellen-aa @kevinreiss - Yes, this makes sense to move to high priority - I am adjusting the ticket label.
