### ISSUE TITLE
Display uniform title from 130 in Orangelight

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#3189]
Currently, only uniform titles from the 240 field are being displayed in Orangelight. These are being indexed along with their author field to `name_uniform_title_1display`. 

When there is no author, but there is a uniform title, these are only being indexed to `uniform_title_s`, and not being displayed. 

Currently, the Uniform titles on the show page link to facet searches against the `name_title_browse_s` facet, and there is a browse link to the author-title headings browse list. 

For title-only uniform titles, the uniform title will link to a left-anchored title search (e.g. https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=left_anchor&q=Bible.+Latin.+Vulgate.), and for now there will be no browse link

**Comment by christinach** [comment]
This was completed.
