### ISSUE TITLE
Availability Labels and Logic

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#319]
https://docs.google.com/spreadsheets/d/1MVM4_Q2ZzFnrpzWtEGywnAoB5hndySOgFzr4Hfun200/edit#gid=979200987

**Comment by kevinreiss** [comment]
@tampakis This is looking pretty good. I noticed one thing that might be an issue. For RBSC locations that have no item records with show "limited". For RBSC locations that have items we show available.

See https://pulsearch-dev.princeton.edu/?f%5Blocation%5D%5B%5D=Rare+Books+and+Special+Collections&f%5Brecently_cataloged_facet%5D%5B%5D=weeks_1

We probably should just make no-item and item holding RBSC/Annex locations display the same label. Do we want that to be "limited" or "available" for both?

**Comment by tampakis** [comment]
I'm not sure. @joycebcat Is there an actual distinction between a rare books record having an item record and not? Maybe we should just list everything from RSBC as limited. Nothing from there can be checked out right?

**Comment by kevinreiss** [comment]
That was my thought.

**Comment by joycebcat** [comment]
This was discussed at the meeting.  For the record, we thought all RB material should have the same status.
