### ISSUE TITLE
Call number browse unable to find oversize CD call numbers

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3192]
### Expected behavior
The call number search should return the search results of the https://catalog.princeton.edu/browse/call_numbers?search_field=browse_cn&q=CD-+40056q 

### Actual behavior
Call number browse is unable to find the oversize CD call numbers. For example: CD- 40056q. The list skips over any oversize CD call numbers with a "q".
https://catalog.princeton.edu/browse/call_numbers?search_field=browse_cn&q=CD-+40056q 

### Impact of this bug
Patrons cannot effectively search using the call numbers browse search

### Notes
[catalog feedback queue ticket](https://faq.library.princeton.edu/admin/ticket?qid=8166278)

**Comment by christinach** [comment]
Search for other call numbers that they have in q 'Oversize' and compare the search results.

**Comment by mzelesky** [comment]
I did some investigation on this, and this seems to be localized to just CD call numbers. This leads me to think it's something to do with how call numbers are normalized in the indexer.

**Comment by mzelesky** [comment]
See 9953224823506421 for a record with a call number with a $k Oversize that shows up correctly.

**Comment by maxkadel** [comment]
Started process to write new call number files 8/1/2023

**Comment by maxkadel** [comment]
Successfully re-created call number browse lists on production.
