### ISSUE TITLE
Update icon-musical-score to actual musical symbol

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#3198]
Reported by Darwin.
Use actual musical symbol to represent musical scores.

### Current symbol
This is similar to actual musical symbols, but the real one should have filled circles
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/c22c34dc-fa23-4347-80ab-8344c745468f)

## Implementation note
Likely places to change: 
* https://github.com/pulibrary/orangelight/blob/90434bd3b056390d50e8d3d0a3a4e1583ed6941f/app/assets/stylesheets/icons/variables.scss#L44
* https://github.com/pulibrary/orangelight/blob/90434bd3b056390d50e8d3d0a3a4e1583ed6941f/app/assets/fonts/icons/pul-icons.svg?short_path=b0edcc6#L15
  * possibly change `d=M894[...]` to `d="M30 0h2v23c0 2.761-3.134 5-7 5s-7-2.239-7-5c0-2.761 3.134-5 7-5 1.959 0 3.729 0.575 5 1.501v-11.501l-16 3.556v15.444c0 2.761-3.134 5-7 5s-7-2.239-7-5c0-2.761 3.134-5 7-5 1.959 0 3.729 0.575 5 1.501v-19.501l18-4z"`

**Comment by christinach** [comment]
users understand that it is a musical symbol.
