### ISSUE TITLE
Deploying doesn't re-generate crontab

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3202]
### Expected behavior
When we deploy some code with a different whenever configuration, that new configuration will be written to the crontab.

### Actual behavior
The crontab currently contains the `sitemap:refresh` rake task, [which we have removed ](https://github.com/pulibrary/orangelight/pull/3169/files#diff-719014e0b73d01f90fc1a0dfbc5029e8eb614c68c87400b0cbd1883f1036614d).

We have deployed since that PR was merged:
```
deploy@catalog2:~$ ls -alrth /opt/orangelight/current
lrwxrwxrwx 1 deploy deploy 40 Sep 16 13:33 /opt/orangelight/current -> /opt/orangelight/releases/20220916133216
```
But crontab still has the rake task, and it says that the whenever generated tasks were in August (though we have deployed more recently, in September).

```
deploy@catalog2:~$ crontab -l
#Ansible: Clean old Blacklight searches and Devise guest user accounts nightly
0 22 * * * /bin/bash -l -c 'export PATH="/usr/local/bin/:$PATH" && cd /opt/orangelight/current && bundle exec rake blacklight:delete_old_searches >> /tmp/guests_searches.log 2>&1 && bundle exec rake devise_guests:delete_old_guest_users >> /tmp/guests_searches.log 2>&1'

# Begin Whenever generated tasks for: orangelight at: 2022-08-30 20:43:47 +0000
0 2 * * 2 bash -l -c 'export PATH="/usr/local/bin/:$PATH" && cd /opt/orangelight/releases/20220830204255 && RAILS_ENV=production bundle exec rake sitemap:refresh >> /tmp/ol_sitemap.log 2>> /tmp/ol_sitemap.log'

# End Whenever generated tasks for: orangelight at: 2022-08-30 20:43:47 +0000
```

### Impact of this bug

catalog-2 is still trying to generate sitemaps, leading to unnecessary solr calls and honeybadger errors.
### Honeybadger link and code snippet, if applicable

https://app.honeybadger.io/projects/54399/faults/87760950

**Comment by christinach** [comment]
clean the stale cron jobs from catalog2 and close the ticket

**Comment by maxkadel** [comment]
It looks like this has been resolved.
