### ISSUE TITLE
'no circ' Annex items should be able to go to any branch library or Firestone

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3203]
### Expected behavior
Annex items should be able to go to any branch library or Firestone

### Actual behavior
Annex items can only be viewed or picked up at Firestone

### Steps to replicate
example record: https://catalog.princeton.edu/catalog/9954244733506421

### Notes
This is an in library use item. Ask Joan M. if we need specific restrictions for 'in library use' items.

**Comment by kevinreiss** [comment]
It does appear an record with an item marked for NoCirc (which is the item policy applied to items that require "In Library Use" are hardcoded to just Firestone. These items should display the same set of pick-up locations that any other item in the holding location they are shelved in.

**Comment by christinach** [comment]
From the circ meeting 09/28/2022. A patron should be able to pick up an Annex item and 'no circ' in any location they want to.

**Comment by christinach** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OrangelightBibdataRequests-571691cab409d8d821b873be/issues/pulibrary/orangelight/3203?planning-poker) with Zenhub @leefaisonr @maxkadel @sandbergja
