### ISSUE TITLE
Request submission error - Item does not have a delivery mode

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#3208]
### Expected behavior
When a patron requests an item through the UI, it has an expected delivery mode.

### Actual behavior
More and more often, the item does not have a delivery mode and raises an exception. This may in part be because the semester is starting, and more items are being requested.

### Steps to replicate
Unclear - when I go directly to a URL mentioned in Honeybadger, if I fill in the Article/Chapter Title and the note, it says the request was successful. If I don't fill out anything, it does not submit but gives an appropriate flash message to fill out the form.

### Impact of this bug
Some patrons may not be able to request items.

### Honeybadger link and code snippet, if applicable
https://app.honeybadger.io/projects/54399/faults/87665915/01GDGTPWYCJ8WZ1TAX9YJHQ16H?page=0#notice-summary

```
[PROJECT_ROOT]/app/models/requests/submission.rb:152:in `categorize_by_delivery_and_location'
          item["type"] = "annex"
        elsif off_site?(library_code)
          raise Exception, "#{self.class}: Item does not have a delivery mode" unless delivery_mode(item)
          item["type"] = library_code
          item["type"] += "_edd" if edd?(item)
```

**Comment by kevinreiss** [comment]
The example URL from this honeybadger trace is interesting because it only shows the EDD option. It should also really be displaying the physical delivery (for in library use since it is a Marquand item) option. I suspect that might be why the form is producing an error. 

https://catalog.princeton.edu/requests/9945463973506421?mfhd=22749241710006421

**Comment by kevinreiss** [comment]
This is the same issue as 3229. Closing in favor of the one with the description.
