### ISSUE TITLE
Display Electronic Portfolios Above Electronic Access Links

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3226]
We display two data points stored in records that are shown in the "Available Online" section.

1. electronic_portfolio_s
2. electronic_access_1display

We should display the data from electronic_porfolio_s before electronic_access_1display. Example record:

https://catalog.princeton.edu/catalog/99114349623506421

**Comment by kevinreiss** [comment]
We can float the electronic_access_1display values to the bottom of the online section, below portfolios and links from related records.

**Comment by kevinreiss** [comment]
electronic_acces_1display is legacy 856 data from the Voyager system.

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OrangelightBibdataRequests-571691cab409d8d821b873be/issues/pulibrary/orangelight/3226?planning-poker) with Zenhub @leefaisonr @maxkadel @rladdusaw @sandbergja

**Comment by sandbergja** [comment]
The order should be:

1. electronic_portfolio_s from this record
1. electronic_portfolio_s from other versions
1. electronic_access_1display

**Comment by kevinreiss** [comment]
Since we have deleted 95% of the 856 links I think we can close this.
