### ISSUE TITLE
Refactor request specs

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#3233]
In preparation for larger code refactors, we should make testing this part of the code easier and more manageable. Some of the spec files for this part of the code are over 1,500 lines, making them difficult to navigate. 

### Requirements
* Ensure that the code coverage remains the same (or better)
* Tests need to pass both locally and in CI

### High priority files to focus on:
* `spec/features/requests/request_spec.rb`
* `spec/models/requests/request_spec.rb`

### Implementation details
* Use test helper methods whenever possible
* Use contexts and describe blocks to structure tests 
* DRY up tests as much as possible
* Separate into different files if necessary

**Comment by kevinreiss** [comment]
Discussed this on 1/13/2023 to plan for re-factor need to do some updated requirements gathering on what are our valid request types and patron groupings with stakeholders.

**Comment by kevinreiss** [comment]
Discussed on 5/5 breaking this up into an EPIC ticket.

**Comment by kevinreiss** [comment]
Some substantive clean-up working happened here: https://github.com/pulibrary/orangelight/pull/3563

**Comment by kevinreiss** [comment]
Will start review here at OL meeting on 12/11/2023.
