### ISSUE TITLE
catalog-staging is down

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/orangelight#3236]
### Expected behavior
search on staging should bring up search results

### Actual behavior
search reports "We're sorry, but there was a problem processing the page you requested."

### Steps to replicate
try a search by call number

### Impact of this bug
can't use staging to allow stageholders to do Q&A

### Honeybadger link and code snippet, if applicable
https://app.honeybadger.io/projects/54399/faults/88939567

```
81 | def sorted_locations(response)
82 | locations_hash = {}.with_indifferent_access
83 | JSON.parse(response.body).each do \|location\|
84 | locations_hash[location['code']] = location.with_indifferent_access
85 | end
```

**Comment by christinach** [comment]
catalog-stgaing is working
