### ISSUE TITLE
error from BD login (possible security issue)

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/orangelight#3238]
### Actual behavior
honeybadger throws an error in orangelight coming from borrow-direct where a user lookup fails.

### Impact of this bug
This could be a user with a netID and SSO account but no ALMA account.

Or it could potentially be an issue having to do with deciding to put off implementation of the cross-site protection gem, since it would break the existing borrow direct login from the main library site.

### Honeybadger link and code snippet, if applicable
https://app.honeybadger.io/projects/54399/faults/89075075
```
bibdata.rb  75  build_api_patron(...)
[PROJECT_ROOT]/app/services/bibdata.rb:75:in `build_api_patron'
      def build_api_patron(api_response:, user:)
        base_patron_json = JSON.parse(api_response.body)
        patron_json = base_patron_json.merge(
          valid: user.valid?
        )
```

**Comment by kevinreiss** [comment]
closing as borrow-direct code has been sunset.
