### ISSUE TITLE
Allow Forrestal Annex microfilm to be able to be delivered to EAL or Firestone

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/orangelight#3251]
### User story
There are two records that are saying all items can only be delivered to Firestone. These are Chinese microfilms that should be able to be sent to EAL for in library use only. 
EAL has a microfilm reader and most researchers looking for Chinese microfilms would be coming to EAL.
### Concrete example
Here are the two records: https://catalog.princeton.edu/catalog/9930714983506421 and https://catalog.princeton.edu/catalog/9930844733506421

### Implementation notes, if any
Requires consultation with Circulation and Inventory Management.

**Comment by christinach** [comment]
Will be resolved by https://github.com/pulibrary/bibdata/pull/2025

**Comment by kevinreiss** [comment]
Deployed to prod. Closing.
