### ISSUE TITLE
Annex Error for No Item Serials

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3252]
https://catalog.princeton.edu/requests/9923478183506421?mfhd=22625563160006421

This form tries to create a hold without a barcode so the request fails. This is a serial in the annex with no items at all. Instead of an alma hold this should either go to recapproblems or the old forannex email address. Will check with Marie.

**Comment by rladdusaw** [comment]
I was able to successfully create a request for this item. Closing this as resolved.
