### ISSUE TITLE
Create a wireframe in orangelight of the three feedback options that we currently have in pulfalight

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3274]
### User story
Users should be able to see at the bottom of the record page the three different form options: 
- Ask A Question
- Suggest A Correction
- Report Harmful Language or Content

### Concrete example
https://findingaids.princeton.edu/catalog/C0101 , scroll down at the bottom of the page. 

![Screen Shot 2022-12-05 at 11 52 52 AM](https://user-images.githubusercontent.com/9905193/205695435-50de8e1c-3f6f-4148-bd93-7a330f757825.png)

### Implementation notes, if any
Create a wireframe of the record page. 
Request approval from the stakeholders.

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OrangelightBibdataRequests-571691cab409d8d821b873be/issues/pulibrary/orangelight/3274?planning-poker) with Zenhub @sandbergja @christinach @regineheberlein @rladdusaw @maxkadel @leefaisonr

**Comment by kevinreiss** [comment]
We only need to wireframe the record page, not the individual form, that is already done in the proposal for this feature. https://docs.google.com/document/d/1HPOUhTo6T9Zi57G0z-hsKIJCKU1u3k_KZgyJyuHunJw/edit

**Comment by christinach** [comment]
@escowles @kevinreiss can you please review the wireframe?

**Comment by escowles** [comment]
@christinach The display looks good — does it stay at the bottom of the page, or does it scroll as the user scrolls through the page like in Pulfalight?

**Comment by christinach** [comment]
@escowles good point. This is only the wireframe. If this is the desired behavior then we will implement it to stay at the bottom of the page like in Pulfalight.

**Comment by escowles** [comment]
👍🏻 Sounds good — we would like it to stay at the bottom of the screen so you don't have to scroll all the way down to see it. Thanks!

**Comment by christinach** [comment]
@escowles good point. This is only the wireframe. If this is the desired behavior then we will implement it to stay at the bottom of the browser window when the user scrolls up or down, like in Pulfalight. So that it is always visible.

**Comment by christinach** [comment]
> 👍🏻 Sounds good — we would like it to stay at the bottom of the screen so you don't have to scroll all the way down to see it. Thanks!

Thank you. I will add this detail in the following implementation ticket.

**Comment by christinach** [comment]
Based on feedback we received from the IRMWG group the button caption is 'Report Harmful Language'
<img width="1538" alt="record_page" src="https://user-images.githubusercontent.com/9905193/208111603-044835d5-15eb-438a-8032-53412c3ba708.png">

**Comment by christinach** [comment]
This is completed.
