### ISSUE TITLE
Use a serif font for call numbers

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#3275]
### Current display
When a call number has the characters L and I, it's hard to tell the difference because of sans-serif font. Example: https://catalog.princeton.edu/catalog/9947668823506421

### Desired display
Change to a serif font for call numbers to make it easier to tell the difference.

### Notes
Approved by DSSG in Feb. 2020

**Comment by kevinreiss** [comment]
Find a serif font that is accessible and try that.

**Comment by sandbergja** [comment]
Here are guidelines for choosing an accessible font: https://webaim.org/techniques/fonts/#readability
