### ISSUE TITLE
Improve user experience of the bookmarked items.

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3291]
### User story
Users don't always know that in order to save the bookmarked items they need to log in first in the catalog. As a result if they close the browser session they loose any bookmarked items. 

### Concrete example
Without being logged in, visit the catalog page and bookmark some records. Go to the Bookmarks view. The bookmarked items are displayed. Close the browser session and open a new one. The bookmarks are not there. 

### Acceptance Criteria

- [ ] Create a wireframe with some ideas on how to notify anonymous users they need to sign in to save bookmarks. 

### Implementation notes, if any
@caroldh suggested to have a bookmark tooltip that will inform the users about this functionality. For example: "Log in to save bookmarks. If you can’t login, bookmarks will not be saved" or something similar that will improve the user experience. 
catalog-feedback ticket #: 10584094

**Comment by christinach** [comment]
Create some prototypes to test different UX options.

**Comment by caroldh** [comment]
Related to #1748 - saving and emailing (or downloading) bookmarks requires logging in to alma account. That could be made clear before patron is using the feature.

**Comment by rladdusaw** [comment]
Created a couple possible [options](https://www.figma.com/design/BTU6c0uNhVFf4wLgB5p8BC/Orangelight-PO-workcycle?node-id=0-1&node-type=canvas&t=FVw7SYewks2UrxES-0) for review.

**Comment by christinach** [comment]
closing in favor of https://github.com/pulibrary/orangelight/issues/4454
