### ISSUE TITLE
Ensure the GA4 migration follows previously set GA settings

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3296]
Ensure the GA4 migration follows previously set GA settings.
Discussed this in the Web Analytics group. 
GA settings see: https://docs.google.com/document/d/1gOdH496jO2_a8SXB3zUv48smyi6ktCPl8V6ltacDLcw/edit#

**Comment by christinach** [comment]
Will look into this the week of 12/26.

**Comment by kevinreiss** [comment]
@christinach we talked about this during ticket review and it would be good if we could do the review of the settings a team when you are back.

**Comment by christinach** [comment]
we will review the GA4 settings on 2/7/23

**Comment by christinach** [comment]
- 'Data retention' previously was 26 months. In GA4 the longest you can retain data is 14 months.

- IP masking: In Google Analytics 4, IP masking is not necessary since IP addresses are not logged or stored.
