### ISSUE TITLE
Title subfield h and indexing

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#331]
@tampakis @jpstroop The title starts with search includes |h when searching.  This has long been a problem in our discovery systems.  |h appears in non-book format material before RDA in between the title and the subtitle.  It is a pain for users because they don't expect it and the print material is retrieved in searches but other formats are not.  Ideally the title starts with search would skip over the |h entirely.  You should be able to get this record:
Behind the beautiful forevers [electronic resource] : life, death, and hope in a Mumbai undercity 
with this title starts with search:
behind the beautiful forevers life

**Comment by tampakis** [comment]
Is this only for the 245 field?

**Comment by joycebcat** [comment]
Yes, subfield h is only used in the 245.
