### ISSUE TITLE
make sure database connection is secure

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#332]
@marvinmarvinb asked if Blacklight's connection to the PSQL is encrypted, since we're sending user data back and forth

**Comment by tampakis** [comment]
Make sure SSL is enabled. Read [18.3.2](http://www.postgresql.org/docs/9.1/static/runtime-config-connection.html)

**Comment by tampakis** [comment]
@kayiwa can we discuss this issue at some point this week?
