### ISSUE TITLE
Upgrade to rails 7

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3321]
[This devise issue may be related](https://github.com/heartcombo/devise/issues/5443)

**Comment by kevinreiss** [comment]
Is it better to do this after we upgrade to Blacklight 8?

**Comment by kevinreiss** [comment]
End of life for Ruby 6.1.x is 6/1/2024.

**Comment by kevinreiss** [comment]
@christinach are you trying to go to 7.1.x or 7.0.x?

**Comment by christinach** [comment]
@kevinreiss we're working on rails 7.0.x
