### ISSUE TITLE
Control Bar Looks off kilter on Record Page on Small Screens

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3334]
Visit any catalog individual record page: https://catalog.princeton.edu/catalog/9912140633506421 
### Current display
<img width="531" alt="Screen Shot 2023-01-03 at 12 35 30 PM" src="https://user-images.githubusercontent.com/278825/210420437-f01a198f-23b2-4ec0-9dbd-21c8f10a4edf.png">
<img width="489" alt="Screen Shot 2023-01-03 at 12 35 21 PM" src="https://user-images.githubusercontent.com/278825/210420440-fefde276-dc24-4ebf-a8a1-46c8be6c1a90.png">

**Comment by christinach** [comment]
@kevinreiss I can't identify the screen size where you can see the control bar like that. Can you add the screen size? If it's not an issue anymore we can close the ticket.
