### ISSUE TITLE
Confirm that objects with generic warnings in figgy mask universal viewer in catalog

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3335]
1. Request permissions to edit objects on the staging site and/or pair with somebody with those permissions (maybe Kim?).
2. Confirm that GRAPHQL_API_URL and FIGGY_URL are pointing to staging, per these instructions: https://github.com/pulibrary/orangelight/blob/0f47f53278e1da85e325ef28ee65ee8ebe2aa8db/README.md#local-development-with-figgy
3. Find an item with a viewer in catalog-staging.
4. Find the same item in figgy-staging.
5. Edit it to include a generic warning.
6. Confirm that the catalog-staging show page does not show the viewer until you opt-in to viewing the content.  If the change is not displaying, try re-indexing.
7. If the opt-in message does display correctly, add some documentation about the generic warnings in the orangelight docs directory.  If it does not display, work with DLSS to identify next steps.

For additional background, here are the notes from our meeting about the harmful content warnings: https://docs.google.com/document/d/1S9VSzrfIPQOuBpigOZeftMr57mI1auvHtngSOWjzn6M/edit

### Acceptance criteria
- [x] I can successfully use this feature with Voice Over in Safari.
- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OrangelightBibdataRequests-571691cab409d8d821b873be/issues/pulibrary/orangelight/3335?planning-poker) with Zenhub @maxkadel @rladdusaw @sandbergja

**Comment by christinach** [comment]
I manually updated https://figgy-staging.princeton.edu/catalog/123bbbfb-4e7d-4bc6-9752-4b48925a1cdf to have Notice type: 'Harmful content'. The figgy viewer in figgy changed to have content 'Content Warning'. 
I updated catalog-staging1 and 2 to point to figgy-staging both the figgy url and graphql. No viewer loaded in Orangelight https://catalog-staging.princeton.edu/catalog/9969219203506421. 
I'll look into it more.

**Comment by christinach** [comment]
The viewer didnt show up because the record is still in Pending. I'll test a different one.

**Comment by christinach** [comment]
I tested https://catalog-staging.princeton.edu/catalog/99113350103506421 with updating https://figgy-staging.princeton.edu/catalog/d3415442-c4a1-4a7d-ba29-284d83573726 to have 'Notice Type': 'Harmful Content'. The viewer in the catalog loads the 'Content Warning' as expected. 
Similar behavior for the 'Explicit content' and the 'Senior Thesis'. We have alrady tested the Senior thesis as part of another ticket.
