### ISSUE TITLE
Available items in firestone$pf and in SCSB display label status Available -  In Process

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3354]
### Expected behavior
The request form should display Available.

### Actual behavior
The request form displays Available - In Process.

### Steps to replicate
Visit https://catalog.princeton.edu/requests/99124983693506421?aeon=false&mfhd=22747210040006421
![Screen Shot 2023-01-05 at 9 41 31 PM](https://user-images.githubusercontent.com/9905193/210919036-ad0b9ebc-e24b-4221-9360-f7fedbdecef7.png)

### Impact of this bug
The label can be misleading and confusing for the user and for us.

### Availability
Holding availability response https://bibdata.princeton.edu/bibliographic/availability.json?deep=true&bib_ids=99124983693506421
```
{
  "99124983693506421": {
    "22747210040006421": {
      "on_reserve": "N",
      "location": "firestone$pf",
      "label": "Firestone Library - Remote Storage (ReCAP): Firestone Library Use Only",
      "status_label": "Available",
      "copy_number": null,
      "cdl": false,
      "temp_location": false,
      "id": "22747210040006421"
    }
  }
}
```
Holding/items availability response https://bibdata.princeton.edu/bibliographic/99124983693506421/holdings/22747210040006421/availability.json
```
[
  {
    "barcode": "",
    "id": "23747230000006421",
    "holding_id": "22747210040006421",
    "copy_number": "1",
    "status": "Available",
    "status_label": "Item in place",
    "status_source": "base_status",
    "process_type": null,
    "on_reserve": "N",
    "item_type": "Gen",
    "pickup_location_id": "firestone",
    "pickup_location_code": "firestone",
    "location": "firestone$pf",
    "label": "Firestone Library - Remote Storage (ReCAP): Firestone Library Use Only",
    "description": "vol.10-13",
    "enum_display": "vol.10-13",
    "chron_display": "",
    "in_temp_library": false
  },
  {
    "barcode": "32101053105035",
    "id": "23747210010006421",
    "holding_id": "22747210040006421",
    "copy_number": "1",
    "status": "Available",
    "status_label": "Item in place",
    "status_source": "base_status",
    "process_type": null,
    "on_reserve": "N",
    "item_type": "Gen",
    "pickup_location_id": "firestone",
    "pickup_location_code": "firestone",
    "location": "firestone$pf",
    "label": "Firestone Library - Remote Storage (ReCAP): Firestone Library Use Only",
    "description": "",
    "enum_display": "",
    "chron_display": "",
    "in_temp_library": false
  }
]
```

### Potential places to look in the code:
https://github.com/pulibrary/orangelight/blob/097b576b3eb4a083dcb03ec5faa00b8342d62ae9/app/models/requests/request.rb#L259-L267

firestone$pf is a Recap location https://bibdata.princeton.edu/locations/holding_locations/firestone$pf

**Comment by christinach** [comment]
I remember that during the circulation meeting (1/4/2023) @mzelesky checked this barcode and it was available 'In'. This was the main confusion. 
Now it is 'OUT' which makes more sense to have the 'In Process'.

**Comment by christinach** [comment]
Response from scsb availability status response
https://scsb.recaplib.org:9093/sharedCollection/bibAvailabilityStatus 
[
  {
    "itemBarcode": "",
    "itemAvailabilityStatus": null,
    "errorMessage": "Bib Id doesn't exist in SCSB database.",
    "collectionGroupDesignation": null
  }
]

The mmsid that this item is assigned in alma doesn't exist in RECAP.
The item in Alma is 'Item in Place''.

Bring this to the circulation meeting to Marie and @mzelesky.

**Comment by christinach** [comment]
This is a data issue.

**Comment by maxkadel** [comment]
@kevinreiss will add to circ meeting agenda

**Comment by kevinreiss** [comment]
This is a data issue. Marie will ask Colleen in microforms to delete the item record that does not have a barcode on this record.
