### ISSUE TITLE
Item requests with manually entered volume don't activate submit button

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/orangelight#3359]
### Expected behavior
When a volume is entered and the checkbox is selected with a delivery location, the submit request button should be active.

### Actual behavior
Example: https://catalog.princeton.edu/requests/9981435603506421?aeon=false&mfhd=22561461580006421
When the first row for user supplied volume information is provided, the submit button is still disabled.

### Steps to replicate
Click the first checkbox, enter a volume, and select a delivery location. The submit button will not be enabled.

### Impact of this bug
If the needed volume is not listed in the pre-populated options the user is unable to request it.

### Implementation notes, if any
The JS code that detects when the form is valid is not working correctly for this case, either the selector is not catching this row of the form or the conditions for determining if the selected choices are valid is not catching this scenario and need to be updated.

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OrangelightBibdataRequests-571691cab409d8d821b873be/issues/pulibrary/orangelight/3359?planning-poker) with Zenhub @leefaisonr @maxkadel @rladdusaw @sandbergja
