### ISSUE TITLE
Access and Language facets selected in the advanced search are displaying twice

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3384]
### Expected behavior

The advanced search screen allows you to choose "inclusive facets", meaning that they use a Boolean OR rather than Boolean AND.  The search results page should display these facets, but not multiple times.

### Actual behavior

The Access and Language facets are displaying the "Any of:" box twice!  The format facets don't appear to be affected

<img width="404" alt="access facet includes two boxes, both of which say Any of: In the library, Online" src="https://user-images.githubusercontent.com/7086943/214941310-37872349-8ac2-435c-b1e1-855f43db61d2.png">

<img width="386" alt="language facet includes two boxes, both of which say Any of: Acoli, Adangme" src="https://user-images.githubusercontent.com/7086943/214941536-168ed1a4-42b3-4817-beae-38ead87a182a.png">

### Steps to replicate

1. Go to https://catalog.princeton.edu/advanced
2. Select multiple values in the Access dropdown
3. Select multiple values in the Language dropdown
4. Press the search button
5. Look at the facets on the side of the search results screen

### Impact of this bug

Odd, cluttered, and potentially confusing UI

### Acceptance criteria

- [ ] Check this on the blacklight 8 branch.  If Blacklight 8 fixes it, then close this ticket.  Otherwise fix it for both main and the blacklight 8 branch.

### Notes

I suspect this bug was introduced as part of the Blacklight deprecation work.

**Comment by sandbergja** [comment]
I wonder if this is the same as https://github.com/projectblacklight/blacklight_advanced_search/pull/128 ?

**Comment by christinach** [comment]
This is not anymore a bug in production - blacklight 7.
Deployed [Blacklight8-upgrade-v2](https://github.com/pulibrary/orangelight/pull/4582) on catalog-staging and tested the advanced search facets.
