### ISSUE TITLE
Add New Stackmap Modal

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3392]
Stackmap's vendor hosts scripts for clients that provides an updated modal view with controls that allow for more interactively with the maps. 

### Current display (from staging with stackmap at Firestone Features turned on)
<img width="722" alt="Screen Shot 2023-02-02 at 10 53 55 AM" src="https://user-images.githubusercontent.com/278825/216389911-501b9c61-8a49-4278-b850-74d5b69a4bf5.png">

### Desired display
The updated code will add controls to the modal. We may have to adjust the modals sizing too. 

### Notes
Two implementation option are suggested. 

HTML VERSION:
```
<!-- STACKMAP CHANGES BEGIN HERE --> 
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<script src="https://www.stackmapintegration.com/princeton-blacklight/StackMap.min.js" type="text/javascript"></script>
<link rel="stylesheet" media="all" type="text/css" href="https://www.stackmapintegration.com/princeton-blacklight/StackMap.min.css" />
<!-- STACKMAP CHANGES END HERE -->
```

```
JAVASCRIPT VERSION:

/* StackMap: Start */
(function(){

    var a = document.querySelector("head");
    var css1 = document.createElement("link");
    css1.type = "text/css";
    css1.rel = "Stylesheet";
    css1.href = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css";
    css1.crossorigin = "anonymous";
    a.appendChild(css1);

    var css2 = document.createElement("link");
    css2.type = "text/css";
    css2.rel = "Stylesheet";
    css2.href = "https://www.stackmapintegration.com/ princeton-blacklight/StackMap.min.css";
    a.appendChild(css2);

    var w = document.createElement("script");
    w.type = "text/javascript"; w.async = true;
    w.src = "https://www.stackmapintegration.com/princeton-blacklight/StackMap.min.js";
    var b = document.body;
    b.appendChild(w);

})();
/* StackMap: END */
```

**Comment by maxkadel** [comment]
Kevin has a meeting with the vendor on 2/9/2023 and will discuss implementation then. 

Possible concerns:
- Button is slow to display on the page
- Text of the button does not match current implementation ("Where to find it" vs. "Map it")

**Comment by maxkadel** [comment]
@kevinreiss  - We also have a failing accessibility test - the map icon is not aria-hidden, which I think is a change they need to make on the vendor side. See https://github.com/pulibrary/orangelight/pull/3402/files#diff-6a0e1ff4df89c6ea88feb537aba63ebace11bdf033243f820206d9e736febebf

**Comment by kevinreiss** [comment]
Spoke with vendor. They will update the label and fix the aria issue. They will also update the display to do more to highlight the pushpin for the shelf location at the current display size and zoom level it can be hard to pick that up quickly. They asked that we add two new data attributes that will help with the display of the labels on the modal in addition to data-map-location. We should add a data attribute containing the Library Name and another containing the human readable shelf label.

**Comment by maxkadel** [comment]
Vendor will fix flagged issues. 

On the maps the icon for the pushpin is hard to see.

Using data attributes - requested more data for human readable labels - @kevinreiss will make ticket for adding attribute.

**Comment by maxkadel** [comment]
Is this work that should be behind the Firestone Stackmap feature flipper? (I wouldn't want to merge it into main in any case until the accessibility test is passing)

**Comment by maxkadel** [comment]
Put this behind Firestone feature flipper - be sure that the new button does not appear for any libraries, including Firestone if the feature is not flipped.

**Comment by maxkadel** [comment]
- This is now behind the same feature flipper as the Firestone Locator
- I have marked the vendor-dependent test as pending

I think at this point we can safely merge this branch into main (pending review, of course)

**Comment by kevinreiss** [comment]
I think we can close this ticket now that it is merged. The vendor is preparing an updated script for us to test again, so we may create new tickets based on how testing that goes.
