### ISSUE TITLE
Which location should show in search results view?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#34]
* ~~One?~~
 * ~~All?~~ 
 * ~~One when one, else something hard-coded, like "Multiple Locations" (could click or hover to show them in a modal or somesuch)~~
 * Pair location name with call number in brief and full results ... maybe consider cutting off at two, or moving into a modal or something...

**Comment by tampakis** [comment]
#101 pairs holding locations and call numbers. #102 limits the holdings to 2 in the search results view.
