### ISSUE TITLE
Request form has no status

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3401]
### Expected behavior
Item status should display in the request form

### Actual behavior
The request form displays no status.

### Steps to replicate
visit https://catalog.princeton.edu/requests/9927845433506421?aeon=false&mfhd=22597058980006421

### Impact of this bug
Users don't know the status of the item and will not request it.
Reported in https://faq.library.princeton.edu/admin/ticket?qid=10891001

### Availability response:
```
// 20230208081825
// https://bibdata.princeton.edu/bibliographic/availability.json?deep=true&bib_ids=9927845433506421

{
  "9927845433506421": {
    "22597058980006421": {
      "on_reserve": "N",
      "location": "firestone$stacks",
      "label": "Firestone Library - Stacks",
      "status_label": "Some items not available",
      "copy_number": null,
      "cdl": false,
      "temp_location": false,
      "id": "22597058980006421"
    }
  }
}
```
### Implementation notes, if any
![Item status does not display in the request form](https://user-images.githubusercontent.com/9905193/217540468-8a85f85a-cbd5-41d7-9cd4-a1957aeae2f2.png)

**Comment by mzelesky** [comment]
In alma, the holding has no items. It's upsetting that Alma provides the same message for a holding with no items as it does for when some items are unavailable.

In my opinion, this would be treated as an In Process request from the request form, but I'd want Circulation to weigh in on that.

**Comment by kevinreiss** [comment]
We have treated items with no holdings like as exceptions for years that go to recap problems. I don't think we really should change anything here. 

Kevin

**Comment by christinach** [comment]
Per @kevinreiss we don't need to change anything in our code to handle this case. This was a special case the book is lost. Items in this state cannot have a status.
