### ISSUE TITLE
Atom XML Returns as HTML

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3406]
### Expected behavior
When clicking on the RSS feed icon for a search our default value is to return Atom xml for the contents of that feed. 

### Actual behavior
When selecting this link you get back the system's default html error page with a 500 response. 

### Steps to replicate
Visit any query as an atom feed: https://catalog.princeton.edu/catalog?format=atom&q=dogs&search_field=all_fields&sort=cataloged_tdt+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&utf8=%E2%9C%93

### Impact of this bug
Users cannot use atom feeds for things like recently cataloging materails. 

### Notes
Interestingly "rss" format feeds do return XML (not very detailed)
https://catalog.princeton.edu/catalog?format=rss&q=dogs&search_field=all_fields&sort=cataloged_tdt+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&utf8=%E2%9C%93

We also have an XML builder template that looks like it "should" handle atom, but is not being invoked when that format is requested. 

https://github.com/pulibrary/orangelight/blob/ac78d93e0a553e79ea37f6ae4cdad40e04c17be0/app/views/catalog/_document_default.atom.builder

### Stack trace
```
{"method":"GET","path":"/catalog","format":"atom","controller":"CatalogController","action":"index","status":500,"error":"ActionView::Template::Error: Invalid formats: \"html\"","duration":117.69,"view":0.0,"db":17.37,"unpermitted_params":["utf8"],"ddsource":["ruby"],"@timestamp":"2023-02-10T18:25:18.984Z","@version":"1","message":"[500] GET /catalog (CatalogController#index)"}

ActionView::Template::Error (Invalid formats: "html"):
    15:
    16:   xml.author { xml.name(document.to_semantic_values[:author].first) } if document.to_semantic_values.key? :author
    17:
    18:   with_format('html') do
    19:     xml.summary 'type' => 'html' do
    20:       xml.text! render partial: 'atom_index', locals: { document: }
    21:     end

app/views/catalog/_document_default.atom.builder:18
app/views/catalog/_document_default.atom.builder:3
app/controllers/catalog_controller.rb:681:in `index'
lib/orangelight/middleware/invalid_parameter_handler.rb:12:in `call'
```

### Acceptance criteria
- [ ] Check in DataDog for ppl visiting this route
- [ ] Investigate how difficult it would be to fix
- [ ] If unused and difficult to fix, remove link
- [ ] Create follow-up ticket, if needed

**Comment by maxkadel** [comment]
Can we get data from Analytics? Probably not, since it's XML. Can't see errors in HoneyBadger. May be able to check in DataDog to see if people are using this URL. 

Do we have any sense of how long it has been broken?

**Comment by maxkadel** [comment]
This ended up being very easy to fix, so I did not investigate its use in Datadog.
