### ISSUE TITLE
Refactor advanced search using the built-in advanced search BL form

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3412]
The built-in advanced search form is included in BL 7 and BL 8.
Things to consider:
1. The queries will turn from q1, q2, q3 to [clause0], [clause1], [clause2] 
2. It uses view components rather the view partials. 
3. It will need a lot of work to make the form look as it does now.
4. It uses the json query DSL. This is the new way BL communicates with SOLR. This will require changes to the catalog controller.

### Acceptance criteria
- [x] There is a new form
- [x] It is behind a feature flipper
- [X] It is ok if this form does not actually successfully perform a search - the search is blocked by changes in Solr / Blacklight

**Comment by maxkadel** [comment]
Still to do:
- Advanced search facets
- Actually searching when you press search
- Numismatics form still uses gem partials rather than Blacklight components

**Comment by maxkadel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DACS-Maintenance-5da0db919c4ddf0001b2eb92/issues/pulibrary/orangelight/3412?planning-poker) with Zenhub @regineheberlein @kevinreiss @christinach @rladdusaw @sandbergja

**Comment by sandbergja** [comment]
I was able to follow these procedures to get advanced search working with the blacklight .internal_test_app: https://code4lib.slack.com/archives/C54TB5WDQ/p1687452502967029

These don't work for orangelight -- I wonder if it's because we also have a complex default query that we also send.

**Comment by kevinreiss** [comment]
Form is partially working, but need to work through these scenarios. 

1. Add support for Boolean operators (they are there now but don't work)
2. Pivot facets are failing when you edit an active search.
