### ISSUE TITLE
Add data attributes with Library and Human Readable Shelf Location for new Stackmap Implementation. 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3413]
Currently we inject an attribute, data-map-location, that contains our machine readable shelf location. The updated stackmap implementation uses this to decide where to inject a stackmap link. The vendor requests we add two additional data attributes to the same element data-map-location is attached to:

data-location-name - Name of the Shelving Location i.e. Stacks, Science Reference, Dixon Collection
data-location-library - Name of the library the location is in, i.e. Firestone, Lewis.

**Comment by maxkadel** [comment]
@kevinreiss  - Is it ok that this is just on the Stackmap Modal branch, or is this something that we need to add to production so it's easier for them to work with?
