### ISSUE TITLE
RSS link in Catalog search results is broken

### ISSUE THREAD

**Issue by sdellis** [pulibrary/orangelight#3419]
### Expected behavior
I'm not entirely sure what should happen if the RSS feed icon is clicked, but I assume it would point to an XML document that contains the search results. If users have RSS readers or browser extensions, those tools may know what to do with the data. When asked about the purpose of the feature, @escowles suggested it may be for being notified about or tracking new catalog resources that apply to the search terms the results were based on. 

<img width="786" alt="Screen Shot 2023-02-13 at 2 42 52 PM" src="https://user-images.githubusercontent.com/609368/218558459-ebbf76db-ac76-46b5-92d9-91db1d1ee686.png">

### Actual behavior
In Chrome, nothing happens when the RSS icon is clicked. In Firefox, the following error appears in the browser:

<img width="812" alt="Screen Shot 2023-02-13 at 2 37 20 PM" src="https://user-images.githubusercontent.com/609368/218558361-c854d4d3-acc6-4cb5-9743-021189674eaf.png">

### Steps to replicate
Perform a search in the Catalog and click the RSS icon.

### Impact of this bug
We don't track the use of this feature, so we can't know for sure. However, the impact is likely small, given that RSS is not used as much as it once was.

### Honeybadger link and code snippet, if applicable

```
```

**Comment by maxkadel** [comment]
Closed by #3417 - see also #3406
