### ISSUE TITLE
Stackmap specs are failing

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3428]
See https://app.circleci.com/pipelines/github/pulibrary/orangelight/3408/workflows/ac3be612-3726-4777-af3b-c71ec95932ba/jobs/9039 for an example failure.

**Comment by sandbergja** [comment]
I was able to reproduce this test failure locally, and can also recreate it in the UI on catalog-staging when the Firestone Locator FlipFlop is turned off.  Is this an issue with the vendor's JS?  If so, should we mark the specs as pending?

**Comment by maxkadel** [comment]
@sandbergja I think marking the specs as pending makes sense. Maybe we can also let them know their JS is broken?

**Comment by sandbergja** [comment]
We are waiting on the vendor to let us know when these javascripts are ready.

Once their js works, our tests will inform us that we need to remove the pending line.

**Comment by rladdusaw** [comment]
Take pending off of tests. Update language to match new button.
