### ISSUE TITLE
Request Selected Items button is active when pickup location is not selected

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/orangelight#3442]
### Expected behavior
A request for an item with no pickup location selected should not allow the request to be submitted.

### Actual behavior
For an item with a pickup location choice, when you select the checkbox but not the pickup location the "Request Selected Items" button becomes enabled. Submitting produces an error.

### Steps to replicate
Visit https://catalog.princeton.edu/requests/99117287933506421?aeon=false&mfhd=22624689900006421
Check the select box for an in process item
The "Request Selected Items" button becomes active.

### Impact of this bug
Users are able to submit an incomplete request that causes an error.

### Honeybadger link and code snippet, if applicable
https://app.honeybadger.io/projects/54399/faults/94055099
```
submission.rb  145  categorize_by_delivery_and_location(...)
[PROJECT_ROOT]/app/models/requests/submission.rb:145:in `categorize_by_delivery_and_location'

143 | item["type"] = "annex"
144 | elsif off_site?(library_code)
145 | raise Exception, "#{self.class}: Item does not have a delivery mode" unless delivery_mode(item)
146 | item["type"] = library_code
147 | item["type"] += "_edd" if edd?(item)
```

### Implementation notes, if any
The logic for enabling the button should include a check to make sure any item with a pickup location has a value.

**Comment by maxkadel** [comment]
This appears to still be an issue as of 8/30/2023 

[Honeybadger error](https://app.honeybadger.io/projects/54399/faults/94055099)
```
Exception: Requests::Submission: Item does not have a delivery mode

143 | item["type"] = "annex"
-- | --
144 | elsif off_site?(library_code)
145 | raise Exception, "#{self.class}: Item does not have a delivery mode" unless delivery_mode(item)
146 | item["type"] = library_code
147 | item["type"] += "_edd" if edd?(item)
```
