### ISSUE TITLE
Update "Partner Request Confirmation" email text message

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3443]
Request from Resource Sharing:

The current text is as follows:

Item sent to be requested from another Library. Requests typically are filled within two weeks when possible. If there is a problem fulfilling your request a member of our Library Staff will contact you. For more detailed information please login to your <a href="https://lib-illiad.princeton.edu/illiad/illiad.dll"<https://lib-illiad.princeton.edu/illiad/illiad.dll>>Illiad Account</a>. (Note: Your username and password is the same as the CAS)

Would it be possible to change it to the following?

This item will be requested from another Library. Most requests will arrive within two weeks. If there is a problem fulfilling your request a member of our Library staff will contact you. For more detailed information, please login to your ILLiad account with your University credentials:  https://library.princeton.edu/services/interlibrary-services

**Comment by maxkadel** [comment]
Question especially for @christinach and @sandbergja  - would this be more accessible if we adjusted the link text?

e.g.

> This item will be requested from another Library. Most requests will arrive within two weeks. If there is a problem fulfilling your request a member of our Library staff will contact you. For more detailed information, please <a href=https://library.princeton.edu/services/interlibrary-services>login to your ILLiad account with your University credentials</a>.

**Comment by christinach** [comment]
@maxkadel yes determining the link purpose would satisfy "WCAG21 2.4.4 Link Purpose (In Context) Level A": 
 https://www.w3.org/TR/WCAG21/#link-purpose-in-context 
https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=244#link-purpose-in-context
https://webaim.org/techniques/hypertext/link_text#text
