### ISSUE TITLE
Refused to display 'https://library.princeton.edu/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3456]
### Expected behavior
When click 'Where to find it' both stackmap and firestone locator should load the map.

### Actual behavior
When the page has both stackmap and firestone locator it errors with https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

### Steps to replicate
1. Load https://catalog.princeton.edu/catalog/9913366553506421 
1. Click on "Where to find it" under the first location ("Architecture Library - Reserve 3-Hour")
1. Check the console in dev tools

### Impact of this bug
The stackmap map will not load. 

### Error
`Refused to display 'https://library.princeton.edu/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

**Comment by christinach** [comment]
@kevinreiss this is for the stackmap

**Comment by maxkadel** [comment]
Also, when we match the feature flippers on staging to the ones on production (with the older Firestone Locator on), we do *not* see this bug, but the first item (the one with the bug) is in a different location on staging than it is in production.

Staging:
![The location of the broken object is "Architecture Library - Stacks"
(https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/43fadd58-01f7-488f-9433-c5735a4a7047)

Production:
![The location of the broken object is "Architecture Library - Reserve 3-Hour"](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/02938d8e-4e2d-407e-bec3-eeda729572cc)

**Comment by maxkadel** [comment]
The stackmap url comes from the `holdings_1display` in Solr (not from the bibdata availability response)

Production location in holdings_1display

```json
  "arch$res3hr": {
    "location_code": "arch$res3hr",
    "current_location": "Reserve 3-Hour",
    "current_library": "Architecture Library",
    "call_number": "HT166.I3",
    "call_number_browse": "HT166.I3",
    "temp_location_code": "arch$res3hr",
    "items": [same as staging]
  }
```

Staging holdings_1display

```json
  "22485327350006421": {
    "location_code": "arch$stacks",
    "location": "Stacks",
    "library": "Architecture Library",
    "call_number": "HT166.I3",
    "call_number_browse": "HT166.I3",
    "items": [same as production]
  }
```
