### ISSUE TITLE
At 125% zoom or higher publication year input is obscured on advanced search form

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3463]
### Expected behavior
I want to type in and see full digit years in the publication year option on the advanced search form. 

### Actual behavior
In the latest Chrome 110.0.5481.177 on OSX Big Sur. You can also see three of four input digits on the form input for Publication Year.
<img width="1572" alt="Screen Shot 2023-03-22 at 4 45 09 PM" src="https://user-images.githubusercontent.com/278825/227046392-3a9f9c92-10df-404f-a1e2-37fbf1ee38c6.png">

### Steps to replicate
Set browser to 125% zoom. Visit https://catalog.princeton.edu/advanced, type in a four digit year in the publication year form element. 

### Impact of this bug
The search still works you just can't see all characters.

**Comment by sandbergja** [comment]
This is also an accessibility issue: [WCAG says that you need to be able to zoom text up to 200%](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html) without loss of content or functionality.

**Comment by christinach** [comment]
Try to test this with a Zoom Magnifier Text tool.
