### ISSUE TITLE
Document Restoration of Solr Index and Database from Backup

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3476]
Add documentation covering these topics. Both the solr index and database have regular back-ups that could be used to return to a recent copy of production data if needed. 

Add the documentation for the following:
- [x] Where to find the most recent copy
- [x] How to restore the data to the production system. 
- [x] Test the restoration procedures on the staging system. 

Also check https://github.com/pulibrary/dpul/blob/3fc9512a5d50b25c971a3cf0ca6b17a91480457b/lib/tasks/replicate.rake#L17

**Comment by christinach** [comment]
See documentation on [how to restore the postgresql (1,2) backup from a google cloud snapshot using restic](https://github.com/pulibrary/pul-it-handbook/blob/main/services/restic_backup.md#restore-from-a-backup). This will result to a .sql file of the database. 
We need to document the psql command to upload the .sql file in the production db.
