### ISSUE TITLE
Add Current Hours At Holding Location to "Copies in Library" Display on Show Page

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#349]
The bibdata holding location contains a reference to the hours calendar id string for the containing library. The show page holdings block should leverage this and display the current open/closed status of the location (or at least link to the calendar). Example from bibdata at https://bibdata.princeton.edu/locations/holding_locations/ues.json: 

```
{
"label": "Architecture Library",
"code": "ues",
"aeon_location": false,
"recap_electronic_delivery_location": false,
"open": true,
"requestable": false,
"always_requestable": false,
"library": {
"label": "Architecture Library",
"code": "architecture"
},
"hours_location": {
"label": "Architecture Library",
"code": "architecture"
},
"delivery_locations": []
}
```

The "code" label can be addressed to https://library.princeton.edu/hours/{hours_location/code} to form the link to current calendar, example: https://library.princeton.edu/hours/architecture.

**Comment by christinach** [comment]
Closing as we no longer have the hours in bibdata.
