### ISSUE TITLE
Incorrectly structured html causes request form not to display correctly

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3498]
example: https://catalog.princeton.edu/requests/993569343506421?aeon=false&mfhd=22693661550006421
### Actual behavior

The location is plasma$nb
It has more than one items. Selecting the first radio button for physical delivery shows the html. 

![Screenshot 2023-04-07 at 8 44 04 AM](https://user-images.githubusercontent.com/9905193/230611400-4a9f80cb-4b11-429e-9cb9-8a08926be1bc.png)
 
### Expected behavior
For the specific item selecting the first radio button should display: 'Pickup location: Lewis Library' 

### Impact
User cannot request a specific volume.

**Comment by kevinreiss** [comment]
I checked the annex which has many serials and didn't see this issue.

**Comment by maxkadel** [comment]
Check whether issue might be in `app/helpers/application_helper.rb` and the use of `.html_safe`

**Comment by maxkadel** [comment]
For a test that fails for the right reason, see https://github.com/pulibrary/orangelight/tree/i3498_requests_html_bug

**Comment by maxkadel** [comment]
Closed by https://github.com/pulibrary/orangelight/pull/3625. Deployed to production 6/30/2023
