### ISSUE TITLE
856 Logic

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#35]
A few things here:

 * [x] When it is a link to a ToC, "Available Online" should not display (@joycebcat, I missed it in my notes, how do we know?)
 * [x] 856 $3 or $z should be anchor text for $u
 * [ ] Location code "elf<i>n</i>" means full text. "elf2" should indicate that this is online available to campus only _(Can we find a way to put this kind of logic should be in a config file?)_

**Comment by tampakis** [comment]
Also see #179

**Comment by tampakis** [comment]
Links in BL: https://github.com/pulibrary/orangelight/blob/development/app/helpers/application_helper.rb#L15-L18
https://github.com/pulibrary/orangeindex/blob/development/lib/traject_config.rb#L156 - remove the $2

**Comment by tampakis** [comment]
We have 856 under control, although the way elf2 is handled could be improved: https://pulsearch.princeton.edu/?f[location_code_s][]=elf2
Only 2 non-suppressed records at the moment though.
