### ISSUE TITLE
Test Blacklight 8 Upgrade with Unapi Gem

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3502]
Before deploying the Blacklight 8 upgrade, we should test this functionality.

We currently rely on a forked version of this gem to provide RIS export functionality to Zotero. Confirm if it works on BL8 or if there is an alternative path:

- [ ] Must have zotero plugin installed in your local browser and have the Zotero desktop client installed
- [ ] Try to import records from Catalog on the search results page
- [ ] Try to import a single record from the catalog show page. 

https://github.com/pulibrary/orangelight/blob/main/Gemfile#L72

**Comment by maxkadel** [comment]
Question: How heavily used is this functionality? Is it worth keeping?

**Comment by kevinreiss** [comment]
Zotero is something the librarians teach in their instruction workshops and I think based past feedback from librarians is pretty widely used particularly in the humanities/social sciences graduate students. To test this you need to install the Zotero desktop and the Zotero "connector" add-on for the browser you are using. The connector will scrap metadata off both the search results and the individual record page by clicking the add-on icon in the browser. ![Screenshot 2023-04-17 at 8.27.33 AM.png](https://images.zenhubusercontent.com/5cba088397df763a9090ce23/531ab53a-7459-4ee9-8053-c74b810dce14)

**Comment by kevinreiss** [comment]
On the record page:![Screenshot 2023-04-17 at 8.48.40 AM.png](https://images.zenhubusercontent.com/5cba088397df763a9090ce23/5bfe000a-7a8d-4892-bb8f-c8052a419dae)

**Comment by kevinreiss** [comment]
![Screenshot 2023-04-17 at 8.48.40 AM.png](https://images.zenhubusercontent.com/5cba088397df763a9090ce23/eb63e38f-c242-417b-852e-d5f7200bcf7f)

**Comment by kevinreiss** [comment]
![Screenshot 2023-04-17 at 8.48.58 AM.png](https://images.zenhubusercontent.com/5cba088397df763a9090ce23/e710d19f-8737-4e92-b992-7b9f7f7d5e2f)

**Comment by kevinreiss** [comment]
The dialog for search results shows all records displayed on the page:![Screenshot 2023-04-17 at 8.50.45 AM.png](https://images.zenhubusercontent.com/5cba088397df763a9090ce23/ed6baf9c-4654-4c87-9e24-8c0714ec811a)

**Comment by kevinreiss** [comment]
Tested successfully with Zotero and latest commit of Blacklight-marc gem 4/17/2023 per @christinach and @sandbergja.

**Comment by christinach** [comment]
See also issue https://github.com/pulibrary/orangelight/issues/178 and if possible close it.

**Comment by christinach** [comment]
Test this again after we upgrade to Blacklight 8.

**Comment by kevinreiss** [comment]
With the re-factor in #4153 this issue is no longer relevant as the blacklight_unapi gem is no longer in the project.
