### ISSUE TITLE
Users cannot request electronic delivery for ReCAP Locations

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3505]
### Expected behavior
When a user visits the request form for an item that offers both physical and electronic delivery from ReCAP they should be able to request other options. 

### Actual behavior
visit https://catalog.princeton.edu/requests/99115215833506421?aeon=false&mfhd=22703340470006421

![Screen Shot 2023-04-11 at 9.07.10 AM.png](https://images.zenhubusercontent.com/5cba088397df763a9090ce23/90fc0ae3-dc2a-4be4-9deb-a1e28ab66f56)

### Steps to replicate
Visit any request form for a recap item. Try and select an item for electronic delivery, fill in the metadata fields required, the Request button at the button page never activates, it does activate when you select physical delivery. 

A mult-item example: https://catalog.princeton.edu/requests/994246483506421?aeon=false&mfhd=22618136940006421

### Impact of this bug
No work around. 

### Implementation notes
Happens on both single and multi-item holdings. Appears to be only ReCAP locations, for example this Firestone item is fine: https://catalog.princeton.edu/requests/99118269913506421?aeon=false&mfhd=22722909750006421, multi-item holding is also at https://catalog.princeton.edu/requests/99126836834306421?aeon=false&mfhd=22961622130006421.

**Comment by sandbergja** [comment]
We haven't checked PUL records yet, just Recap records so far.

**Comment by christinach** [comment]
in progress work https://github.com/pulibrary/orangelight/tree/3505-electronic-delivery.
