### ISSUE TITLE
2 links on the home page don't need to open in a new tab

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3508]
### Steps to recreate

1. Go to the main page of the catalog
2. Click the "Statement on language in description" link
3. Click the "PUL Open Dataset" link
4. Note that both links open in a new tab

### URL

https://catalog.princeton.edu/

### Issues

[G200: opening new tabs only when necessary](https://www.w3.org/WAI/WCAG21/Techniques/general/G200).  It's not necessary for these links to open in a new tab

### Severity

Low

### WCAG Conformance level (A, AA, AAA)

AA

### User impact

Disorienting to users

### Recommended fix

Remove `target="_blank"`

### Acceptance criteria
- [x] These links don't open in a new tab

**Comment by maxkadel** [comment]
There is a separate partial for the Statement on language in description on the show page, that also opens in a separate tab - https://github.com/pulibrary/orangelight/blob/919ed9d529a71027cd1aead3928a6760ea7b86e2/app/views/catalog/_statement_on_language_in_description.html.erb
