### ISSUE TITLE
Call number display doesn't match browse

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/orangelight#351]
https://pulsearch-dev.princeton.edu/browse/call_numbers?search_field=browse_cn&q=m23.l5S6
https://pulsearch-dev.princeton.edu/catalog/1414145

Oversize materials do not display Oversize in the call number browse. Also, when you click Browse Call Number back from the above record, the item does not display.

**Comment by tampakis** [comment]
The call number browse link to the browse list works properly now (852 subfield $c is excluded from the browse keyword) as of #353. At the implementation group meeting, we decided for the time being to exclude the subfield $c from the call number browse display as well.
