### ISSUE TITLE
Users cannot request partner items for in-library use at Marquand

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/orangelight#3529]
### Expected behavior
Users should be able to request partner items

### Actual behavior
Users cannot request partner items requestable that are in-library use at Marquand library and don't offer electronic delivery options. 

### Steps to replicate
Occurs when requesting https://catalog.princeton.edu/catalog/SCSB-14299852

### Impact of this bug
Users don't have access to the resources.

### Honeybadger link and code snippet, if applicable

https://app.honeybadger.io/projects/54399/faults/95376613

### Implementation notes, if any

<img width="1297" alt="Screenshot 2023-04-20 at 1 38 48 PM" src="https://user-images.githubusercontent.com/5940563/233445216-f4345455-bd2d-46e0-b78c-4d2d2363c1d1.png">

**Comment by sandbergja** [comment]
An example in resource sharing.  The row is not selected, expected behavior is that is selected: https://catalog.princeton.edu/requests/SCSB-12077423?aeon=false
