### ISSUE TITLE
Publication information not included in citation when recorded in the 264 field in addition to the 260 field

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#3546]
### Expected behavior
When I click on the "Cite" button on a record, the basic metadata available for that record should be displayed in the three citation styles, including publication location and publisher. 

### Actual behavior
For newer records that use the RDA standard of recording the publisher information in the 264 field, rather than the 260, the citation does not include publisher information.

See the [original report of the issue](https://pulibrary.slack.com/archives/CA0UY0Q07/p1683294853354019).

[Example record](https://catalog.princeton.edu/catalog/99121975393506421)
![Citation lacking publication info](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/dd9103b4-2fff-4342-bb26-b6605f7fa596)

![Record of same work showing publication info](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/07524ee2-b031-44fc-a067-9c09a8bd5c5b)

### Steps to replicate
1. Go to https://catalog.princeton.edu/catalog/99121975393506421
2. Note that the record has information under "Published/Created"
3. Click the "Cite" button
4. Note that the citations lack publication information

### Further example records
* https://catalog.princeton.edu/catalog/99121129543506421
* https://catalog.princeton.edu/catalog/99125387422406421
* https://catalog.princeton.edu/catalog/99125387423606421
* https://catalog.princeton.edu/catalog/99127123592306421

### Impact of this bug
Citations are inaccurate and not as useful for newly cataloged works

### Implementation notes, if any
Per @sandbergja it may be most appropriate to do this work in the blacklight-marc gem, in [the citations code](https://github.com/projectblacklight/blacklight-marc/blob/main/app/models/concerns/blacklight/marc/document_export.rb), by adding 264_1 as an option for publication information.

**Comment by kevinreiss** [comment]
We will try submitting a patch to Blacklight-marc, then when that is in the gem updating OL to that version.

**Comment by sandbergja** [comment]
The fix has been merged upstream -- @rladdusaw will update the version of blacklight-marc that we use in orangelight.
