### ISSUE TITLE
Item in work order Preservation and Conservation cannot be requested through Resource Sharing

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3557]
### Expected behavior
An item which is not requestable should have the option to be requested through 'Resource Sharing'

### Actual behavior
Item displays with no Resource Sharing option

### Steps to replicate
Visit https://catalog.princeton.edu/requests/9942430233506421?aeon=false&mfhd=22600149340006421 

### Impact of this bug
Users cannot request the specific item.

### Notes
The specific item is in work order: 'Preservation and Conservation'.

```
```

### Implementation notes, if any
Check https://github.com/pulibrary/orangelight/blob/2b2de056363f912003a43dd98aff49bcfe6df795/app/models/requests/requestable/item.rb#L251

**Comment by kevinreiss** [comment]
This resource has a "nil" services value. it should be assigned the service name for "Resource Sharing".

**Comment by kevinreiss** [comment]
I think we want to make sure this requestable case is assigned the "ill" service: https://github.com/pulibrary/orangelight/blob/main/app/models/requests/router.rb#L104
