### ISSUE TITLE
Trigger Figgy's harmful content warning display automatically via record metadata

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#3560]
### User story

As a cataloguer I want to identify records which have harmful content and display a pop-up in the viewer to warn our patrons about what they might see.

### Acceptance criteria

- [ ] A record with a digitization in Figgy and marked with a harmful content warning in the MARC displays a pop-up warning them with the information that's in the MARC record.

### Concrete example

This is the MARC equivalent of https://findingaids.princeton.edu/catalog/C1372_c47202-68234

### Implementation notes, if any

When importing metadata records, Figgy looks for a key in the jSON-LD that is "content_warning", and if found automatically marks the viewer to display that content. An example:

https://findingaids.princeton.edu/catalog/C1372_c47202-68234.json

According to some prior discussion, this field would get pulled from 520 first indicator 4. We need to map this value into the "content_warning" field we expose. 

### Relevant Tickets

https://github.com/pulibrary/figgy/issues/5090

**Comment by mzelesky** [comment]
Here are 6 records with 520 fields with a first indicator of 4.
9990795563506421
99125167742806421
99125167742406421
99125167741906421
99125167726506421
99125167672406421

**Comment by kevinreiss** [comment]
@escowles will follow-up with Jennifer for more details on the conventions catalogers will follow for creating these notes.

**Comment by escowles** [comment]
Thanks for finding examples @mzelesky — I took a look at those, and the 520 notes are all more general summary notes than harmful content warnings. Here are links for easy review:

https://catalog.princeton.edu/catalog/9990795563506421/staff_view
https://catalog.princeton.edu/catalog/99125167742806421/staff_view
https://catalog.princeton.edu/catalog/99125167742406421/staff_view
https://catalog.princeton.edu/catalog/99125167741906421/staff_view
https://catalog.princeton.edu/catalog/99125167726506421/staff_view
https://catalog.princeton.edu/catalog/99125167672406421/staff_view

So I think the key question for DSSG is: How would we like to unambiguously identify our harmful content notes? We could include the URL of the harmful content statement in $u, and/or we could include NjP in $c.

**Comment by mzelesky** [comment]
Would DSSG only want the 520 1st indicator 4 fields to show on PUL records, or also on SCSB records?

Here is a report of all 520|4 fields: https://docs.google.com/spreadsheets/d/1X5-slibmZU0s7aqnVpYNjS0RUh9S-KozMF2Vhn-Z32U/edit?usp=sharing
