### ISSUE TITLE
Restrict automatic Google thumbnail import for Special Collections print materials records 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/orangelight#3570]
### User story
_As a researcher looking at online catalog records for print materials held in Special Collections, I may be confused by the thumbnail image automatically populated in the upper left corner of the record from Google. The thumbnail may be misrepresenting the year, edition, or item that is described in the record. It may influence whether I use, request for digitization, or discard the item in my research or may influence my decision to come to the library to view the item in person._ 

### An idea
What if we used the holding location codes for items as our map to define what "automatically populated by google" thumbnails should be enabled/disabled? This would be far easier than the idea of manually researching/selecting, ingesting, and adding thumbnails locally that represent the items in the catalog. If an item is important enough to have a thumbnail as a visual, perhaps it is important enough to be digitized in its entirety (then it would be automatically populated thanks to figgy ingest/completion). 

### Acceptance criteria

- [x] All "Aeon" locations in Bibdata data don't request a Google Book Cover Image.
- [x] Show the default cover image instead for these locations. 
- [x] Let SC Public Service staff know we are making this change. (Sara L. and Christa). 
- [x] I can successfully use this feature with Voice Over in Safari.
- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Concrete example
Eric White received a question from a researcher about the editions of Candide present in Special Collections, who was led astray by the thumbnails of the title pages present in the catalog. See [slack comment](https://pulibrary.slack.com/archives/CA0UY0Q07/p1671710840477119) and [a title search for early editions of Candide](https://catalog.princeton.edu/?f%5Baccess_facet%5D%5B%5D=In+the+Library&q=Candide&range%5Bpub_date_start_sort%5D%5Bbegin%5D=1759&range%5Bpub_date_start_sort%5D%5Bend%5D=1853&search_field=left_anchor). 

A specific example of different editions that have the same image are:
* https://catalog.princeton.edu/catalog/9924628093506421 ([Paris, Lambert] 1759.)
* https://catalog.princeton.edu/catalog/9924628083506421 ([Genève, Cramer] 1759.)

**Comment by kelea99** [comment]
Feedback from Will Noel - in person, in SC: This is a great idea. Having no thumbnail from google for the Special Collections Print materials.  Once an item is digitized and ingested into figgy, the thumbnail can be selected via order manager (if the default is not ideal) and  will be visible in the online catalog, and it will be an image from the actual item.  This proposal would solve the reported painpoint.

**Comment by christinach** [comment]
See older issue https://github.com/pulibrary/orangelight/issues/1478

**Comment by kelea99** [comment]
@christinach and @maxkadel - should #1478  be closed in preference of this one? We could note this ticket in the reason for closing? Especially since it was approved as preferable to show nothing vs. reviewing thumbnails pulled in from Google and to show something only if it is digitized for the SC print materials?

**Comment by maxkadel** [comment]
I'm tempted to continue to view them as separate issues - one is for any books that have the wrong cover, this is specifically about special collections materials, which have a somewhat different use case and rationale for hiding the Google book covers. 

Also, the solution suggested in #1478 is basically a blocklist of individual books, whereas this ticket is suggesting blocking entire locations.

**Comment by kelea99** [comment]
@christinach and @maxkadel thank you!  what you both recommend makes sense. What i hear as actionable is:

- Keep both tickets noted here open (agreed and done)
- Look through feedback queue for orangelight/issues to find other submitted tickets related to book covers  (who will do this? I can help here).
- both bullets are to be discussed at standup on 06/26/2023.

**Comment by christinach** [comment]
@kelea99 `Look through feedback queue for orangelight/issues to find other submitted tickets related to book covers (who will do this? I can help here).` sorry for the confusion -> I was referring to the catalog feedback queue and not the github tickets. I will filter these old closed tickets and reference any reported records I find with the wrong google book cover and not in special collections.

**Comment by minjiec** [comment]
Hi, @christinach, are you able to see the [LibAnswers](https://princeton.libapps.com/libapps/login.php?site_id=1685) Cataloging queue? I did discover a curious case of mismatched cover image (see ID 11634921 at the top)

Our Blacklight record somehow links to the cover of a self-published Amazon Kindle book with some similarity in the wording of the title. The book is not even available in Googld Books, so I don't know how the link is made. Our bib has a correct OCLC number; and no ISBN.

(A Harvard copy of the same title mis-linked to the same cover image back in early June when I first spotted the case, but has since been corrected with a wholesome image of the table of contents now that I recheck the record.)

Minjie

**Comment by christinach** [comment]
@minjiec based on the OCLC number google books return this cover page https://books.google.com/books?vid=OCLC1745235. 

I think you could use this form to request a correction on the cover https://support.google.com/websearch/troubleshooter/6113172?hl=en&url=https://books.google.com/books?vid=OCLC1745235&hl=en&v=G1F5CQAAQBAJ&is=atb&visit_id=638235480505539176-3125556337&rd=2#ts=6113305

**Comment by minjiec** [comment]
@christinach Google Books promptly solved the mismatched cover image. Our [Blacklight record](https://catalog.princeton.edu/catalog/9929787213506421), with a blank cover, looks alright now.
[[1-2703000034072] Your Google Support Inquiry_ Case ID.pdf](https://github.com/pulibrary/orangelight/files/11906257/1-2703000034072.Your.Google.Support.Inquiry_.Case.ID.pdf)

**Comment by christinach** [comment]
@minjiec thank you for letting us know!

**Comment by minjiec** [comment]
I just alerted books-library-support@google.com another mismatched cover issue, which affects PUL's record [All men are brothers](https://catalog.princeton.edu/catalog/9922865223506421). 

> The scanned resource, [a supreme court record](https://books.google.com/books?vid=OCLC1619175), is assigned the wrong OCLC number [1619175](https://worldcat.org/en/title/1516642), which is for Pearl Buck's translation titled _All Men are Brothers_. (This mis-linkage is slightly affecting my institutional library catalog record for _[All Men are Brothers](https://catalog.princeton.edu/catalog/9922865223506421)_, showing a wrong cover image there.)
> 
> The most likely match is OCLC#37912861, a title contributed by the [City University of New York (CUNY) library](https://cuny-al.primo.exlibrisgroup.com/permalink/01CUNY_AL/29tk2q/alma991010341379706121).

**Comment by minjiec** [comment]
Update: my previous alert to books-library-support@google.com has remained not addressed for 3 months. Today I sent another cover mismatch alert, responding to a patron's report via [LibAnswers](https://faq.library.princeton.edu/admin/ticket?qid=12267996).
![image](https://github.com/pulibrary/orangelight/assets/54282275/d198e778-2984-4591-a445-000e48b910b4)

This time I found a local solution without having to rely on Google Books. Because the cover image of our own copy has been scanned and stored in Figgy, I added a 856 ark address to the bib, and this overrode the mismatched cover fed by Google. The takeaway is, when push comes to shove, we can scan our own cover to block out the wrong image.

**Comment by caroldh** [comment]
We should resolve this one way or another. I defer to the comment by Will Noel dated May 19 - "Having no thumbnail from google for the Special Collections Print materials. Once an item is digitized and ingested into figgy, the thumbnail can be selected via order manager (if the default is not ideal) and will be visible in the online catalog, and it will be an image from the actual item. This proposal would solve the reported painpoint." Removing thumbnails from SC books might be simplest fix.

**Comment by minjiec** [comment]
Painpoint indeed. 

Even for [a book](https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=9914412023506421) of which we have scanned the cover, Blacklight still displays two versions (the actual one from Figgy or the Google thumbnail) randomly in the search results view, depending on my search criteria.

Correct thumbnail--
![image](https://github.com/user-attachments/assets/97fb6418-5e9b-4d27-9629-3912179fbf36)

Incorrect thumbnail--
![image](https://github.com/user-attachments/assets/2fbd8e9a-a242-485a-96c1-593c6078313a)

And when I click into the catalog record, the Google version takes precedence--
![image](https://github.com/user-attachments/assets/9a656199-dc78-47bd-ba3e-b279016099d0)

**Comment by maxkadel** [comment]
@minjiec - interesting! Could you share the searches you did to get the different thumbnails?

**Comment by minjiec** [comment]
Max, it's impossible to figure out the rhyme and rhythm of it. I have conducted the same searches, and the thumbnail images actually flip between the two versions as I refresh the pages. Never thought I would be able to watch a mini-anime show on Blacklight!

Try searches below, and refresh (F5) once or twice to see if the cover slips.
[Search 1](https://catalog.princeton.edu/?f%5Bauthor_s%5D%5B%5D=Travers%2C+P.+L.+%28Pamela+Lyndon%29%2C+1899-1996&q=mary+poppins&search_field=left_anchor&sort=pub_date_start_sort+asc%2C+title_sort+asc%2C+score+desc):
![image](https://github.com/user-attachments/assets/c8feef75-bd51-4e3a-bfb8-78ec28135852)

[Search 2](https://catalog.princeton.edu/?f%5Blocation%5D%5B%5D=Special+Collections&q=mary+poppins&search_field=left_anchor&sort=pub_date_start_sort+asc%2C+title_sort+asc%2C+score+desc):
![image](https://github.com/user-attachments/assets/4c1fd4a9-a2e1-43f8-9e19-deb0296fce94)

**Comment by maxkadel** [comment]
Ah, good to know! Thanks for the info @minjiec!
