### ISSUE TITLE
Add the rack-mini-profiler gem

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3573]
### Success criteria

- [x] The rack-mini-profiler is visible to developers in development
- [x] On staging, qa, and prod, the rack-mini-profiler is visible only to logged-in admin users
- [x] On staging and prod, we follow [the steps to enable this in a multi-server environment](https://github.com/MiniProfiler/rack-mini-profiler#access-control-in-non-development-environments).

**Comment by maxkadel** [comment]
What storage should we use in production and production-like environments? It looks like the suggested storage is Redis, but from what I can see Redis is not yet configured for Orangelight. 

See https://github.com/MiniProfiler/rack-mini-profiler#storage

**Comment by sandbergja** [comment]
We discussed this existing ticket: https://github.com/pulibrary/princeton_ansible/issues/2799

Our preferred approach would be to create a new Redis 6 box, and point Orangelight to it.

**Comment by maxkadel** [comment]
Deployed and tested on production
