### ISSUE TITLE
Cross-team discussion on solr performance

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3588]

**Comment by sandbergja** [comment]
We will bring this up in cross-ITIMS

**Comment by maxkadel** [comment]
Discussed in Cross-Team IT meeting, see [agenda for 5/26/2023](https://docs.google.com/document/d/1AllskD7tY3mGIc7qVqqs46zSVDGHXckFSl_G1BFJiUg/edit#heading=h.fwz47htecosy) for notes.
