### ISSUE TITLE
Load test the staging solr catalog collection

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3590]
Our goal for this ticket is to load test solr itself, not the application as a whole.  We'd like to know the thresholds (e.g. requests/second) at which performance starts to degrade.

Some possible tools:
- Seige
- JMeter

Success criteria

- [ ] Document how to do this, so that we can repeat it as needed.  If we use JMeter or Seige, we can save the configuration as a file and put it in a github repo to make this repeatable.  Here is a [JMeter example](https://github.com/curationexperts/jmeter-examples).
- [ ] Record the metrics as a benchmark.

This would be a good ticket to pair up on.

**Comment by maxkadel** [comment]
Started a [github repo](https://github.com/pulibrary/solr_load_testing) for JMeter tests

**Comment by sandbergja** [comment]
The benchmarking data is too big for Github! 😱  Let's create a new directory in Google Drive.

**Comment by maxkadel** [comment]
Screenshot of Datadog dashboard for duration of load test on staging - ![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/46d05741-f948-45e1-98bd-2d6c524bfe96)
