### ISSUE TITLE
Investigate impact of Zookeeper on Solr performance

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#3594]
See, for example, https://cwiki.apache.org/confluence/display/solr/solrperformanceproblems#SolrPerformanceProblems-SolrCloud - sections on Zookeeper.

**Comment by sandbergja** [comment]
Solr performance is much better with its new memory resources.  Since solr is no longer the bottleneck for catalog performance, we don't need to prioritize this investigation at this time.
