### ISSUE TITLE
Subject subfield display

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#36]
For now at least, should be separated by `--`. 

Do we want to try something similar SUL's SearchWorks, e.g. check out the behavior for the heading "Mathematicians > Great Britain > Biography" [here](http://searchworks.stanford.edu/view/3956599). The tool tips that show up when you hover over each subfield explain what's going on.

**Comment by tampakis** [comment]
Accomplished subject hierarchy highlight and  tooltips in #163 and #176.
