### ISSUE TITLE
Increase the document cache for Orangelight

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#3603]
This work will be done in the pul_solr repository

The document cache size should be more than 30,000 (see #3586)

**Comment by maxkadel** [comment]
See documentCache config for the catalog - https://github.com/pulibrary/pul_solr/blob/0b70cb2bb4714df7aae0d0910e9287a215800819/solr_configs/catalog-production-v2/conf/solrconfig.xml#L129-L131

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/pul_solr/pull/365/files
