### ISSUE TITLE
Remove the new_action_note_display Flipflop feature

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3611]
We have migrated to the new action note display, so we no longer need this feature.  We also no longer need any code that is called when this Flipflop condition is false, such as the following line in the catalog controller:

https://github.com/pulibrary/orangelight/blob/dbb2573d0d9a5dcb31bdaca13590bb644d81d35f/app/controllers/catalog_controller.rb#L358

### Success criteria

- [x] This flipflop feature is removed
- [x] Any code that is called when `Flipflop.new_action_note_display?` is false is removed
- [x] Update tests

### Related ticket

- https://github.com/pulibrary/bibdata/issues/2173, but since we are using FlipFlop, these two tasks can be done in either order.

### Implementation note
- Remove feature from [feature list](https://github.com/pulibrary/orangelight/blob/dbb2573d0d9a5dcb31bdaca13590bb644d81d35f/config/features.rb#L34)

**Comment by maxkadel** [comment]
Fixed by #3630

Deployed to production 7/7/2023
