### ISSUE TITLE
Redis requires database names to be numbers. We should put numbers in the env var.

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#3629]
See https://github.com/pulibrary/princeton_ansible/issues/4046 - string names don't actually work, it's probably using the default db, which is not great for shared architecture. 

It looks like the configuration is also duplicated in both `config/orangelight.yml` and `config/redis.yml`, and we should also resolve this duplication.

We believe we're using number: 0. Make that explicit or choose another number between 1 and 15. https://www.digitalocean.com/community/cheatsheets/how-to-manage-redis-databases-and-keys#managing-databases

**Comment by carolyncole** [comment]
I did not find the scholarsphere code.  As I suspected it has changed a ton... Here is the definition of a redis prefix: https://docs.spring.io/spring-data/redis/docs/1.8.0.RELEASE/api/org/springframework/data/redis/cache/RedisCachePrefix.html#:~:text=Due%20to%20the%20'flat'%20nature,caches%20or%20keys%20inside%20Redis).

That said it looks like that is not good practice: https://stackoverflow.com/questions/16819514/stats-of-elements-with-a-prefix-in-redis. It causes linear searching...

**Comment by maxkadel** [comment]
Miniprofiler, which is the main use case for Redis for Orangelight, works fine when logged in on staging.
