### ISSUE TITLE
Advertise open dataset

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#3638]
### User story
As a user harvesting data from Orangelight, I would like to know about the ability to download the dataset from https://catalog.princeton.edu/dataset (which may have the data that I am trying to get in a more convenient format (and lower impact on the service).

### Acceptance criteria

- [x] Add note to rate-limiting responses?
- [ ] Is there a header we could add to all responses?
- [ ] Could we add a meta tag or comment to all HTML responses?
- [ ] Can we add a comment to `robots.txt`?

**Comment by christinach** [comment]
We're waiting to see if this can be resolved in the nginx level https://app.zenhub.com/workspaces/dacs-work-cycle-board-571691cab409d8d821b873be/issues/gh/pulibrary/princeton_ansible/4073

**Comment by christinach** [comment]
Sending the rate limit is enough
