### ISSUE TITLE
Investigate availability display to be accessible for all users 

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3643]
Availability display exists in:
1. The search results
2. Record page 
3. Requests form

- [x] Assess/audit each place availability is displayed for accessibility. https://github.com/pulibrary/dacs_handbook/blob/main/Accessibility/audit_procedure.md
- [x] Create accessibility tickets for any accessibility issues you find.

**Comment by kevinreiss** [comment]
Discuss standup 12/4 will split into three investigate tickets.
