### ISSUE TITLE
Refactor numismatics advanced search using the built-in advanced search BL form

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3645]
The built-in advanced search form is included in BL 7 and BL 8.
Things to consider:
1. The queries will turn from q1, q2, q3 to [clause0], [clause1], [clause2] 
2. It uses view components rather the view partials. 
3. It will need a lot of work to make the form look as it does now.
4. It uses the json query DSL. This is the new way BL communicates with SOLR. This will require changes to the catalog controller.

### Acceptance criteria
- [ ] There is a new form
- [x] It is behind a feature flipper
- [x] It is ok if this form does not actually successfully perform a search - the search is blocked by changes in Solr / Blacklight

related to #3412

**Comment by maxkadel** [comment]
See also [https://github.com/pulibrary/pul_solr/issues/370](pul_solr issue to add new handler)
