### ISSUE TITLE
Stop using the solr LegacyBM25SimilarityFactory

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3647]
See #1958

We use the LegacyBM25SimilarityFactory in our schema.xml:

https://github.com/pulibrary/pul_solr/blob/9945ef4167f44acb277f02b0059fa9df992aee4d/solr_configs/catalog-production-v2/conf/schema.xml#L60-L67

This will be removed in Solr 9, so we will need to look into other ways to ensure relevancy.

Test all sets of PF and QF values and ensure scores are the same with both factories:

- [x] qf and pf
- [x] author_qf and author_pf
- [x] left_anchor_qf and left_anchor_pf
- [x] in_series_qf and in_series_pf
- [x] publisher_qf and publisher_qf
- [x] notes_qf and notes_pf
- [x] series_title_qf and series_title_pf
- [x] title_qf and title_pf
- [x] subject_qf and subject_pf

**Comment by sandbergja** [comment]
@rladdusaw wrote several test cases that check the specific scores that solr generates for different types of searches.  Adjust pf and qf values to make the scores consistent with the behavior under the legacy similarity factory.

**Comment by rladdusaw** [comment]
When the change was made from LegacyBM25SimilarityFactory to BM25SimilarityFactory they removed a [constant factor of 2.2](https://issues.apache.org/jira/browse/SOLR-13025?jql=text%20~%20%22bm25similarityfactory%22) from the denominator of the [equation](https://en.wikipedia.org/wiki/Okapi_BM25) used to calculate the scores. To keep the scores consistent and ensure that the order of search results are unchanged we need to reintroduce this factor into the boosts of our search fields.

To reproduce the scores exactly we are multiplying the qf and/or the pf values by 2.2. By benchmarking the values with tests using the legacy factory we can then determine which values we need to boost. So far the pf values always need to be boosted but sometimes the qf values need to remain unchanged.

**Comment by hackartisan** [comment]
A change in the denominator should impact all scores equally, resulting in lower scores but the same relative order. I'm curious why we need to ensure the score stays the same.

I believe there are a bunch of relevance ranking tests in the pul_solr codebase, are those not sufficient to ensure that the ranking stays good? I'm interested to hear your insights here since we're about to be building a new solr collection.
