### ISSUE TITLE
Use Symbols instead of Strings in URL Helpers

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#365]
This sort of deprecation warning should be dealt with. It appears numerous times when the test suite is run. 

```DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_catalog__search_form_html_erb__3788262371396974169_58485220 at /home/travis/build/pulibrary/orangelight/app/views/catalog/_search_form.html.erb:28```

**Comment by tampakis** [comment]
Fixed in #666.
