### ISSUE TITLE
Remove blacklight_advanced_search gem

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3679]
### Success criteria

- [x] The old versions of the advanced search and numismatics forms are removed
- [x] The feature flippers for the advanced search and numismatics forms are removed
- [ ] The blacklight_advanced_search gem is removed from the Gemfile.

**Comment by kevinreiss** [comment]
It's possible if we remove the advanced search gem from the query builder process, things may keep working.
