### ISSUE TITLE
Verify that the new numismatics form searches correctly

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3680]
### Implementation notes

* One possible approach would be to edit the existing numismatics tests to include an `allow` for Flipflop to enable the new form, similar to this:

Acceptance Criteria

- [ ] New  form is being tested by and is passing automated tests
- [ ] New form has been manually tested as well. 

https://github.com/pulibrary/orangelight/blob/b8a749802d46056d3c2787a27b02f5ad941e6a2c/spec/system/stackmap_spec.rb#L11

**Comment by rladdusaw** [comment]
Found one new issue https://github.com/pulibrary/orangelight/issues/3742
