### ISSUE TITLE
Verify that the new advanced search form searches properly

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3681]
### Implementation notes

* One possible approach would be to edit the existing advanced search tests to include an `allow` for Flipflop to enable the new form, similar to this:

https://github.com/pulibrary/orangelight/blob/b8a749802d46056d3c2787a27b02f5ad941e6a2c/spec/system/stackmap_spec.rb#L11

Acceptance Criteria

- [x] New  form is being tested by and is passing automated tests
- [x] New form has been manually tested as well.

**Comment by maxkadel** [comment]
Created issues:
- https://github.com/pulibrary/orangelight/issues/3734 
-
