### ISSUE TITLE
Move Flipflop out of controller

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#3695]
Right now the JSON query DSL flipflop is within the CatalogController, which means that it won't actually switch the feature unless the application server is re-started. 

We should move this into a helper or service, so that Flipflop works as expected, to ease testing and have more consistent behavior.

**Comment by rladdusaw** [comment]
Example code (Just don't start the method name with "get" to make Rubocop happy) https://github.com/pulibrary/orangelight/pull/3694/commits/13b1d340e6649f7c56c826d7890a66d70044a497
