### ISSUE TITLE
Removing a search constraint from a regular search raises RSolr error

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3704]
When using Blacklight and trying to remove a search constraint generated by regular search, raises 

```RSolr::Error::Http - 400 Bad Request Error: Error when parsing json query, expect a json object here, but found : null```

To Replicate
1. Pin your blacklight to https://github.com/projectblacklight/blacklight/tree/release-7.x
2. Activate JSON DSL Flipper
3. Active new Advanced Search Form Flipper
4. Do a keyword search in the basic form on the homepage
5. On search result screen remove a search constraint. I.e. "cats" in this screenshot. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWhTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dde837621e3cb7f6135844794dc9640a70aa4afe/Screenshot%202023-08-30%20at%2010.20.03%20AM.png)

Also see #3700.

**Comment by christinach** [comment]
@rladdusaw checked this and it works as expected.

**Comment by maxkadel** [comment]
Still an issue - on staging, because it's a production-like environment, instead of raising the error it creates a flash message that says 

> Sorry, I don't understand your search.

**Comment by maxkadel** [comment]
There is already an [issue](https://github.com/projectblacklight/blacklight/issues/3048) and [PR](https://github.com/projectblacklight/blacklight/pull/3057) for this problem. The PR is blocked by missing tests, and Ben Arminter (creator of the PR) has given me a thumbs-up to work on adding tests and trying to get it merged.

**Comment by maxkadel** [comment]
PR against the fork to add a test - https://github.com/barmintor/blacklight/pull/1

**Comment by maxkadel** [comment]
Fixed by https://github.com/projectblacklight/blacklight/pull/3074 and https://github.com/pulibrary/orangelight/pull/3735
