### ISSUE TITLE
Missing "Not Available" Status Labels for Alma

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3706]
Items are placed in Alma  "In Process" type of "Collection Development Office" and "Holdings Management" in Alma. These should be treated as not available and be routed to resource sharing for request. We must have missed accounting for these at some point. 

Example Item: https://catalog.princeton.edu/catalog/9914253073506421

Request form gives you the normal pick-up request options now. 

https://catalog.princeton.edu/requests/9914253073506421?aeon=false&mfhd=22616976310006421

# Implementation Notes
Believe this status needs to be added to:

https://github.com/pulibrary/orangelight/blob/5741b2abfe7ad68dab50d87b32ae5a70b3a999dc/app/models/requests/requestable/item.rb#L141

We will want to create a test for an item in this state.

**Comment by pmgreen** [comment]
Looked at this during circ checkin 8/30/23. Need to add:
- Collection Development Office
- Holdings Management
