### ISSUE TITLE
Include record location and availability in call number browse

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#372]
For unique call numbers (associated with only 1 record) it would be useful to include location and record availability.

From John Logan:
 > this list would be much more useful if the entries included information about location and availability. Let’s say that you’re working on Hamlet and want to see a list of books concerning that play. You search for the call number PR2807.B and get a great list of books, but you have to click on each item to find out whether the book is available and where it’s shelved.

**Comment by kevinreiss** [comment]
Isn't each call number that appears in the browse list associated with a single bib id? If that is the case pulling in the same data displayed on the search results list seems feasible.

**Comment by tampakis** [comment]
Yeah this wouldn't be that hard to implement. We might have to refactor the display a bit to fit the extra info, but the availability part should be as simple as just including the bib id in a data atrribute so the javascript knows where to prop the record status.

**Comment by jpstroop** [comment]
:+1: If we had a "hearts and minds" label, I'd apply it.
