### ISSUE TITLE
When a record is missing the app should redirect to the app 404 template.

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3732]
### Expected behavior
When a record is missing the application should redirect to the 404 with the message 'The page you were looking for doesn't exist.' which is in public/x404.html

### Actual behavior
The application is redirecting to the load balancer 404

### Steps to replicate
Load a random id in the catalog `catalog.princeton.edu/catalog/788744494949`

### Impact of this bug
Not user friendly. The user thinks that the app is broken.

### Honeybadger link and code snippet, if applicable

```
```

### Implementation notes, if any
The expected behavior broke recently.

**Comment by kevinreiss** [comment]
Possibly related to recent changes nginx to deal with handling errors from spiders.

**Comment by christinach** [comment]
closed in favor of https://github.com/pulibrary/princeton_ansible/issues/4258

**Comment by christinach** [comment]
proxy ticket https://github.com/pulibrary/princeton_ansible/issues/4258
