### ISSUE TITLE
[catalog-qa] When blacklight 8 features are enabled empty/keyword search does not work

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3739]
### Expected behavior
When I run an empty or keyword search I should get search results.

### Actual behavior
When I run an empty or keyword search I get the error 'Sorry I don't understand your search'

### Steps to replicate
Enable Blacklight features in https://catalog-qa.princeton.edu/features 
Run an empty or keyword search in https://catalog-qa.princeton.edu/

### Impact of this bug
Blocks Blacklight 8 upgrade

### Notes
This behavior is specific to catalog-qa with Blacklight 8 features enabled.

**Comment by sandbergja** [comment]
Fixed by deploying pul_solr to production.
