### ISSUE TITLE
Clearing a search field doesn't remove it from the search

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/orangelight#3742]
### Expected behavior
When a field is cleared that value is no longer passed to the search

### Actual behavior
After clearing a field the value is still passed to the search

### Steps to replicate
In the numismatics search select a field then clear it, perform the search and it is still being used as a search field.

### Impact of this bug
Search results are not correct until the facet is clicked off in the results page.

### Notes
This issue is specific to the Blacklight 8 upgrade. 
We don't see it in production.

**Comment by maxkadel** [comment]
Is this issue also present in the new advanced search form?

**Comment by kevinreiss** [comment]
I could not replicated this but did discover these two issues #3752 and #3753

**Comment by sandbergja** [comment]
We could not recreate this, so closing for now.
