### ISSUE TITLE
Define how to set up two choices in test and development environments such that they don't reflect in staging/prod.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#3746]
Part of #3744 

I need a way to add an algorithm that's only in test/development, and document that.
Also will need a way to add fixtures that will reflect algorithm changes.

**Comment by jrgriffiniii** [comment]
Fixtures are going to require a more detailed understanding as to how the algorithms are going to be implemented.

**Comment by tpendragon** [comment]
This is in FlipFlop. It may be in the future that we want configurable enabled algorithms, but right now we just need "can I switch at all" - we're closing this.
