### ISSUE TITLE
Wireframe an interface for switching algorithms.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#3747]
Part of #3744 

# Discussion Record

These were the questions we asked: 

Answer the question - where do we want to add this? The search bar? Where sorting is? Both?
What motivates a user to see and interact with the algorithm switcher?
"Not seeing the results you want? Try this!"
Add user stories here. Is this something we expect naive searchers to do, or more experienced searchers, do we want people to discover this feature fast or just be available and offer instruction so it's there?
How do we name the algorithms in a way that makes sense?
Wireframe some options here and pick one.

We decided on the most simple case: just something to switch between and communicate which is in use. The group will collaborate on its approval.

## Acceptance Criteria

Build a wireframe that shows an algorithm switcher next to the sort dropdown. The group will collaborate on approving it.

**Comment by tpendragon** [comment]
Add a success criteria here. "Create X wireframes and the group choose ones"

**Comment by carolyncole** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHV0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--011b0773f324e67a6961072c1e4ef9c63eb3b731/Screenshot%202023-11-07%20at%207.41.00%E2%80%AFAM.png)

**Comment by hackartisan** [comment]
This look like a good start! I'm looking at the other dropdowns and their labels give and indication of what the current selection is. So maybe this new one should say "Default relevance"? and then the other options would be like "Cat boost relevance"?

**Comment by carolyncole** [comment]
From meeting discussion:
![Screenshot 2023-11-07 at 11 22 57 AM](https://github.com/pulibrary/orangelight/assets/1599081/103a8d51-d015-4aac-851b-5ef5adad42e4)
![Screenshot 2023-11-07 at 7 41 00 AM](https://github.com/pulibrary/orangelight/assets/1599081/3ba342f6-00df-49b9-b31c-99b624293870)

**Comment by carolyncole** [comment]
Another version of the drop down list.  Also change the title to `Rank by` to match `Sort by`

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWEyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--505dd5eabb354c5dfd2d8fb40f8eb8a2dd0c053b/Screenshot%202023-11-07%20at%2011.22.57%E2%80%AFAM.png)

**Comment by carolyncole** [comment]
We are unsure if we can include the explanation text in the menu, but we like the above design.
