### ISSUE TITLE
Implement interface (frontend) for switching algorithms

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#3748]
Part of #3744 

Blocked by wireframes in #3747 

## Acceptance Criteria

The dropdown from #3747 should add a query parameter to the URL that defines the algorithm to use. See #3750 for reasoning.

The dropdown should not display if an advanced search is happening.

**Comment by tpendragon** [comment]
We chose this wireframe: https://github.com/pulibrary/orangelight/issues/3747#issuecomment-1802037349

**Comment by eliotjordan** [comment]
Similar work in Figgy: https://github.com/pulibrary/figgy/commit/435a59244392de4973557a0d7d18c9f21777831f
