### ISSUE TITLE
How should algorithm switching be implemented such that it goes into the code base?

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#3749]
Part of #3744 

We don't want to actually implement a secondary algorithm, so where can we get this code in such that it's a maintenance burden we're comfortable with? We don't want a long running branch from this work.

Options:

* Add it behind a feature flipper in the Catalog
* Add it to Blacklight (may be tough to get merged, and be blocked by Blacklight 8)
* ??

We're especially looking for feedback from DACS on this.

## Acceptance Criteria

Communicate with DACS and get confirmation that if we add a feature flipper that we can merge our PRs into main and they're okay with that maintenance burden.

**Comment by hackartisan** [comment]
I think the feature flipper is the best way forward. It is an accepted and well-understood pattern on the DACS team, and this feature is new enough that we're not even sure we're going to commit fully to it, so it seems premature to ask the Blacklight community to take on its maintenance.

**Comment by carolyncole** [comment]
Documentation PRs can be merged outside a feature flipper
Code PRs need to be behind a feature flipper
