### ISSUE TITLE
Text Field Values vanish when you edit an advanced search with Blacklight 8 Features Active

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3753]
With Blacklight features active:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjIwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d9d4ca16871ee70daf3f14c2bdebfe2eeb593b27/Screenshot%202023-09-19%20at%209.28.15%20AM.png)

Starting at the advanced search form run a keyword search for "dogs" with a library facet filter active

URL https://catalog-qa.princeton.edu/catalog?utf8=%E2%9C%93&clause%5B0%5D%5Bfield%5D=all_fields&clause%5B0%5D%5Bquery%5D=dogs&clause%5B1%5D%5Bop%5D=must&clause%5B1%5D%5Bfield%5D=author&clause%5B1%5D%5Bquery%5D=&clause%5B2%5D%5Bop%5D=must&clause%5B2%5D%5Bfield%5D=title&clause%5B2%5D%5Bquery%5D=&f_inclusive%5Blocation%5D%5B%5D=Special+Collections&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&commit=Search

Click Edit Search. The keyword value disappears from the form:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnkwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b83c439897e92e92e38637bbda291d1587f598cd/Screenshot%202023-09-19%20at%209.47.20%20AM.png)

**Comment by maxkadel** [comment]
Was not able to re-create issue.

**Comment by maxkadel** [comment]
Closed as non-reproducible.
