### ISSUE TITLE
bib linking profiles not present 787 and 776

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#376]
@tampakis Hi Nikitas, the equivalent of bib linking which you have done in BL is OK except that two profiles we have in Voyager are missing.  

787W to bib ID
and
776W to bib ID

Example record for the first profile is: 4153328 and for the second profile is: 4178285

**Comment by tampakis** [comment]
I currently only include OCLC numbers from 776/787 in the record linking mechanism. I'm a bit concerned about detecting whether or not the value in subfield $w actually corresponds to a bib id. For instance record [8638176](https://pulsearch-dev.princeton.edu/catalog/8638176) has DLC and OCLC numbers in those fields. Is there a way to know for sure? Can we assume that all values in 776W/787W are bib ids if they don't have a prefix surrounded by parentheses?

**Comment by joycebcat** [comment]
Ah, we don't want to use any numbers except those without a prefix.  Anything else can be ignored.
