### ISSUE TITLE
Evaluate Highlighting Features 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3762]
Review the capabilities of these two systems for supporting search highlighting. 

- [ ] Include pointers to any existing Blacklight documentation or example implementations for search highlighting. 
- [ ] Include pointers to existing documentation sample implementations on Solr's highlighting features.

**Comment by kevinreiss** [comment]
See

Does not appear to be built-in support for highlighting results in Blacklight
Gist by Chris Beer demonstrating highlightling implementation https://gist.github.com/cbeer/319834

Solr has documentation on highlighting search results https://solr.apache.org/guide/solr/latest/query-guide/highlighting.html

**Comment by tpendragon** [comment]
Add acceptance criteria

**Comment by kevinreiss** [comment]
This ticket was essentially research to support the implementation in #3795. Since we've accomplished that I'm going to close it.
