### ISSUE TITLE
Design the biased search results reporting form

### ISSUE THREAD

**Issue by kelynch** [pulibrary/orangelight#3777]
Part of #3761 

Utilize feedback page mockups from [this slide deck](https://docs.google.com/presentation/d/1ygrKEbRC3t5ppfWRdLpcOjv7LIrGwp8zaHeGIwukIEw/edit#slide=id.g20f5e26bc90_0_15).

* Review and decide on a wireframe to use (see https://github.com/pulibrary/orangelight/issues/3790)
* Define the preliminary fields of the form
  * Name (optional)
  * Email (optional)
  * Message (required)
  *  Search parameters (required, prepopulated with search parameters from the user)
* Define the text on the form
  * Use the text from the wireframe in the slide deck, minus the second sentence in the first paragraph (starts with "For example...") 
* Define the post-submission message of the form
  * Review the post-submission text for the harmful content form in Orangelight, and start with something like this. 
* Determine and design how the form looks and behave on the search results page
  * Starting with the orange banner approach

**Comment by kelynch** [comment]
Consider the pattern created by the Report Harmful Language form and its call to action at the record level, and what we could do to be appropriately in sync with this.

The form should explicitly include the information they are submitting, including contextual search results, search terms, parameters, facets, etc in a meaningful way.

**Comment by kelynch** [comment]
We decided not to provide preemptive examples of biased results to users, so as not to give them stereotype threat.  While this is in the mockups linked above, we do not intend to use this language.

**Comment by sdellis** [comment]
One thing that's been expressed by the implementation team is the desire to be consistent and use UI patterns for reporting harmful language that we already have in place. The team has pointed to the lower tray of "buttons" on the Finding Aids and the Catalog record/show pages as something users may be familiar with. 

I wonder if this is the best approach though? I find these buttons to be a bit hard to see. I wonder if we would include the "Ask a Question" and "Suggest a Correction" links, or if we would simply have one gray button for "Report Biased Results"? We can contrast the original mockup that has a "banner/announcement" pattern with the mockup that uses the existing UI "button tray" pattern for interacting with PUL Staff. My question is "Would one large Report Biased Results button at the bottom essentially serve as a less visible and descriptive banner?"

Thoughts?

New Mockup:
<img width="1049" alt="Screenshot 2023-10-25 at 9 37 52 AM" src="https://github.com/pulibrary/orangelight/assets/609368/406a1ee9-0835-4fd7-8426-58f9d905b6d8">

Original Mockup:
<img width="835" alt="Screenshot 2023-10-25 at 9 57 35 AM" src="https://github.com/pulibrary/orangelight/assets/609368/b0ae1de4-c336-43f9-8763-813a34c156d2">

**Comment by kelynch** [comment]
I can see the benefit of keeping the UI consistent with reporting harmful language as shown in the new mockup, however I agree that it's harder to see than the original and to me seem likely to be missed.  My instinct after looking at these is to use the "banner/announcement" pattern in the original mockup, as it's a) more visible and b) follows another related established pattern.  I'm interested in others' thoughts here.

**Comment by sandbergja** [comment]
I agree that the original wireframe provides more context, visibility, and clarity about what we want users to do.  I think we should implement it!

I think we should also make a long-term plan for the UI, too.  We wouldn't want to have the banner up forever or it could lose some of its impact.

Also, if we still have the banner saying "we are working to address bias" up, say, 3 years from now, and haven't actually made many visible improvements, the words could sound empty and we could break some trust with users.  That's not something the UI could fix, of course, but I wanted to bring it up.

**Comment by kelynch** [comment]
These are great ideas.  A long-term plan for the UI could be part of planning work for a follow up cycle on this.

**Comment by sdellis** [comment]
Mockups of Banner Placement on the Results Screen:

<img width="373" alt="Screenshot 2023-11-07 at 2 43 31 PM" src="https://github.com/pulibrary/orangelight/assets/609368/0e78159e-944d-4036-aed9-b20632a0470d">
<img width="1214" alt="Screenshot 2023-11-07 at 2 41 21 PM" src="https://github.com/pulibrary/orangelight/assets/609368/6f7ba2dd-57b9-41e4-a393-b7c9ade0648e">

These should now be actionable.

**Comment by sdellis** [comment]
Draft version of the Reporting Form is ready for feedback:

<img width="1106" alt="Screenshot 2023-11-08 at 2 02 56 PM" src="https://github.com/pulibrary/orangelight/assets/609368/6fe2c2a2-85ff-4221-ac62-f4c6612310d6">

**Comment by kelynch** [comment]
Both the banner and the form look great to me, thank you!

**Comment by sdellis** [comment]
Taking a second look, my only thoughts are: 
1) Don't include the Bookmark check boxes in the result set excerpt. Perhaps also don't include "Availability" indicator?
2) Either make it more clear that the results are an excerpt (just the top 3?) or make it so the user can scroll through all the results in case the biased results are further down.
3) We should probably display the search terms and selected facets along with the results set
4) If someone reports the second page of a result set biased, we don't show the top 10, but rather the set from that page.

**Comment by kelynch** [comment]
I agree on all points, for point #2 maybe allowing the user to scroll would be best, to ensure we're including the reported issue.

**Comment by sdellis** [comment]
Based on a discussion the team had during today's check-in, we are going to simplify the initial deliverable by creating a link to the search results the user is reporting on instead of re-creating/i-framing the search results in the form modal. This link should open a new tab to prevent the user from losing any content they may have entered in the form.

**Comment by kelynch** [comment]
Work ongoing for this in #3789
