### ISSUE TITLE
elf2 holding notes

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#378]
So I did a query on our [elf2 holdings](https://pulsearch.princeton.edu/?f[location_code_s][]=elf2) and it turns out we only have 2 records with that location code. One we came across yesterday. Both are missing links. @joycebcat  will any new records coming in be assigned that location code?

**Comment by joycebcat** [comment]
@tampakis We might get more things for elf2, but it is highly unlikely.  We have 100 suppressed records in addition to the 2 active records.  I'm going to look into them a little bit harder as well as check out the 803 plain elf objects to see what they are.

**Comment by tampakis** [comment]
It'd be a good idea to display the 852 $z for elf2 locations like in [8861649](https://pulsearch.princeton.edu/catalog/8861649):
```
z| Accessible from designated East Asian Library computers only 
```

**Comment by mzelesky** [comment]
Shouldn't they display for all locations, as it's a public note?

**Comment by tampakis** [comment]
We added logic to not display holding information for elf locations.

**Comment by jpstroop** [comment]
Currently only one record in elf2. @joycebcat any updates? Propose we review in January and act or close then.

**Comment by joycebcat** [comment]
We still need this location for this one particular object.  The note is important for users to see.  @tampakis would it help if I moved the note to 866 |z, or would that not make any difference on an elf* mfhd?

**Comment by tampakis** [comment]
None of the holding notes display for elf* mfhds currently. The easiest way to get that note to display without refactoring the code would be to move the note to a note field like the 506.
