### ISSUE TITLE
CDL Login Prompt delayed/not working at all for CDL items

### ISSUE THREAD

**Issue by kelea99** [pulibrary/orangelight#3788]
### Expected behavior
When I navigate to CDL items (like [this one]( https://catalog.princeton.edu/catalog/997310793506421) ), click on the link to "view digital content", and  scroll down to the bottom of the record in the grey boxed area, I expect a blue button to pop up that I can click on to log in and access the item.

### Actual behavior
Include screenshots, or links and browser version if relevant
When I navigate to some CDL items (like [this one]( https://catalog.princeton.edu/catalog/997310793506421) ), click on the link to "view digital content", and  scroll down to the bottom of the record in the grey boxed area, no blue button pops up that I can click on to log in and access the item. (See Video demo from student and staff)

https://github.com/pulibrary/orangelight/assets/45043014/29487751-0cc0-4345-8152-27ea1e5366d6

### Steps to replicate

1. Go to: https://catalog.princeton.edu/catalog/997310793506421 in incognito window.
2. Click on "View Digital Content"  in holdings
3. does the blue button appear for you?

### Original Slack information from Firestone Public Services colleague, Carol Houghton

> _Hi Kim! I got several CDL titles - recently scanned books- to experiment with. I really didn’t run into problems myself. Couple of titles took maybe 5 seconds for digital checkout banner to show up. But not terribly slow. But I have permissions for figgy so don’t have the same user experience as normal patrons. I had a desk student try and one title was fine but one didn’t load. I took a video…._

### Impact of this bug
E.g. "I can't work until this is fixed" or "I have a workaround"
users cannot access our materials via CDL for some of these items and therefore cannot use those items in their research.

### Honeybadger link and code snippet, if applicable

```
```

**Comment by kevinreiss** [comment]
If we need another example: https://catalog.princeton.edu/catalog/99125533238106421. this one came in a recent catalog feedback ticket.

**Comment by kelea99** [comment]
More information from Public services today, @kevinreiss : They tested a CDL book on a student's computer in Safari and when she clicked view digital content, the blue banner thing did not load at all. she switched to Chrome and it did appear, though very slow to appear in the blank gray screen. Can we check the different browsers as well?

**Comment by kevinreiss** [comment]
I've checked Chrome, Firefox and Safari myself (on mac at least) and seen it appear very quickly in all three of them, other times it's very slow. I'm not sure this is a browser specific issue given the intermittent nature of the problem. It seems that fact it sometimes works fine, sometimes it takes forever to display, or even sometimes never renders suggests that the series of ajax actions that render the button perform very inconsistently.

**Comment by kevinreiss** [comment]
Each CDL item seems to require four ajax actions to complete to display successfully. I think we need to drill into way we sometimes have a set of conditions where they don't or take forever. 

<img width="1185" alt="Screenshot 2023-10-26 at 3 41 02 PM" src="https://github.com/pulibrary/orangelight/assets/278825/eed534b0-9d27-4883-87df-7e3124547c34">

**Comment by kevinreiss** [comment]
The first one from bibdata is an Alma api related action, where we've always seen a lot of variability in response time.

**Comment by kevinreiss** [comment]
Figgy ultimately renders the Blue Button, so I suspect at least one of the the actions marked "graphql" are ultimately not returning any data in some cases.

**Comment by kelea99** [comment]
Id assume the alma related action can't really be improved re: speed/consistency. are we at the mercy of the host for that one?

**Comment by kevinreiss** [comment]
The only way to improve it is to not do it.

**Comment by kevinreiss** [comment]
Waiting to hear some more info from DLS ticket investigation.

**Comment by tpendragon** [comment]
@kevinreiss I'm going to close our ticket. We've made the blue box appear pretty quickly. It still takes a while for the viewer to appear - to speed that up I think you'd have to speed up getting the CDL flag.

**Comment by kevinreiss** [comment]
Sounds good @tpendragon.

**Comment by kelea99** [comment]
Feedback from Carol H. and her students! 

> _I found 3 random titles to try and had my two students at the Info Desk try accessing them from their laptops - the initial time for the “status” to load in blacklight is still slow (that is nothing new, and not unique to the CDL titles!) but the “view digital content” link was super quick! yay!_

**Comment by kevinreiss** [comment]
Closing this and will investigate improving the situation with loading the CDL under https://github.com/pulibrary/bibdata/issues/1996
