### ISSUE TITLE
Choose Solr Highlighting Option

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3795]
Solr offers three options for highlighting: https://solr.apache.org/guide/solr/latest/query-guide/highlighting.html#choosing-a-highlighter. Select an option and update blacklight to pass these values to solr. It looks like all options are compatible with the version of Solr we run. 

1. Unified
2. Original 
3. FastVector

- [x] Working group for the feature agrees on the option. TBD tomorrow 11/7/23.
- [x] Implement the selected option as query parameters passed by blacklight to solr
- [x] Create any supporting tests using the example queries "Black Teenagers" or "White Teenagers"

# Implementation Notes
See #3762 for the team's work/notes to date.

**Comment by christinach** [comment]
Solr documentation, [Unified option](https://solr.apache.org/guide/solr/latest/query-guide/highlighting.html#unified-highlighter).
According to the documentation it looks like the unified option is the one to choose and implement. The last paragraph confused me a little bit but I hope that adding the unified option highlighting doesn't mean that we ignore the boosted fields. Most likely the specs (related to boosted fields) will let us know. : 
```
The Unified Highlighter is the newest highlighter (as of Solr 6.4), which stands out as the most performant and accurate of the options. It can handle typical requirements and others possibly via plugins/extension. We recommend that you use this highlighter as a first choice.

The UH highlights a query very accurately and thus is true to what the underlying Lucene query actually matches.

A strong benefit to this highlighter is that you can opt to configure Solr to put more information in the underlying index to speed up highlighting of large documents; multiple configurations are supported, even on a per-field basis. There is little or no such flexibility of offset sources for the other highlighters. More on this below.

There are some reasons not to choose this highlighter: Passage scoring does not consider boosts in the query. Some users want more/better passage breaking flexibility. The "alternate" fallback options are more primitive.
```
