### ISSUE TITLE
Highlight Search Terms in the Main Entry Fields

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3796]
### User story
As a user I would like to understand the context for my search results better by seeing my search terms highlighted in the main entry fields of records returned in my search result. 

### Acceptance criteria

- [x] Highlighting in main entry field resides behind a feature flipper.
- [x] Review current schema and see where the following fields are indexed, see https://pul-confluence.atlassian.net/wiki/spaces/ALMA/pages/1770331/MARC+fields+indexed+in+Blacklight. Confirm they are dynamic fields, see https://github.com/pulibrary/pul_solr/blob/main/solr_configs/catalog-production-v2/conf/schema.xml#L535. 
- [x] Include 100 Field 
- [x] Include 110 Field
- [x] Include 111 Field
- [x] Include 130 Field 
- [x] Search terms are highligted in the title statement
- [x] I can successfully use this feature with Voice Over in Safari. https://github.com/pulibrary/orangelight/issues/3825
- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Concrete example
Example queries to use in development/tests "Black Teenagers", "White Teenagers". 

### Implementation notes, if any
Mock-ups: https://www.figma.com/file/tIpQVIoflo4znSX2lMcHt8/Search-%26-Race-Group-2%3A-Highlighting-Mockups?type=whiteboard&node-id=0-1 

Fields need to be add here: https://github.com/pulibrary/pul_solr/blob/main/solr_configs/catalog-production-v2/conf/solrconfig.xml#L135.

**Comment by kevinreiss** [comment]
Update ticket with accessibility checks see ticket #3803

**Comment by rladdusaw** [comment]
Aside from voiceover not indicating emphasis everything seems to be working.
