### ISSUE TITLE
Select "emphasis" style for search highlighting 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3803]
### User story
As a user I would like to see search terms highlighting reinforcing why a result was returned for my query. 

### Acceptance criteria 
- [x] Decide which style to use
       * Background color 
       * Underlining
       * option1: Use background color in the search results and underlining in the record page
       * option2: Use underlining in both the search results and the record page. (Benefit: Starting at the lowest level of highlighting we can test if the underlining meets the success criteria or if the highlighting needs to be more prominent)
- [ ] Search terms are highlighted consistently. 
- [x] I can successfully use this feature with Voice Over in Safari. https://github.com/pulibrary/orangelight/issues/3825
- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Concrete example
Black teenagers or White Teenagers can be used for example records/automated tests. 

### Implementation notes

Wireframes: https://www.figma.com/file/tIpQVIoflo4znSX2lMcHt8/Search-%26-Race-Group-2%3A-Highlighting-Mockups?type=whiteboard&node-id=0-1

**Comment by christinach** [comment]
In our standup 11/6/23 we decided that we will start with the underlining option.

**Comment by kevinreiss** [comment]
Choosing italics text with a background color, implement something that passes color contrast. See color picker in figma wireframe.
