### ISSUE TITLE
Check to see if we need to integrate highlighting into engineering RequestHandler

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#3820]
Here's the draft PR: https://github.com/pulibrary/pul_solr/pull/374

### Acceptance Criteria

Highlighting is in every search handler or none of them.

**Comment by kevinreiss** [comment]
This is added here: https://github.com/pulibrary/pul_solr/blob/main/solr_configs/catalog-production-v2/conf/solrconfig.xml#L132-L135. @tpendragon can this one be closed?
