### ISSUE TITLE
[Search results] Create a Snippet in Search Results Page to Display Subject or Note Fields

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3829]
### User story
As a user I would like context for why a record matched in our query and would like to see subject or notes fields containing terms highlighted on search results. 

### Acceptance criteria

- [x] Create a single snippet returned to the search results page that contains any subject access or notes fields that contain highlighted query terms. 
- [x] Search terms in the snippet are highlighted with the strategy in #3803. See wireframe https://www.figma.com/file/tIpQVIoflo4znSX2lMcHt8/Search-%26-Race-Group-2%3A-Highlighting-Mockups?type=whiteboard&node-id=0-1 subject access fields and note fields. 
- [x] I can successfully use this feature with Voice Over in Safari.
- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/orangelight/pull/3841
