### ISSUE TITLE
some 77x fields not displayed

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#385]
At least some of the 77x fields are not displaying.  I found 780s and 785s which do display (and are linked), and a 776 the same, but the 775 on this record does not display:
9496768

We should review what is/isn't displayed and or linked and rationalize the list.

**Comment by tampakis** [comment]
@joycebcat I've added that to tomorrow's agenda. 775 doesn't display in Voyager/Primo either. BTW, how do you do BIB lookup in Voyager again?

**Comment by joycebcat** [comment]
@tampakis I sent a separate message out to LISSC+ about V and Primo.  You do a Command KW search for "brid" followed by a space and then the number.  You have to choose the Command KW index from the list or it won't work.
