### ISSUE TITLE
Library Use Only ReCAP locations Should be Requestable for "In Library Use" only

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3853]
### Expected behavior
When I visit a Library Use Only ReCAP record I should only be able to request the materials for "In Library Use". Some locations like Eastasian "QL" do behave likes this, some Eastasian "PL" do not. 

### Actual behavior
Vist https://catalog.princeton.edu/requests/99126860826906421?aeon=false&mfhd=22966468740006421 

### Steps to replicate
Visit a record located in Eastasian "PL" and click request. 
### Impact of this bug
Impact is low since items won't actually be circulated, but this could be confusing to users since right now these items look like standard recap requests. 

### Implementation Notes
In bibdata all recap_rmt holding locations are marked as "circulates" true so I don't think that flag is the cause of the inconsistency. Locations I think are impacted are: PB, PK, PL, PM, PN, PS, PT, PW.

**Comment by christinach** [comment]
We noticed that the item type policy is different among items in the same location. @kevinreiss will bring this up to @mzelesky and Marie Wange-Connely.

**Comment by kevinreiss** [comment]
Marie needs to look into this further. Will research if there any locations that actually should have both CLOSED and GEN items.

**Comment by kevinreiss** [comment]
Spoke with Marie and Mark about this at the circ meeting today, we can close this ticket. If we see this problem again, the item records need to be checked and marked as NoCirc. We don't need to adjust the code to handle this case.
