### ISSUE TITLE
Browse for the "ayn" character is off

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3864]
### Expected behavior
Browse indexes should work consistently for the "ayn" character. 

### Actual behavior
Reported by [Joyce Bell](https://pulibrary.slack.com/archives/CA0UY0Q07/p1700144259062799) - "The indexing around the "ayn" character has been off for over a month. If I do a browse search for "ibn al-arabi" vs. "ibn al-ʻarabī" I get to different spots in the index. Same with "ibn ʻAbd al-ʻAzīz" vs. "ibn Abd al-Azīz"."

### Steps to replicate
Run a browse search for the examples from Joyce's report. 

https://catalog.princeton.edu/browse/subjects?search_field=browse_subject&q=ibn+al-arabi
https://catalog.princeton.edu/browse/subjects?search_field=browse_subject&q=ibn+al-%CA%BBarab%C4%AB

https://catalog.princeton.edu/browse/subjects?search_field=browse_subject&q=ibn+%CA%BBAbd+al-%CA%BBAz%C4%ABz
https://catalog.princeton.edu/browse/subjects?search_field=browse_subject&q=ibn+Abd+al-Az%C4%ABz

Both of the above pairs should take you to the same place in the subject browse index. 

### Impact of this bug
No real workaround. 

### Implementation notes, if any
We confirmed browse index cron jobs are running successfully on their schedule.

**Comment by sandbergja** [comment]
This behavior changed between postgres 11 and 12.  So, when we upgraded from Postgres 10 to 13, the alphabetization changed.

I verified this by `podman run -it -p 1234:5432 -e POSTGRES_PASSWORD=password postgres:12`, then `psql -h localhost -U postgres -W -p 1234 < ~/Desktop/ayin-tester.sql` with the following "ayin-tester.sql" file.

```
CREATE TABLE strings (string text);
INSERT INTO strings VALUES ('ibn al-arabi'), ('ibn al-ʻarabī'), ('ibn al-arabi'), ('ibn ʻAbd al-ʻAzīz'), ('ibn Abd al-Azīz');
SELECT * FROM strings ORDER BY string;
--- Expect ibn Abd al-Azīz and ibn ʻAbd al-ʻAzīz to be next to each other
```
