### ISSUE TITLE
Numismatics form - submit button should render the index result page

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3874]
### Expected behavior
When I'm in the numismatics form and submit an empty query or using the query fields of the form I expect to see the results page or no results. 

### Actual behavior
When I'm in the numismatics form and submit an empty query or using the query fields of the form the application redirects me to the homepage.

### Steps to replicate
Go to the numismatics form submit an empty query. The application will redirect you to the homepage.

**Comment by kevinreiss** [comment]
@christinach I just tried this myself and was taken here when I clicked submit with no filters selected:

https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&advanced_type=numismatics&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&f1=all_fields&q1=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search
