### ISSUE TITLE
Audit Accessibility of Availability Display on Search Results 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3878]
- [x] Assess/audit each place availability is displayed for accessibility. https://github.com/pulibrary/dacs_handbook/blob/main/Accessibility/audit_procedure.md
- [x] Create accessibility tickets for any accessibility issues you find.

**Comment by christinach** [comment]
https://docs.google.com/spreadsheets/d/1cbn0-jq_I3_lth7rVKZ508yUUXEXr95B1Tfhqz8xMsw/edit#gid=0

**Comment by christinach** [comment]
[Accessibility audit - Availability in Catalog search results_12_15_2023](https://docs.google.com/spreadsheets/d/1cbn0-jq_I3_lth7rVKZ508yUUXEXr95B1Tfhqz8xMsw/edit#gid=0)
