### ISSUE TITLE
Investigate Accessibility of Availability Display on Request Form

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3880]
- [x] Assess/audit each place availability is displayed for accessibility. https://github.com/pulibrary/dacs_handbook/blob/main/Accessibility/audit_procedure.md
- [x] Create accessibility tickets for any accessibility issues you find.

**Comment by sandbergja** [comment]
The availability display is great on the request form from an accessibility perspective.  I noticed [three other accessibility issues](https://docs.google.com/spreadsheets/d/1l-I50q8APh1m4naCt5dSdNvKUa9ZwQhe-e-5t9ip4ic/edit#gid=0).
