### ISSUE TITLE
Catalog Site Reports HTTP 400 Errors

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3896]
### Expected behavior
Users visit the catalog and receive the load balancer default error screen. A HTTP 400 error is recorded for them until they completely clear their browser cache. 

### Actual behavior
Include screenshots, or links and browser version if relevant

### Impact of this bug
E.g. "I can't work until this is fixed" or "I have a workaround"

### Implementation notes, if any
See [our troubleshooting notes](https://docs.google.com/document/d/1irv4XN10Ttzs162kbnM7wgJOHyhIeUrtml_Sf9SXrQw/edit#heading=h.bolcr07r0ift)

Related [pull request](https://github.com/pulibrary/princeton_ansible/pull/4530) in princeton ansible

**Comment by sandbergja** [comment]
Next thing to check: meet with Alain to see how the cookies are getting added.  The cookies can be found in the application tab of the dev tools.  Remember to check the cookie limit in the browser in the Chrome settings. See if the on-campus network is involved?  Or if the cookies are coming from library sites or different *.princeton.edu sites that we don't control (we would have to reach out to them).

**Comment by kevinreiss** [comment]
@christinach and I met with Alain and couldn't identify any pattern to the cookies beyond some set by Princeton single sign on services seem large. Not really sure where to take this. Alain will take a screenshot of cookies and their sizes if he encounters the error again.

**Comment by kevinreiss** [comment]
Submit an advisory ticket to OIT saying we had to adjust buffer sizes to deal with cookies set for *.princeton.edu, most of which appeared related to our campus IDP, idp.princeton.edu.

**Comment by kevinreiss** [comment]
Asked under REQ0421808.

**Comment by kevinreiss** [comment]
Response from OIT:

```
This problem is typically caused by applications that redirect back to themselves multiple times, adding more cookie data or GET URLs each time. We've already increased the maximum headers size allowed by the SSO systems as much as we dare, but the problem still happens occasionally. Clearing browser caches or using new/private/incognito browser instances may temporarily work around the problem, but we cannot prevent all applications from misbehaving. At best, we can ask vendors to fix their applications.```

**Comment by kevinreiss** [comment]
Discussed at 12/15. Closing this OL ticket in favor of more general follow-up in https://github.com/pulibrary/dacs_handbook/issues/154.
