### ISSUE TITLE
Name-title entries showing up in "related names"

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#39]
If there is a `$t` in a 7xx, shouldn't it be something else?

E.g. in http://pulsearch-dev.princeton.edu/catalog/489972 we have:

```
700 1_ $a Wedekind, Frank, $d 1864-1918. $t Erdgeist
700 1_ $a Wedekind, Frank, $d 1864-1918. $t Büchse der Pandora
```

Correct me if I'm wrong, but would it work to do this:

"Related works:" for `700 1_` with a `$t`
"Contains:" for `700 12` with a `$t`
(else) "Related names:" (perhaps further limited by relator)

**Comment by tampakis** [comment]
Closed by pulibrary/orangeindex#8
