### ISSUE TITLE
Fake EDD Request Appears in Production SCSB. 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3910]
### Expected behavior
When the OL test suite is run it should not actually place live requests in a system. 

### Actual behavior
Fake EDD requests for a test suite item and fake patron appear in the production system. 

<img alt="Example of fake request in production system" width="1688" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0pvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1841b425d6d4bf0cfb48fe27e5e6635e07bb3773/Screenshot%202023-12-15%20at%202.31.56%E2%80%AFPM.png" alt="Screenshot 2023-12-15 at 2.31.56 PM.png" />

### Steps to replicate

1. See if a "real" API key is being passed in the test environment. 
2. Run the test suite
3. Check SCSB production to see a request for this barcode is presented. 

### Impact of this bug
This has happened five times. Staff can cancel the requests when they appear. 

### Implementation notes, if any
Item is [referenced in the request controller cassette](https://github.com/pulibrary/orangelight/blob/82fc3026d75d491d2c27902521a024f69cdbd027/spec/cassettes/request_controller.yml#L610-L647) and in a [controller spec](https://github.com/pulibrary/orangelight/blob/82fc3026d75d491d2c27902521a024f69cdbd027/spec/controllers/requests/request_controller_spec.rb#L105-L128).

**Comment by christinach** [comment]
We've found an issue and followed up with the vendor.

**Comment by christinach** [comment]
Vendor fixed the issue.
