### ISSUE TITLE
Investigate Blacklight::Exceptions::ECONNREFUSED in the solr layer

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3911]
### What maintenance needs to be done?

We get `Blacklight::Exceptions::ECONNREFUSED` from Solr for basic queries (e.g. simply retrieving documents).  We should investigate why the Catalog and Bibdata sometimes gets a Connection Refused when they try to query solr.

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?

Because it prevents users from accessing the catalog in a very unpredicatable way.  It may also be indicative of a larger problem.  It can cause data to be missing from the catalog if it happens during indexing.

### Acceptance criteria
 - [x] Investigate to see if it's something about solr
 - [x] Investigate to see if it's something about our solr boxes
 - [x] Investigate to see if it's something about the network

### See

* [example orangelight honeybadger](https://app.honeybadger.io/projects/54399/faults/102440643)
* [example bibdata honeybadger](https://app.honeybadger.io/projects/54497/faults/103044592/)

**Comment by rladdusaw** [comment]
These errors correlate to the load balancer configuration updates

**Comment by christinach** [comment]
see https://github.com/pulibrary/princeton_ansible/issues/4596
