### ISSUE TITLE
Remove the located_in_an_open_library? concept from requests

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3915]
### What maintenance needs to be done?

Remove the [located_in_an_open_library?](https://github.com/pulibrary/orangelight/blob/82fc3026d75d491d2c27902521a024f69cdbd027/app/models/requests/requestable_decorator.rb#L68-L70) concept from requests.  All libraries are now considered to be "open", so it is no longer needed. 

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Timeline

It would be good to remove this before refactoring the request specs, because it will simplify that work.

### Why is this maintenance needed?

Remove some unnecessary complexity in requests.

### Acceptance criteria
 - [ ] This #located_in_an_open_library? method and list of open libraries are removed from the code
 - [ ] Any tests that consult this method and determine that a library is closed are removed from the code
 - [ ] Any tests that consult this method and determine that a library is open have their descriptions updated to remove mention of "open libraries" or "closed libraries"

**Comment by christinach** [comment]
When I removed the located_in_an_open_library? method it fell back to the help_me? method. Also in the code we’re checking if the item has a barcode. If it doesn’t then it is not eligible for library services. Is this still true?

Discussed this in our checkin today (1/3/24). @kevinreiss confirmed we are not using the help_me? method any more and that if an item does not have a barcode it should still be eligible to request.
