### ISSUE TITLE
Orangelight ga cookie has .princeton.edu as its domain

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3918]
### Expected behavior

Catalog sets google analytics cookies for the catalog.princeton.edu domain on prod, catalog-staging.princeton.edu, and catalog-qa.princeton.edu on qa.  This means that the user's browser will only send the ga cookies when the user visits the catalog, not other princeton sites.

### Actual behavior

The ga cookies has the .princeton.edu domain instead, so the browser still sends them even when you visit other Princeton sites.

### Steps to replicate

1. In Firefox, visit the catalog.
2. In devtools, open the storage tab
3. Open Cookies
4. Notice that the orangelight session cookie has the correct domain, and that the google analytics cookies have .princeton.edu

### Impact of this bug

Cookies are sent when they don't need to be

### Implementation notes, if any

* [Google documentation](https://developers.google.com/tag-platform/security/guides/customize-cookies#change_cookie_domain)

**Comment by kevinreiss** [comment]
Related to: https://github.com/pulibrary/dacs_handbook/issues/154
