### ISSUE TITLE
Update Twitter Icon in Footer

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3927]
### What maintenance needs to be done?
Either update to "X" or remove the twitter icon in the site footer. 

### Level of urgency
- [ ] High
- [ ] Moderate
- [x] Low

### Why is this maintenance needed?
Twitter no longer exists, we still have the twitter icon in the footer, do we want to change that to X or remove it entirely? The Library is still posting on "X" somewhat regularly.

### Acceptance criteria
 - [ ] Replace twitter icon with X icon.

**Comment by christinach** [comment]
Since the library website has it, I think we should keep it.

**Comment by christinach** [comment]
This is not needed anymore. We're using the Lux footer
