### ISSUE TITLE
Orangelight failing tests

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#3930]
Last commit was on Friday January 5th. The tests were passing.

January 9th : [Circleci is failing](https://app.circleci.com/pipelines/github/pulibrary/orangelight/4407/workflows/5eb0d646-623c-4da9-9b1e-bfac3966c8a9/jobs/14944?invite=true#step-120-43302_74)

```
rspec ./spec/features/requests/request_spec.rb:383 # request form a Princeton CAS user When visiting an alma ID as a CAS User allows CAS patrons to request an on-order item
rspec ./spec/features/requests/request_spec.rb:1449 # request form An Alma user allows a physical pickup request of ReCAP Item
rspec ./spec/features/requests/request_spec.rb:1455 # request form An Alma user allows a physical pickup request of a - Library In Use - ReCAP Item
```

**Comment by rladdusaw** [comment]
The test on line 383 is passing before this commit https://github.com/pulibrary/orangelight/commit/07ae5d5bf3db33afa1efdb5814f2b36c185fac78
