### ISSUE TITLE
Can't log in via CAS when running locally

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3936]
### Expected behavior
When I run orangelight locally, I can log in and see my bookmarks

### Actual behavior
When I try to log in, it takes me to CAS, I enter my credentials, I am returned to Orangelight, but I am still not logged in to Orangelight.

### Steps to replicate

1. Start rails server locally
2. Go to http://localhost:3000/bookmarks
3. Click the sign in link
4. Enter CAS credentials if prompted
5. Note that you are not yet signed in to the catalog

### Impact of this bug

Devs can't access feature flipper or other features behind authentication.

### Implementation notes, if any

This is a regression caused by #3932.

**Comment by christinach** [comment]
resolved by [Fix CAS Login for local development](https://github.com/pulibrary/orangelight/pull/3937)
