### ISSUE TITLE
Error requesting Resource Sharing item

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/orangelight#3948]
### Expected behavior
A request should be made

### Actual behavior
The request causes an error

### Impact of this bug
User is unable to request item

### Honeybadger link and code snippet, if applicable
https://app.honeybadger.io/projects/54399/faults/103856161
```
NoMethodError: undefined method `[]' for nil:NilClass delivery_location.values.first[:contact_email] ^^^^^^^^^^^^^^^^</div>
70 | return I18n.t('requests.on_shelf.email') if library_code == "firestone"
-- | --
71 | delivery_location = Requests::BibdataService.delivery_locations.select { \|_key, value\| value[:library][:code] == library_code }
72 | delivery_location.values.first[:contact_email]
73 | end
74 | end
```

### Implementation notes, if any
Assign this location: https://bibdata.princeton.edu/locations/delivery_locations/12
- [x] https://github.com/pulibrary/bibdata/issues/2304

**Comment by kevinreiss** [comment]
In the stacktrace you see the user requested vol E. which is actually available for a regular pick-up request.

**Comment by christinach** [comment]
resolved by https://github.com/pulibrary/bibdata/pull/2305
