### ISSUE TITLE
Additional holdings on search results page differ for Alma vs. SCSB holdings

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#3960]
### Current display
See below from the [search results page for the issn for the journal Science](https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=0036-8075)
![First result has italic text, the second result has a grey button and different text](https://github.com/pulibrary/orangelight/assets/45948126/88a03717-92f3-4cf3-9416-e7ae50ca532e)

### Desired display
- The display should be the same for additional holdings regardless of whether it is SCSB or Alma record

### Acceptance criteria
- [ ] It is a button with a pointer on hover.
- [ ] It is always a grey, with the text "View Record for Full Availability"
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

**Comment by ellen-aa** [comment]
See #3824 - can these be looked at at the same time?
