### ISSUE TITLE
Unavailable SCSB Items should use the same label values as PUL Items

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3963]
### What maintenance needs to be done?
Our availability labels for items that are checked are not consistent at the moment on either the search results page or the catalog individual record page. Items from SCSB partners that are not available state "checked out" instead of "unavailable" on the search results.  On the individual record page SCSB partner items display a label of "Not Available". In both cases the label should be "Unavailable". 

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
Use label values consistently to minimize user confusion. 

### Acceptance criteria
 - [x] SCSB Partner Items (records starting ID values beginning with SCSB-) that are not available for loan display a badge of"unavailable" on the search results page. 
 - [x] SCSB Partner items that are not available for loan display a badge of"unavailable" on the individual record page. 

### Implementation notes, if any
First resolve [bibdata#2142](https://github.com/pulibrary/bibdata/issues/2142)
Then confirm that the [bibdata#2142](https://github.com/pulibrary/bibdata/issues/2142) fix resolves this ticket
Example search results page: https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=beach+stories+by+the+sand+and+sea
Example record page: https://catalog.princeton.edu/catalog/SCSB-3870091

**Comment by christinach** [comment]
closed and improved by https://github.com/pulibrary/bibdata/issues/2142 and https://github.com/pulibrary/orangelight/issues/4001
