### ISSUE TITLE
Timeout error sending email in illiad.rb

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/orangelight#3973]
### Expected behavior
When a user submits a request it is created successfully

### Actual behavior
There is an error being generated in sending the email from illiad.rb

### Impact of this bug
The user might not be able to request the item

### Honeybadger link and code snippet, if applicable

```
227 | return
-- | --
228 | when :wait_readable
229 | (io = @io.to_io).wait_readable(@read_timeout) or raise Net::ReadTimeout.new(io)
230 | # continue looping
231 | when :wait_writable
```

**Comment by kevinreiss** [comment]
Closing as this an example of the broad issue under review.
