### ISSUE TITLE
Items in the Resource Sharing Library Don't Display Availability

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3978]
### Expected behavior
When an item is unavailable I expect the availability displays in the catalog to display the red "unavailable" badge. 

### Actual behavior
When an item is in not available because it is charged out to the resource sharing library no status is displayed at all, the search results page badge never advances beyond loading and nothing is displayed at all on the catalog page. 

### Steps to replicate
Go to https://catalog.princeton.edu/catalog/9910266103506421 and observe the availability section
Go to https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=9910266103506421.

### Impact of this bug
It's confusing. the reocod page shows a request button no availability badge, the search results page never loads availability for the MMS ID. 

### Implementation Notes
See bibdata availability response: https://bibdata.princeton.edu/bibliographic/availability.json?deep=true&bib_ids=9910266103506421
<img width="1986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2ZoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0291f785d9b11c70299926374fd0bc62758434c/Screenshot%202024-03-14%20at%203.24.50%E2%80%AFPM.png" alt="Screenshot 2024-03-14 at 3.24.50 PM.png" />

I think this is a global issue, but further spot checking should be done to confirm.

**Comment by christinach** [comment]
This is a known issue and it has to do with the mismatch of the holding location between the indexed record and the availability javascript call. As soon as the record is reindexed the status will display.
See [temporary location documentation](https://github.com/pulibrary/bibdata/blob/main/docs/temporary_locations.md)

**Comment by kevinreiss** [comment]
Given that the availability call returns unavailable and seems to say there is a temp location condition is there any reason we just can't display that? I understand the indexed data is behind which is why we see nothing in the UI. Or would trying to do something cause more problems. I think this issue may be magnified by the seeming wider variance we are having in terms of when items get indexed lately.

**Comment by kevinreiss** [comment]
@christinach and I investigated this issue and it's magnified during periods when publishing jobs are skipped or slow because of irregularities in the alma batch job cycle. This condition shows up during the period when a record is moved to the temp location in Alma but has not yet been indexed by Orangelight.

**Comment by christinach** [comment]
@kevinreiss can we close this ticket. The availability will display as soon as the record will get reindex. See [temporary location documentation](https://github.com/pulibrary/bibdata/blob/main/docs/temporary_locations.md)
