### ISSUE TITLE
Examine CAS Logout

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#398]
Can CAS be configured to go stale after a certain period of time.

**Comment by kevinreiss** [comment]
This devise module might be useful here, http://www.rubydoc.info/github/plataformatec/devise/master/Devise/Models/Timeoutable.

**Comment by escowles** [comment]
It's easy to configure the session cookies to expire after a certain amount of inactivity.  How long should the session stick around without activity?  An hour? A day? A week?  Since they never timeout now, I'm leaning towards the longer end of that range.

**Comment by tampakis** [comment]
A day sounds reasonable to me

**Comment by kevinreiss** [comment]
Timeouts are good and in order, but @tampakis If I remember the complaint that generated this was the proverbial "I'm on a public terminal terminal, forgot to close the browser and someone else is seeing my library account." That is a problem with all CAS enabled services, I'm not sure if a timeout really can address that problem.

**Comment by tampakis** [comment]
Well, I don't think there's anything we can do about a user forgetting to close the browser other than making sure the public terminals themselves are always in private browsing sessions and that they automatically close after a certain period of inactivity (like 10 minutes).

Now I am remembering another aspect of this that did come up during the user testing. When users choose to sign out, they should also be signed out of CAS. I'm going to open up another issue for that.

**Comment by jpstroop** [comment]
Yeah, public terminals are the problem. We should have a timeout as well, but clicking "log out" should destroy the cookie. Is there an option for not setting a cookie in the first place as well (force users to tick a box if they want to stay logged in? I have no idea how that works).

**Comment by kevinreiss** [comment]
I agree, before we say replace the Main Catalog links in our public terminal images we should check what our default policies are for private browsing/browser inactivity timeouts. This is an old problem for a new system (this issue has been around since Borrow Direct went under CAS years ago).

**Comment by escowles** [comment]
In theory, I think you can customize the expiration of the cookie.  But in practice it'll be hard because the user is logging into CAS, not our apps.  So we don't have a place to capture that decision.
