### ISSUE TITLE
Display FaST Subject Headings

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4003]
- [x] Fast Headings are displayed in their own distinct section under "Details" on the record page
- [x] Label for section can be "FaST Subjects"
- [x] This section is NOT linked as browsing options like LCSH (at least as part of this ticket)
- [ ] QA on Display in Orangelight.

**Comment by kevinreiss** [comment]
We've already implemented the bibdata side of this ticket and staff in CaMS are considering doing more cataloging with FaST.

**Comment by maxkadel** [comment]
Example record - 9979775553506421
