### ISSUE TITLE
Add citation for SCSB Records

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#4012]
### User story
As a researcher who will be citing SCSB records  I want to easily copy and paste a citation into my document

### Acceptance criteria
- [x] Display 'Cite' button
- [x] Update the code to build the citations for  SCSB records
- [x] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

### Concrete example

See the title at[ this link](https://catalog.princeton.edu/catalog/SCSB-5789141) from Columbia's holdings (SCSB) as an example. You cannot cite, nor export to a bibliographic management system (e.g. Zotero). 

### Implementation notes, if any
Related to https://github.com/pulibrary/orangelight/issues/4124
- Investigate using [citeproc-ruby](https://github.com/inukshuk/citeproc-ruby)

**Comment by christinach** [comment]
related to https://github.com/pulibrary/orangelight/issues/4124

**Comment by maxkadel** [comment]
I tried citeproc-ruby and ran into some problems. 
a) I could not figure out why, but when using the MLA format, it did not add the delimiter between the last and first names. This could be a bug or driver error?
b) The publisher is not in the Solr record without the place of publication, which is needed for most MLA book citations.
c) Again, this could be my own error, but I can't get all the fields I need without another call to Solr. At that point in the code, the fields included in the document are very minimal.

**Comment by maxkadel** [comment]
Closed by #4427
