### ISSUE TITLE
Investigate - Certain Marquand Stacks Items are not Requestable for Physical Delivery

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4017]
The outcome of this ticket should be a further ticket for fixing this bug (this ticket is just to understand the behavior better).

### Expected behavior
Marquand remote storage items should be able to be requested for physical and electronic delivery.

### Actual behavior
Some items are only requestable for electronic delivery. 

### Steps to replicate
Pull up the request form for any of these four Alma barcodes:

32101025842038 - https://catalog.princeton.edu/requests/9917246853506421?aeon=false&mfhd=22497122020006421
32101080737925 - https://catalog.princeton.edu/requests/9920270733506421?aeon=false&mfhd=22592461030006421
32101025671833 - https://catalog.princeton.edu/requests/9917081153506421?aeon=false&mfhd=22704104010006421
32101000111136 - https://catalog.princeton.edu/requests/991824813506421?aeon=false&mfhd=22678070550006421
 

### Impact of this bug
Users can't make a phyiscal request of items in this state. 

### Implementation notes
These four barcodes are items that have been de-accessioned from the clancy off-site storage facility. The are all in Marquand stacks. All items here should be requestable for physical delivery unless on order/in process. This is not a global issue for all items in the location, something is being processed oddly for items like the examples. This came up while investigating what the state of items will be during the period of approximately Feb. 2025-August 2025 when ALL items will be de-accessioned and moved back to the stacks in Marquand, but the Library itself will remain closed. During this time all items need to be requested and moved over to Marquand's Firestone location. The Library itself re-opens in August 2025. 

(The unique aspect of these items is that they used to be in Clancy, and are no longer in Clancy. By February 2025 there will be many items in this state.)

**Comment by rladdusaw** [comment]
All of these items have been deaccessioned:

"status":"Item has been Deaccessioned on 02-20-2024"

When Orangelight checks them to see what options to display it falls into the online only category.

**Comment by kevinreiss** [comment]
Anything with a status of "Not Found" in Clancy (even de-accessioned items) is returning true.
