### ISSUE TITLE
When possible, create a dropdown to select chapter titles for EDD

### ISSUE THREAD

**Issue by sdellis** [pulibrary/orangelight#4018]
When there's a value in the 505 field, break on double dashes to offer a dropdown in the EDD form for Chapter Titles. This could be a stretch, but the usability tests show that this content is generally consistent when present and could be used more effectively.

**Comment by christinach** [comment]
Create a new ticket to display the table of contents in the request form. @kevinreiss

**Comment by kevinreiss** [comment]
closing in favor of https://github.com/pulibrary/orangelight/issues/4060
