### ISSUE TITLE
Investigate why "Exception: Requests::Submission: Item does not have a delivery mode" have returned

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#4027]
### Expected behavior

We do not ever see this error, since #3266 does not allow users to submit the form without choosing a delivery mode.

### Actual behavior

We [still receive this error in honeybadger](https://app.honeybadger.io/projects/54399/faults/104024956/)

### Steps to replicate

We have not yet been able to replicate the issue.  Here are the specific forms that have raised this issue:

- https://catalog.princeton.edu/requests/9923789943506421?aeon=false&mfhd=22512302470006421
- https://catalog.princeton.edu/requests/SCSB-8493465?aeon=false&mfhd=8649819
- https://catalog.princeton.edu/requests/SCSB-7312748?aeon=false&mfhd=7409534
- https://catalog.princeton.edu/requests/SCSB-7666984?aeon=false&mfhd=7800626
- https://catalog.princeton.edu/requests/995649483506421?aeon=false&mfhd=22552842250006421
- https://catalog.princeton.edu/requests/991790103506421?aeon=false&mfhd=22602227270006421

One possibility is that the users do some workaround with their own Javascript, but it's come from a variety of patrons with different user agents, so this doesn't seem very likely.

### Impact of this bug
E.g. "I can't work until this is fixed" or "I have a workaround"

### Honeybadger link and code snippet, if applicable

* [Honeybadger link 1](https://app.honeybadger.io/projects/54399/faults/104024956)
* [Honeybadger link 2](https://app.honeybadger.io/projects/54399/faults/111353360/01J7BV2R0B9PZNJ1ZZD5407S4M)

```
elsif off_site?(library_code)
          raise Exception, "#{self.class}: Item does not have a delivery mode" unless delivery_mode(item)
          item["type"] = library_code
```

**Comment by rladdusaw** [comment]
This error can be replicated if you first select the first item's delivery location and then check select checkbox for the second item. The javascript then enables the submit button allowing an invalid request to be submittted.
