### ISSUE TITLE
es6 over coffeescript

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#403]
Convert custom coffeescript/js code over to es6. @tpendragon did you run into major hiccups in doing this for plum?

**Comment by tpendragon** [comment]
https://github.com/pulibrary/plum/pull/169/files That's basically all it takes. To use all of ES6' features you'll need https://github.com/pulibrary/plum/commit/87c9436a16e7a1c9f35fde112c95a92a68bdb655#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R98 and https://github.com/pulibrary/plum/commit/87c9436a16e7a1c9f35fde112c95a92a68bdb655#diff-a9c3bd311eab80c9ebe6a69830f9ad02R13 too.

**Comment by tpendragon** [comment]
The big things to remember are: Indents don't matter in ES6, so you have to use `{}` to separate things out. Parentheses are required in `if` statements. There are no implicit returns in ES6, so you have to `return` at the end if you want a value to come out. There's a "fat arrow" in ES6 so `() =>` in Coffeescript becomes `() => {}` in ES6, but there's no skinny arrow equivalent for quick functions. So `() -> ` in Coffeescript becomes `function() {}` in ES6.

**Comment by tampakis** [comment]
Thanks for this information @tpendragon. Doesn't seem like much of a pain to convert.

**Comment by tampakis** [comment]
availability and book covers

**Comment by tpendragon** [comment]
@christinach Why'd you close this? There's still several coffeescript files.

**Comment by christinach** [comment]
I couldnt see them. I see coffeescript in package.json and yarn lock

**Comment by christinach** [comment]
https://github.com/pulibrary/orangelight/blob/main/app/assets/javascripts/book_covers.js.coffee
https://github.com/pulibrary/orangelight/blob/main/app/assets/javascripts/bookmark_all.js.coffee
