### ISSUE TITLE
Edit Search in advanced search makes it hard to remove the currently selected facet

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#4050]
### Expected behavior

When I press "Edit search", it's easy to remove a facet I've already selected.

### Actual behavior

It is odd and unintuitive.

### Steps to replicate

1. Go to advanced search
2. Select scsbhl as a location
3. Press search
4. Press Edit Search
5. Try to remove scsbhl and select scsbcul instead.  Note that it is difficult and unintuitive.

### Impact of this bug

Annoyance for user, it's easy to think you removed it but it didn't, so you get unexpected search results.

**Comment by kevinreiss** [comment]
Choose to modify existing JS in OL rather than replacing it with a entirely new component.
