### ISSUE TITLE
Review Labels

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4079]
- [x] Combine duplicate labels
- [x] Delete outdated labels (i.e. Alma related labels)
- [x] Add a description for every label

**Comment by christinach** [comment]
@kevinreiss I've added a description in all the labels and deleted many of them. Can you please take a look https://github.com/pulibrary/orangelight/labels?page=1&sort=name-asc

**Comment by kevinreiss** [comment]
These all look good to me. Closing the issue. Thanks for reviewing them @christinach.
