### ISSUE TITLE
Clarify how facets work from main search vs. advanced search in the help page

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#4080]
### Current display
The different behavior of the advanced search facets is not clear from the Advanced Search page.

When facets are added from the main search page, they are used as "AND" searches. When facets are added from the Advanced Search page, they are used as "OR" searches.

When a user does a regular search with facet limits, then edits the search, taking them to the Advanced Search page, the facets on the right side of the page do not reflect the facets they selected. This is actually correct behavior, since we don't want to automatically change an "AND" search to an "OR" search, but it's not clear to users that this is what's happening.

The facet constraint is reflected in the "Within search" section, but does not display as a facet in the "Limit results by" dropdown section, even when it's a facet that is present there.
![image](https://github.com/pulibrary/orangelight/assets/45948126/1944d766-8c9e-4bdd-a6c9-2f57b77270a3)

#### Steps to replicate
- Go to root of application
- Under "Limit your search" in the "Access facet, select "In the Library"
- Click "Edit search"
- Note that "Access:In the Library" is present in the "Within search" section, but not within the "Access" facet on the right side of the page.

### Desired display
Something that makes it clear to the user that the facets selected on the right side of the Advanced Search page will function differently from the facets selected from the main search (as "OR" facets, rather than "AND" facets), and that this is why they do not appear in the already selected facets when editing a search.

### Acceptance criteria
- [ ] Describe this behavior of the facets on the advanced search in the help page

### Notes

Sample simple search: https://catalog.princeton.edu/?f%5Blanguage_facet%5D%5B%5D=English&f%5Blanguage_facet%5D%5B%5D=Sanskrit&f%5Blocation%5D%5B%5D=ReCAP&per_page=100&q=india&search_field=all_fields&sort=pub_date_start_sort+asc%2C+title_sort+asc%2C+score+desc

Replicating that in Advanced Search: <img width="1242" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjVOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c45e8572bb970260d681ea8f2c47d3a23ae0f0a/image.png" alt="image.png" />

Search results from Advanced Search (where it is an OR search, not an AND search): https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&q1=india&op2=AND&f2=author&q2=&op3=AND&f3=title&q3=&f_inclusive%5Blanguage_facet%5D%5B%5D=English&f_inclusive%5Blanguage_facet%5D%5B%5D=Sanskrit&f_inclusive%5Badvanced_location_s%5D%5B%5D=ReCAP&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&search_field=advanced&commit=Search

**Comment by ellen-aa** [comment]
The fact that these work differently actually seems very useful. Carol and I are not sure how we could be explicit about the difference between the two outside of teaching a user by showing an example.

**Comment by maxkadel** [comment]
@ellen-aa  - I'm wondering whether this would be a good question / collaboration with the UX team?

**Comment by ellen-aa** [comment]
@maxkadel - Yes, that's a great suggestion. Carolyn Cole also mentioned possibly describing this on the Help page, which Christina added to the Acceptance criteria so we don't forget.
