### ISSUE TITLE
Upgrade to Bootstrap 5

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#4081]
### What maintenance needs to be done?

Migrate from Bootstrap 4 to Bootstrap 5

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### EOL upgrade

[Bootstrap 4's end of life was January 1, 2023](https://getbootstrap.com/docs/4.6/end-of-life/)

### Why is this maintenance needed?
- We shouldn't rely on EOL software
- [Blacklight is considering stopping support for bootstrap 4](https://github.com/projectblacklight/blacklight/issues/3211)
- Bootstrap 5 removes a dependency on jquery, which could allow us to do the same
- Bootstrap 5 includes accessibility improvements

### Acceptance criteria
 - [ ] We use Bootstrap 5 instead of 4
 - [ ] The site largely functions and looks the same

### Implementation notes, if any

Current versions of Blacklight support both bootstrap 4 and 5.

[Migrating to v5](https://getbootstrap.com/docs/5.0/migration/)

**Comment by kevinreiss** [comment]
Draft PR: https://github.com/pulibrary/orangelight/pull/4446
