### ISSUE TITLE
Search results page is missing facets with new features enabled

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#4106]
### Expected behavior

The search results page has the following facets on the left side, whether or not the new Blacklight 8 features are turned on:

- Access
- Library
- Format
- Publication year
- Language
- Subject: Topic
- Subject: Genre
- Subject: Era
- Recently added
- Instrumentation
- Place of publication
- Classification
- SuDocs

### Actual behavior

If you do an advanced search with the Blacklight 8 features enabled, most of the facets are missing from the left side.

### Steps to replicate

1. Log in to the catalog as an Orangelight admin
1. Go to /features in your browser
1. Turn on the "View components advanced search" feature. It doesn't matter whether the other Blacklight 8 features are on or off.
1. Go to /advanced in your browser
2. Do a search
3. Note that most of the facets are missing from the left side of the screen

### Impact of this bug

This blocks us from turning on the new advanced search form in production, which in turn blocks the Blacklight 8 upgrade.

### Notes

Thanks to @ellen-aa and @caroldh for finding this issue!

**Comment by maxkadel** [comment]
@sandbergja  - I think this may be fixed by [making sure the advanced search form has the right facets](https://github.com/pulibrary/orangelight/pull/4129)
