### ISSUE TITLE
Refactor Middleware::InvalidParameterHandler

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#4110]
### What maintenance needs to be done?
The InvalidParameterHandler needs to be refactored to be part of the controller architecture, rather than the middleware architecture, so that things like warden / current_user are available in the context.

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### EOL upgrade
- [x] EOL Date - not known for sure, but needed in support of Rails 6 EOL upgrade.

### Why is this maintenance needed?
- This is blocking the upgrade from Rails 6 to Rails 7 - Rails 6 is nearing end of life

### Acceptance criteria
 - [ ] We do not have to create a proxy for Warden (this aspect seems to be what is creating problems with the upgrade)
 - [ ] Request performance is not negatively impacted
 - [ ] There is not a regression in error handling for non-standard urls

### Implementation notes, if any
- It is not clear from the tests / code when the custom error page is actually being displayed, and when it's displaying the default error page from nginxplus. Before doing QA on this, we should verify the current behavior and verify that this is the correct behavior. 
- We might want to use rescue_from or rescue_with_handler in the application_controller.rb

**Comment by christinach** [comment]
@sandbergja and I [changed the bad request to use the load balancer's page and not a custom bad request error page](Removed custom bad_response response page.](https://github.com/pulibrary/orangelight/pull/4148/commits/44712a3329373fb3a147a842e88e5964e883cd0a)).
