### ISSUE TITLE
Review Catalog Help Page

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4134]
### What maintenance needs to be done?
Some features documented on our [catalog help page](https://catalog.princeton.edu/help/) appear to not be working. Need to review this page to make sure it's current and accurate. 

### Level of urgency
- [ ] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
Some examples do not work as described. 

### Acceptance criteria
 - [ ] Examples on the page are current and accurate.

**Comment by sandbergja** [comment]
All of the examples work (regardless of whether the JSON query DSL is turned on or off) except for the "Requiring words and phrases".  I didn't see any differences between searches for `+cuba +politics` vs `cuba politics`

**Comment by kevinreiss** [comment]
Is the "+" just the default behavior of the system?

**Comment by ellen-aa** [comment]
@kevinreiss Does the default behavior use AND?

**Comment by kevinreiss** [comment]
Yes the default behavior is AND.

**Comment by ellen-aa** [comment]
@kevinreiss In my mind, the "+" scenario can be removed. @caroldh, what do you think?

That said, I wonder if it would be helpful under "Keyword searching" to say the following: Combine keywords and attributes to find specific items. All keywords and attributes contained in the search will be found in the records of items in the search results." I'm trying to figure out a way for users to understand that all the keywords in the search are treated as required by default. Let me know if you all think this is redundant or unclear in the sample language I've suggested.

**Comment by kevinreiss** [comment]
Do we need to also mention the default stemming behavior that happens with keyword searching? Right now stemming is referenced separately at the bottom of the page now.

**Comment by ellen-aa** [comment]
@kevinreiss Yep, it sounds like the language in the whole page might need to be reviewed and updated to reflect the current default behavior. The examples could also be more illustrative. May I ask who is responsible for this type of labor? Is that a PO duty or does that require leadership approval?

**Comment by kevinreiss** [comment]
This page has essentially been unchanged for [eight years](https://github.com/pulibrary/orangelight/commits/main/app/views/pages/help.html.erb) so reviewing it is long overdue. I think between yourself and @caroldh and the DACS team we can work together to make sure it's current and understandable for users. We can discuss a plan the next time we have a meeting. 

For the purposes of this ticket how about we remove the section "Requiring words and phrases" and make the text under the first section "keyword searching" to be this modified version of your section? 

Combine keywords to find specific items. By default all keywords contained in your search will be found in the records of items in the search results.

**Comment by ellen-aa** [comment]
@kevinreiss I really like the modified language that you suggested and am onboard with what you propose for this ticket. @caroldh - let us know if you have a different opinion. Shall we make a new ticket to review the page as a whole and get it updated?

**Comment by kevinreiss** [comment]
Yes. let's make a new ticket.

**Comment by kevinreiss** [comment]
See https://github.com/pulibrary/orangelight/issues/4220 for future work/review of this page.
