### ISSUE TITLE
Upgrade to Ruby 3.2 or higher

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4145]
### What maintenance needs to be done?
Project should be run with Ruby 3.2 or higher

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### EOL upgrade
- [ ] EOL Date 3/31/2025

### Why is this maintenance needed?
- Ruby 3.1 is coming to an end of life. 

### Acceptance criteria
 - [ ] .ruby-version should be on Ruby 3.2 or higher
 - [ ] Test application locally on Ruby 3.2 or higher
 - [ ] Staging environment is on Ruby 3.2 or higher
 - [ ] QA environment is on Ruby 3.2 or higher
 - [ ] Production Environment is on Ruby 3.2  or higher
 - [ ] CI uses Ruby 3.2 or higher
 
### Implementation notes

It may be cleaner to rebuild these VMs fresh (using the playbook in Ansible Tower).

**Comment by christinach** [comment]
Resolved by https://github.com/pulibrary/orangelight/pull/4665 and https://github.com/pulibrary/princeton_ansible/pull/5675
