### ISSUE TITLE
Rails 7 upgrade triggers an error when hitting https://catalog.princeton.edu/unapi

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#4153]
### Description of the issue
After upgrading to blacklight 7.38.0 and Rails 7 we're seeing [honeybadger errors](https://app.honeybadger.io/projects/54399/faults/110773459) related to 'unapi'.

### Actual behavior
This link `<link rel="unapi-server" type="application/xml" title="unAPI" href="[/unapi](https://catalog.princeton.edu/unapi)"/>` is loaded in the [application.html](https://github.com/pulibrary/orangelight/blob/main/app/views/layouts/application.html.erb#L45).

### Notes
Dropdown 'Send' -> 'RIS' exports the ris file and imports it in the Zotero app.
The [invalid parameter handler](https://github.com/pulibrary/orangelight/blob/main/lib/orangelight/middleware/invalid_parameter_handler.rb) was changed to send the bad request to the load balancer and not to a custom error page

### Honeybadger link and code snippet, if applicable
[Honeybadger error 110773459](https://app.honeybadger.io/projects/54399/faults/110773459)

```
ActionView::MissingTemplate: Missing template catalog/formats.xml with {:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :vtt, :png, :jpeg, :gif, :bmp, :tiff, :svg, :mpeg, :mp3, :ogg, :m4a, :webm, :mp4, :otf, :ttf, :woff, :woff2, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip, :jsonld, :refworks_marc_txt, :openurl_kev, :endnote, :marc, :marcxml, :openurl_ctx_kev, :dc_xml, :oai_dc_xml, :rdf_dc, :ris, :mendeley], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}.

Searched in:
  * "/opt/orangelight/releases/20240828230910/app/views"
  * "/opt/orangelight/shared/bundle/ruby/3.1.0/gems/health-monitor-rails-12.3.0/app/views"
  * "/opt/orangelight/shared/bundle/ruby/3.1.0/gems/flipflop-2.7.1/app/views"
  * "/opt/orangelight/shared/bundle/ruby/3.1.0/gems/devise-4.9.4/app/views"
  * "/opt/orangelight/shared/bundle/ruby/3.1.0/bundler/gems/blacklight_unapi-79ac4bf1914f/app/views"
  * "/opt/orangelight/shared/bundle/ruby/3.1.0/gems/blacklight_range_limit-8.5.0/app/views"
  * "/opt/orangelight/shared/bundle/ruby/3.1.0/gems/blacklight-marc-8.1.4/app/views"
  * "/opt/orangelight/shared/bundle/ruby/3.1.0/gems/blacklight_dynamic_sitemap-1.0.0/app/views"
  * "/opt/orangelight/shared/bundle/ruby/3.1.0/gems/blacklight_advanced_search-7.0.0/app/views"
  * "/opt/orangelight/shared/bundle/ruby/3.1.0/gems/blacklight-7.38.0/app/views"
  * "/opt/orangelight/shared/bundle/ruby/3.1.0/gems/view_component-2.83.0/app/views"
  * "/opt/orangelight/shared/bundle/ruby/3.1.0/gems/kaminari-core-1.2.2/app/views"
  * "/opt/orangelight/shared/bundle/ruby/3.1.0/gems/actiontext-7.0.8.4/app/views"
  * "/opt/orangelight/shared/bundle/ruby/3.1.0/gems/actionmailbox-7.0.8.4/app/views"

Did you mean?  catalog/formats
               catalog/facet
               catalog/sms
               catalog/email
               catalog/email_success
               catalog/endnote
```

**Comment by kevinreiss** [comment]
The replicate how this error is caused you:

1. Install and activate the Zotero browser Plugin https://www.zotero.org/download/connectors
2. Run the desktop Zotero app
3. Everytime you load a search results page or a record page it will request the /unapi route, which when this succeeds you will see an icon on the browser toolbar you can can click to see a list of possible bibliograhpic records you can import, instead you get the 500 error now.

**Comment by kevinreiss** [comment]
In the last major version upgrade to BL 7, this fix was required to keep the blacklight_unapi gem working: https://github.com/pulibrary/blacklight_unapi/commit/0797d5f520dba1a885e6a86821b241dd2a7fb02e.

**Comment by kevinreiss** [comment]
In Firefox and Chrome, I don't see the 500 error generated when I run those browsers without the Zotero connector activated.

**Comment by kevinreiss** [comment]
The video here demontrates how this operates when the "unapi" route is working: https://libguides.princeton.edu/zotero.

**Comment by kevinreiss** [comment]
I'm going to reach out to Willow, who is the guide editor, and see if the docs can be updated. I think we should remove the unapi gem to close this issue. There is one UI change that I'll suggest in a separate ticket.

**Comment by kevinreiss** [comment]
If we remove the unapi gem we can close this issue https://github.com/pulibrary/orangelight/issues/3502.
