### ISSUE TITLE
Upgrade to Rails 7.1

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4159]
### What maintenance needs to be done?
Need to upgrade and test application with rails v. 7.1. 

### Level of urgency
- [x] High
- [ ] Moderate
- [ ] Low

### EOL upgrade
- [ ] EOL Date 4/1/2025. 

### Why is this maintenance needed?
Ruby 7.1 is approaching end of security maintenance.

### Acceptance criteria
 - [ ] App runs on Rails 7.1

**Comment by christinach** [comment]
resolved by https://github.com/pulibrary/orangelight/pull/4152
