### ISSUE TITLE
Ensure OR and NOT Searching Work from New Advanced Search

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4167]
### What maintenance needs to be done?
When the project is using the JSON Query DSL and new advanced search features on we should test these operators. 

### Level of urgency
- [ ] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
- Ensure features have continuity. 

### Acceptance criteria
 - [ ] Confirm OR Searching is functioning
 - [ ] Confirm NOT Searching is functioning

### Implementation Notes
Look for hardcoded references to MUST in the search builder.

**Comment by maxkadel** [comment]
Examples of hard-coded "must" that I'm concerned about:

- https://github.com/pulibrary/orangelight/blob/e2bd076f6617b7bff87e55d5fd32e0f1b2051e4a/app/models/search_builder.rb#L146
```ruby
    def using_json_query_dsl(solr_parameters)
      solr_parameters.fetch('json', nil)&.fetch('query', nil)&.fetch('bool', nil)&.fetch('must', nil)&.present?
    end
```
- https://github.com/pulibrary/orangelight/blob/e2bd076f6617b7bff87e55d5fd32e0f1b2051e4a/app/models/search_builder.rb#L24
```ruby
 solr_parameters.dig('json', 'query', 'bool', 'must').map! do |search_element|
```

**Comment by christinach** [comment]
@sandbergja and I looked into https://github.com/pulibrary/orangelight/blob/e2bd076f6617b7bff87e55d5fd32e0f1b2051e4a/app/models/search_builder.rb#L146 and https://github.com/pulibrary/orangelight/blob/e2bd076f6617b7bff87e55d5fd32e0f1b2051e4a/app/models/search_builder.rb#L24 and it does not hit the method `using_json_query_dsl` when we're using the advanced search form. Only when using the main search, which does not have a concept of should, must_not.

**Comment by maxkadel** [comment]
Great, thanks for checking that @christinach!
