### ISSUE TITLE
Remove unneeded PPPL code from requests

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#4174]
### What maintenance needs to be done?

Remove some PPPL code that is no longer used.

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
- To simplify Requests, plasma physics materials are all now located at Lewis Library. It no longer exists as it's own physical space. 

### Acceptance criteria
 - [x] [Email config values](https://github.com/pulibrary/orangelight/blob/2e813be3a5f05e89b1e6c3f873fb534f33eea229/config/locales/requests.en.yml#L70-L76), [features](https://github.com/pulibrary/orangelight/blob/2e813be3a5f05e89b1e6c3f873fb534f33eea229/app/mailers/requests/request_mailer.rb#L74), [templates](https://github.com/pulibrary/orangelight/blob/2e813be3a5f05e89b1e6c3f873fb534f33eea229/app/views/requests/request_mailer/ppl_email.html.erb) and [email specs](https://github.com/pulibrary/orangelight/blob/2e813be3a5f05e89b1e6c3f873fb534f33eea229/spec/mailers/requests/request_mailer_spec.rb#L942) related to ppl can be purged.
 - [x] Confirm that the staff workflow pick-up notification email still goes to lewislib@princeton.edu after we remove these features. See[ commit.](https://github.com/pulibrary/orangelight/commit/127a4549e2d40bd9643d0b8ca06faf18b881d3de) 
 - [ ] Update the mailer spec to confirm that a PPL item uses the lewis library email templates. 

### Implementation notes
Any PPL items should now use the Lewis email templates.

**Comment by sandbergja** [comment]
That makes sense, thanks @kevinreiss .  Should I close this ticket and open a new one for `open_libraries`?

**Comment by kevinreiss** [comment]
Yes, let's make a new ticket for open_libraries? - I think this construct can definitely go. Searching again I see a few more references to plasma in the codebase and a unique ppl email template. It's likely these can go but maybe let's keep this ticket open and I'll see if I can put some more details about these plasma related features.

**Comment by kevinreiss** [comment]
It looks like open_libraries was removed in this commit: https://github.com/pulibrary/orangelight/commit/de0997a40268ce4813f032d5bd16f255a688df5e.
