### ISSUE TITLE
Run Reek on the Requestable Class 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4175]
### What maintenance needs to be done?
 The reek score of this file is currently 20. 

### Level of urgency
- [ ] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
- The file has a very high complexity score.

### Acceptance criteria
 - [ ] Warnings are lowered to 10 or less. 

### Implementation notes, if any
```reek app/models/requests/requestable.rb``` to see current report.

**Comment by sandbergja** [comment]
The Requestable class is now down to 6 reek warnings, so I'm closing this ticket.
