### ISSUE TITLE
Run Reek on Request Class

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4178]
### What maintenance needs to be done?
 The reek score of this file is currently 53. 

### Level of urgency
- [ ] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
- The file has a very high complexity score.

### Acceptance criteria
 - [ ] Warnings are lowered to 40 or less. 

### Implementation notes, if any
```reek app/models/requests/request.rb``` to see current report.

**Comment by sandbergja** [comment]
The reek score has been reduced to 40, so we can close this now.  Thanks, @christinach ! 🐬
