### ISSUE TITLE
Document Upgrade to Blacklight Built-in advanced search. 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4192]
### Introduction
Upgrading to the built-in blacklight advanced search features from the advanced_search_gem was challenging and time consuming. We should document the blockers we encountered and the upgrade steps for other PUL teams and the Blacklight community. 

### Acceptance criteria

- [x] Create blog post
- [x] It has introduction: Explains the goals and purpose of this documentation.
- [x] Attempt to reference significant commits that highlight examples of key pattern changes required to provide for feature continuity. 

#### Additional acceptance criteria 
- [x] It includes references: References any related resources that have assisted creating this documentation (links to other tickets, online articles etc.).

**Comment by maxkadel** [comment]
Will review draft during team tech time
