### ISSUE TITLE
Update and Revise Catalog Help Page

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4220]
### What maintenance needs to be done?
Review and revise the catalog's [help documentation](https://github.com/pulibrary/orangelight/commits/main/app/views/pages/help.html.erb). 
### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
- The current help page has not been revised in over eight years. It also does nothing to help users with any actions in the catalog other than searching. 

### Acceptance criteria
 - [ ] Discuss how this page can be better and more accurate with Librarian stakeholders
 - [ ] Discuss how this page can be more effective with the UX Team.

**Comment by ellen-aa** [comment]
@kevinreiss Carol and I are trying to wrap up editing for the Help page, but we are encountering problems regarding wildcard searching. Would it be possible to find documentation from Blacklight on whether wildcards work reliably? See the following examples:

wom?n: https://catalog.princeton.edu/catalog?search_field=all_fields&q=wom%3Fn

wom!n: https://catalog.princeton.edu/catalog?search_field=all_fields&q=wom%21n

wom#n: https://catalog.princeton.edu/catalog?search_field=all_fields&q=wom%23n

women OR womyn OR woman: https://catalog.princeton.edu/catalog?per_page=100&search_field=all_fields&q=women+OR+womyn+OR+woman

**Comment by ellen-aa** [comment]
@kevinreiss - any news on Blacklight documentation for searching?

**Comment by kevinreiss** [comment]
Thanks @sandbergja.

**Comment by ellen-aa** [comment]
@sandbergja Thank you so much! This helps @caroldh and I a great deal.

**Comment by ellen-aa** [comment]
Hi @kevinreiss and @sandbergja, below please find the revised text for the Help page. Let @caroldh and I know if you have any questions or concerns.

**Keyword searching:** 

Combine keywords to find specific items. By default all keywords contained in your search will be found in the records of items in the search results.

Examples:
morrison beloved
Egypt foreign relations

**Phrase searching:**

Use quotation marks to search as a phrase.

Examples:
"free market"
"mourning becomes electra"

**Excluding words or phrases:**

Use "-" or “NOT” before a word or phrase to exclude it.

Examples:
jaguar -car -automobiles
jaguar NOT car NOT automobiles

**Joining queries:**

Use "OR", "AND", and "NOT" to create complex boolean logic. You can use parentheses in your complex expressions. Use the[ Advanced Search](https://catalog.princeton.edu/advanced) to join across multiple fields. 

Examples:
activism OR “social justice”
India AND (activism OR “social justice”)
(India NOT Indiana) AND (activism OR “social justice”) 

**Truncation and wildcards:**

English terms are automatically stemmed to include plural and singular forms, as well as common suffix and tense variations. 

An asterisk may also be used to truncate any term from either the beginning or end of the word, or in the middle of the word to replace a character.

Examples:
*est (This search would match pest, test, jest, etc.)
art* (This search would match art, arts, artistic, artisan, artistry, artisanal, etc.)
wom*n (This search would match woman, women, womyn.)

**Comment by caroldh** [comment]
@ellen-aa  Ellen, I think the *'s are missing in the "*est" and art*" examples?

**Comment by ellen-aa** [comment]
@caroldh Great catch! I think that Github is reading the asterisks as formatting, so they are there when I add the text, but not when I click to add the comment. Let me try to troubleshoot...
