### ISSUE TITLE
Add new facet icon for databases format

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#4239]
### What maintenance needs to be done?
We need to add a new icon for Databases. After [bibdata#2433](https://github.com/pulibrary/bibdata/issues/2433) we're indexing format: databases.

### Why is this maintenance needed?
- New resources with databases format will appear in the Format facet with no icon.
#### example from catalog-staging
![format facet - screenshot indicating that databases is missing an icon](https://github.com/user-attachments/assets/5ac1c9cb-5d48-4e8f-81e3-678fe4725bfa)

### Acceptance criteria
 - [ ] Format facet has an icon for databases
 - [ ] Use the [databases icon from allsearch](https://allsearch.princeton.edu/?q=robot#library-databases)

### Notes
This change needs to happen before the next full reindex.

**Comment by kevinreiss** [comment]
Should the label be "Database" rather than "Databases"? All the other labels are singular. There are two icons marked with data in the project

```.icon-data-file``` and ```icon-open-dataset``` would one of those work?
