### ISSUE TITLE
Extract the ask_me eligibility checks from the requests Router into its own class

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#4252]
### What maintenance needs to be done?

Extract the AskMe eligibility checks from the requests Router into its own class.

### Why is this maintenance needed?
* The Router class will no longer need to know all the details about what makes a requestable and user eligible to request the AskMe service.
* The eligibility logic for the AskMe service will be easier to understand, test, and modify in a single location

### Acceptance criteria
 - [x] There is a new class in the `ServiceEligibility` module that is responsible for determining if a user and a requestable are eligible for the AskMe service
 - [x] The new class has a similar API to other classes in the `ServiceEligibility` module 
 - [x] The Router uses the new class to determine eligibility for the AskMe service

### Implementation notes, if any
See PR #4238 for examples

**Comment by kevinreiss** [comment]
I'm not sure if we need this option any longer. It was an option of last resort for items when the library spaces were closed to the public and we did not have the book pick-up service set up yet.
