### ISSUE TITLE
Investigate openurl_ctx_kev

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#4270]
### What maintenance needs to be done?
Determine whether we can remove `openurl_ctx_kev` method (included in debride report) - if it is safe to remove, do so, if not, add to `.debride_allowlist.txt`

### Implementation notes, if any
If this can be removed, determine whether SolrOpenUrlContext ctx method can also be removed.
The method is used a lot in the view layer.

**Comment by kevinreiss** [comment]
It looks like this was brought into requests (possibly to aid with the creation of OpenURL values that are passed to [ILLiad)](https://github.com/pulibrary/orangelight/blob/28fcb2243cc9dfa9a8d645f1fe22a4d9fa3c19b0/app/models/requests/solr_open_url_context.rb#L10-L13). We no longer pass OpenURLs to ILLiad in requests so maybe in the requests context it's fine for this to go. The "openurl_ctx_kev" construct does do useful things related to Blacklight's use of the CoINS standard we are using for Zotero compatibility. see https://github.com/search?q=repo%3Apulibrary%2Forangelight+openurl_ctx_kev&type=code, but I think that does not intersect with the Request's implementation.
