### ISSUE TITLE
Refactor IlliadPatron to use patron group information from Alma via Bibdata, rather than from LDAP

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#4300]
### What maintenance needs to be done?
Refactor IlliadPatron to use patron group information from Alma by way of Bibdata, rather than from LDAP.

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
- It would be nice to eventually not need the extra call to ldap
- Alma is the source of truth about patron groups and what they can / cannot do
- Hopefully simplify the code some

### Acceptance criteria
 - [ ] Any patron mapping for Illiad is done based on the Alma patron groups, not information from LDAP

### Implementation notes, if any
[slack discussion](https://pulibrary.slack.com/archives/C031U4XCUH2/p1726083680117029)

**Comment by christinach** [comment]
Closing this ticket as Illiad needs Ldap.
