### ISSUE TITLE
Your Account Cancel Request Notification

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#434]
Add a callback to a succesful ajax cancel request that adds some animation or color coding that gives the user a better idea that the request has completed successfully. Currently a successfully cancelled item disappears and a flash message shows up in #main-flashes. This is a bit barebones.

**Comment by axamei** [comment]
Let's make the #main-flashes container sticky so users can see alerts regardless of their location on the page. Include animation to #main-flashes (pulse or slide down) and cancelled item (fade out and slide).
