### ISSUE TITLE
Zotero publisher in author field 

### ISSUE THREAD

**Issue by beth-german** [pulibrary/orangelight#4436]
### Expected behavior
When add a catalog record to a Zotero library, the publisher is only in the publisher field. 

### Actual behavior
Publisher is in the author field. 

### Steps to replicate
1. Add catalog record to zotero library via extension 
2. Check the record in zotero 

![image](https://github.com/user-attachments/assets/1837f8a4-75ad-4217-bfca-d2925a59da9d)
![image](https://github.com/user-attachments/assets/6b0d0917-761c-4c0f-81f7-bb1a7bc91263)

### Impact of this bug
Need to manually update field. 

### Acceptance criteria
- [ ] Since we do not currently know whether this behavior is needed for Aeon (see comments), we should change the behavior only for Zotero, not for Aeon

### Implementation notes, if any
From website feedback form: When you are looking at the record of an item and click for zotero to import the item to your citation library, the zotero software thinks the location is an author.  This never used to happen with the old system.

**Comment by maxkadel** [comment]
@sandbergja will check with public services about whether they need the aucorp field for Aeon

**Comment by kevinreiss** [comment]
Related user feedback from 10/26 in libanswers

``` ever since the update of the catalog, the zotero plugin for safari imports the book publisher as the author - presumably because the field is called "published", rather than "publisher" - fixing this would save me, and many other researchers working with zotero a great deal of effort which now has to be invested in fixing flawed citations. thank you so much for your help!

Sent from https://catalog.princeton.edu/catalog/99115140253506421 via LibAnswers API
```

**Comment by maxkadel** [comment]
@sandbergja will reach out to Sara Logue (currently on vacation)
