### ISSUE TITLE
Draft copy for home page

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#444]
Currently:

> This catalog is being developed to eventually replace our twenty year old Main Catalog and incorporate the best features of new types of library search technology. Please note that the Main Catalog and the Books+ systems will continue to be available throughout our beta development phase.

> This site is in active development. For more details about these changes, please see our release notes. 

Let's firm this up and make it seem less like WIP before we go to beta.

**Comment by kevinreiss** [comment]
@jpstroop How about just dropping the last sentence. Our last release note was 8/31/2015 so I don't think that has caught on as a way to update the staff. I think the first paragraph reads well.

**Comment by mzelesky** [comment]
@jpstroop Minor grammatical point: '20 year old' should be '20-year-old'.

**Comment by mzelesky** [comment]
Here's my suggested revision:

This catalog is being developed to replace our 20-year-old Main Catalog and incorporate the best features of current library search methods. Please note that the Main Catalog and Books+ will continue to be available throughout the beta development phase.

**Comment by jpstroop** [comment]
I was thinking that both of these paragraphs should go, actually. We can leave the WIP banner up for a while, but I'd like the home page to be a little less tentative.

**Comment by kevinreiss** [comment]
This one can be closed. 19314043a76899bc0001bb3aa3852551999531f8
