### ISSUE TITLE
Display vern title for related records when it exists

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#4447]
### Current display
Related records in the 'Details' section display only the romanization title

### Desired display
Related records in the 'Details' section display display both the romanization and the vern title when it exists.

### Acceptance criteria
- [x] Details section has related records with both romanization and vern title if the vern title exists.
- [x] I can successfully use this feature with Voice Over in Safari.
- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

### Notes
Feedback from @tventimi in the [#catalog slack channel](https://pulibrary.slack.com/archives/CA0UY0Q07/p1728574880526479)

Example records: 
https://catalog.princeton.edu/catalog/99125087383506421
https://catalog.princeton.edu/catalog/99124987353506421

**Comment by christinach** [comment]
@ellen-aa @caroldh I added the PO (review) label for this ticket. Please review it when you have availability.

**Comment by ellen-aa** [comment]
@christinach @caroldh - I added PO (high value) to this ticket because including the original-language script is a dei issue and helpful for those unfamiliar with LC-Romanization practices.

**Comment by christinach** [comment]
@ellen-aa thank you !
