### ISSUE TITLE
[Call number (browse)] Search for a call number starting with a specific number should not result in a shorted list of the call_numbers

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#4449]
### Expected behavior
When I search for https://catalog.princeton.edu/browse/call_numbers?search_field=browse_cn&q=87550
I expect to find call number results that start with 87550 or include 87550

### Actual behavior
When I search for https://catalog.princeton.edu/browse/call_numbers?search_field=browse_cn&q=87550
I get a sorted list of the call numbers

### Steps to replicate
[Search for 87550](https://catalog.princeton.edu/browse/call_numbers?search_field=browse_cn&q=87550)

vs [Search for 87550 with a space after](https://catalog.princeton.edu/browse/call_numbers?search_field=browse_cn&q=87550+)
or vs [Search for 87550 with a space after and in front](https://catalog.princeton.edu/browse/call_numbers?search_field=browse_cn&q=+87550+)

Both of the last two example searches include resources with the call number I'm interested.

### Further notes
[From the catalog slack channel. Minjie was trying to find resources that started with call number 87550](https://pulibrary.slack.com/archives/CA891BNR0/p1728591709420199?thread_ts=1721054299.974209&cid=CA891BNR0)

**Comment by christinach** [comment]
@ellen-aa @caroldh I labeled this ticket with PO review. Please review it when you have availability.

**Comment by ellen-aa** [comment]
@christinach @caroldh , I added PO (high value).
