### ISSUE TITLE
Catalog Annoucement Should Display HTML

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4459]
### What maintenance needs to be done?
The catalog announcement feature should display html as well as plain text. Right even if you insert html (either escaped or unescaped) it s display as plain text. 

### Level of urgency
- [ ] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
- It's useful for HTML (primarily links) to be included in announcements. 

### Acceptance criteria
 - [x] Basic HTML tags are formatted properly in the catalog announcement message. 

### Implementation notes, if any
Example string used when I discovered this issue. 

```How do you search the Library catalog? <a href='https://libcal.princeton.edu/appointments?u=119086'>Sign-up for a short interview</a> on Zoom to help the Library improve our catalog.```

**Comment by christinach** [comment]
Deployed on https://catalog-qa.princeton.edu/
