### ISSUE TITLE
Advanced Search Form Performance is Slow

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4498]
### What maintenance needs to be done?
Advanced Search form is taking 15 to 20 seconds to load. 

### Level of urgency
- [x] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
- Advanced search form performance is very slow. 

### Implementation notes, if any
See if caching the limiter facets can help. It appears from a quick look in datadog (thanks @sandbergja) that solr performance for this page is very slow right now.

**Comment by sandbergja** [comment]
Closing, since the caching solved the immediate problem
