### ISSUE TITLE
Advanced Search Form Search Raises NoMethodError: private method `display_label' called for nil:NilClass

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4554]
### Expected behavior
Advanced search form submission results in a rendered constraint component with a display label value. 

### Actual behavior
When running an advanced search certain queries generate a 500 error for display_label in the constraint_component.html.erb . 

### Steps to replicate
See any of the URLs for advanced search queries that resulted in this error in honey badger. Example:

```
https://catalog.princeton.edu/?clause[0][field]=series_title%27nvOpzp;%20AND%201=1%20OR%20(%3C%27%22%3EiKO)),&clause[0][query]=%E6%96%B0%E6%9C%88%E6%96%87%E8%97%9D%E5%8F%A2%E6%9B%B8%27nvOpzp;%20AND%201=1%20OR%20(%3C%27%22%3EiKO)),&f[format][]=Journal%27nvOpzp;%20AND%201=1%20OR%20(%3C%27%22%3EiKO)),&f[lc_rest_facet][]=JS%20-%20Local%20Government%27nvOpzp;%20AND%201=1%20OR%20(%3C%27%22%3EiKO)),&f[publication_place_facet][]=Japan%27nvOpzp;%20AND%201=1%20OR%20(%3C%27%22%3EiKO)),&per_page=50%27nvOpzp;%20AND%201=1%20OR%20(%3C%27%22%3EiKO)),&sort=title_sort%20asc,%20pub_date_start_sort%20desc,%20score%20desc%27nvOpzp;%20AND%201=1%20OR%20(%3C%27%22%3EiKO))
```
### Impact of this bug
I am not sure if this a "real" error. It could be the work of a crawler, it seems unlikely a human would create a URL similar to what you see in the logs. 

### Honeybadger link and code snippet, if applicable
https://app.honeybadger.io/projects/54399/faults/112626938.

**Comment by sandbergja** [comment]
Opened upstream PR here: https://github.com/projectblacklight/blacklight/pull/3442
