### ISSUE TITLE
Make tracking down introduction of bugs in Rails apps easier

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#4556]
### What maintenance needs to be done?
Track deployments in Honeybadger.

### Level of urgency
- [x] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
 This will allow us to see correlations between bugs and specific deploys / commits.

### Acceptance criteria
 - [x] When we deploy the application, if that deploy introduces new errors, a link to the commit and subsequent deploys is included in the "history" section in Honeybadger

![image](https://github.com/user-attachments/assets/95bf2606-db52-479c-8276-81cf4539080e)

### Implementation notes, if any
- In the application's Capfile, add the line `require 'capistrano/honeybadger'`
- May also need to add the honeybadger gem to the gemfile if not already present - `gem 'honeybadger'`
- Approvals and Allsearch API currently do this, if you want an example.

**Comment by rladdusaw** [comment]
This was resolved in https://github.com/pulibrary/orangelight/pull/4632
