### ISSUE TITLE
BorrowDirect requests display item titles in all caps and pickup locations start with a period 

### ISSUE THREAD

**Issue by axamei** [pulibrary/orangelight#456]
![screen shot 2016-04-26 at 10 40 53 am](https://cloud.githubusercontent.com/assets/8161144/14822251/ecb5edd6-0b9b-11e6-9c6d-2d8182fdf8bf.png)

**Comment by axamei** [comment]
Same display in "classic" catalog. 

![screen shot 2016-04-26 at 10 46 49 am](https://cloud.githubusercontent.com/assets/8161144/14822323/3b1056b0-0b9c-11e6-980a-b2bf15f4fdcb.png)

**Comment by kevinreiss** [comment]
That is actually the string stored in Voyager's configuration tables. We could clean it up in OL with a helper function applied to strings rendered for pickup locations. @tampakis I think that is probably worth doing.

**Comment by kevinreiss** [comment]
We could also create a helper that munges the title string into a better form. Though I suppose that could be dangerous if a record's title was actually in all caps.

**Comment by kevinreiss** [comment]
As far as I can tell other than the convention of having the title in all caps there is no other way to distinguish a Borrow Direct item from any other charged item.

**Comment by mzelesky** [comment]
They have a location code of 'bdirect' in the 852. Does that help? Maybe there's some sort of helper text that appears for BorrowDirect items?

**Comment by mzelesky** [comment]
The item type also has 'Borrow Direct' in the label.

**Comment by kevinreiss** [comment]
Mark, we are using some Voyager Web Service interface for accounts so are currently limited to the data it provides, unless we want to add additional calls to load bib, holdings, or item data. However it does look like that does make it into the response, so we can act upon it. Thanks for pointing that out. For reference here is what the responses from those services look like:

```
<myac:chargedItem>
          <myac:itemId>7371112</myac:itemId>
          <myac:itemBarcode>32101100475563</myac:itemBarcode>
          <myac:dueDate>2016-06-07T23:45:00.000-04:00</myac:dueDate>
          <myac:origDueDate>2016-06-07T23:45:00.000-04:00</myac:origDueDate>
          <myac:todaysDate>2016-04-29T12:16:41.000-04:00</myac:todaysDate>
          <myac:title>POSTCAPITALISM - A GUIDE TO OUR FUTURE </myac:title>
          <myac:author xsi:nil="true"/>
          <myac:location>Borrow Direct Service. Princeton University Library</myac:location>
          <myac:locationCode>bdirect</myac:locationCode>
          <myac:callNumber xsi:nil="true"/>
          <myac:statusCode>2</myac:statusCode>
          <myac:requestCount>0</myac:requestCount>
          <myac:copyNumber>0</myac:copyNumber>
          <myac:itemtype/>
          <myac:renewable>true</myac:renewable>
        </myac:chargedItem>
```

**Comment by mzelesky** [comment]
It would definitely be helpful for patrons to easily know which items are Borrow Direct items, as they have a very different loan period and different renewal limits.

**Comment by kevinreiss** [comment]
Yes, an action item has emerged from this discussion.

**Comment by kevinreiss** [comment]
Going to re-open. #481 added a note that an item is a Borrow Direct loan but didn't do anything with the All CAPs and pickup locations starting with a "."
