### ISSUE TITLE
Blacklight 8: Record page Feedback Options 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4567]
### Expected behavior
When using one of the three record record page feedback options:

1. Ask a Question
2. Suggest a Correction
3. Report Harmful Language 

I expect to click on the option see a modal window, submit my inquiry and be taken back to the record page.  

### Actual behavior
Include screenshots, or links and browser version if relevant
<img width="1050" alt="Screenshot 2024-11-13 at 3 59 38 PM" src="https://github.com/user-attachments/assets/24614486-caa6-4104-a876-bceadb67647c">

If I select any of these three options, and submit the modal form I am taken to a blank page rather than the record page. The screenshot below is what you'll see:

![suggestion](https://github.com/user-attachments/assets/5b485a7a-132b-486a-a031-9dd5374782e9)

### Steps to replicate
1. Checkout the blacklight 8 branch
1. Visit https://catalog.princeton.edu/catalog/99125105012606421
2. Select "Suggest a Correction"
3. Submit the Form that appears
4. You'll be taken to a blank page.

### Impact of this bug
Data submitted goes to the appropriate libanswers queue but the user experience is confusing. 

### Implementation notes, if any
Noting that if you submit these forms on staging the submissions will actually go into libanswers. 

There is some potentially related discussion in the #blacklight channel on the code4lib slack.

**Comment by sandbergja** [comment]
@winsice-ng pointed out a potentially related ticket #3945.  It's not quite the same issue, since in that case, the input is invalid and there is a `NoMethodError`.  In this case, there is no `NoMethodError` -- but definitely potentially related!

**Comment by christinach** [comment]
@sandbergja and I resolved the issue upstream. 
See: https://github.com/projectblacklight/blacklight/pull/3467 and
https://github.com/projectblacklight/blacklight/pull/3466

We pinned the Blacklight upgrade branch to release-8.x until there is a new release for blacklight 8.7

**Comment by christinach** [comment]
We still need to do some more work. We're noticing that the event is not added when the modal is loaded.
