### ISSUE TITLE
Blacklight 8: Previous and Next in blacklight facet modal triggers an error

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#4571]
### Expected behavior
When I click on Language facet and then on 'more', I'm able to navigate through the language results by clicking Next and Previous.

### Actual behavior
When I click on Language facet and then on 'more', I'm able to navigate through the language results by clicking Next and Previous.

### Steps to replicate
1. Check out the blacklight 8 branch
1. Go to https://catalog.princeton.edu/catalog?search_field=all_fields&q=dog
1. Click on 'Language' facet. 
1. Click 'more' . 
1. In the modal click 'Next'. Some times it will let you click more than once and then it will fail on 'Previous'. Other times it will fail the first time you click on 'Next'
1. The following error appears in the modal: 
![error in blacklight modal](https://github.com/user-attachments/assets/3c2f4b28-d831-4524-b644-d28bff3780ec)

### Impact of this bug
Users cannot use Previous and Next in the modal to navigate through the results.

**Comment by maxkadel** [comment]
Unable to replicate on Blacklight 8 branch - possibly fixed by https://github.com/pulibrary/orangelight/pull/4602
