### ISSUE TITLE
BL7: UrlGenerationError in feedback # ask_a_question

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#4577]
### Expected behavior
Using the Ask a Question form successfully sends a message via the LibAnswers API and does not raise an error.

### Actual behavior
Does not appear to send the message via the LibAnswers API, raises an error.

### Steps to replicate
1. Go to a record page (e.g. https://catalog.princeton.edu/catalog/9948547563506421)
2. Click "As a Question"
3. Send a test question
4. Check Honeybadger error for new instances (https://app.honeybadger.io/projects/54399/faults/114589196)

### Impact of this bug
Patrons cannot use contact forms

### Honeybadger link and code snippet, if applicable
https://app.honeybadger.io/projects/54399/faults/114589196

```
ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"catalog", :id=>nil}, possible unmatched constraints: [:id] Did you mean? solr_document_path
42 |  
-- | --
43 | def path(method_name)
44 | raise ActionController::UrlGenerationError.new(message, routes, name, method_name)
45 | end


```

**Comment by kevinreiss** [comment]
These forms don't send email any longer. They utilize the API for libanswers.

**Comment by maxkadel** [comment]
Not actually able to recreate, closing for now.
