### ISSUE TITLE
Move and rename "pul" in the holding location dropdown

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/orangelight#4579]
### Description
In the "Advanced Search" Holding Location menu, the Holding Library locations are listed first, followed by the more granular locations, followed by "pul".

### Impact
It is not apparent that "pul" is an option unless you either know it's there or you scroll all the way to the bottom of the list.

### Acceptance criteria

- [ ] When this option is selected, it is at the top of the selected options.
- [ ] When this option is not selected, it is at the top of the unselected options.
- [ ] This option is named "All Princeton Holdings"

### Implementation notes
Intuitively, should this be the first choice in the menu, so that the location filters go logically from broadest (all of PUL but not partners) to specific holding libraries within PUL to specific locations within the specific libraries?

**Comment by christinach** [comment]
closed in favor of https://github.com/pulibrary/orangelight/issues/4578
