### ISSUE TITLE
Investigate behavior of "More in this series" link

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#4595]
### What maintenance needs to be done?
Determine whether the change in the query dsl changed the behavior of the "More in this series" link

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
- Requested by Minjie on [slack in the #catalog channel](https://pulibrary.slack.com/archives/CA0UY0Q07/p1732126142414459)

Record: [Wo de jia](https://catalog.princeton.edu/catalog/99100263053506421)
> I am expecting about [163 results](https://catalog.princeton.edu/?q=you+tong+wen+ku&search_field=left_anchor) that have the string of "you tong wen ku" in (series) title field

Instead the "More in this series" hyperlink for the Romanized titles is retrieving [462 results](https://catalog.princeton.edu/catalog?clause%5B0%5D%5Bfield%5D=series_title&clause%5B0%5D%5Bquery%5D=You+tong+wen+ku.+di+1+ji%2C+She+hui+lei&commit=Search)

### Acceptance criteria
- [x] Determine whether the change in the query dsl changed the behavior of the "More in this series" link
- [ ] If it has changed, make a ticket to restore previous behavior
- [ ] If it has not changed, investigate what the correct behavior is, and if it is different from the current behavior, make tickets for desired behavior

### Implementation notes, if any
Possibly an inadvertent change in [#advanced_search_series_link](https://github.com/pulibrary/orangelight/blob/bfa30eb44baba6d4e53dc7f362155af7770e1019/app/processors/orangelight/series_link_processor.rb#L29) when we switched to the JSON dsl? Possibly in [this commit](https://github.com/pulibrary/orangelight/blame/f4d9a400d388eeec901af2aa4117c8497a4fd2fb/app/processors/orangelight/series_link_processor.rb)?

Should `"clause[0][field]"` be `in_series` rather than `series_title`?

**Comment by sandbergja** [comment]
After some investigation: yes, the field should be `in_series` rather than `series_title`.  But also,  pre-JSON Query DSL, [we had code that applied the left anchor logic to the in_series field as well](https://github.com/pulibrary/orangelight/blob/f4d9a400d388eeec901af2aa4117c8497a4fd2fb/app/helpers/advanced_helper.rb#L112), we need to add that to the JSON Query DSL version as well.
