### ISSUE TITLE
Availability Status in Search Results for RBSC ReCAP

### ISSUE THREAD

**Issue by swiftg** [pulibrary/orangelight#464]
The On-Site Access availability button that displays for RBSC material might mislead patrons when viewing search results that include RBSC ReCAP material.  An example, a keyword search for Rollins Cowboy will retrieve material that is housed on-site (record 2) and material housed off-site (record 3).  Based on our recent usability testing of the library website, patrons do not know what ReCAP means. This would be especially true for non-Princeton patrons, which make up nearly 50% of the RBSC use.  The danger here is that patrons will see the On-Site Access button for ReCAP material, drive or fly to Princeton without requesting the item, only to arrive and be told the material is house off-site and will take 2-3 days to arrive.  
![search dislpay](https://cloud.githubusercontent.com/assets/9615715/14888232/3ec80460-0d27-11e6-87e5-028349c4e03c.jpg)

**Comment by kevinreiss** [comment]
@swiftg Is there an expectation that people can show up to RBSC and get materials that are in non-ReCAP locations on demand? I thought access needs to be scheduled ahead for all RBSC items? Is there a consistent treatment we could give all RBSC locations (whether they are at ReCAP or not) that would be effective in telling interested parties they need to schedule ahead to see the material?

**Comment by tampakis** [comment]
Add "by request" to Recap and Annex items.

**Comment by kevinreiss** [comment]
But isn't the "by request" also true for the standard materials in the Firestone or Mudd vaults?

**Comment by tampakis** [comment]
Yeah so for those we should add "by request" also to be consistent.

**Comment by kevinreiss** [comment]
So the proposal is to add this to all items, not just the "Off-site" ones?

**Comment by tampakis** [comment]
Yeah I think so - all "Available" off-site items and the on-site rare books and mudd items.

**Comment by kevinreiss** [comment]
Okay. That is easy enough.

**Comment by kevinreiss** [comment]
@swiftg @tampakis So, the label for all "aeon" locatons (whether at RBSC, MUDD, Annex, or ReCAP) should be "On-site access - by request".

**Comment by kevinreiss** [comment]
Resolved. @swiftg please tell us if this needs further examination.
