### ISSUE TITLE
See all items in a Library's collection even if at ReCAP

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#494]
From Julie M.:

> https://pulsearch.princeton.edu/catalog/9230299
> The RBSC recap material is coded as 'recap' not rarebooks and so, you need to do two searches to see if we have a title in rbsc. The link above is one example.

This further blurs the distinction between a physical location and a logical collection, but we're already on that road by having "Rare Books ..." as a library, so I don't think that's an issue. I do think there could be some merit to mapping the recap location codes to holding libraries and allowing users to flag whether or not offsite storage locations should be included in results.

**Comment by kevinreiss** [comment]
Somewhat related to the complaint that flagging RBSC ReCAP locations as "on-site" access is confusing, see #464. Based on feedback I've received from EAL, Marquand, and Mendel over the years I think that in addition to MUDD and Rare Books those libraries would all also welcome it if a default search of their collections could include the locations they have out at ReCAP that are specifically designated for them.

**Comment by kevinreiss** [comment]
In terms of of an offsite flag does that mean we would add a third choice under "Access" where we have an "Offsite Material" choice in addition "In the Library" and "Online"?

**Comment by jpstroop** [comment]
That's what @tampakis was thinking, and it probably makes sense from a UI perspective, but I don't want to put us on the slipperly slope toward include/exclude facets, which is what this would be.

**Comment by jpstroop** [comment]
@kestlund is interested as well.
