### ISSUE TITLE
Use MARCIT OpenURL to link to Query SFX API

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#499]
For online titles that come from the Marcit service use the OpenURL stored in the 856 field rather than the one in the blacklight ctx span tag to query the SFX API to fetch full-text links for display in the 'Online' section. See https://pulsearch.princeton.edu/catalog/8614008 for an example. 7 full-text options should appear instead of two.

**Comment by tampakis** [comment]
Another example. Without the direct lookup, more than 50 matches are returned via Umlaut where as the direct lookup has only 4.
pulsearch: https://pulsearch.princeton.edu/catalog/8622069 (takes a long time to pull the links in)
Getit page: http://getit.princeton.edu/resolve?url_ver=Z39.88-2004&ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&rfr_id=info:sid/sfxit.com:opac_856&url_ctx_fmt=info:ofi/fmt:kev:mtx:ctx&sfx.ignore_date_threshold=1&rft.object_id=110978978742211&svc_val_fmt=info:ofi/fmt:kev:mtx:sch_svc&

**Comment by kevinreiss** [comment]
In order to rectify this the code at https://github.com/pulibrary/orangelight/blob/development/app/helpers/application_helper.rb#L13 needs to be updated to provide a way to tell the js at https://github.com/pulibrary/orangelight/blob/development/app/views/catalog/_show_main_content.html.erb#L19 to use the querystring attached to the 856 url value starting with "getit.princeton.edu" as the OpenURL to passed to Umlaut rather than the one in span tag at https://github.com/pulibrary/orangelight/blob/development/app/views/catalog/_show_main_content.html.erb#L19. That span tag value is generated via the code under discussion for review/replacement in #256.

**Comment by kevinreiss** [comment]
Right now we scrape the URL looking for marc-it records. The object ID value is actually stored in the 035a. Look at that value to see if we can use that to determine direct SFX lookups instead of looking at the URL.
