### ISSUE TITLE
Endnote Export for Theses Records Produces Error

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#501]
Saw this one logged on New Relic a few times this week. Requested by Googlebot. 

Example: https://pulsearch.princeton.edu/catalog/dsp01qz20sv84g.endnote
```
NoMethodError: undefined method `[]' for nil:NilClass
```
…arc-5.10.0/lib/blacklight/solr/document/marc_export.rb: 175:in `block in export_as_endnote'
…arc-5.10.0/lib/blacklight/solr/document/marc_export.rb: 166:in `each'…arc-5.10.0/lib/blacklight/solr/document/marc_export.rb: 166:in `export_as_endnote'…18.0/app/models/concerns/blacklight/document/export.rb:  93:in `export_as'…-5.18.0/app/controllers/concerns/blacklight/catalog.rb: 189:in `block (2 levels) in additional_export_formats'…-5.18.0/app/controllers/concerns/blacklight/catalog.rb:  72:in`show'…2.0/gems/actionview-4.2.6/lib/action_view/
.....
```

**Comment by kevinreiss** [comment]
It appears that most of the alternate format links output in the head section of the record page for these records don't work. Only the basic .xml format produces some minimal DC output.

**Comment by escowles** [comment]
Doesn't work for non-MARC records so it should be disabled for those.

**Comment by jpstroop** [comment]
See https://github.com/pulibrary/orangelight/issues/533#issuecomment-222684802 : same question
