### ISSUE TITLE
Format facet for manuscripts and dissertations

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#506]
The format facets for mss and disserations aren't ideally populated right now -- below are some suggested guidelines for handling these categories which should provide a better user experience.  There are other ways we might approach the problems if these aren't practical.

If 502 is present, treat the object as a dissertation.

If an object is a dissertation, do not also treat it as a manuscript  (meaning that presence of 502 overrides LDR/06 value)

Manuscripts which have 264 |b data should not be treated as manuscripts (meaning that LDR/06 t,d,f are treated as manuscripts EXCEPT when there is a publisher’s name present in 264)

**Comment by tampakis** [comment]
Decision from Tuesday meeting - get rid of dissertation facet altogether.
