### ISSUE TITLE
Negative faceting

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#52]
I.e. "Show me everything without this value".

People think they want it, but it tends to lead to confusion.....

**Comment by tampakis** [comment]
Yale has this in their QuickSearch: (http://search.library.yale.edu/catalog?&f[-format][]=Books&f[lc_1letter_facet][]=P+-+Language+and+Literature&f[lc_2letter_facet][]=P3&q=&search_field=all_fields). The url syntax seems to have the negative facets have the same name as the regular facet with a minus sign preceding the name [-format] vs [format].

**Comment by kevinreiss** [comment]
I believe the summon project actually removed negative faceting from their
interface because user testing consistently showed the feature was
confusing and statistics showed it was lightly used.

**Comment by tampakis** [comment]
The only negative facets I see having any utility are the ones involving format. Things like exclude online, or exclude audio, etc.

**Comment by jpstroop** [comment]
This would be a pretty significant hack to BL as well. I'd rather hear a really strong use case before we consider it.
