### ISSUE TITLE
/catalog/citation

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#533]
This routes produces 
```ActionView::Template::Error: undefined method `find' for nil:NilClass``` with some regularity. See new relic for stack trace.

**Comment by escowles** [comment]
Doesn't work for non-MARC data, so we should disable it to avoid this error.

**Comment by jpstroop** [comment]
Is that the right thing to do, or should we try to support citations from other formats? The records may lack the granularity we need to do so, so disabling may be the practical route...just checking.

**Comment by escowles** [comment]
Disabling to avoid the error is the short-term fix for the problem, but I agree that supporting non-MARC formats is the medium/long-term approach.  I'll create a ticket for supporting non-MARC records for citations.

**Comment by jpstroop** [comment]
:+1:

**Comment by tampakis** [comment]
Yes. Later this week. I will work on pulling the citation/export stuff from the Solr Docs instead. Related to #218 - the OpenURL also pulls from MARC.

**Comment by tampakis** [comment]
This method returns true if the record is a MARC record in the Voyager system: https://github.com/pulibrary/orangelight/blob/development/config/initializers/blacklight_initializer.rb#L16-L19
