### ISSUE TITLE
flash messages in modals

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#538]
Currently flash messages that are triggered within modal windows (like sending an e-mail or SMS of a record) are rendered as part of the modal window container. They should render as part of the main container.
When an e-mail is successfully sent no flash message appears because the modal window is dismissed. When an error occurs, the flash message is off-center:
![flash_modal](https://cloud.githubusercontent.com/assets/4650153/15373893/b6a5148e-1d15-11e6-9e9a-0fc652658496.png)

**Comment by axamei** [comment]
I don't think it would be helpful it the message is rendered in the main container since the modal overlays it. I will keep modal flash messages in the modal instead and create a delay before the modal dismisses so you can see the "email sent" message. How does that sound?

**Comment by tampakis** [comment]
Yeah that's fine. I thought it would be easier to implement if it went 
back to the main container.
