### ISSUE TITLE
Come up with better call number browse link label on show view

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#544]
Users are skipping over the "[Browse]" link in the record show view, partly because it's not prominently displayed and partly because users don't know that clicking the link would allow the users to view items that would be shelved near the record. Some suggestions of replacement text:
"More like this"
"View items shelved nearby"
"Virtual shelf browse"

**Comment by tampakis** [comment]
"Browse nearby call numbers"

**Comment by jpstroop** [comment]
Try making all browse links pills ( / buttons)

**Comment by kevinreiss** [comment]
"More like this" seems like good language to use, if Call Number is fairly reliable way to find similar items.

**Comment by jpstroop** [comment]
"More like this" doesn't seem right me. Adjacent call numbers don't necessarily mean books have anything to do with each other: a biography of Milton Babbit (electronic music pioneer) might shelve after a biography of Harry Babbit (voice of Woody Woodpecker). I'd expect "More like this" to do something clever with subject headings, names, AND classification to build me a custom, focused data set.

https://cwiki.apache.org/confluence/display/solr/MoreLikeThis

**Comment by kevinreiss** [comment]
Maybe let's keep it in reserve for when we have a feature like that 😄

**Comment by jpstroop** [comment]
Yeah. Blacklight already has support for More like this using that Solr feature. I used in LAE, though it's very conservative, and I'm still not sure how well it works. See "Similar Items" at the bottom of this page: http://lae.princeton.edu/catalog/1czn9

**Comment by jpstroop** [comment]
"More like this" is misleading, per impl. group. Come up with a better label.

**Comment by tampakis** [comment]
Current label: "Browse nearby items" - items not physically nearby
