### ISSUE TITLE
LaTex rendering triggered by grave accent character

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#546]
A pair of ` characters trigger the mathjax LaTex rendering: https://pulsearch.princeton.edu/catalog/8571247

I wonder how frequently this occurs?

**Comment by mzelesky** [comment]
It occurs in exactly 1,350 Voyager records. @joycebcat Is this character a valid character for MARC records? It is U+0060.

**Comment by joycebcat** [comment]
That is a legit part of the basic Latin character set, but it is a spacing grave, and I'm not aware of any legit use of this character as a diacritic.  I suspect all the occurrences are, like the example above, from loaded data and in particular contents notes where it started out as a quotation mark or something similar.  We get a lot of bad characters in these 505 fields.  I can zap the existing problems, but I don't have a good way to prevent them from coming in again with bulk loads.  Something that could be logged perhaps?

**Comment by mzelesky** [comment]
@joycebcat This could be added to a monthly error detection script. Or were you thinking of having some checks run daily against the bulk load records? Perhaps we could work on a list of such checks to run on the bulk load records. I believe we had discussed that at one point. Regardless, I'll send you the file of records with that character. A lot of the them are indeed in contents notes, but a lot of them are also just randomly in records at the end of a field.

**Comment by tampakis** [comment]
javascript included here: https://github.com/pulibrary/orangelight/blob/development/app/views/layouts/blacklight.html.erb#L23
