### ISSUE TITLE
Remove "on-order" / "order received" dates from availability label?

### ISSUE THREAD

**Issue by axamei** [pulibrary/orangelight#553]
![screen shot 2016-05-24 at 5 06 40 pm](https://cloud.githubusercontent.com/assets/8161144/15548686/85206aaa-2277-11e6-8176-29d070cbbb93.png)

Some dates go back to 2007 (see screenshot). Not sure how helpful that information is at a glance. We can keep the dates in the tooltips. The label should only have the text "On-order" or "Order Received" in them.

**Comment by mzelesky** [comment]
Agreed; but keeping it in the tooltip might help staff troubleshoot a problem. The date also displays in Voyager. I'll have to run a report to find how many of these long-received items there are.
