### ISSUE TITLE
My Account navigation

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#556]
Feedback:

> On the your account page, when you click Outstanding Requests, you are jumped down the page to that header. There should be a link to go back to top, as, when you have lots of check out books, the three lower categories (Outstanding Requests, Items Available for Pickup, Fines and Fees) are quite far down.

This came up somewhere else, I think. As with any page that is a list of things, it can get long. Would a fixed position navigation bar make sense? Are those a nightmare on mobile?

**Comment by axamei** [comment]
We can implement the "back to top" like the main library site. It will take up less real estate than a fixed nav bar.
