### ISSUE TITLE
Date formatting inconsistencies

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#57]
@joycebcat There seems to be inconsistencies for the formatting of the 008 date. Although 'u' is supposed to indicate an unknown year, sometimes a blank is used. Records published during the first millennium also appear in two formats - either padded by a 0, or with the last digit blank. With both of these formatting inconsistencies present I am unable to accurately extract an accurate date from all of the records. 
For instance, let's say we have the value `200_` 
This record may either be from 200 or from sometime in the 2000s. Based on my sample data, both of these cases are relatively rare. Something published in 200 usually appears as `0200` and something with an unknown 2000's date would be `200u`. Ideally all of the records with dates should fill every digit from 7-11 by either padding 0s from the left or with with u's on the right.

**Comment by tampakis** [comment]
@joycebcat There were a couple more of these in the records I indexed from Primo staging. Here are there bib ids:
7231855 (has valid date in 260c but has 9999 in 008[07-10]
3316911 (600 in 008[07-10] becomes 6000)
3316897 (498 in 008[07-10] becomes 4530)
4677701 (2994 in 008[07-10] probably a typo - 260c has 2004)

**Comment by joycebcat** [comment]
The 4 above are fixed.  The two middle records have a zero padding out the beginning of the date.
