### ISSUE TITLE
"Other versions" misse / tighter Umlaut integration?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#575]
> Journal holdings information is still problematic. It would be great if we had one record for a journal which shows print and electronic holdings. I thought it was fixed so that at least on the electronic records the holding would appear as they do in GetIt but I just tested that again and they are not displaying with the availability dates. This is IMPORTANT users need to be able to see the holdings without having to click through several pages

See "Other Versions" here: https://pulsearch.princeton.edu/catalog/1075815 

This does seem buried, and maybe another side bar would be better. It seems like the ideal would be to embed the[ results from getit](https://getit.princeton.edu/resolve?umlaut.referent_id=425425&url_ver=Z39.88-2004&url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&ctx_ver=Z39.88-2004&ctx_tim=2016-06-02T10%3A22%3A40-04%3A00&ctx_id=&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rft.eissn=1466-1853&rft.genre=journal&rft.issn=1063-0732&rft.jtitle=Journal+of+urban+technology&rft.language=eng&rft.lccn=+++94655045+&rft.object_id=954925275494&rft.place=ENGLAND&rft.pub=JUT+Press&rft.stitle=JOURNAL+OF+URBAN+TECHNOLOGY&rft.title=Journal+of+urban+technology&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&rfr_id=info%3Asid%2Fsfxit.com%3Acitation) though it's not clear how consistent those would be. 

I'm also worried about the sidebar becoming the new center column. We're packing in a lot of info over there already.

**Comment by kevinreiss** [comment]
For "other versions" that are Marc-it titles (i.e. have an 856 starting with getit.princeton.edu) we could definitely leverage the value in the solr doc to render a block using Umlaut's jquery plugin. For "other versions" that are print titles we could likewise call the availability javascript for that bib ID and render a block of whatever comes back there from biddata. 

Regarding the right becoming the new center I kind of like Cornell's approach, https://newcatalog.library.cornell.edu/catalog/5726305. The user has to opt-in to seeing the availability for a title and the often overly long availability information doesn't have to stuffed into a skinny column that can be hard to read and is frequently longer than the wider area we devote to the descriptive metadata for a title which is sort of off-putting.

**Comment by jpstroop** [comment]
There are definitely aspects of the Cornell layout that I like, and if we can get the data from Umlaut, I think we should make that a priority. I don't like having everything down at the bottom of the page though, either--I'm really missing something in the shopping cart space on Cornell's pages.

I wonder if we could keep the box at right for what we have now, but then build out something like what Cornell has specifically for Journals? It feels like too much in the case of a simple monograph, which is still the bulk of the collection

**Comment by kevinreiss** [comment]
We could definitely alter the display by leveraging the format type in the solr document. How would we re-format what we have now to tell the user that need to make it below the descriptive metadata section to review individual journal holdings and dates?

**Comment by jpstroop** [comment]
I think the box at the right would always be there, and that in the Journal case you'd have a link there that triggers a jump down the page, similar to the Cornell "Check Availability" feature

**Comment by kevinreiss** [comment]
I think this one's day has passed.
