### ISSUE TITLE
Inconsistent capitalization in Copies in Library box

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#580]
"Where to Find It", but "Browse nearby items"

https://pulsearch.princeton.edu/catalog/9462018

I think I prefer title caps in this case, so "Browse Nearby Items"

**Comment by axamei** [comment]
Availability text should also be changed. 

"All items available" and "On-site access" in this example: https://pulsearch.princeton.edu/catalog/493646

**Comment by tampakis** [comment]
Or maybe only capitalize the first word in "Where to find it" ?

**Comment by jpstroop** [comment]
Yeah, first word or title case are the options. Seeing the other labels Axa mentioned, I'm less opinionated now.
