### ISSUE TITLE
Make "Other Library Resources" list less prominent

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#584]
Changed from horizontal to vertical because it was wrapping on smaller screens. Still need to come up with a solution for that, but vertical takes up too much space. (from Usability study and impl. group)

**Comment by tampakis** [comment]
Making the other links run across should help draw less attention to them. Some other suggestions:
 - We should also make the "Other Library Resources" and link font a bit smaller.
 - If we add a visible line break it will help push the links further down.
 - Put the link for learning more on a separate line.
