### ISSUE TITLE
Set CAS timeout to be shorter for public terminals

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#585]
The committee thinks 30 minutes is too long (even though people stay logged into email, google, facebook, etc. at the same machines). See if there's a glob pattern for machine names, or else a registry of IP addresses :disappointed:

**Comment by tampakis** [comment]
```ruby
# config/initializers/session_store.rb
Rails.application.config.session_store :cookie_store, key: '_orangelight_session',
                                                      expire_after: 30.minutes
```
30 minutes is too long for public terminals and too short for personal machines. Removing timeout until a better solution is found.
