### ISSUE TITLE
Update 246 labels

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#591]
For the 246 field use "Other title(s)" regardless of indicator. Continue to use $i as label if present.
Feedback:

> display of varying forms of title, examples:
> A - [Arizoniana](https://pulsearch.princeton.edu/catalog/357301)
> B - [Business week](https://pulsearch.princeton.edu/catalog/425417)
> 
> There are problems with some 246 labels; though 246 second indicator 0 is called "portion of title", its actual use is broader than that. We wonder if it would be better simply to list all the 246s under an umbrella label like "Other title(s)" -- perhaps with the exception of 246s with a note in subfield i, as in example B. In that example, the note looks a bit awkward as is, though, with the colon at the end not lining up with the entry.

**Comment by mzelesky** [comment]
I wonder if it would be possible to dedupe the 'Other Title(s)' if the 210, 222, and 246 fields all map to that label. If you look at https://pulsearch.princeton.edu/catalog/357301 (the Arizoniana example above), 'Arizoniana' is shown as the title at the top of the record, then it appears in exactly the same form twice in 'Other Title(s)'. Same with the Business week record. A question for @joycebcat and serials: are the 222 field 'Key Title' and 210 field 'Abbreviated title (a shortened form of the Key Title) useful for display/searching? Those fields are only used for serials, and I would assume other records with variant titles would not have duplicate values in separate 246s.

**Comment by tampakis** [comment]
Should we not display the 246 if the first indicator has a value of 2 or 3?

**Comment by mzelesky** [comment]
I think that would be good (examples that use those indicators are spelling out numbers, the ampersand, etc.). @joycebcat?

**Comment by joycebcat** [comment]
Whoa!  We need to include all the variant titles coming from 246 fields regardless of the indicator.  I see absolutely no problem with grouping them under "Other title(s)" for a label.  This is going to include partial titles, corrected titles, alternate forms of word in the title, parallel titles and some misc. title variants.

**Comment by jpstroop** [comment]
Agree--is local practice different from what the MARC docs say? We're just talking about display, not indexing.

**Comment by joycebcat** [comment]
Yes, @jpstroop  local practice doesn't match the actual MARC definitions.  PS staff don't like when a search result returns a string which doesn't actually appear in the visible data.    Yes, @tampakis, I recall a discussion about collapsing them all into a single label, and I have absolutely no objection to doing so myself.
