### ISSUE TITLE
Try honeybadger.io

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#596]
@eefahy just told me about this. Free for OSS.

**Comment by jpstroop** [comment]
Not pressing. Wondering if @kayiwa has any opinions?

**Comment by kayiwa** [comment]
hmmm. Do we have a "philosophy" on who we give our data to? My default preference* is I will pay for a good product but I'd like it to be self hosted. Not a fan of "phone home" aggregation. 

*Francis default may not be PUL's ;-)

**Comment by kayiwa** [comment]
I've implemented happily Amon happily which doesn't not compare "feature for feature" but does most of what honeybadger does but with a less "cool" name. 

https://www.amon.cx/

**Comment by jpstroop** [comment]
I'm happy to wait and see if it's something we really need and then evaluating. It seems like something that would be useful during development or beta more than in production. Closing; we can reopen when there's a use case.
