### ISSUE TITLE
Previous/Next doesn't work with multiple tabs

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#599]
Blacklight gets confused about the search context when doing searches with multiple tabs. For instance, when opening the result of [any search](https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=anything) in another tab, the Previous/Next search context says the result is `1 of n` regardless of the actual result number.

**Comment by escowles** [comment]
I was able to open two searches in two separate tabs, and page through the search results and then open items and page through items.  I did not see any problems with the search results or numbers of records getting mixed up between the two tabs.
