### ISSUE TITLE
Make entire call number browse row link to record

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#604]
Currently only the call number text is a link in the call number browse. Make the whole row link to record/search, especially for the exact matches (the blue row).

**Comment by tampakis** [comment]
Also this was brought up in a feedback:
> Regarding call no. browse on basic screen. I note that the searched call no. comes in as the fourth item on the list (at least in my case)--ML458 .D57 2015). Why so far near the bottom? I can see why having a preceding call no. might be helpful, but not 3. Better to have the searched call no. closer to the top, I think. Is exact search possible? Or perhaps if the searched call no. came at the top of the list, it would have the effect of an exact search.

**Comment by mzelesky** [comment]
Perhaps just making the exact result more prominent would suffice? Making the call number bold? All text of the exact match bold?

**Comment by tampakis** [comment]
Decided at implementation group meeting: Only display 2 before call number match, not 3. Make the text in the matching row bold.
