### ISSUE TITLE
Split subjects for Topic facet

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#62]
The subfields we're concerned about are `a`, `x`, and `z` (`y` goes in Era, `v` and terms from Joyce's list in #47 go in Genre). However, `a` can be followed by other subfields that should be included in the value that gets added to the index, e.g. `d` could be the date for a name.

Suggest using a `while` loop over the subfields that assembles the string, and breaks when it hits a subfield that should be in a separate value. Lovely MARC.

**Comment by tampakis** [comment]
Use labels like Subject: Era, Subject: Topic, Subject: Geographic for facets
