### ISSUE TITLE
Disable stemming for specific words?

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#631]
Perthes should not stem to Perth.

**Comment by tampakis** [comment]
https://github.com/pulibrary/pul_solr/blob/master/solr_configs/pulmap/conf/protwords.txt

**Comment by tampakis** [comment]
Constanter

**Comment by jpstroop** [comment]
Be sure to email Steve once this is fixed...maybe give him a lightweight
explanation and ask for more exceptions if he can think of them/as he finds
them.
