### ISSUE TITLE
Next Record 500 Error

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#637]
If you leave an OL record page open too long in a browser window and then return and click a "Next Record" button you get a 500 error and the following URL:

https://pulsearch.princeton.edu/catalog/9676483/track?counter=4&search_id=1475057

We should look into a more graceful failure page. The error that is produced seems to be `ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken`.

**Comment by tampakis** [comment]
This is an error that should be fixed in the Blacklight gem for search sessions that time out.

**Comment by jpstroop** [comment]
Is this still an issue? I'm seeing a reasonable error page, unless you think there's something better was can do.

**Comment by tampakis** [comment]
I think if the `counter` and `search_id` params of the url are stale, the record should still display, but without any "previous" or "next" buttons.

**Comment by hackmastera** [comment]
@tampakis is there a BL issue we can point to from this one?
