### ISSUE TITLE
Double locate

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#64]
When something has multiple (online?) locations, rather that "Locate, Locate" use the location as the text for the anchor. Maybe sticking some JSON in the index for parsing in the view would be an easier way to go about this?

**Comment by tampakis** [comment]
Holdings are now grouped based on [call number](https://github.com/pulibrary/orangelight/blob/development/app/helpers/application_helper.rb#L32-L54).
Closed by #101 and #102
