### ISSUE TITLE
Stub or mock client-side calls to external APIs

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#656]
The test for the umlaut/getit service fails because the record for the fixture no longer exists.

https://pulsearch.princeton.edu/catalog/8606339

**Comment by eliotjordan** [comment]
https://github.com/pulibrary/orangelight/blob/development/spec/features/availability_spec.rb#L32

**Comment by eliotjordan** [comment]
The simple solution here is to swap out the fixture. The better solution is to figure out how to test ajax calls to external services.

**Comment by kevinreiss** [comment]
Best thing is to probably mock the call out to the live service with a Faraday stub.

**Comment by eliotjordan** [comment]
@kevinreiss These are ajax calls made by the client.

**Comment by eliotjordan** [comment]
Does Faraday provide methods for doing this? A quick search reveals a JS library called [Mockjax](https://github.com/jakerella/jquery-mockjax) This article is also helpful: https://robots.thoughtbot.com/using-capybara-to-test-javascript-that-makes-http.

**Comment by tpendragon** [comment]
I've done this before with jasmine-ajax: http://jasmine.github.io/2.0/ajax.html, but I don't remember where...

**Comment by tpendragon** [comment]
Ah, in CC: https://github.com/projecthydra/curation_concerns/blob/master/spec/javascripts/file_manager_member_spec.coffee

**Comment by kevinreiss** [comment]
Some more context for this one. This is the documentation for the utility within Umlaut that is being called here:

https://github.com/team-umlaut/umlaut/wiki/JQuery-Content-Utility

The set-up for the Jquery call is in https://github.com/pulibrary/orangelight/blob/master/app/views/catalog/_show_main_content.html.erb#L10-L87. 

The data attributes and id values that are used in the set-up for the Jquery currently come the urlify helper https://github.com/pulibrary/orangelight/blob/94ac1340597df639711782c8adfe50cedf9671fb/app/helpers/application_helper.rb#L8 and two other umlaut related helpers called in this partial https://github.com/pulibrary/orangelight/blob/master/app/views/catalog/_show_availability_sidebar.html.erb.

**Comment by hackmastera** [comment]
Thanks @kevinreiss

**Comment by hackmastera** [comment]
On checkin we discussed several possibilities, including:
* the capybara thoughtbot article linked above (a bit heavyweight, also introduces a sinatra dependency)
* refactoring the js to test this functionality in a unit testing rather than a feature test, using jasmine's ajax.js
* using jest for unit tests since we're introducing it in another of our applications. but mocking is only offered at the function level, and hopes of moving to it for feature tests generally seem to go against general use / best practice.

Two other projects were discovered during the call:
* https://github.com/hashrocket/capybara-webmock
* https://github.com/oesmith/puffing-billy

I'm going to try using puffing-billy since it appears to be a more mature project, more recently updated, and with better documentation.

Ultimately the goal is to not call the external API from tests. I'm going to rename this issue to reflect that. may also be able to tackle bibdata calls, but may put that in its own issue.

**Comment by hackmastera** [comment]
Okay I think puffying-billy is a dead end. Its README recommends turning off webmock on tests that use puffing-billy. But this would leave us hitting bibdata on those tests. still we can improve things if we do that, but it's not ideal; it's really better to not have to hit the external api in the test at all.

* https://github.com/oesmith/puffing-billy#working-with-vcr-and-webmock
* https://github.com/oesmith/puffing-billy/issues/44#issuecomment-38746497

Gonna look again at capybara-webmock but I'm starting to think that unit testing the JS is probably the right call here.

**Comment by hackmastera** [comment]
capybara-webmock doesn't do any actual mocking https://github.com/hashrocket/capybara-webmock/issues/20#issuecomment-346095880

**Comment by kevinreiss** [comment]
Are the main points of concern here specs that hit https://bibdata.princeton.edu/availability and https://getit.princeton.edu? For the latter all we'd really want to test are that the appropriate id divs that utility overlays "full_text" and other services on. That works if you make the assumption that getit is going send back something reasonable. The JS unit testing sounds like the way to go for the availability calls.

**Comment by hackmastera** [comment]
Okay @tampakis had a new idea that doesn't require us to refactor the javascript and also doesn't require us to run sidecar servers!

The plan is to serve static fixture files out of the `public/` directory. Store them in `spec/` and have a script in our test setup that copies them; this way they're not served in production. Change the method/s that actually make the external calls to require the server host as an argument. Then client-side code can use fixtures from `localhost` and server-side can continue using webmock.

**Comment by hackmastera** [comment]
quick fix was applied in #657. closing this as it is now superceded by #1092.
