### ISSUE TITLE
e-mailing bookmarks / catalog-help reporting address

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#689]
@tampakis @jpstroop 
Jane encountered a problem e-mailing items she had bookmarked to herself: "I just tried to email the results of a search from the Blacklight catalog (the 3 titles on AST 303 Course Reserve) and received error message “We’re sorry, but there was a problem processing the page your requested.”   I had bookmarked the 3 titles ,  clicked on Email , addressed it and added message."  I tried and had the same problem. Also, the message that came up suggested e-mailing "catalog-help" -- does this e-mail address go anywhere?

**Comment by kevinreiss** [comment]
See #690. Corrected.

**Comment by kevinreiss** [comment]
@joycebcat @tampakis I don't know what the "catalog-help" address is. Should that be the address of the catalog email we have in the new libanswers system?

**Comment by joycebcat** [comment]
Maybe it was something we intended to set up?  Anyway, it is a question of where these issues should go.  Sending them to "catalogn" puts them into my Q, sending them to "lsupport" put them into systems Q.  If we need an address to appear when something doesn't work right, it should go to Systems, not to me.

**Comment by tampakis** [comment]
Closed by #686.
