### ISSUE TITLE
RSS/Atom Review

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#69]
Blacklight lets you get any query as any RSS/Atom feed. We should review what we metadata we want to dump to these queries.

http://pulsearch-dev.princeton.edu/?f%5Blanguage_facet%5D%5B%5D=Chinese&format=rss
http://pulsearch-dev.princeton.edu/?f%5Blanguage_facet%5D%5B%5D=Chinese&format=atom

Making sure we have facets for each library, and each location code along with some reasonable would enable blacklight to replace the very buggy standalone new titles service we run now.

**Comment by axamei** [comment]
Added feed icon next to pagination in #387. 

To do: clean up content placed in the summary tag.

**Comment by tampakis** [comment]
Closed by #399
