### ISSUE TITLE
Upgrade PhantomJS

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#693]
Test suite on CI reports. 

`You're running an old version of PhantomJS, update to >= 2.1.1 for a better experience.`

**Comment by tampakis** [comment]
Add this to our Travis yml? https://github.com/mitchlloyd/ember-orbit/commit/9d3afe3d0434d9e3572e018d65ea96857fe5fa25
Travis only has version 1.9.8 installed on their containers.

**Comment by tampakis** [comment]
This bug
