### ISSUE TITLE
ISSN Weirdness when "-" included

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#694]
I know this was closed out awhile back: https://github.com/pulibrary/pul_solr/pull/3 but ISSNs still seem to be a problem:

https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=issn_s&q=10668543+OR+21693838
or
https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=10668543+OR+21693838

Both bring back the single record that should match. Including the "-" character gives you thousands of unrelated results:

https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=issn_s&q=1066-8543+OR+2169-3838
https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=1066-8543+OR+2169-3838

**Comment by tampakis** [comment]
It looks like adding the OR is the problem.

**Comment by kevinreiss** [comment]
This was resolved with adding issn and isbn as discrete search options.
