### ISSUE TITLE
Consider a different cover service (or no cover service)

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#703]
We are getting a lot of reports about wrong covers, and we have no way to fix them with the Google service. We have access to Bowker's cover service, but it has significantly less titles.

**Comment by tampakis** [comment]
Most inaccuracies are lccn lookups, remove them from the lookup.

**Comment by jpstroop** [comment]
Meeting on 11/1/2016: maybe create a "bad covers" service that is generated from user reports. Query that before hitting the covers service to know not to check/render particular covers.

**Comment by tampakis** [comment]
Another reported example:
https://pulsearch.princeton.edu/catalog/2309264

Maybe we should consider to stop looking up based on LCCN, or excluding LCCN when ISBN/ISSN/OCLC are present.

For this record:
LCCN (mis)match - https://books.google.com/books?id=rY92QgAACAAJ&source=gbs_ViewAPI
OCLC match - https://books.google.com/books?id=9nUuQAAACAAJ&source=gbs_ViewAPI

**Comment by kevinreiss** [comment]
I think LCCN is pretty much useless in this context.

**Comment by jpstroop** [comment]
👍
