### ISSUE TITLE
Temp Location Availability

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#704]
Make sure that the correct labeling (and links) are updated after availability loads. 

See https://pulsearch.princeton.edu/catalog/5318288. Should not display paging requests given the temporary location.

**Comment by tampakis** [comment]
Paging request button doesn't display on the record display, but the paging warning icon appears in the search results still: https://pulsearch-dev.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=5318288

**Comment by kevinreiss** [comment]
Resolved in ee600b850ba68e25af04bff08f5214420737f274.
