### ISSUE TITLE
Add hierarchy to classification facet for major schemes

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#71]
Major categories are:
- [x]  LoC
- [x]   SuDoc
- [ ]  Richardson (@joycebcat  will supply a list of labels that map to highest levels of the scheme)
- [ ]  Harvard Yenching (?? thoughts about this one?)
- [x] Accession Numbers - starting with, e.g. CD-, DVD-, MICROFILM- ... no reason to include these

"Electronic Resource.*" should also be excluded. (correct?)

There are also shelf numbers (e.g. Islamic MSS, Scheide) and collection numbers (Mudd, RBSC), that will need to be handled case by case later on. This issue can be closed when the three or four (if we include H. Yenching) are handled.

**Comment by tampakis** [comment]
https://en.wikipedia.org/wiki/Harvard%E2%80%93Yenching_Classification
