### ISSUE TITLE
CSS for tour item

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#716]
Looks like there's a length problem?

![screenshot from 2016-09-07 12-41-08](https://cloud.githubusercontent.com/assets/999701/18320625/a88f4c4e-74f8-11e6-9ed2-d3b9d48d21e8.png)

**Comment by axamei** [comment]
@tampakis Could this be because the availability label / "On-site access" is loading after introjs?

**Comment by jpstroop** [comment]
I think we could push to prod without fixing this immediately. Just something I noticed.

**Comment by tampakis** [comment]
Yeah it's because the box gets drawn before the request button appears (which happens after availability js runs).
