### ISSUE TITLE
Add additional elements to browse tables

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#73]
* [x] Call number browse needs brief title, creator, date
 * [ ] Does Subject need scheme? (Voyager has a column that says Library of Congress)
 * [x] Does Names need type? (Voyager has a column that indicates Personal or Corporate)

**Comment by tampakis** [comment]
Show pages for browse pages should be disabled. http://pulsearch-dev.princeton.edu/browse/names/23526
