### ISSUE TITLE
Reply-to on Feedback Form

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#731]
This should not be set to l-support on feedback form submissions.

**Comment by tampakis** [comment]
Other suggestions: "activate" the e-mail modal once it gets clicked so users can type the e-mail address without clicking in the email.
Update the header text from "Email this" to "Email the catalag record and (optional) message."
Explore whether it is easy to add the ability to "remember" the email address so the user doesn't have to type each time they send a record.

**Comment by jpstroop** [comment]
This may be done? Not seeing SN@P tickets anyway.

**Comment by tampakis** [comment]
Yeah lsupport is no longer the reply to for feedback. I just realized put my comments on an unrelated issue.
