### ISSUE TITLE
META - left anchored search.

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#74]
Closing #33 and #66 and summarizing here:

We think we have it solved using n-grams, not tokenizing at all, collapsing the case using the ICUFoldingFilterFactory, and the  [Dueber method](http://robotlibrarian.billdueber.com/2012/03/boosting-on-exactish-anchored-phrase-matching-in-solr-sst-4/) :wink:.

A left-anchored search must be available be available for the following: 

 * [ ] Call Number
 * [ ] Subject
 * [ ] Names
 * [ ] Titles

In the case of title, __let's try putting it in the index both with and without the initial article__ (based on 245 indicator 2) so that users don't need to know.

Outstanding questions:

 * Should there be one "Starts with" search, in which case we should somehow bring out _why_ this result was returned (did the hit come from subject, creator, title, etc.) see [HighlightingParameters](http://wiki.apache.org/solr/HighlightingParameters); or should we have "Creator starts with", "Title starts with", etc. etc.
 * Does the user have to supply the wildcard, or should/can we tack it on?
 * Could take it a step further and do autocomplete from these fields when a user is typing a search? see [Suggester](https://wiki.apache.org/solr/Suggester). Would be awesome.

**Comment by tampakis** [comment]
The functionality is there by stripping out whitespaces in Blacklight and the [EdgeNGramFilterFactory](https://wiki.apache.org/solr/AnalyzersTokenizersTokenFilters#solr.EdgeNGramFilterFactory). Will this scale? It can create tokens up to the first 50 characters of an entry.

My Blacklight [whitespace stripper code](https://github.com/pulibrary/orangelight/blob/development/app/helpers/blacklight_helper.rb#L26-L33) doesn't work on advanced search.
