### ISSUE TITLE
Pagable Holdings should suppress "Where to Find It Links"

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#751]
No reason to show a link to a location you can't access.

**Comment by kevinreiss** [comment]
We currently generate this in application_helper which makes it difficult to handle things like temp items and items in open stack locations that may be charged out. @tampakis maybe we should offload the generation of this link to availability.js entirely?

**Comment by tampakis** [comment]
I think offloading the link to the availability makes a lot of sense, especially since the map link is supposed to use the temporary location loaded from the availability response

**Comment by kevinreiss** [comment]
One slightly annoying thing is that availability.js needs be made aware of what is and what isn't "pageable."

**Comment by tampakis** [comment]
The logic for drawing the paging request button and the where to find it should live in the same place.

**Comment by kevinreiss** [comment]
Getting all those into the same routine seemed out of scope for this PR. I put in something to handle the "temp" location in the JS after suppressing pageable links in application_helper. I think we need to rethink the notion of our "holdings" data model a bit so we can unify things in a more coherent way. Right now we have logic relating to the request button, stackmap, and the availability labels broken up in three places (availability.js, application_helper.rb, and within marc_liberation).

**Comment by kevinreiss** [comment]
Closing.
