### ISSUE TITLE
Lost should be red

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#754]
See https://pulsearch.princeton.edu/catalog/1712726. Also the request form should not show recall since the item isn't charged.

**Comment by tpendragon** [comment]
Apparently that record got found. What color should lost be?

**Comment by kevinreiss** [comment]
Apparently there happy endings for Library materials. The label color when an item is "Lost" should be red.

**Comment by jpstroop** [comment]
There aren't accessibility concerns as long as the text is there as well, right? Pick something pretty ;-)
