### ISSUE TITLE
Items from Visuals need more holdings context.

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#757]
From Julie:

> Now that we are using the new online catalogue for the visuals material through Aeon, we need to work on the location display.
> Right now it says drawer 5, but nothing more for a location. We have 8 vaults and many flat files, many drawer 5s.
> I need the "folder/box" field from the visuals database to appear. Can that be changed?
> 
> Currently:
> Rare Books and Special Collections - Graphic Arts Collection
> GC059 GA 2011.01538 Drawer 05/GC059/Half Folio/Artists Q-Z Drawing/American/20th c./GC059
> 
> Folder/box field:
> Folder/Box = A Middle 38/Drawer 05/GC059/Half Folio/Artists Q-Z

**Comment by kevinreiss** [comment]
@tampakis is working on this per OL meeting today.

**Comment by jpstroop** [comment]
For more background: Don has to change some queries and maybe then update an XSLT, which Gary will then need to change on the server.

**Comment by jpstroop** [comment]
This came up again today. Needs to be a priority for next sprint.

New SQL from DT:

> SQL for query “DRTExclude” for Gary to use in selecting records for output as XML:
> 
> ```
> SELECT Data.idRecord
> FROM Data INNER JOIN Elements ON Data.idElement = Elements.idElement
> WHERE (((Data.idElement)=13) AND ((Data.Value) Like "Graphic Arts/*")) OR (((Data.idElement)=24) > AND ((Data.Value)="Deaccessioned"));
> ```
> The query that makes the table is unchanged:
> 
> ```
> INSERT INTO DRTRecordsQuery ( idRecord, Element, [Value] )
> SELECT Data.idRecord, Elements.Element, IIf([LongData].[idData] Is Null,[data].[Value],[longdata].[LongValue]) AS [Value]
> FROM ((Data INNER JOIN Elements ON Data.idElement = Elements.idElement) LEFT JOIN LongData ON Data.idData = LongData.idData) LEFT JOIN DRTExclude ON Data.idRecord = DRTExclude.idRecord
> WHERE (((DRTExclude.idRecord) Is Null))
> ORDER BY Data.idRecord, Elements.Element;
> ```

**Comment by kevinreiss** [comment]
If we can make the data stored in the holdings_1display key for "visuals" more granular mapping the data into the appropriate fields for Aeon will be straightforward. Example: https://pulsearch.princeton.edu/catalog/visuals46572.json
