### ISSUE TITLE
Minimize buttons on index and show views

### ISSUE THREAD

**Issue by axamei** [pulibrary/orangelight#760]
Change to show only icons/one word on mobile view? 

index:
<img width="309" alt="screen shot 2016-10-11 at 2 37 10 pm" src="https://cloud.githubusercontent.com/assets/8161144/19283555/4f6cd770-8fc0-11e6-8f0f-07b3c4a0d35c.png">

show:
<img width="317" alt="screen shot 2016-10-11 at 2 37 25 pm" src="https://cloud.githubusercontent.com/assets/8161144/19283557/513f5046-8fc0-11e6-992d-ad2515f0a05d.png">

**Comment by jpstroop** [comment]
I think that makes sense :+1:
