### ISSUE TITLE
ISBN qualifiers - display form

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#761]
With a recent change to MARC, ISBN qualifying data can be coded separately and we have a number of records with the new coding.  Qualifying information is coded in |q.  According to the online spec, we would NOT expect to use parentheses in the |q when coding the data, but it is desirable to display it with punctuation or it all runs together.  Unfortunately there are many records in Voyager with the |q AND parentheses, as well as a number without.  Can we have BL display the data with parens if they aren't already present?  If there are multiple |q's present, one set of parens and a space colon space in between as seen below.

Example:
9781138909847 ‡q hardback

Example in Blacklight:
https://pulsearch.princeton.edu/catalog/9919546

Complicated example:
9781472460462 ‡q hardback ‡q alkaline paper

Desired display form:
9781472460462 (hardback  : alkaline paper)

**Comment by tampakis** [comment]
@joycebcat - I'm looking at the example record in Blacklight and notice that the ebook isbn doesn't display because it has a subfield $z instead of $a. We don't want to display that at all right?

**Comment by joycebcat** [comment]
@tampakis Correct, we don't want to display it.  |z is by definition an invalid ISBN.  It is also used (as I mentioned also on the other ticket) for other physical version, although that isn't actually correct MARC usage.

**Comment by tampakis** [comment]
Example with two values in the subfield $q https://catalog.princeton.edu/catalog/9056720

**Comment by tampakis** [comment]
Modify isbn_display field, https://github.com/pulibrary/marc_liberation/blob/master/marc_to_solr/lib/traject_config.rb#L854

**Comment by jrgriffiniii** [comment]
Display form modifications were addressed by https://github.com/pulibrary/marc_liberation/pull/377
