### ISSUE TITLE
Should be able to print MARCXML and HTML view of records

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#77]
For HTML this likely just means a print CSS. For MRX it means getting the "Librarian View" out of the modal.

Note that Blacklight sets the Content-Type header to "application/marcxml+xml; charset=utf-8", which some browsers understand (Chrome did in mine just now and rendered it as expected) but others (whatever @tampakis was using on 10/7) do not and just a return a long string. We should probably wait for browsers to catch up since this is a relatively minor feature.

E.g. http://pulsearch-dev.princeton.edu/catalog/3428957.marcxml

**Comment by tampakis** [comment]
Librarian view is sufficient.
