### ISSUE TITLE
Send Temp Location Code to New Stackmap

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#778]
When new stackmap is launched undo https://github.com/pulibrary/orangelight/pull/776.

**Comment by mzelesky** [comment]
This issue came up again today in discussions with Stokes Library. In some cases, because the temporary location is not used, it sends the user to a different library entirely. This is especially important for Reserve Items.

**Comment by tampakis** [comment]
@mzelesky do you have a bib id we can use for testing?

**Comment by mzelesky** [comment]
https://pulsearch.princeton.edu/catalog/9082288

The second holding is on reserve at Engineering, but it points to Stokes.

**Comment by mzelesky** [comment]
The only type of temp location that currently works is an item that is a permanent Firestone item that has a temp location also within Firestone.

**Comment by mzelesky** [comment]
- { } Firestone permanent location with branch temp location should send the temp location to Stackmap
 - { } Firestone permanent location with Firestone temp location should send the MFHD location to Firestone Locator
 - { } Firestone temp location with branch permanent location should send the MFHD location to Firestone Locator
 - { } Branch temp location with branch permanent location should send the temp location to Stackmap

**Comment by tampakis** [comment]
Stackmap service has been refactored. Firestone locator is a mess.
