### ISSUE TITLE
Solr stemming potential features

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#791]
Stemming related:
 - [ ]  consider a [less aggressive](https://cwiki.apache.org/confluence/display/solr/Filter+Descriptions#FilterDescriptions-KStemFilter), possibly [dictionary-based](https://cwiki.apache.org/confluence/display/solr/Filter+Descriptions#FilterDescriptions-HunspellStemFilter) stemmer
 - [ ] disable stemming for phrase searches
Relevancy related:
 - [ ] Use [remove duplicates](https://cwiki.apache.org/confluence/display/solr/Filter+Descriptions#FilterDescriptions-RemoveDuplicatesTokenFilter) filter? so titles with the same word multiple times don't get such a high boost.

**Comment by tpendragon** [comment]
Do we have concrete examples of how searching isn't precise enough?

**Comment by tampakis** [comment]
Compare [production](https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&q1=&op2=AND&f2=author&q2=&op3=AND&f3=left_anchor&q3=wire&f_inclusive[format][]=Journal&range[pub_date_start_sort][begin]=&range[pub_date_start_sort][end]=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search) and [dev](https://pulsearch-dev.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&q1=&op2=AND&f2=author&q2=&op3=AND&f3=left_anchor&q3=wire&f_inclusive[format][]=Journal&range[pub_date_start_sort][begin]=&range[pub_date_start_sort][end]=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search). Although relevancy is a lot better, records with the "wireless" shouldn't match at all. The stemmer is too aggressive.

**Comment by tpendragon** [comment]
That's not stemming's fault, that's because you're using an n-gram filter for left-anchored searches.

**Comment by tpendragon** [comment]
The reason I ask is I don't think we're actually using a stemmer, are we? I only see stem filters in the solrconfig for text_en field types, which we're not using.

**Comment by tpendragon** [comment]
@tampakis Should we move this out of ready until we have searches to improve?
