### ISSUE TITLE
Ampersand in titles should be equivalent to and?

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/orangelight#792]
Compare these two results lists:

https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=%22pride+and+prejudice%22

https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=%22pride+%26+prejudice%22

Not all editions of Pride and Prejudice show up in a search of "Pride and prejudice". While this issue can also be addressed with adding 246s to the bibs, I am wondering if it could also be addressed on the Orangelight side.

**Comment by tampakis** [comment]
Closing a search for `Pride & Prejudice` without quotes yields a superset of the `Pride and Prejudice` search. Searches within quotes are more supposed to be more like exact string searches.
https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=pride+%26+prejudice
https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=pride+and+prejudice
