### ISSUE TITLE
Email this record improvements

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#793]
- [x] "activate" the e-mail modal once it gets clicked so users can type the e-mail address without clicking in the email.
 - [x] Update the header text from "Email this" to "Email the catalog record and (optional) message."
 - [ ] Explore whether it is easy to add the ability to "remember" the email address so the user doesn't have to type each time they send a record.
 - [ ] Allow users to set a reply-to/email-from value when records are being shared on behalf of another person.

**Comment by tpendragon** [comment]
I'm sort of hesitant to implement #4...providing a form to send emails as others seems problematic. Maybe if it just set the from as the person who's logged in?

**Comment by tpendragon** [comment]
For bullet point three, can we just count on browser's autocomplete functionality? Chrome just sort of does what I'd want. I can probably write something that stores the email in a cookie, or even a session, but we'd have to override both the controller and the mailer from Blacklight to make it work.

**Comment by jpstroop** [comment]
Isn't point 4 essentially setting up a spam service? Agree; if you're logged in it could be from your_netid@princeton.edu.

Agree about point 3. Has anyone asked for this? Could we use a similar approach and default to the email being from the netid of the person who is logged in?
