### ISSUE TITLE
Record should be able to load without a call to bibdata

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#798]
When going to the individual record show page, a bibdata call to fetch the marc is made to construct the open url on page load. When bibdata is under heavy load/down, the page may never load. Possibly make this part of a js call or reconsider adding the open url to the solr index to avoid constructing the open url "on the fly."

**Comment by tampakis** [comment]
Related to #804. I confirmed when bibdata is down the record show page doesn't load because Orangelight makes a request to bibdata for the live Marc XML before loading the page to construct tbe openurl.

**Comment by kevinreiss** [comment]
The idea was to always replace that live call with bibdata with something that drew an an openURL that was pre-baked in the index. The the methods in Orangelight that call bibdata live were overridden from blacklight-marc https://github.com/projectblacklight/blacklight-marc/blob/b7fde6c238dd5a1cd6a63aae17822ca18659efc7/app/models/concerns/blacklight/solr/document/marc.rb. The ```to_marc``` method there calls ```marc_record_from_marcxml``` that expects to find a string of Marc in the solr document as a field. Our override makes does a live call instead.

A lot of the the alternative format types that get rendered as <link> tags in the <head> of the show page also make use of to_marc pretty extensively through blacklight-marc. So if crawlers try and traverse those links the live call is going to get hit again as well. We may actually just want to consider loading in the marc record as a string value in a field in the solr doc  if we want to keep using these features from blacklight-marc.

**Comment by kevinreiss** [comment]
This hack in the urlify helper https://github.com/pulibrary/orangelight/blob/development/app/helpers/application_helper.rb#L14-L17 is the use case *when* we currently want the OpenURL to fetch electronic journal holdings from Umlaut for the appropriate records. If we want to try to execute an interim step to mitigate the real-time calls to when they are useful wrapping the code in this partial https://github.com/pulibrary/orangelight/blob/development/app/views/catalog/_show_main_content.html.erb#L18-L53 that sets up the javascript needed to fetch data from getit.princeton.edu in some version of the code in the urlify helper code reduce the use of bibdata greatly. There are roughly 40,000 journal records that fall into case tested in the helper.
