### ISSUE TITLE
Keep bots off of bibdata?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#804]
I *think* bots crawling Orangelight might be hitting bibdata for availability unnecessarily. How can we stop this? One solution might be to use the load balancer to direct bots to separate instances of Orangelight that don't show availability. Or, since availability is a secondary request, is there a way to keep bots from making that request? I don't know anything about bots and AJAX.

**Comment by hackmastera** [comment]
Discussed at all hands the week of 12/4/2017. bibdata should be set up under load balancer, with bot traffic filtered out, upon completion of pulibrary/marc_liberation#282

**Comment by eliotjordan** [comment]
Load balancer is now filtering out bots.

**Comment by jpstroop** [comment]
All bots, or are we still being crawled by Google?

**Comment by hackmastera** [comment]
@jpstroop this issue is about keeping bots off of bibdata. I don't think we want an exception for google, right?

**Comment by jpstroop** [comment]
Yes, my bad. I was thinking it was the whole catalog, not just bibdata.
