### ISSUE TITLE
Don't hardcode blacklight-core and use Rsolr to make solr request

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#809]
- [ ] [Browse Lists](https://github.com/pulibrary/orangelight/blob/1e937344e629592d7122dc2933cb70d4bace1d94/lib/orangelight/browse_lists.rb#L17)
 - [ ] [OCLC/ISBN/ISSN/LCCN lookup](https://github.com/pulibrary/orangelight/blob/1e937344e629592d7122dc2933cb70d4bace1d94/app/helpers/blacklight_helper.rb#L230)
 - [ ] [Reserves core](https://github.com/pulibrary/orangelight/blob/1e937344e629592d7122dc2933cb70d4bace1d94/app/indexers/reserve_indexer.rb#L16)

**Comment by tampakis** [comment]
blacklight-core is no longer hardcoded, but still switch to use rsolr

**Comment by eliotjordan** [comment]
@tampakis I think we can close this. All of the tasks above appear to be completed. Do you agree?
