### ISSUE TITLE
Record not appearing in BL

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#821]
Record missing from Blacklight:
10037283 

Neither the bib nor the mfhd is suppressed.  It was last touched on Dec. 27th.  I don't see any reason why it shouldn't be appearing in BL.

**Comment by mzelesky** [comment]
I double-checked for any invalid characters in this record and there were none. It might be helpful for troubleshooting to know that the bib record was suppressed on December 22nd (the date it was created) and unsuppressed on December 27th.

**Comment by tampakis** [comment]
The daily update process failed on December 27th (because Bibdata had crashed from GoogleBot). I just ran the refresh manually: pulsearch.princeton.edu/catalog/10037283
