### ISSUE TITLE
Refactor availability.js

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#823]
There's a lot going on here that could be split out into context sensitive classes. It should be ES6 instead and pull the appropriate query URLs from the DOM, as well.

**Comment by jpstroop** [comment]
see also pulibrary/marc_liberation#145 maybe?

**Comment by jpstroop** [comment]
@kevinreiss has pointed out that the availability logic lives in three places: here, in the bento search, and in Umlaut/getit. His idea, and I tend to agree, is that we should push it all down into MARC Liberation.

**Comment by tpendragon** [comment]
Yeah, that's definitely part of it.

**Comment by christinach** [comment]
related to https://github.com/pulibrary/orangelight/issues/1895

**Comment by hackmastera** [comment]
Links given in #1895 may be helpful.

The availability code gets very complex as soon as one starts to follow all the paths. Even if ultimately we want to refactor functionality out to marc_liberation, getting this code converted out of coffeescript and covered by tests will be a useful step in that process.
