### ISSUE TITLE
Page numbers beyond the actual range of records

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#84]
http://pulsearch-dev.princeton.edu/catalog?utf8=%E2%9C%93&page=5&q=&search_field=all_fields&range[pub_date_start_sort][begin]=2211&range[pub_date_start_sort][end]=6001&commit=Limit

I came across this when trying to set a date limit after browsing through a results view. While setting other facet limits start a new search, the date limit applies the search constraint without reseting the page number, which is especially a problem when there are less pages of results returned than the currently set page (as shown above). In general I think it's a bug that Blacklight doesn't check whether or not any given page (even if it is manually entered in the url) is actually a valid page of results. If it is beyond the range, it should just return the last page of results.

I think that this should display the "last" page of results, which in this case is page 1:
http://pulsearch-dev.princeton.edu/?utf8=%E2%9C%93&search_field=all_fields&q=nickel+coins&page=4

**Comment by escowles** [comment]
Looks like an easy upstream fix: https://github.com/projectblacklight/blacklight_range_limit/pull/76
