### ISSUE TITLE
OR broken in advanced search?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#846]
I just put in this search

![image](https://cloud.githubusercontent.com/assets/999701/22462144/12a0941e-e77a-11e6-9927-184164d2526b.png)

and it returns (0) results. A simpler search (and I think they're all required in this case?) `dostoyevsk* dostoevsk* sochinen*` at least gives some results.

**Comment by tampakis** [comment]
Need to switch to edismax parser in advanced search to support wildcards and boolean operators at the same time.

**Comment by jpstroop** [comment]
:+1:

**Comment by tampakis** [comment]
Check to see if this is still an issue

**Comment by eliotjordan** [comment]
This appears to be fixed.
