### ISSUE TITLE
Google Book Cover Peculiarity

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#848]
This record book cover display is off: https://pulsearch.princeton.edu/catalog/3857226

**Comment by jpstroop** [comment]
Whatthe huh?

**Comment by kevinreiss** [comment]
That's what it looks like on google's page: https://books.google.com/books?id=4GMxkAEACAAJ&hl=&as_pt=BOOKS&source=gbs_api. Shrinkwrap included....

**Comment by tampakis** [comment]
Another example: https://pulsearch.princeton.edu/catalog/7145132
@axamei could you take a look at the css rule for the floating book cover image? Ideally the thumbnail is "top-justified." Simply removing [this line](https://github.com/pulibrary/orangelight/blob/1e937344e629592d7122dc2933cb70d4bace1d94/app/assets/stylesheets/components/record--sidebar.scss#L46) is an option. Then I guess we could add a padding-top property of 10px?

**Comment by axamei** [comment]
Yikes. Adding ```.document-thumbnail img { max-height: 100%; }``` should fix it.
