### ISSUE TITLE
Audit OpenURL Paramters

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#85]
For integration with pulgetit (umlaut) and other local applications (aeon) that may be openURL aware adding a parameter to the OpenURLs produced by the system is useful. The parameter "rft_id" can be used for this. A convention I've seen in other applications is to form the value to include the URL of the source system and the bib ID, so in our instance this would be something like:

rft_id=http://pulsearch.princeton.edu/bib/{bibliographic_id}

perhaps when we have multiple data sources feeding the base URL could be a bit different for different data sources i.e.

rft_id=http://pulsearch.princeton.edu/findingaids/{finding_aid_id}

**Comment by tampakis** [comment]
@kevinreiss Can we close this issue?

**Comment by kevinreiss** [comment]
Did you add an openURL representation to the Solr Doc?

**Comment by tampakis** [comment]
Not yet, but I don't think that's what this issue is getting at. I think it's about what you added here: https://github.com/pulibrary/orangelight/blob/development/config/initializers/blacklight_initializer.rb#L58

**Comment by kevinreiss** [comment]
Okay, calculating the OpenURL at import time seems the best way to go in the long-term. But short-term, yes let's close this out and that hackery can be removed later.
