### ISSUE TITLE
MARC Senior Thesis Format

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#855]
It looks like there are thousands of MARC records corresponding to senior theses that are getting classified as books. Should the format classifier be updated to match additional dissertation notes?
https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=%22Senior+Princeton+University+1971%22
https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=%22Senior+Princeton+University%22

This is related to a feedback item where a user limited the format to senior thesis and was unable to find a particular thesis which was classified as a book.

**Comment by joycebcat** [comment]
@tampakis What criteria currently exists?  It is based on the 502 note, right?  From looking around, I'm wondering if you aren't normalizing the text.  I'm seeing that the spacing around the dashes differs.

I see something marked as a senior thesis with this note:
Thesis (Senior)--Princeton University, 1995. 
https://pulsearch.princeton.edu/catalog/6574111 

And something NOT marked as a senior thesis with this note:
Thesis (Senior) -- Princeton University, 1976. 
https://pulsearch.princeton.edu/catalog/5186764

**Comment by tampakis** [comment]
@joycebcat, currently it's any 502 $a that contains the following exact strings:
`(Senior)--Princeton University`
`Thesis (Senior)-Princeton University`

Maybe I can change the string match criteria to ignore symbol characters.

**Comment by tampakis** [comment]
And whitespace

**Comment by joycebcat** [comment]
Yeah, that would be a good thing to do.  Normalization is important most of the time because there are often little variations, like capitalization or spacing, that are going to mess things up.

**Comment by tampakis** [comment]
Another issue is that the dissertation note can be split across subfield $b and $c. The format classifer was only looking at $a.
https://pulsearch.princeton.edu/catalog/3714905/staff_view
