### ISSUE TITLE
856 Indexing Issue

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#856]
Bib https://pulsearch.princeton.edu/catalog/9797425 has a slightly different Full-text URL than it's MARC source record has in the 856 field:

https://pulsearch.princeton.edu/catalog/9797425.json
https://getit.princeton.edu/resolve?url%5Fver=Z39.88-2004ctx%5Fver=Z39.88-2004ctx%5Fenc=info:ofi/enc:UTF-8rfr%5Fid=info:sid/sfxit.com:opac%5F856url%5Fctx%5Ffmt=info:ofi/fmt:kev:mtx:ctxsfx.ignore%5Fdate%5Fthreshold=1rft.object%5Fid=110992357342110svc%5Fval%5Ffmt=info:ofi/fmt:kev:mtx:sch%5Fsvc

https://bibdata.princeton.edu/bibliographic/9797425
https://getit.princeton.edu/resolve?url%5Fver=Z39.88-2004&ctx%5Fver=Z39.88-2004&ctx%5Fenc=info:ofi/enc:UTF-8&rfr%5Fid=info:sid/sfxit.com:opac%5F856&url%5Fctx%5Ffmt=info:ofi/fmt:kev:mtx:ctx&sfx.ignore%5Fdate%5Fthreshold=1&rft.object%5Fid=110992357342110&svc%5Fval%5Ffmt=info:ofi/fmt:kev:mtx:sch%5Fsvc&

The former one looks like the ampersands have all be stripped out. I don't really see this pattern repeated in other records so this seems a one off problem. This is from the bulk monthly Marc-it ingest so if this pattern was widely repeated I think we'd be getting quite a few problem tickets.

**Comment by mzelesky** [comment]
I found at least two other records with the same issue:

https://pulsearch.princeton.edu/catalog/9797426
https://pulsearch.princeton.edu/catalog/9797427

Unfortunately, I think it is larger than a one-off problem.

**Comment by mzelesky** [comment]
All SFX records between bib ID 9797097 and 9797527 have the same problem. Other records around those bib IDs render correctly. It is also a problem for 9989776-9992252. What's interesting is batches of SFX records loaded between those 2 ranges render correctly.

A potential clue is the apostrophe does not display in the record view for "Princeton's" in the display tag (taken from the 856 |z). Is there some sort of punctuation stripping going on for certain records?

**Comment by kevinreiss** [comment]
@tampakis @mzelesky any thoughts on how we can resolve this?

**Comment by tampakis** [comment]
Yeah, @mzelesky's clue helped me out, it has do with a particular range of bib ids that had invalid xml characters. I "cleansed" them but I guess it also stripped out apostrophes and ampersands

**Comment by kevinreiss** [comment]
Do we need to do a bulk update on the Voyager side so they will be filtered through the daily data load?

**Comment by mzelesky** [comment]
It would be easy enough for me to export the records and reimport them (making sure the bad XML characters are taken care of).

**Comment by tampakis** [comment]
I need to do a full reindex anyway to fix #855. Hopefully that will resolve the issue. It should be done by the end of the day today.

**Comment by tampakis** [comment]
Ok all the links mentioned in this issue work again. Somewhat magically, both the MARC field of interest and the issue number are both 856.
