### ISSUE TITLE
Include 050 in call number browse

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#864]
Especially for electronic resources

**Comment by jpstroop** [comment]
This might be a dupe. I know it has come up multiple times (David asked recently, and I think we talked about this in the early days of the project). I thought we had decided against it, but can't recall why.

It seems like the recap partner records could benefit from this as well, when that becomes a thing.

**Comment by tampakis** [comment]
@jpstroop @escowles I think we should discuss this at the next Lissc+

**Comment by tampakis** [comment]
I'll send an email to Lissc+

**Comment by christinach** [comment]
see https://github.com/pulibrary/bibdata/issues/1017
