### ISSUE TITLE
Availability should use ARIA Live regions on the Show Page

### ISSUE THREAD

**Issue by sdellis** [pulibrary/orangelight#870]
This will make search results more accessible by letting screen readers know about (and announce) the availability of results.

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OrangelightBibdataRequests-571691cab409d8d821b873be/issues/pulibrary/orangelight/870?planning-poker) with Zenhub @leefaisonr @maxkadel @rladdusaw @sandbergja

**Comment by sandbergja** [comment]
Noting that the Deque University section on lazy loading says that:

- Placeholders for AJAX content should inform screen reader users that the content is loading.
- "Lazy loading" AJAX content should not be announced as it loads.

**Comment by sandbergja** [comment]
Closing this issue.  There is already an "Availability" heading that makes the availability section relatively prominent.  An aria live region could be potentially confusing, and there is no way for the user to repeat the unexpected message if they wanted to hear it again.
