### ISSUE TITLE
Accession number normalization with decimal numbers

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#872]
The arbitrary accession number normalization is becoming increasingly complex. Should we support correctly sorting decimal numbers? Should we be in the business of stripping out period character that appear in the middle of the call number string?

From feedback:
> The call no. construction Princeton MS 184 Rare Books and Special Collections - Manuscripts Collection is very unforgiving, and most of the call nos. have MS. (that is, a period at the end). These file separately and after those with MS. A number of items (including many recent music acquisitions) lack the period. Is it possible to normalize this, or do we need to get these call nos. amended in the records. Try this URL and scroll down: https://pulsearch.princeton.edu/browse/call_numbers?search_field=browse_cn&q=Princeton+MS
>
> Additionally, whether the accession number is a decimal number affects the sort order. The normalizer doesn't expect decimal numbers for normalization. For example:
Princeton MS. 138-67 becomes PRINCETON MS. 138-0000067
Princeton MS. 138.74 becomes PRINCETON MS 138.0000074
Princeton MS 184 becomes PRINCETON MS 0000184

**Comment by christinach** [comment]
We will discuss this with @regineheberlein tomorrow.

**Comment by christinach** [comment]
per @regineheberlein we can close this one
