### ISSUE TITLE
Add website nav bar to orangelight

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#878]
This is feedback from Anne. Add this:

![screen shot 2017-05-11 at 12 36 20 pm](https://cloud.githubusercontent.com/assets/999701/25961007/b9b1fe76-3646-11e7-9051-c94baf76a889.png)

to the catalog.

**Comment by kevinreiss** [comment]
@axamei had done some work to make the menu friendly for rails projects in the https://github.com/pulibrary/pul_assets. I think what is there needs some more to work play well with the blacklight bootstrap conventions but a good starting place.

**Comment by jpstroop** [comment]
I should have added, this is one of a set of prereqs. she gave for moving OL to catalog.princeton.edu
