### ISSUE TITLE
Return content_title_index field on a "show" record lookup

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#886]
Having this available will address this issue https://github.com/pulibrary/orangelight/issues/4018. A nice enhancement to make Scan to PDF requests more accurate.

**Comment by kevinreiss** [comment]
Hi @tampakis. Current _index index fields aren't stored. The listings in this value are useful as individual tokens for display in the requests issue tagged in the previous comment. Should we store them in another field like `chapter_title_display` or add an exception to include the content_title_index field itself.

**Comment by tampakis** [comment]
So we have two content fields:
`contents_display 505agrt`
`content_title_index 505t`

Would the contents_display field serve your needs? Or should we also store the content_title_index field?

**Comment by christinach** [comment]
closing as implementing the new ticket from https://github.com/pulibrary/orangelight/issues/4018#issuecomment-2120876599, we wouldn't need a dropdown
