### ISSUE TITLE
Same advanced facet value getting submitted multiple times

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#894]
When editing an [advanced search with already submitted advanced facet values](https://pulsearch.princeton.edu/advanced?commit=Search&f1=all_fields&f2=author&f3=title&f_inclusive%5Blanguage_facet%5D%5B%5D=Abkhaz&op2=AND&op3=AND&q1=&q2=&q3=&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&search_field=advanced&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&utf8=%E2%9C%93), the same value gets submitted [twice](https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&f2=author&f3=title&f_inclusive%5Blanguage_facet%5D%5B%5D=Abkhaz&op2=AND&op3=AND&q1=&q2=&q3=&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&search_field=advanced&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&f1=all_fields&q1=&op2=AND&f2=author&q2=&op3=AND&f3=title&q3=&f_inclusive%5Blanguage_facet%5D%5B%5D=Abkhaz&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search).

**Comment by christinach** [comment]
closing in favor of https://github.com/pulibrary/orangelight/issues/3384
