### ISSUE TITLE
SCSB Display Bug

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#898]
Why does https://pulsearch-recap.princeton.edu/catalog/SCSB-6333251 bomb out on the show route?

**Comment by mzelesky** [comment]
Some things about the record:

2 852s for different holdings. However, there is no corresponding 876 for the 852 with |0 6381442.
The 009 has a period in it.

Is the multiple 852s where one has no corresponding items the problem?

**Comment by kevinreiss** [comment]
Yes this is indeed the issue. The lack of items causes a method that display use restrictions in the holdings area to break.

```ActionView::Template::Error (undefined method `map' for nil:NilClass):
    1: <% online, physical = holding_request_block(document) %>
    2: <% unless online.nil? %>
    3:   <div class="location--panel location--online">
    4:     <div class="panel panel-default">
  app/helpers/application_helper.rb:170:in `recap_item_list'
  app/helpers/application_helper.rb:160:in `process_physical_holding'
  app/helpers/application_helper.rb:98:in `block in holding_request_block'
  app/helpers/application_helper.rb:97:in `each'
  app/helpers/application_helper.rb:97:in `holding_request_block'
  app/views/catalog/_show_availability_sidebar.html.erb:1:in `_app_views_catalog__show_availability_sidebar_html_erb___3110835727802327653_69876049254600'
  app/views/catalog/show.html.erb:27:in `_app_views_catalog_show_html_erb___4030767740993414437_69876045291920'```

Why would we have a holding with no items? Is this something we should take up the HTC or should we adjust our code to just through away an empty holding in partner records.

**Comment by mzelesky** [comment]
I think we need to take it up with HTC if the next full dump includes these 'orphan holdings.'

**Comment by kevinreiss** [comment]
resolved
