### ISSUE TITLE
Repress "Unknown" format from display?

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#901]

**Comment by tampakis** [comment]
@joycebcat, @kevinreiss I think we should consider hiding the "unknown" from from display in the facets and in the record display. They come from two sources:
 - Voyager, happens infrequently but sometimes remains in the system for a while before being cleaned up. [Current example](https://pulsearch.princeton.edu/catalog/10277841)
 - SCSB, not a large percentage of records, but still [thousands of them](https://pulsearch-recap.princeton.edu/?f%5Bformat%5D%5B%5D=Unknown).

**Comment by joycebcat** [comment]
@tampakis  Yes, I agree.  Especially with all the outside data coming in.  I would really like to leave it in the dev site if possible because that gives me a place to check for clean-up purposes.
