### ISSUE TITLE
Upgrade Ruby to Version 2.4.2

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#914]
We're still on version 2.2.3. Technically Blacklight isn't supported on that version.

**Comment by tampakis** [comment]
Ansiblize!

**Comment by jrgriffiniii** [comment]
Within Ubuntu 16.04 LTS environments, only Ruby release 2.3.1 is available as a dkpg:
```
[...]
Welcome to Ubuntu 16.04.3 LTS [...]
[...]
user@some-host:~$ ruby --version
ruby 2.3.1p112 [...]
```

Hence, the scope of this update has been downgraded.

**Comment by jrgriffiniii** [comment]
Proposed solutions related to infrastructure and modifications to Ansible Roles have been outlined in https://github.com/pulibrary/princeton_ansible/issues/134
