### ISSUE TITLE
Stopwords stripping doesn't work properly in Solr

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#92]
A known major bug: https://issues.apache.org/jira/browse/SOLR-3085

Basically stopwords get stripped but they are still counted as terms. This messes up the 'mm' algorithm. We'll track the issue, but for now will not do any special treatment of stopwords.

**Comment by jpstroop** [comment]
We're currently not stripping any stopwords, and nobody is complaining. Closing.
