### ISSUE TITLE
Can't remove advanced facet limits individually

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#921]
Check out this "edit search" https://pulsearch.princeton.edu/advanced?commit=Search&f1=all_fields&f2=author&f3=title&f_inclusive%5Badvanced_location_s%5D%5B%5D=ues&op2=AND&op3=AND&q1=&q2=&q3=&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&search_field=advanced&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&utf8=%E2%9C%93

If you remove the ues holding location limit from the form it still gets submitted anyway.

**Comment by escowles** [comment]
I was unable to reproduce this — I was able to remove the ues location, and that worked as expected when I added other limits to the query or not.
