### ISSUE TITLE
Support SCSB Availability

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#922]
Use the ```scsb_id``` param passed to the availability controller in marc liberation for the "show" display and the ```barcodes``` param for the "search" view. Also make sure availability works in browse view.

**Comment by kevinreiss** [comment]
Still need to do this in "browse" view.

**Comment by kevinreiss** [comment]
This turns out to be more painful than I thought. The SCSB system provides to two availability lookups. One via a single BIB ID value that gives you all barcodes/item status for the record and one via barcode that lets you supply up to 50 barcodes at a time. The current browse model only gives you access to the BIB ID and a holding ID. Doing lookups for every individual SCSB bib ID in a given browse display seems prohibitive as does loading the solr document to fetch the first barcode value in the items key in the holdings hash. I put in a placeholder block that tells the user to see the full record for availability.

**Comment by kevinreiss** [comment]
Do we want to leave this as is @tampakis in the browse view?

**Comment by tampakis** [comment]
Will revisit as part of ILS migration

**Comment by kevinreiss** [comment]
It appears we decided not have any availability on the browse screens post alma. Closing. Re-open if I am mistaken.
