### ISSUE TITLE
Show closing date for periodicals in search results

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#936]
From Darwin:

> Is it possible to get the closing / cease date to show up in the short-list records for serial titles? Here's an example for American drama: https://pulsearch.princeton.edu/catalog/9792735. It ceased in 2007, and is clearly indicated as such in the bibliographic record. 
> 
> In the short display of a results set, however, the date is 1991-, implying to most patrons, I would think, that the publication is still ongoing. [See sample results set.](https://pulsearch.princeton.edu/?f1=subject&f2=author&f3=title&f_inclusive%5Bformat%5D%5B%5D=Journal&op2=AND&op3=AND&q1=theater+%22united+states%22&q2=&q3=&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&search_field=advanced&sort=title_sort+asc%2C+pub_date_start_sort+desc)

**Comment by jrgriffiniii** [comment]
From what I could determine, this appears to be related to a MARC field value in the record within the catalog.  Please see the following:

- https://pulsearch.princeton.edu/catalog/9792735
- https://pulsearch.princeton.edu/catalog/9792735.json
```
[...]
pub_created_display: [
"Cincinnati, Ohio : American Drama Institute, c1991-"
],
[...]
pub_date_start_sort: 1991,
pub_date_end_sort: 2007,
[...]
```

Which was extracted from:
- https://bibdata.princeton.edu/bibliographic/9792735/jsonld
- https://bibdata.princeton.edu/bibliographic/9792735

(Specifically, 260):
```
[...]
<datafield ind1=" " ind2=" " tag="260">
  <subfield code="a">Cincinnati, Ohio :</subfield>
  <subfield code="b">American Drama Institute,</subfield>
  <subfield code="c">c1991-</subfield>
</datafield>
[...]
```

Hence, I shall proceed by looking to resolve this from within [pulibrary/marc_liberation](https://github.com/pulibrary/marc_liberation) as well.

**Comment by jrgriffiniii** [comment]
This should be closed by https://github.com/pulibrary/marc_liberation/pull/312
