### ISSUE TITLE
Always HTTPS

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#94]
As part of our infrastructure planning I think we should consider setting up this service to only use HTTPS. Certainly we should run anything with an authenticated user over https, but I think we should consider just making https the default.

**Comment by kevinreiss** [comment]
@tampakis - I'll get SSL certs for the pulsearch and pulsearch-dev domains through OIT.

**Comment by jpstroop** [comment]
:+1:

**Comment by tampakis** [comment]
Thanks for doing this @kevinreiss
