### ISSUE TITLE
Add temp location and availability to email

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#951]

**Comment by tampakis** [comment]
From feedback:
> When you click "e-mail" to send yourself a catalog record, the system doesn't send you the Availability status or any current Temp locations. I sent this to myself today; one holding is in fact Charged out, and the other is on 3-Hour Reserve, but none of that info is included.

**Comment by tampakis** [comment]
dupe of recently opened issue

**Comment by christinach** [comment]
dupe of https://github.com/pulibrary/orangelight/issues/1890
