### ISSUE TITLE
Should OL offer a way to request reserve items?

### ISSUE THREAD

**Issue by sdellis** [pulibrary/orangelight#953]
BorrowDirect allows the request of non-circulating items. However, OrangeLight does not offer a way to request items if all copies are on reserve. We should determine the frequency of this scenario and discuss with Joan/Marie how we want to move forward policy-wise (i.e., should there be a Request button on on-reserve items in OL?).

**Comment by kevinreiss** [comment]
I have referred this question circ/resource sharing staff.
