### ISSUE TITLE
searching: 245 subfields

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#96]
The title index should NOT include all subfields of the 245 field.

The title index should include: a b f g k n p s

**Comment by joycebcat** [comment]
actually, it would be worth asking Don in RB about the subfields f and g and k.  I'm not sure to what extent RB people would consider them part of the title and therefore something users would search for that way.

**Comment by tampakis** [comment]
Review the title search keyword feature in general.

**Comment by tampakis** [comment]
For now remove c and h

**Comment by tampakis** [comment]
Title keyword currently includes `245abcfghknps`
There is a separate title field that doesn't include c and h as well for the left-anchored search.
