### ISSUE TITLE
Add ability to view Princeton Only holdings

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#968]
Not sure how prominent this should be. I'm thinking of adding a code to the advanced location dropdown or a checkbox.

**Comment by joycebcat** [comment]
@tampakis I've just had a message from a Collection Development staff member about her need to be able to search specifically for Princeton-owned material when going through a list of titles for potential purchase/addition to our collection.  She knows about the advanced search option but it doesn't stick.  A filter as suggested here would probably work OK for her.

**Comment by tampakis** [comment]
@joycebcat, can you explain what "it doesn't stick" means? I don't know how adding an additional filter would be any different from the "pul" location code.

**Comment by joycebcat** [comment]
Just that new searches wipe out this limit.  If you add a filter that is available from the main search page, it is easier to apply than setting it through the advanced search each time.  If there is a way to set the limit as a default, that is really what they are looking for.

**Comment by tampakis** [comment]
Perhaps we can discuss this at the next Lissc? I agree that adding the limit in the main search would be simpler, but it wouldn't be discreet. Setting a default limit for a logged-in account might be preferable.

**Comment by joycebcat** [comment]
Good idea.  LISSC should discuss.
