### ISSUE TITLE
searching: author browse

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#97]
The author browse is including subfield e data such that two lines are created for the name one with and one without the relationship designator (|e).  I think we should discuss this issue and decide whether or not this is the desired result.  The inclusion or exclusion of the |e data is going to impact other aspects of searching as well.

Eysenck, H J (Hans Jurgen), 1916-1997
Eysenck H J (Hans Jurgen), 1916-1997, ed.

**Comment by tampakis** [comment]
The e is no longer part of the author facet: https://pulsearch-dev.princeton.edu/browse/names?search_field=browse_name&q=Eysenck%2C+H+J+%28Hans+Jurgen%29%2C+1916-1997
