### ISSUE TITLE
searching: sorting of diacritics in browse indexes

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#98]
In the name and the subject browse indexes the letters with diacritics are sorting after all the letter without diacritics.  The headings should be normalized before sorting so that they are intermingled.

current incorrect situation:
Ezhava
Ezquerra
Ezra
Ecole (with accent on E)
Eglise (with accent on E)

**Comment by tampakis** [comment]
Reseeding the browse db fixed this: 
[Εcole and  École appearing together regardless of diacritics](http://pulsearch-dev.princeton.edu/browse/names?search_field=browse_name&q=ecole)
[F appearing after Ez](http://pulsearch-dev.princeton.edu/browse/names?search_field=browse_name&q=ez)
