### ISSUE TITLE
Include more information for other version titles

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#990]
Perhaps more info about the other matched versions can be displayed to reduce confusion when there are multiple other versions matches: https://pulsearch.princeton.edu/catalog/3287143

Also displaying the cataloging note in 776 subfield $i would help. See #595.

**Comment by jrgriffiniii** [comment]
In order to address resolving this more immediately, I will use more human-friendly metadata attributes and attempt to ensure that the sidebar links consume less space within the sidebar itself.

**Comment by kevinreiss** [comment]
Is the re-factoring here where we might want to consider addressing a portion of https://pulsearch.princeton.edu/catalog/SCSB-5855877 and rendering any "use restrictions" an other copy might have in some fashion with the other metadata? The SCSB items will explicitly tell you in the holdings data hash whether or not they have restrictions. Princeton items located at "aeon i.e. rare books" locations also would be good to flag as restricted use if were to go this route.

**Comment by jrgriffiniii** [comment]
> The SCSB items will explicitly tell you in the holdings data hash whether or not they have restrictions. Princeton items located at "aeon i.e. rare books" locations also would be good to flag as restricted use if were to go this route.

@kevinreiss that's fine with me, this is still in the process of being adjusted in response to layout issues.  I can include this within the scope of the Pull Request.

**Comment by jrgriffiniii** [comment]
After meeting and discussing the progress on this issue with @tampakis , the following improvements were identified:
- Rendering the Bib. ID for "Other versions" links is acceptable (given the varying nature of each catalog record)
- "Other version" information should also be included in the Requests form
