### ISSUE TITLE
Unexpected/inconsistent advanced search behavior

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#995]
Reported in sn@p:
> If I do a keyword search for CHRB* (restricted to PUL results only) I get
2216 results:
> https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&q1=CHRB*&op2=AND&f2=author&q2=&op3=AND&f3=title&q3=&f_inclusive%5Badvanced_location_s%5D%5B%5D=pul&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search
> And if I do a keyword search for "Chinese Rare Books Project" (also
restricted to PUL) I get 11 results:
> https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&q1=CHRB*&op2=AND&f2=author&q2=&op3=AND&f3=title&q3=&f_inclusive%5Badvanced_location_s%5D%5B%5D=pul&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search
> But if I combine the two terms with OR, I get 1334 results:
> https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&f2=all_fields&f3=title&op2=OR&op3=AND&q1=CHRB*&q2=%22Chinese+Rare+Books+Project%22&q3=&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&search_field=advanced&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&f1=all_fields&q1=CHRB*&op2=OR&f2=all_fields&q2=%22Chinese+Rare+Books+Project%22&op3=AND&f3=title&q3=&f_inclusive%5Badvanced_location_s%5D%5B%5D=pul&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search
> Shouldn't this last search contain the combined results of the previous two
(i.e., between 2216 and 2227 results)?  I am not sure if the problem has to
with the fact that I am combining different types of search logic
(wildcards, phrases, and booleans) in the same query.  I used the advanced
search form to construct this query.

**Comment by tampakis** [comment]
Main issue, wildcard searching doesn't work when combined with boolean searches.

**Comment by christinach** [comment]
We tested it. It seems to work.
